### ISSUE TITLE
Return messages in pt_BR.

### ISSUE THREAD

**Issue by zeizzz** [BeyondTrust/pbis-open#100]
Version: 8.5.7.385
OS/Distro: Linux/Debian 9.1

Hello,

I apologize for my English, I'm using Google Translate.

I'm from Brazil.

I am using PBIS-OPEN in my company and I am very satisfied with the results. However, I can not get the message "New password", "Your password as expired ..." and others to return in pt_BR, even if the locale is used.
I am using Debian 9 with KDM. How do I get my messages back in Portuguese?

Thank you for your attention.

**Comment by rbest-bt** [comment]
We currently do not have support for other locales. I have raise this as an issue we should address.

**Comment by zeizzz** [comment]
Is there any way to translate these messages manually?

**Comment by rbest-bt** [comment]
Quickest solution would be to check out the code, change all the instances and rebuild the installers. A quick search for this line and it looks to be in 2 places.
>./lsass/interop/auth/pam/pam-auth.c:                    "Your password has expired",
./lsass/interop/auth/pam/pam-acct.c:                "Your password has expired",

Most of what you need to changed should just be text replacements. We currently have a few big projects on the go so I'm not sure when we will get to this.
