### ISSUE TITLE
/etc/hosts gets overwritten

### ISSUE THREAD

**Issue by jrose84** [BeyondTrust/pbis-open#101]
**Version**: 8.5.7-385
**OS/Distro**: CentOS Linux release 7.3.1611 (Core)
**Issue/Impact**: /etc/hosts entry for the host is overwritten

I am using ansible for configuration management. I notice that the entry my rhel role adds to /etc/hosts gets overwritten when I run the pbis role. I think I isolated the issue, but want to confirm.

If ansible already configures /etc/hosts with the necessary entries, is this necessary?
`/opt/pbis/bin/config UserDomainPrefix {{AD_domain}}`

**Comment by ferricoxide** [comment]
PBIS/LikeWise has been doing for as long as I've been using it (so, 8 years, now?). Was always frustrated by it, since it tended to overwrite FQDN with bare node-name.

**Comment by RBoulton-BT** [comment]
As far as I'm aware the only time PBIS should change the /etc/hosts file is during the default domainjoin-cli join processing. I believe this action can be disabled by passing the --disable hostname option to the domain join-cli command.

I'll take a look at the config processing but I will be very surprised if this does any manipulation of the /etc/hosts file.

**Comment by jrose84** [comment]
Tried that, does't work...
Syntax tried `shell: domainjoin-cli join --disable hostname {{domain_fqdn}} {{domain_user}} {{domain_pass}}`
Tried omitting this as well, which also fails to resolve my issue:
`  command: /opt/pbis/bin/config UserDomainPrefix {{domain_fqdn}}`

**Comment by jrose84** [comment]
Tried running commands manually on the host and they fail to work, which makes no sense since the server gets configured correctly with the exception of the contents of /etc/hosts.

Here is the error when I try to configure PBIS manually:
domainjoin-cli join --disable hostname kwitzg.com jrose

Error: LW_ERROR_ACCESS_DENIED [code 0x00009cde]

**Comment by RBoulton-BT** [comment]
You'll need to sudo domainjoin-cli if you're not root.
