### ISSUE TITLE
BeyondTrust Password Safe - delay in loading (~1 minute) the content after logon to console

### ISSUE THREAD

**Issue by jgravikumar88** [BeyondTrust/pbis-open#102]
Hi Team,
 Please suggest if you have seen this kind of issue earlier. After Login in BeyondTrust Password Safe - there is a delay of loading the content approximately 1 minute and all the tabs will be displayed or non funtion. After 1 minute the content will be visible.

Thanks
Ravi

**Comment by RBoulton-BT** [comment]
Hi Ravi,

This GitHub project is for the Community edition of PowerBroker Identity Services only. Unfortunately we can't offer support for BeyondTrust Password Safe here. 

Please get in touch with your BeyondTrust Support team who will be happy to help https://www.beyondtrust.com/support.
