### ISSUE TITLE
AD users allowed in RequireMembershipOf can jump between servers without re-typing the password

### ISSUE THREAD

**Issue by mimmofu** [BeyondTrust/pbis-open#105]
Hi folks,
no issues on running pbis-open over Ubuntu as well as on CentOS so far. The only concern I have is that AD users that are already authenticated on a Linux system, can SSH-jump on other servers, pbis-open enabled as well, without being re-authenticated. Like an implicit SSH trust.

Is this by design? If so, how can be turned off?

Thanks,

**Comment by RBoulton-BT** [comment]
Yes this is Kerberos single sign-on in action. When your user authenticates with AD using PBIS they will get a Kerberos ticket. This ticket is then used to provide Single Sign-On to other PBIS enabled hosts.

If you need to disable this you can just set "GSSAPIAuthentication no" in the SSHD configuration of the target hosts.

**Comment by rbest-bt** [comment]
In the next release - 8.6.0 - there will be an option during domainjoin to disable this:
>/opt/pbis/bin/domainjoin-cli join --nogssapi

**Comment by jeanmoussignac** [comment]
When is the release 8.6?

**Comment by rbest-bt** [comment]
The plan is before the end of the month.

**Comment by rbest-bt** [comment]
https://github.com/BeyondTrust/pbis-open/releases/tag/8.6.0
