### ISSUE TITLE
Cannot logon when using PBIS Open on a vlan (DMZ)

### ISSUE THREAD

**Issue by staundk** [BeyondTrust/pbis-open#106]
**Version**: 8.5.7.385
**OS/Distro**: Ubuntu desktop 16.04 - Server
**Issue/Impact**:
We have been using PBIS open for several years now but always had an issue when using it on another network than our primary Domain network.
Pbis can connect to our ReadOnly DC and different commands like enum-groups, find-user-by-name works fine.

But no one can log on. When entering username/ password the logon process is trying to logon - a minute later - Login Incorrect.
If we move the server back to our primary network everything works again.

All our windows servers on the same DMZ/ vLAN network are able to logon to the ReadOnly DC.

 1. systemctl status lwsmd.service

`lwsmd.service - BeyondTrust PBIS Service Manager
   Loaded: loaded (/lib/systemd/system/lwsmd.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2018-03-01 10:39:22 CET; 16min ago
  Process: 1142 ExecStart=/opt/pbis/sbin/lwsmd --start-as-daemon (code=exited, status=0/SUCCESS)
 Main PID: 1266 (lwsmd)
    Tasks: 331
   Memory: 36.4M
      CPU: 1.023s
   CGroup: /system.slice/lwsmd.service
           ââ1266 /opt/pbis/sbin/lwsmd --start-as-daemon
           ââ1315 lw-container lwreg
           ââ1405 lw-container eventlog
           ââ1469 lw-container netlogon
           ââ1627 lw-container lwio
           ââ1702 lw-container lsass
           ââ1775 lw-container reapsysl

Mar 01 10:39:21 srv-jen-nsb3 systemd[1]: Starting BeyondTrust PBIS Service Manager...
Mar 01 10:39:21 srv-jen-nsb3 /opt/pbis/sbin/lwsmd[1266]: Logging started
Mar 01 10:39:21 srv-jen-nsb3 lwreg[1315]: Logging started
Mar 01 10:39:21 srv-jen-nsb3 eventlog[1405]: Logging started
Mar 01 10:39:22 srv-jen-nsb3 netlogon[1469]: Logging started
Mar 01 10:39:22 srv-jen-nsb3 lwio[1627]: Logging started
Mar 01 10:39:22 srv-jen-nsb3 lsass[1702]: Logging started
Mar 01 10:39:22 srv-jen-nsb3 lsass[1702]: Logging redirected
Mar 01 10:39:22 srv-jen-nsb3 reapsysl[1775]: Logging started
Mar 01 10:39:22 srv-jen-nsb3 systemd[1]: Started BeyondTrust PBIS Service Manager.
`

 2. /opt/pbis/bin/lwsm list

`lwreg          running (container: 1315)
dcerpc         stopped
eventlog       running (container: 1405)
lsass          running (container: 1702)
lwio           running (container: 1627)
netlogon       running (container: 1469)
rdr            running (io: 1627)
reapsysl       running (container: 1775)
usermonitor    stopped
`

 3. /opt/pbis/domainjoin-cli query
`Name = srv-jen-nsb3
Domain = DOMAIN.LOC
Distinguished Name = CN=SRV-JEN-NSB3,OU=Engineering,OU=Servers,OU=Intern,OU=Company,DC=Domain,DC=loc`

 4. pbis status
`Status:        Online
        Mode:          Un-provisioned
        Domain:        DOMAIN.LOC
        Domain SID:    S-1-5-21-1602433843-221394268-410060929
        Forest:        DOMAIN.loc
        Site:          NSB-DMZ
        Online check interval:  300 seconds
        [Trusted Domains: 1]

        [Domain: OURDOMAIN]

                DNS Domain:       DOMAIN.loc
                Netbios name:     DOMAIN
                Forest name:      DOMAIN.loc
                Trustee DNS name:
                Client site name: NSB-DMZ
                Domain SID:       S-1-5-21-1602433843-221394268-410060929
                Domain GUID:      c23ace86-95a4-4c49-b463-4791ea135afe
                Trust Flags:      [0x001d]
                                  [0x0001 - In forest]
                                  [0x0004 - Tree root]
                                  [0x0008 - Primary]
                                  [0x0010 - Native]
                Trust type:       Up Level
                Trust Attributes: [0x0000]
                Trust Direction:  Primary Domain
                Trust Mode:       In my forest Trust (MFT)
                Domain flags:     [0x0021]
                                  [0x0001 - Primary]
                                  [0x0020 - GC offline]

                [Domain Controller (DC) Information]

                        DC Name:              SRV-RODC-NSB1.DOMAIN.loc
                        DC Address:           10.1.1.10
                        DC Site:              NSB-DMZ
                        DC Flags:             [0x0001e8fc]
                        DC Is PDC:            no
                        DC is time server:    yes
                        DC has writeable DS:  no
                        DC is Global Catalog: yes
                        DC is running KDC:    yes

                [Global Catalog (GC) Information]

                        GC Name:              SRV-DC-NSB5.DOMAIN.loc
                        GC Address:           10.10.10.14
                        GC Site:              NSB
                        GC Flags:             [0x0001f1fc]
                        GC Is PDC:            no
                        GC is time server:    yes
                        GC has writeable DS:  yes
                        GC is running KDC:    yes
`
 5. /opt/pbis/bin/enum-users

`Shows all our users.`

 6. attach logs
  - /opt/pbis/bin/lwsm set-log-target -p lsass -  file /tmp/lsass.log
  - /opt/pbis/bin/lwsm set-log-level -p lsass - debug
  - attach log
`20180301104538:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:480: Switched gss krb5 credentials path from <null> to FILE:/var/lib/pbis/krb5cc_lsass.DOMAIN.LOC
20180301104538:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:480: Switched gss krb5 credentials path from <null> to FILE:/var/lib/pbis/krb5cc_lsass.DOMAIN.LOC
20180301104538:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:480: Switched gss krb5 credentials path from <null> to FILE:/var/lib/pbis/krb5cc_lsass.DOMAIN.LOC
20180301104538:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:480: Switched gss krb5 credentials path from <null> to FILE:/var/lib/pbis/krb5cc_lsass.DOMAIN.LOC
20180301104538:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:480: Switched gss krb5 credentials path from <null> to FILE:/var/lib/pbis/krb5cc_lsass.DOMAIN.LOC
20180301104538:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:480: Switched gss krb5 credentials path from <null> to FILE:/var/lib/pbis/krb5cc_lsass.DOMAIN.LOC
20180301104539:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:480: Switched gss krb5 credentials path from <null> to FILE:/var/lib/pbis/krb5cc_lsass.DOMAIN.LOC
20180301104539:DEBUG:lsass:LsaAdBatchEnumObjects():lsass/server/auth-providers/ad-open-provider/batch_enum.c:936: Error code: 40036 (symbol: LW_ERROR_NO_MORE_USERS)
20180301104539:DEBUG:lsass:AD_OnlineEnumObjects():lsass/server/auth-providers/ad-open-provider/online.c:4010: Error code: 259 (symbol: ERROR_NO_MORE_ITEMS)
20180301104539:DEBUG:lsass:AD_EnumObjects():lsass/server/auth-providers/ad-open-provider/provider-main.c:5133: Error code: 259 (symbol: ERROR_NO_MORE_ITEMS)
20180301104539:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:480: Switched gss krb5 credentials path from <null> to FILE:/var/lib/pbis/krb5cc_lsass.DOMAIN.LOC
20180301104539:DEBUG:lsass:LsaSrvEnumObjects():lsass/server/api/api2.c:942: Error code: 259 (symbol: ERROR_NO_MORE_ITEMS)
20180301104539:DEBUG:lsass:LsaSrvEnumObjects():lsass/server/api/api2.c:942: Error code: 259 (symbol: ERROR_NO_MORE_ITEMS)
20180301104539:VERBOSE:lsass-ipc:lwmsg_peer_task_handle_assoc_error():lwmsg/src/peer-task.c:625: (session:538c7b08c0993ae5-6e26b81ee6e19d50) Dropping: LWMSG_STATUS_PEER_CLOSE
20180301104622:VERBOSE:lsass:LsaUmpCheckUsers():lsass/server/auth-providers/ad-open-provider/lsaum_p.c:697: Lsa User Manager - checking user credentials refresh list
20180301104636:VERBOSE:lsass:LsaSrvIpcCheckPermissions():lsass/server/api/ipc_state.c:79: Permission granted for (uid = 0, gid = 0, pid = 2622) to open LsaIpcServer
20180301104636:VERBOSE:lsass-ipc:lwmsg_peer_log_accept():lwmsg/src/peer-log.c:230: (session:03cef1a0f0b4ed0a-da8178f9b2197d69) Accepted <local euid:0 egid:0 pid:2622>
20180301104636:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:480: Switched gss krb5 credentials path from <null> to FILE:/var/lib/pbis/krb5cc_lsass.DOMAIN.LOC
20180301104636:VERBOSE:lsass:AD_CheckExpiredObject():lsass/server/auth-providers/ad-open-provider/online.c:1804: Using cache entry for sid S-1-5-21-1602433843-221394268-410060929-11182, updated 58 seconds ago
20180301104636:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:480: Switched gss krb5 credentials path from <null> to FILE:/var/lib/pbis/krb5cc_lsass.DOMAIN.LOC
20180301104636:VERBOSE:lsass:AD_CheckExpiredObject():lsass/server/auth-providers/ad-open-provider/online.c:1804: Using cache entry for sid S-1-5-21-1602433843-221394268-410060929-513, updated 906 seconds ago
20180301104636:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:480: Switched gss krb5 credentials path from <null> to FILE:/var/lib/pbis/krb5cc_lsass.DOMAIN.LOC
20180301104636:VERBOSE:lsass:AD_OnlineGetGroupMemberSids():lsass/server/auth-providers/ad-open-provider/online.c:4420: Cache entry for group membership for sid S-1-5-21-1602433843-221394268-410060929-513 is incomplete
20180301104636:DEBUG:lsass:AD_EnumMembers():lsass/server/auth-providers/ad-open-provider/provider-main.c:5270: Error code: 259 (symbol: ERROR_NO_MORE_ITEMS)
20180301104636:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:480: Switched gss krb5 credentials path from <null> to FILE:/var/lib/pbis/krb5cc_lsass.DOMAIN.LOC
20180301104636:DEBUG:lsass:LsaSrvEnumMembers():lsass/server/api/api2.c:1149: Error code: 259 (symbol: ERROR_NO_MORE_ITEMS)
20180301104636:VERBOSE:lsass-ipc:lwmsg_peer_task_handle_assoc_error():lwmsg/src/peer-task.c:625: (session:03cef1a0f0b4ed0a-da8178f9b2197d69) Dropping: LWMSG_STATUS_PEER_CLOSE`

**Output/Error**:

**Steps to Reproduce**:
 1. install command
 2. Domainjoin command
 3. Command that returns issue

**Comment by rbest-bt** [comment]
There are issues with site detection for GC when switching sites. With the next release the installed software will come with a script that will assist with rodc/offline domainjoins. One of the options in the script will allow you to specify the site.
>     --site <sitename> (optional) = the Site the computer is in, if site lookups are failing.

This is not a fix but a solution until we can address these in the future

File is already committed and available here:
https://github.com/BeyondTrust/pbis-open/blob/master/reskit/offline-join.pl

**Comment by staundk** [comment]
The host is already joined to the domain, do I need to disjoin and then rejoin with the offline-join.pl script?

**Comment by rbest-bt** [comment]
I'm happy to hear it's working. The script helps the site logic with a new registry option that sets the site. 

If you have any other issues feel free to open a new issue.
