### ISSUE TITLE
AD User: Password does not meet requirements

### ISSUE THREAD

**Issue by Sebi94nbg** [BeyondTrust/pbis-open#108]
**Version**: 8.5.7.385
**OS/Distro**: Ubuntu server 16.04
**Issue/Impact**:
I've logged in with an Active Directory (= AD) user, which works just fine. Then I've tried to change the password from the Linux system, but I always get the error message, that the password does not meet the requirements even when it does.

I've tried to change the password like this:
`ad.user@ubuntu:~$ passwd`
`ad.user@ubuntu:~$ /opt/pbis/bin/passwd`

We've tried to use a password, which is using a workmate with his Windows notebook. This password was accepted by our current password policy on Windows, but not on Linux.

**AD Password Policy Settings**:

My AD has following password policies:

- Enforce password history: 2 passwords remembered
- Maximum password age: 90 days
- Minimum password age: 0 days
- Minimum password length: 10 characters
- Password must meet complexity requirements: Enabled

**Output/Error**:

Both above commands did not change the password in the Active Directory and returned the same message:
```
Current password:
New password:
Re-enter password:
Password does not meet requirements:
passwd: Authentication token manipulation error
```

**Steps to Reproduce**:
 1. Login as AD user in Ubuntu
 2. Try to change the password of the AD user
 3. Use one of the above commands to change the password

**Comment by Sebi94nbg** [comment]
Thanks for your quick reply. My `/etc/pam.d/common-passwd` contains this:
```
password	[success=2 default=ignore]	pam_lsass.so
password	[success=1 default=ignore]	pam_unix.so	obscure	try_first_pass	sha512
password	requisite					pam_deny.so
password	required					pam_permit.so
password	optional		pam_encryptfs.so
```

**Comment by Sebi94nbg** [comment]
Any solutions for my problem, @rbest-bt?

**Comment by rbest-bt** [comment]
Not at this time. This is on my list to investigate. Currently we are working on getting the 8.6.0 release out

**Comment by broyuken** [comment]
I'm having the same issue, is there a solution?

**Comment by broyuken** [comment]
This is still an issue. Can we try to get this resolved please? What information is required from us, I will gladly provide.

**Comment by rbest-bt** [comment]
pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
