### ISSUE TITLE
PBIS Open PAM Settings for AIX - AD has precedence over local account

### ISSUE THREAD

**Issue by nyoukhana** [BeyondTrust/pbis-open#109]
**Version**: 8.5.4.334
**OS/Distro**: AIX
**Issue/Impact**:
*Note:  PBIS Open PAM Settings for AIX - AD has precedence over local account*
This question is more of an how to.
PBIS Open - I have installed PBIS Open

How do you configure AIX PAM settings to allow Windows Active Directory precedence over local AIX Accounts?

As you know the the configuration file in AIX is /etc/pam.conf

thank you
Ninos Youkhana

**Comment by cboutilier-bt** [comment]
There is no additional configuration that is required for PAM. PBIS takes AD account precedence over local accounts on all platforms.
