### ISSUE TITLE
Specify a single Nic/IP for update-dns

### ISSUE THREAD

**Issue by bt-jq-it** [BeyondTrust/pbis-open#110]
We're using Docker on CentOS.  Docker creates multiple virtual nics, with private 172 addresses.  update-dns registers A records for these in addition to the physical nic.

Obviously, this breaks a lot of software that relies on dns.

There's no way to scavenge the virtual ones from the dns server without deleting the valid record.  It would be great to just add an inline option to specify either the name of the nic, or the IP, after update-dns.

**Comment by dmorash-BT** [comment]
You should be able to do that currently. You can join without updating DNS via disabling the DDNS module, e.g. domainjoin-cli join --disable DDNS.   Then you can run update-dns with the --ipaddress option, e.g. update-dns --ipaddress 10.100.1.76

**Comment by bt-jq-it** [comment]
Ahh, thanks for that.  I didn't realize that you could only disable it at joining.  I'll need to script a leave and rejoin to get this into my machines.  Again, thanks for the quick response!

**Comment by sticks221** [comment]
Forgive the commenting on an old closed post but, did this work for anyone or does anyone have another solution? I have the same problem but no matter how hard I try, PBIS will not stop updating DNS with tens of 172 addresses.  Even the preview shows that it remains fully configured despite completely uninstalling (with purge) and reinstalling.

![image](https://user-images.githubusercontent.com/25580546/122917628-21a45c80-d356-11eb-882a-724684968000.png)

**Comment by bt-jq-it** [comment]
This works for me:

`domainjoin-cli join --disable DDNS domainnname domainadminusername`

note the spaces and the double dash before DDNS
