### ISSUE TITLE
How To Set Display Name Attribute?

### ISSUE THREAD

**Issue by TheVakman** [BeyondTrust/pbis-open#111]
Version: 8.5.7.385
OS/Distro: Ubuntu Desktop 16.04.4
Issue/Impact:
This is less of an issue and more of a question.

I am joining Ubuntu to Active Directory with PBIS Open but the name displayed in Ubuntu is the user's last name only.

I need the display name (as displayed at the Ubuntu login greeter and in menu dialogs) to be the sAMAccountName. Instead, it seems to be picking our displayName but cutting off the first name.
This is likely because for displayName, we use LastName, FirstName.

Is there a setting to change this?

**Comment by rbest-bt** [comment]
Thank you for your question and report. At this time there is no option to change what is displayed on the login screen. There is an issue with commas in the displayName truncating the display. I've logged a bug for it to be addressed.

**Comment by TheVakman** [comment]
@rbest-bt Thanks, it works really well otherwise from what I've tried so far but unfortunately, the last name only will be a showstopper here.

Could I log a separate one for a requested enhancement? As even if this bug was squashed, I'd still prefer to either show first name or username at the login screen instead of displayName.

**Comment by rbest-bt** [comment]
I agree it would be a good feature but are not sure when we'd get to it. I have logged the enhancement request to investigate so you do not need to log one in GitHub. If there are additional enhancement requests then feel free to log them.

Leaving this issue open to track the bug.

**Comment by TheVakman** [comment]
Thanks!

**Comment by rbest-bt** [comment]
pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
