### ISSUE TITLE
membership can not sync?

### ISSUE THREAD

**Issue by a-bian** [BeyondTrust/pbis-open#112]
**Version**: 8.5.7.385
**OS/Distro**: CentOS 6.9
**Issue/Impact**: membership can not sync

Already logged in to bash.
Then add the test user to the linux group in the DC.
At this point in the terminal to perform the following command found inconsistent

`[test@centos:/home]$ id
uid=1372063343(CN\test) gid=1372062209(CN\domain^users) groups=1372062209(CN\domain^users),137206397(CN\sudo)

[test@centos:/home]$ id test
uid=1372063343(CN\test) gid=1372062209(CN\domain^users) groups=1372062209(CN\domain^users),137206397(CN\sudo),1372063446(CN\linux)

[test@centos:/home]$ /opt/pbis/bin/lwsm list
lwreg           running (container: 15486)
dcerpc          stopped
eventlog        running (container: 15558)
lsass           running (container: 15769)
lwio            running (container: 15698)
netlogon        running (container: 15629)
rdr             running (io: 15698)
reapsysl        running (container: 15853)
usermonotor     stopped`

Attempted to restart related services and reset the NssGroupMembersQueryCacheOnly value.
Also tried ad-cache --delete-all ...
But there is no way to solve this problem.

This problem is in a VNC logged on by a colleague a long time ago. A permission error occurred when trying to create a new group in the last few days. But he actually belongs to this group. If he uses su his username in the current VNC terminal. This has permission. Personally guess whether the authorization information is not synchronized.

**Comment by rbest-bt** [comment]
The issue is that the user's group 1372063446(CN\linux) does not get reported for the user 'test' every time?

**Comment by a-bian** [comment]
If you exit the current terminal and log in again, the new user group can be retrieved. If you do not log in again, there is no way to get a new user group.

**Comment by rbest-bt** [comment]
Groups do not load dynamically in linux but at the time of login. This can be reproduced with local only users and groups. There are workarounds:
https://superuser.com/questions/272061/reload-a-linux-users-group-assignments-without-logging-out

**Comment by a-bian** [comment]
Thanks!  You are right！
