### ISSUE TITLE
PBISO - Sudo: I have existing sudoers, how to i integrate it with PBIS-Open

### ISSUE THREAD

**Issue by nyoukhana** [BeyondTrust/pbis-open#113]
**Version**: Latest
**OS**: IBM AIX
**How To**: 
I have existing sudo setup on my AIX Box already.
I have installed PBISO succesfully thereafter 
What are the next steps to test if sudoers works and or any configuration that needs to be done in PBIS Open?

Thank you
Ninos

**Comment by cboutilier-bt** [comment]
Hi @nyoukhana If you add your ad user to your sudoer's file, you can set PBIS to work with sudo in 2 different ways. 
1. You can add username to the sudoer's file. You will need to set the AssumeDefaultDomain config option to true if you do not specify the domain\\user in the sudoer's file.  This will allow you to sudo **without** the domain\\username. 
2. You can specify domain\\username in the sudoer's file. You will **NOT** need to set AssumeDefaultDomain to true in this case. 

In either case, if you ssh with an ad user and run sudo /opt/pbis/bin/get-status it will work. Let me know if there are any further questions.
