### ISSUE TITLE
Installing PBISO without rebooting AIX

### ISSUE THREAD

**Issue by nyoukhana** [BeyondTrust/pbis-open#114]
Good morning,

Is there a way to get PBISO working "authenticating" ad group.
without rebooting the AIX box. I cant afford to perform reboots.

I have restarted the following...
1. (PBISO) /opt/pbis/bin/lwsm restart lwio
2. (AIX) telinit  q 
3. (AIX) stopsrc -s sshd ; startsrc -s sshd
4. (PBISO) /opt/pbis/bin/ad-cache --delete-all

thank you
Ninos

**Comment by rbest-bt** [comment]
Do you have issues with authenticating without a reboot? The rebooting warning is mostly a catch all for issues around gdm and nscd. Are you running a caching service like nscd?

**Comment by nyoukhana** [comment]
GDM is the GNOME Display Manager - Not sure what the equivilent of this is for AIX

NSCD for AIX is netcd - Is not enable.
http://www-01.ibm.com/support/docview.wss?uid=swg21500565

**Comment by cboutilier-bt** [comment]
What issues are you having around authentication? Can you provide some more details like steps to reproduce and error messages?

**Comment by nyoukhana** [comment]
ssh or direct login doesn't work unless I reboot, after installing and joining AD. Is there a way to restart and AIX Services or additional PBISO services that will allow me to authenticate without an AIX reboot?

**Comment by rbest-bt** [comment]
LWIO should restart most of the ADB services, lsass handles authentication. I would start narrowing down if it's lsass or sshd that requires the restart.

From our testing, no reboot is required after an install/domainjoin.
