### ISSUE TITLE
samba-interop-install - ERROR_BAD_COMMAND

### ISSUE THREAD

**Issue by staundk** [BeyondTrust/pbis-open#116]
Compiled daemon version: 8.6.0.427
Packaged product version: 8.6.427.243473

**OS/Distro**: Ubuntu desktop 12.04 - Server
**Issue/Impact**:
We have a samba share on this server that breaks once in a while - usually it can be fixed with 

./samba-interop-install --install

But when running this command on the latest version of PBIS I now get an error

`Error: ERROR_BAD_COMMAND`

The error even happen if I just use --check-version. 
Server has been rebooted just in case something else was wrong.
looks like samba-interop-install is corrupt or!?

 1. systemctl status lwsmd.service : Running
 2. /opt/pbis/bin/lwsm list
`lwreg          running (container: 1060)
dcerpc         stopped
eventlog       running (container: 1108)
lsass          running (container: 1246)
lwio           running (container: 1199)
netlogon       running (container: 1154)
rdr            running (io: 1199)
reapsysl       running (container: 1297)
usermonitor    stopped
`
 3. /opt/pbis/domainjoin-cli query
  - Able to query our ActiveDirectory
 4. pbis status
  - Online
 5. /opt/pbis/bin/enum-users
  - getting a list of our users.
 6. attach logs
  - /opt/pbis/bin/lwsm set-log-target -p lsass -  file /tmp/lsass.log
  - /opt/pbis/bin/lwsm set-log-level -p lsass - debug
  - attach log

**Steps to Reproduce**:
 1. install command

./samba-interop-install --install
Error: ERROR_BAD_COMMAND

**Comment by RBoulton-BT** [comment]
samba-interop can take a --loglevel debug argument, does this provide any more details of the problem?

./samba-interop-install --loglevel debug --install

**Comment by staundk** [comment]
Hi,

the debug log shows : 

`[CaptureOutputWithStderr() /builder/src-git/Platform/src/linux/samba-interop/tools/samba-interop-install.c:337] Error code 22
[CheckSambaVersion() /builder/src-git/Platform/src/linux/samba-interop/tools/samba-interop-install.c:486] Error code 22
[main() /builder/src-git/Platform/src/linux/samba-interop/tools/samba-interop-install.c:1626] Error code 22
Error: ERROR_BAD_COMMAND
`

**Comment by RBoulton-BT** [comment]
Unfortunately that didn't tell us much.

It tries to find smbd in the path:
/usr/sbin:/usr/local/sbin:/usr/local/samba/sbin:/opt/csw/samba/sbin:/opt/sfw/samba/sbin:/opt/csw/bin:/usr/local/bin

and then runs <path>/smbd -V

Where is your smbd located? 
What happens when you try to run smbd -V?

If your preferred smbd is not located in the path above, you can specify id on the commandline:

./samba-interop-install --install /my/special/smbd

**Comment by staundk** [comment]
Something has f.... up my samba installation. After a purge of samba and a reinstall it works again. Thank you for leading me to this.
