### ISSUE TITLE
PBIS is not recognizing DUO as a PAM module in the server

### ISSUE THREAD

**Issue by diegofduarte** [BeyondTrust/pbis-open#119]
**Version**: 8.5.3.293
**OS/Distro**: CentOS 7 (AWS version)
**Issue/Impact**:

We use DUO to authenticate users using 2MFA, and PBIS is complaining about it. it asked to attach our pam.d entries for /lib64/security/pam_duo.so, so here is:

The usual domainjoin join command returns the error.

```
#%PAM-1.0
# This file is auto-generated.
# User changes will be destroyed the next time authconfig is run.
auth        required      pam_env.so
auth  requisite pam_unix.so nullok try_first_pass
auth  sufficient /lib64/security/pam_duo.so
auth        requisite     pam_succeed_if.so uid >= 1000 quiet_success
auth        required      pam_deny.so

account     required      pam_unix.so
account     sufficient    pam_localuser.so
account     sufficient    pam_succeed_if.so uid < 1000 quiet
account     required      pam_permit.so

password    requisite     pam_pwquality.so try_first_pass local_users_only retry=3 authtok_type=
password    sufficient    pam_unix.so sha512 shadow nullok try_first_pass use_authtok
password    required      pam_deny.so

session     optional      pam_keyinit.so revoke
session     required      pam_limits.so
-session     optional      pam_systemd.so
session     optional      pam_mkhomedir.so umask=0077
session     [success=1 default=ignore] pam_succeed_if.so service in crond quiet use_uid
session     required      pam_unix.so
```

When reporting an issue it's important that we have as much detail as you can provide. The following is a list of commands to check.

 1. systemctl status lwsmd.service
```
Apr 09 17:03:56 ip-10-147-7-222 systemd[1]: Started BeyondTrust PBIS Service Manager.
Apr 09 17:03:56 ip-10-147-7-222 netlogon[992]: [netlogon] Missing client site name from DC response from xxxxxxxxxxxx.CORP (10.143.101.117)
Apr 09 17:04:00 ip-10-147-7-222 lwio[1040]: [lwio] GSS-API error calling gss_init_sec_context: 851968 (Unspecified GSS failure.  Minor code may provide more information)
Apr 09 17:04:00 ip-10-147-7-222 lwio[1040]: [lwio] GSS-API error calling gss_init_sec_context: -1765328353 (Decrypt integrity check failed)
Apr 09 17:04:00 ip-10-147-7-222 lsass[1082]: [lsass] Ignoring failure enumerating trusts for forest xxxxxxxx.CORP. Error was ERROR_GEN_FAILURE (31)
```

 2. /opt/pbis/bin/lwsm list

```
[centos@ip-10-147-7-222 ~]$ /opt/pbis/bin/lwsm list
lwreg          running (container: 894)
dcerpc         stopped
eventlog       running (container: 960)
lsass          running (container: 1082)
lwio           running (container: 1040)
netlogon       running (container: 992)
rdr            running (io: 1040)
reapsysl       running (container: 1181)
usermonitor    stopped
```

 3. /opt/pbis/domainjoin-cli query

(run after reboot)
```
[centos@ip-10-147-7-222 opt]$ sudo /opt/pbis/bin/domainjoin-cli query
Name = ip-10-147-7-222
Domain = xxxxxx.CORP
Distinguished Name = CN=IP-10-147-7-222,CN=Computers,DC=xxxxxxxx,DC=CORP
```

 4. pbis status
```
(cant show, but return the whole forest and directories as expected)
```
 5. /opt/pbis/bin/enum-users
(cant show, but enum all the users as expected)

**Output/Error**:

Warning: System restart required
Your system has been configured to authenticate to Active Directory for the first time.  It is recommended that you restart your system to ensure that all applications recognize the new settings.

Error: Unknown PAM module [code 0x0000a609]

The PowerBroker Identity Services PAM module cannot be configured for the sshd service. This service uses the '/lib64/security/pam_duo.so' module, which is not in this program's list of known modules. Please email PowerBroker Identity Services technical support and include a copy of /etc/pam.conf or /etc/pam.d.

**Steps to Reproduce**:
 1. install command
 2. Domainjoin command
 3. Command that returns issue

**Comment by diegofduarte** [comment]
(edited with some outputs)

**Comment by rbest-bt** [comment]
We modify the PAM files on domainjoin. On the save side we fail with Unknown PAM module to prevent messing up the PAM configuration with unknown PAM modules.

Work around
1. Remove pam_duo.so from your pam files
2. Issue domainjoin
3. Add pam_duo.so to your pam files
