### ISSUE TITLE
Upgrade overwrote files in /etc/pam.d/

### ISSUE THREAD

**Issue by kefir-** [BeyondTrust/pbis-open#12]
I am running Ubuntu 16.04.1 LTS with recent PBIS software (installed from the PPA), and recently received updates to versions:

- pbis-open-upgrade 8.5.2.265
- pbis-open 8.5.2.265

After this, no domain logins worked any more. Local logins worked fine. After some debugging, I found that several files in /etc/pam.d/ had been replaced when I updated some packages. The offending files included:

- /etc/pam.d/common-account
- /etc/pam.d/common-auth
- /etc/pam.d/common-password
- /etc/pam.d/common-session
- /etc/pam.d/common-session-noninteractive

All these files had been renamed to *.lwidentity.orig, (which sounds like it has something to do with likewise) and had been replaced with files without any reference to pam-lsass. When I reinstated all the *.lwidentity.orig files, domain users immediately started working again.

All the *.lwidentity.orig files are dated 2 Jan 2017, 15:57:17. Reading **/var/log/apt/term.log**, I see from the latest update:

```
Log started: 2017-01-02  15:56:54
(Reading database ...)
<snip>
Setting up pbis-open-upgrade (8.5.2.265)
Setting up pbus-open (8.5.2.265)
Importing registry...

<snip>
Log ended: 15:57:34
```

**Comment by rbest-bt** [comment]
I have not seen this but I will give it a try. I'm happy to hear the .orig files worked for you. Have you come across this issue in the 8.5.3 and 8.5.4 releases?

NOTE: PowerBroker Identity Services is the new product name for likewise Identity Services after being acquired by [Beyond Trust](https://www.beyondtrust.com/)
