### ISSUE TITLE
Use UNIX Attributes instead of AD UID/GID

### ISSUE THREAD

**Issue by tmatthaeus** [BeyondTrust/pbis-open#120]
Is there a way to use the UID/GID from UNIX Attributes in my linux machine, connected to the ActiveDirectory via PBIS?
Currently now I am testing with PBIS-OPEN 8.6.0.427.

id USERNAME is giving me back the UID/GID from the AD:
uid=2115504596(tma) gid=2115502593(domain^users) groups=2115502593(domain^users),2115503216(it),2115503091(others)

But I need the UID/GID from the Unix Attributes:
uid=60620(tma)

Is there any way to configure this?
![bildschirmfoto 2018-04-10 um 14 29 30](https://user-images.githubusercontent.com/1618310/38557179-7223f1f8-3ccc-11e8-81a7-5b59ddb90378.png)

**Comment by rbest-bt** [comment]
PBIS open generates uid and gid for each user and group. This allows users to work without the Active Directory setup. Using the Active Directory POSIX Attributes is not possible with open.

If you would like to use the Active Directory Attributes instead you can try [PBIS Entreprise](https://www.beyondtrust.com/products/powerbroker-identity-services-ad-bridge/) with a Default Cell setup.

**Comment by tmatthaeus** [comment]
And with PBIS Enterprise it is possible to have the POSIX groups?

**Comment by rbest-bt** [comment]
Yes both users and groups provisioned to the default cell store their information in the POSIX attributes. More information in the [Installation ](https://github.com/BeyondTrust/pbis-open/wiki/docs/PBIS_Installation_Guide.pdf)and [Administration ](https://github.com/BeyondTrust/pbis-open/wiki/docs/PBIS_Administration_Guide.pdf) guides under the wiki.
