### ISSUE TITLE
UPN vs Slash Format Authentication Issues - SSH using trusted child domain

### ISSUE THREAD

**Issue by linsona** [BeyondTrust/pbis-open#121]
**Version**: All versions
**OS/Distro**: Amazon Linux

**Issue/Impact**:
We are facing an issue using pbis-open when sshing into a remote linux box using UPN formatting versus slash formatting, specifically for trusted child domains.
 
Scenario: We have a user called “test_user” in a trusted child domain called child1.roota.corp
 
When sshing using pbis and UPN formatting:

`$ ssh test_user@child1.RootA.corp@W.X.Y.Z`
We get a permission denied.
 
When sshing using pbis and slash formatting:
`$ child1.RootA.corp\\test_user@W.X.Y.Z`
We get authenticated correctly, and sshing using UPN format is also successful after. (The host is now aware of the trusted child domain after the successful auth using slashes – verified using $ pbis status)
 
After looking at the packet capture for initial ssh login using UPN formatting, a “DsrGetDcName” RPC call is made to locate the child domain in the trusted AD. PBIS uses the NetBIOS domain name (CHILD1), and subsequently fails. Attached screen grab (upnformat.png)
 
After looking at the packet capture for initial ssh login using slash formatting, a “DsrGetDcName” RPC call is made to locate the child domain in the trusted AD. PBIS uses the full child domain FQDN (child1.RootA.corp) and succeeds. Attached screen grab (slashformat.png)

![slashformat](https://user-images.githubusercontent.com/38224693/38585318-44c8c4ca-3cce-11e8-9080-7884fc016603.png)
![upnformat](https://user-images.githubusercontent.com/38224693/38585319-44dfc22e-3cce-11e8-9d11-595d784e5733.png)

**Comment by cboutilier-bt** [comment]
I believe that there is a bug here. However, we need a few more details. 

What version of PBIS are you using? Additionally, can you run the following commands and attach the log file. If you could reproduce this on a failed attempt and a valid attempt, that would be great. 

You can do that by running the following commands: 
/opt/pbis/bin/lwsm set-log-target -p lsass - file /tmp/lsass.log
/opt/pbis/bin/lwsm set-log-level -p lsass - debug

**Comment by linsona** [comment]
Thanks for the reply. I am attaching a file named "pbis_user_and_status.txt" describing the trusted child domain user and the output of "$ pbis status" after successful auth. I am also attaching the lsass.log file:

When sshing using pbis and UPN formatting:
`$ ssh test_user@child1B.rootB.corp@10.99.3.143`
We get a permission denied.
Attached file: `lsass_failed.log`
 
When sshing using pbis and slash formatting:
`$ ssh child1B.rootB.corp\\test_user@10.99.3.143`
Successful auth.
Attached file: `lsass_passed.log`

And as mentioned, `ssh test_user@child1B.rootB.corp@10.99.3.143` works after using slash formatting. (Trusted child domain cached on system)

Note: AXXXXXXXXXXXX -- account_id references have been redacted.

[pbis_user_and_status.txt](https://github.com/BeyondTrust/pbis-open/files/1929732/pbis_user_and_status.txt)
[lsass_passed.log](https://github.com/BeyondTrust/pbis-open/files/1929733/lsass_passed.log)
[lsass_failed.log](https://github.com/BeyondTrust/pbis-open/files/1929734/lsass_failed.log)

**Comment by linsona** [comment]
Any update on this issue?

**Comment by wmalcolm** [comment]
Any update on this issue?

**Comment by rbest-bt** [comment]
not at this time

**Comment by wmalcolm** [comment]
Any update on this issue at this time?

**Comment by rbest-bt** [comment]
Any updates will be posted here. There are none at this time.

**Comment by rbest-bt** [comment]
Please upgrade to Active Directory Bridge Enterprise. If the issue still exists then please submit a ticket to our service team and we’ll have a look for you.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
