### ISSUE TITLE
make package fails on Ubuntu 16.04 - Missing header files error

### ISSUE THREAD

**Issue by viralmutant** [BeyondTrust/pbis-open#124]
**Version**: 8.5.4.334
**OS/Distro**: Ubuntu desktop 16.04 - unity desktop
**Issue/Impact**:
Unable to make package on Ubuntu.

**Output/Error**:
```
           [compile] lwsm/server/main.c (host/x86_64)
../lwsm/server/main.c:40:20: fatal error: ctexec.h: No such file or directory
compilation terminated.
           [compile] FAILED: 'gcc' '-m64' '-O0' '-g' '-Wall' '-Werror' '-Wmissing-prototypes' '-I../lwsm/server/.' '-Iobject/lwsm/server/.' '-I../lwsm/server/../include' '-Iobject/lwsm/server/../include' '-DDEBUG=1' '-DLWSM_DISABLE_DEPRECATED' '-DLWSM_BUILD' '-Istage/opt/pbis/include' '-DHAVE_CONFIG_H' '-D_MK_HOST_X86_64' '-D_MK_HOST' '-fPIC' '-MMD' '-MP' '-MF' '.MakeKitDeps/object_lwsm_server_main.lwsmd.host.x86_64.dep' '-o' 'object/lwsm/server/main.lwsmd.host.x86_64.o' '-c' '../lwsm/server/main.c'
Makefile:7499: recipe for target 'object/lwsm/server/main.lwsmd.host.x86_64.o' failed
make: *** [object/lwsm/server/main.lwsmd.host.x86_64.o] Error 1
```

**Steps to Reproduce**:
 1. configure succeeded after installing all the dependencies
 2. `make package` however failed with error posted above

**Steps taken to Debug 1**:
- It seems it's unable to find that header file placed at ../centutils/include/ directory

**Workaround 1**:
- Ran that failed gcc manually with an additional -I directive
```
'gcc' '-m64' '-O0' '-g' '-Wall' '-Werror' '-Wmissing-prototypes' '-I../lwsm/server/.' '-Iobject/lwsm/server/.' '-I../lwsm/server/../include' '-Iobject/lwsm/server/../include' '-DDEBUG=1' '-DLWSM_DISABLE_DEPRECATED' '-DLWSM_BUILD' '-Istage/opt/pbis/include' '-I../centutils/include' '-DHAVE_CONFIG_H' '-D_MK_HOST_X86_64' '-D_MK_HOST' '-fPIC' '-MMD' '-MP' '-MF' '.MakeKitDeps/object_lwsm_server_main.lwsmd.host.x86_64.dep' '-o' 'object/lwsm/server/main.lwsmd.host.x86_64.o' '-c' '../lwsm/server/main.c'
```

`make package` proceeds further until it hits another roadblock:
```
[compile] domainjoin/domainjoin-cli/src/main.c (host/x86_64)
../domainjoin/domainjoin-cli/src/main.c:39:23: fatal error: linenoise.h: No such file or directory
compilation terminated.
           [compile] FAILED: 'gcc' '-m64' '-O0' '-g' '-Wall' '-Werror' '-I../domainjoin/domainjoin-cli/src/../include' '-Iobject/domainjoin/domainjoin-cli/src/../include' '-I../domainjoin/domainjoin-cli/src/../../include' '-Iobject/domainjoin/domainjoin-cli/src/../../include' '-I../domainjoin/domainjoin-cli/src/../../libdomainjoin/include' '-Iobject/domainjoin/domainjoin-cli/src/../../libdomainjoin/include' '-DDEBUG=1' '-Istage/opt/pbis/include' '-DHAVE_CONFIG_H' '-D_MK_HOST_X86_64' '-D_MK_HOST' '-fPIC' '-MMD' '-MP' '-MF' '.MakeKitDeps/object_domainjoin_domainjoin-cli_src_main.domainjoin-cli.host.x86_64.dep' '-o' 'object/domainjoin/domainjoin-cli/src/main.domainjoin-cli.host.x86_64.o' '-c' '../domainjoin/domainjoin-cli/src/main.c'
Makefile:12925: recipe for target 'object/domainjoin/domainjoin-cli/src/main.domainjoin-cli.host.x86_64.o' failed
make: *** [object/domainjoin/domainjoin-cli/src/main.domainjoin-cli.host.x86_64.o] Error 1
```

**Steps taked to Debug 2**:
- It seems it's now unable to locate header file placed at ../linenoise/ directory

**Workaround 2**:
- Help failed gcc make the object file by manually running with an additional -I directive
```
'gcc' '-m64' '-O0' '-g' '-Wall' '-Werror' '-I../domainjoin/domainjoin-cli/src/../include' '-Iobject/domainjoin/domainjoin-cli/src/../include' '-I../domainjoin/domainjoin-cli/src/../../include' '-Iobject/domainjoin/domainjoin-cli/src/../../include' '-I../domainjoin/domainjoin-cli/src/../../libdomainjoin/include' '-Iobject/domainjoin/domainjoin-cli/src/../../libdomainjoin/include' '-I../linenoise' '-DDEBUG=1' '-Istage/opt/pbis/include' '-DHAVE_CONFIG_H' '-D_MK_HOST_X86_64' '-D_MK_HOST' '-fPIC' '-MMD' '-MP' '-MF' '.MakeKitDeps/object_domainjoin_domainjoin-cli_src_main.domainjoin-cli.host.x86_64.dep' '-o' 'object/domainjoin/domainjoin-cli/src/main.domainjoin-cli.host.x86_64.o' '-c' '../domainjoin/domainjoin-cli/src/main.c'
```

Finally `make package` succeeds

**Comment by rbest-bt** [comment]
If your able to reproduce this issue can you double check whether ctexec.h actually gets created under the staging folder? If it's not then this is a new issue. If it does exists then it's a race condition we've seen fixed using -j option to limit the job count.

**Comment by viralmutant** [comment]
I am still observing failures, with the latest code, but things have changed.

`../configure --debug` failed too with error
`[lwbase] endianness (host/x86_32):             [lwbase] ERROR: could not determine endianness`

Had to use other flags with configure
`../configure --debug=yes --build-isas=x86_64`

configure succeeded after that.

 'make package' still failed, but this time for another .h file:
`In file included from ../lwsm/server/main.c:40:0:
stage/opt/pbis/include/ctexec.h:61:19: fatal error: lwexc.h: No such file or directory`

There is no lwexc.h under debug directory.
`root@ubuntu1604:~/pbis-open/debug# find . -name lwexc.h
root@ubuntu1604:~/pbis-open/debug# find ../ -name lwexc.h
../centutils/include/lwexc.h`

**Comment by rbest-bt** [comment]
If you try the following does it succeed?
> make -j2 package

**Comment by viralmutant** [comment]
Nope, same error

**Comment by RBoulton-BT** [comment]
I usually find a make all will resolve most dependencies, so you could try "make -j2 all package" and see if that helps.

**Comment by viralmutant** [comment]
Yes, 'make all package' seems to resolve this
