### ISSUE TITLE
Reinstalling pbis-open modifies common-auth to disallow all logins

### ISSUE THREAD

**Issue by viralmutant** [BeyondTrust/pbis-open#125]
**Version**: 8.5.4.334
**OS/Distro**: Ubuntu desktop 16.04 - unity desktop
**Issue/Impact**:
*Unable to login with any user, including root*

**Output/Error**:
- Did a build of pbis-open, joined to active directory domain.
- Then modified nsswitch.conf and common-auth PAM file as follows:
`passwd:         compat lsass
group:          compat lsass
`
`auth    [success=1 default=ignore]      pam_unix.so nullok_secure
auth        sufficient    pam_lsass.so try_first_pass disable_password_change
`
**Steps to Reproduce**:
1. Made some change to source code and rebuilt
2. Reinstalled, at it moved original 'common-auth' to 'common-auth.lwidentity.orig'
3. Generated new common-auth, removing the lsass line, as:
`auth    [success=0 default=ignore]      pam_unix.so nullok_secure
...`

**Now here is the problem, success=0. This disallows all logins, including local users, to my machine. Had to reboot in single user mode and recover**

**Comment by rbest-bt** [comment]
Modifying the code, nsswitch, and pam configuration can have this effect. Without access to all the files/changes/system it would be hard to track down. 

If you would like to modify pam or any other part of the authentication process, I would recommend using pamtester to confirm that the modifications will work.
