### ISSUE TITLE
User in nested AD groups causes a login hang

### ISSUE THREAD

**Issue by dvosbury** [BeyondTrust/pbis-open#127]
**Version**: 8.5.2.265 and 8.6.0.427
**OS/Distro**: Centos 6.5 and 7.3.1611
**Issue/Impact**: User unable to login

**Steps to Reproduce**:
 1. Add a user to an AD group that is a member of around 200 other groups.
 2. The nested groups are setup so that a Nosudo group is a member of server1nosudo group, server2nosudo group etc. Each servernosudo group is listed in the requiremembershipof parameter so that the members of the nosudo group can login to each of the servers. But it also gives the flexibility to just add a user to say server2nosudo group so that they can login to server2 only.
 2. When logging in the user shell hangs.
 3. The only way to fix the issue is to delete and recreate a new account for the user. Put them in a non-nested group that has login access to all systems. Remove the account from that group and then add them back to the nested group. Although, this doesn't seem to be a permanent solution as I've had to recreate the AD account a third time already. I have two other account setup like this that don't have this problem as far as I know.

Is there some limitation or bug in PBISO where you can't use nested groups. ie. User is a member of nosudo group. Nosudo group is a member of server1nosudo group, server2nosudo group etc.?

I ran several of the troubleshooting steps like turning on PAM debug logging etc. The only error that I come up with that might mean something is this:

su: [lsass-pam] [module:pam_lsass]LsaPamNotifyUserLogon failed [login:user][error code: 40058] 

This error was produced when I su'ed from my working account to this user's account and the login hangs. The account actually shows up as logged in if you look at the process list, but they never get a prompt. Sometimes if you ctrl-c to get out of the hung login you get a core-dump error, but no core dump is actually produced.

Other accounts that are just a member of a group that has access to all systems work fine.

I tried looking for a user forum to ask this question before submitting a bug report, but couldn't find one for PBIS-Open. Is there a user forum for PBISO?

**Comment by dvosbury** [comment]
I could use some help in determining if this is a bug in PBISO or I need to reconfigure the agent in some way. I've been using the software for some time with no major issues. Is there some log files that you'd like me to provide. This problem is not isolated to just one system, but many. However, the problem only seems to affect users that utilize this AD group structure I explained.

**Comment by cboutilier-bt** [comment]
You can set the debug logging on lsass.
/opt/pbis/bin/lwsm set-log-target -p lsass - file /tmp/lsass.log
/opt/pbis/bin/lwsm set-log-level -p lsass - debug

If you want to upload the debug file, that will help us narrow it down.

**Comment by dvosbury** [comment]
Here is the lsass debug log you requested. It has entries from when trying to login to a problem account.
[lsass.log](https://github.com/BeyondTrust/pbis-open/files/1960750/lsass.log) Let me know if you need anything else to help troubleshoot the issue. Once I remove the user from AD and recreate the account with the user a member of a smaller number of groups, they are able to login successfully, if that helps.

**Comment by rbest-bt** [comment]
Please upgrade to Active Directory Bridge Enterprise. If the issue still exists then please submit a ticket to our service team and we’ll have a look for you.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
