### ISSUE TITLE
Fedora 28 - Error during installation of pbis-open 8.6.0

### ISSUE THREAD

**Issue by antoniotvr** [BeyondTrust/pbis-open#128]
Hi.

I have enabled yum repo as indicated here:

https://repo.pbis.beyondtrust.com/yum.html

Then I have tried to install pbis-open with commands indicated:

sudo yum clean all 
sudo yum install pbis-open

but I obtain the following error:

Problem: conflicting requests
  - nothing provides sh-utils needed by pbis-open-8.6.0-427.x86_64

I have found that "sh-utils" is part of "coreutils" package:

yum search sh-utils

Last metadata expiration check: 0:16:33 ago on Mon 07 May 2018 10:09:34 AM CEST.
============================ Description Matched: sh-utils =============================
coreutils.x86_64 : A set of basic GNU tools commonly used in shell scripts

that is yet installed.

How can I solve this issue?

Thank you

**Comment by antoniotvr** [comment]
I found by doing a search in your repository that maybe it would be enough to update the ini files you use to compile rpm packages.

In Fedora, but also in CentOS, sh-utils are in coreutils package.

This cause an installation error.

Thank you

**Comment by antoniotvr** [comment]
Another note (maybe useful for you): sh-utils is the Debian nomenclature of the package. So I think that a simple change of ini files must solve the issue.

Regards

**Comment by rbest-bt** [comment]
I'll have a look. Hopeful that's all it is with no impact elsewhere

**Comment by antoniotvr** [comment]
Thank you for your answer.


Il giorno lun 7 mag 2018 alle 14:47 rbest-bt <notifications@github.com> ha
scritto:

**Comment by johu** [comment]
Looks like it is already fixed in master 5517ac69cb90a39a3e38d2709a5194c3f0d11bda. When can we expect a updated package in fedora/centos?

**Comment by nning** [comment]
It seems, 5517ac6 already fixes this issue; when can we expect an updated release?

Thanks!

**Comment by nning** [comment]
Great, thanks for the update!

**Comment by rbest-bt** [comment]
Just uploaded the [8.6.1-beta.1](https://github.com/BeyondTrust/pbis-open/releases/tag/8.6.1-beta.1) which includes this change.

**Comment by nning** [comment]
Thanks for releasing a beta!

I updated to the beta version and did a release upgrade to Fedora 28. After rebooting, GNOME login manager does not show domain accounts anymore and also manually specifying my domain user does not work.

Do you have a clue what could have went wrong here?

I will try to provide logs or further information tomorrow.

Thanks very much!

**Comment by nning** [comment]
`lwsmd` needs libnsl so it seems the package for Fedora 28 has to depend to the libnsl package. Now everything works like a charm. Thank you very much!

**Comment by GlennSmeulders** [comment]
@nning How did you manage to resolve this issue? I've been having the same problem with the latest version of Fedora. Thanks!

**Comment by GlennSmeulders** [comment]
@rbest-bt I still receive the error:
`domainjoin-cli: error while loading shared libraries: libnsl.so.1: cannot open shared object file: No such file or directory`

**Comment by johu** [comment]
@GlennSmeulders  This is what I have done to update to Fedora 28 including the new pbis-open version

`dnf install libnsl --releasever=28 # Missing dep for pbis-open 8.6.1
dnf install nss-pem-1.0.3-9.fc28 --releasever=28 # Known bug
wget https://github.com/BeyondTrust/pbis-open/releases/download/8.6.1-beta.1/pbis-open-8.6.1.455.linux.x86_64.rpm.sh
sh pbis-open-8.6.1.455.linux.x86_64.rpm.sh
rm -f /etc/yum.repos.d/pbiso.repo
dnf upgrade --refresh
dnf system-upgrade download --releasever=28
dnf remove orca # Improve performance in Gnome
dnf system-upgrade reboot
`

**Comment by rbest-bt** [comment]
sh-utils fixed with 5517ac69cb90a39a3e38d2709a5194c3f0d11bda which is in 8.7.0

We are working on libnsl and ncurses for the next release

**Comment by rbest-bt** [comment]
ncurses was replaced in 8.7.1 with 
- 113326 - libedit replaced with linenoise

**Comment by antoniotvr** [comment]
Thank you

Il giorno lun 19 nov 2018 alle 21:34 rbest-bt <notifications@github.com> ha
scritto:
