### ISSUE TITLE
login with an e-mail address and password possible?

### ISSUE THREAD

**Issue by ickbinhier** [BeyondTrust/pbis-open#13]
Hello,

I run several Ubuntu 16.04 computers with pbis open against an AD authetify. Login with username and password is also running.

Is a login with an e-mail address and password possible? Since I have found nothing in the documentation, I ask the question here.

**Comment by RBoulton-BT** [comment]
I don't believe it's possible to use the email address (mail attribute) to perform logon. 

You can use either the NT4 style <DOMAIN>\<sam account name> or the UPN <account name>@<DNS domain name>

It may be possible to make your UPN match your email address.
