### ISSUE TITLE
Solaris Package?

### ISSUE THREAD

**Issue by jrose84** [BeyondTrust/pbis-open#130]
I current handle configuration management using ansible and deploy PBIS to CentOS systems using the standard package management modules. However, the Solaris installs available do not conform to the standard packages that are used to install software on SunOS. I was curious why SunOS installs are handled this way but from other platforms, you're using standard packages (e.g. RPM for RHEL).

**Comment by rbest-bt** [comment]
In Enterprise we supply a p5p file to upload PBIS file a local repository.

Information on this is in the [installation guide](https://github.com/BeyondTrust/pbis-open/wiki/docs/PBIS_Installation_Guide.pdf)
