### ISSUE TITLE
Unable to log into alternative domain in forest.

### ISSUE THREAD

**Issue by KevinAslett** [BeyondTrust/pbis-open#131]
**Version**: 8.6.0.427
**OS/Distro**: Ubuntu desktop 16.04 - unity desktop
**Issue/Impact**: Unable to login on alternative domain after Horizon 7 clone.
I have a gold master VM that is joined to our staff domain which is part of a forest. I can log into this VM with a user in the staff domain. I can also login with a user in the student domain which is also part of the same forest.  However, when I login to a cloned VDI session, I can only login with user accounts in the staff domain, not the student domain.

**Output/Error**:
![image](https://user-images.githubusercontent.com/40014176/41077390-f059c634-6a48-11e8-9867-26fab86f966e.png)

[lsass.log](https://github.com/BeyondTrust/pbis-open/files/2078877/lsass.log)

.
**Steps to Reproduce**:
 1. install command
![image](https://user-images.githubusercontent.com/40014176/41077449-3253be50-6a49-11e8-8f95-9fdac074133d.png)
.

 2. Domainjoin command
I used the gui
 3. Command that returns issue
# su student\\username

**Comment by rbest-bt** [comment]
Going off this statement
> I have a gold master VM that is joined to our staff domain which is part of a forest. 

The master image should not be at a joined state. It's ok with pbis installed but the join creates a few things that are unique to the machine: computer object, machine password, krb5 ticket.

I recommend creating an image with pbis installed. After a clone change the hostname and join the domain.

**Comment by KevinAslett** [comment]
The Horizon View agent handles the clone rename and re-join to the domain.

If I remove it from the domain first, the whole process fails.  Thanks for your reply, but this is a specific issue to using PBIS with Horizon View.

Thanks

Kevin Aslett
Systems Engineer | CITS@MOE

Curtin University
Tel | +61 8 9266 1022
Email | k.aslett@curtin.edu.au<https://sixprd0210.outlook.com/owa/redir.aspx?C=PLRXm6bdvEGmLoLra3uzlU1QkTXig88IQDth5vzZd_T5Gp6x8uEZK9tyDoCzECoNs_ZrbcrqiQM.&URL=mailto%3ak.aslett%40curtin.edu.au>
Web | http://curtin.edu.au<https://sixprd0210.outlook.com/owa/redir.aspx?C=PLRXm6bdvEGmLoLra3uzlU1QkTXig88IQDth5vzZd_T5Gp6x8uEZK9tyDoCzECoNs_ZrbcrqiQM.&URL=http%3a%2f%2fcurtin.edu.au%2f>


Curtin University is a trademark of Curtin University of Technology.
CRICOS Provider Code 00301J

**Comment by mayfield1814** [comment]
I have this issue as well. I followed this link to create my vm's, https://virtualizationreview.com/articles/2018/03/30/how-to-create-a-linux-instant-clone-for-horizon.aspx but ran into the issues mentioned above. Users in the domain can log in, but those in a different domain cannot.
Thanks in advance for your help.

**Comment by rbest-bt** [comment]
Were the clones from a joined state? The linked setup do not address the potential of conflicting hostnames or computer objects. 

- What does the lsass logs show for the failed login?

**Comment by rbest-bt** [comment]
No response. Closing issue
