### ISSUE TITLE
AssumeDefaultDomain not working, maybe due to lowercase NetBIOS name

### ISSUE THREAD

**Issue by andreasbergen** [BeyondTrust/pbis-open#133]
**Version**: 8.6.0.427
**OS/Distro**: SLES 12.3
**Issue/Impact**:
I do have an active directory domain and a linux box joined to it. Anyway when I configure AssumeDefaultDomain it seems to work only partially: While "id shortusername" gives a result, it does so using a name with the domain-name:

root-> id fhdadm
uid=1249380406(FLWAFOSRZ\fhdadm) gid=1249378817(FLWAFOSRZ\domain^users) groups=1249378817(FLWAFOSRZ\domain^users),1249379480(FLWAFOSRZ\sapinst),1249379481(FLWAFOSRZ\sapsys)

I guess this might be due to the fact that the NetBIOS name is in lowercase.

Any idea what could be the reason?

Here's some additional output:

[flw501:/opt/pbis/bin]14:53
root-> /opt/pbis/bin/config --details AssumeDefaultDomain
Name: AssumeDefaultDomain
Description: Apply domain name prefix to account name at logon
Type: boolean
Current Value: true
Accepted Values: true, false
Current Value is determined by local policy.

[flw501:/opt/pbis/bin]14:53
root-> /opt/pbis/bin/config --details UserDomainPrefix
Name: UserDomainPrefix
Description: Domain short name prefix to be used when AssumeDefaultDomain setting is enabled
Type: string
Current Value: "FLWAFOSRZ"
Current Value is determined by local policy.

flw501:/opt/pbis/bin]14:59
root-> /opt/pbis/bin/enum-users
User info (Level-0):
====================
Name:              FLWAFOSRZ\guest
Uid:               1249378805
Gid:               1249378818
Gecos:             <null>
Shell:             /bin/sh
Home dir:          /home/local/FLWAFOSRZ/guest

User info (Level-0):
====================
Name:              FLWAFOSRZ\krbtgt
Uid:               1249378806
Gid:               1249378817
Gecos:             <null>
Shell:             /bin/sh
Home dir:          /home/local/FLWAFOSRZ/krbtgt

User info (Level-0):
====================
Name:              FLWAFOSRZ\administrator
Uid:               1249378804
Gid:               1249378817
Gecos:             <null>
Shell:             /bin/sh
Home dir:          /home/local/FLWAFOSRZ/administrator

...

[lsass.log](https://github.com/BeyondTrust/pbis-open/files/2098774/lsass.log)

**Comment by rbest-bt** [comment]
pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
