### ISSUE TITLE
domainjoin fails Solaris 10 branded zone on Solaris 11

### ISSUE THREAD

**Issue by jmresume** [BeyondTrust/pbis-open#134]
**Version**: 8.6.1.455
**OS/Distro**: Solaris 10 Sparc Jan18 Critical Patch Update applied
**Issue/Impact**: Cannot join domain, interesting effect is on /etc/krb5.keytab, becomes a link to itself.
lrwxrwxrwx   1 root     root          16 Jun 13 16:07 krb5.keytab -> /etc/krb5.keytab
have to issue an find . -inum #### -exec rm {} \; to remove it.

 1. svcs -a|grep lwsmd
online         16:04:16 svc:/network/lwsmd:default

 2. /opt/pbis/bin/lwsm list
lwreg          running (container: 1514)
dcerpc         stopped
eventlog       running (container: 1515)
lsass          running (container: 1518)
lwio           running (container: 1517)
netlogon       running (container: 1516)
rdr            running (io: 1517)
reapsysl       running (container: 1519)
usermonitor    stopped

 3. /opt/pbis/domainjoin-cli query
Name = oraappprod02
Domain =
 4. pbis status
LSA Server Status:

Compiled daemon version: 8.6.1.455
Packaged product version: 8.6.455.443
Uptime:        0 days 0 hours 6 minutes 28 seconds

[Authentication provider: lsa-activedirectory-provider]

        Status:        Unknown
        Mode:          Unknown

 5. /opt/pbis/bin/enum-users

 6. attach logs
  - /opt/pbis/bin/lwsm set-log-target -p lsass -  file /tmp/lsass.log
  - /opt/pbis/bin/lwsm set-log-level -p lsass - debug
  - attach log

**Output/Error**:
20180613161315:ALWAYS:LwSmSetMaxLogLevel():lwsm/server/logger.c:662: Log level changed to DEBUG
20180613161344:VERBOSE:lsass:LsaSrvIpcCheckPermissions():lsass/server/api/ipc_state.c:79: Permission granted for (uid = 0, gid = 0, pid = -1
) to open LsaIpcServer
20180613161344:VERBOSE:lsass-ipc:lwmsg_peer_log_accept():lwmsg/src/peer-log.c:230: (session:00a9a1d08631199b-d32f90c7381ec623) Accepted <loc
al euid:0 egid:0 pid:-1>
20180613161344:DEBUG:lsass:AD_JoinDomain():lsass/server/auth-providers/ad-open-provider/provider-main.c:2441: Joining domain DOMAIN.COM
20180613161344:VERBOSE:lsass:AD_JoinDomain():lsass/server/auth-providers/ad-open-provider/provider-main.c:2461: Affinitized to DC 'ns-sna02.
DOMAIN.com' for join request to domain 'DOMAIN.COM'
20180613161344:DEBUG:lsass:AD_PreJoinDomain():lsass/server/auth-providers/ad-open-provider/provider-main.c:2288: Clearing old join state
20180613161344:DEBUG:lwreg:RegTransactOpenKeyExW():lwreg/client/clientipc.c:438: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073
741772)]
20180613161344:DEBUG:lwreg:LwNtRegOpenKeyExA():lwreg/client/regntclient.c:933: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-107374
1772)]
20180613161344:DEBUG:lwreg:RegShellUtilGetValue():lwreg/shellutil/rsutils.c:1427: Error: 40700
20180613161344:DEBUG:LwpsLegacyGetDefaultJoinedDomain():lsass/pstore/lsapstore-backend-legacy-internal.c:711: -> 0 (ERROR_SUCCESS) (EE = 685
)
20180613161344:DEBUG:lwreg:RegTransactOpenKeyExW():lwreg/client/clientipc.c:438: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073
741772)]
20180613161344:DEBUG:lwreg:LwNtRegOpenKeyExA():lwreg/client/regntclient.c:933: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-107374
1772)]
20180613161344:DEBUG:lwreg:RegShellUtilGetValue():lwreg/shellutil/rsutils.c:1427: Error: 40700
20180613161344:DEBUG:LwpsLegacyGetDefaultJoinedDomain():lsass/pstore/lsapstore-backend-legacy-internal.c:711: -> 0 (ERROR_SUCCESS) (EE = 685
)
20180613161344:DEBUG:lwreg:RegTransactOpenKeyExW():lwreg/client/clientipc.c:438: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073
741772)]
20180613161344:DEBUG:lwreg:RegShellIsValidKey():lwreg/shellutil/rsutils.c:235: Error: 40700
20180613161344:DEBUG:lwreg:RegShellUtilDeleteTree():lwreg/shellutil/rsutils.c:511: Error: 40700
20180613161344:DEBUG:lwreg:RegTransactOpenKeyExW():lwreg/client/clientipc.c:438: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073
741772)]
20180613161344:DEBUG:lwreg:RegShellUtilGetKeyObjectCounts():lwreg/shellutil/rsutils.c:1175: Error: 40700
20180613161344:DEBUG:lwreg:RegTransactGetValueW():lwreg/client/clientipc.c:809: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-10737
41772)]
20180613161344:DEBUG:lwreg:LwNtRegGetValueA():lwreg/client/regntclient.c:793: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741
772)]
20180613161344:DEBUG:lsass:LsaJoinDomainUac():lsass/server/auth-providers/ad-open-provider/join/join.c:311: LsaJoinDomainUac(oraappprod02, 
domain.com, DOMAIN.COM, <null>, martinj@DOMAIN.COM, ********, Solaris, 5.10, PBIS Open 8.6.455.455.443d3e40a2d0e1437e9501cb2d242c96c9023d9
4, 0, 0)
20180613161344:DEBUG:lsass:LsaSetSMBCreds():lsass/server/auth-providers/ad-open-provider/join/lsakrb5smb.c:178: Switching default credential
s path for new access token
20180613161344:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:479: Switched gss krb5 credentials path from FILE:/tmp/krb
5cc_0 to FILE:/tmp/tktamaW9c
20180613161344:DEBUG:lwio:LwNtCreateFile():lwio/client/ntfileapictx.c:585: LEAVE_IF: -> 0xc0000002 (STATUS_NOT_IMPLEMENTED) (EE = 0)
20180613161344:DEBUG:lsass:LsaOpenPolicy2():lsass/client/rpc/lsa/lsa_openpolicy2.c:95: Converted DCERPC code 0x16C9A04F to NTSTATUS 0xc00000
01
20180613161344:DEBUG:lsass:LsaOpenPolicy2():lsass/client/rpc/lsa/lsa_openpolicy2.c:96: Error at /builder/src-git/Platform/src/linux/lsass/cl
ient/rpc/lsa/lsa_openpolicy2.c:96 [code: C0000001]
20180613161344:DEBUG:lsass:LsaJoinDomainInternal():lsass/server/auth-providers/ad-open-provider/join/join.c:731: Error at /builder/src-git/P
latform/src/linux/lsass/server/auth-providers/ad-open-provider/join/join.c:731 [code: C0000001]
20180613161344:DEBUG:lsass:LsaJoinDomainUac():lsass/server/auth-providers/ad-open-provider/join/join.c:389: Error code: 31 (symbol: ERROR_GE
N_FAILURE)
20180613161344:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:479: Switched gss krb5 credentials path from <null> to FIL
E:/tmp/krb5cc_0
20180613161344:DEBUG:lsass:AD_JoinDomain():lsass/server/auth-providers/ad-open-provider/provider-main.c:2522: Error code: 31 (symbol: ERROR_
GEN_FAILURE)
20180613161344:DEBUG:lsass:AD_ProviderIoControl():lsass/server/auth-providers/ad-open-provider/provider-main.c:4758: Error code: 31 (symbol:
 ERROR_GEN_FAILURE)
20180613161344:DEBUG:lsass:LsaSrvProviderIoControl():lsass/server/api/provider.c:99: Error code: 31 (symbol: ERROR_GEN_FAILURE)
20180613161344:ERROR:lsass:LsaSrvProviderIoControl():lsass/server/api/provider.c:128: Failed to run provider specific request (request code
= 8, provider = 'lsa-activedirectory-provider') -> error = 31, symbol = ERROR_GEN_FAILURE, client pid = -1
20180613161344:VERBOSE:lsass-ipc:lwmsg_peer_task_handle_assoc_error():lwmsg/src/peer-task.c:625: (session:00a9a1d08631199b-d32f90c7381ec623)
 Dropping: LWMSG_STATUS_PEER_CLOSE

**Steps to Reproduce**:
 1. install command
./pbis-open-8.6.1.455.solaris.sparcv9.pkg.sh -- --current-zone
 2. Domainjoin command
./domainjoin-cli --loglevel verbose join --assumeDefaultDomain yes DOMAIN.COM username
Joining to AD Domain:   DOMAIN.COM
With Computer DNS Name: oraappprod02.DOMAIN.COM

 3. Command that returns issue: domainjoin-cli
Error: ERROR_GEN_FAILURE [code 0x0000001f]

**Comment by jmresume** [comment]
UPDATE:
I discovered a difference between a running zone with PBIS than this zone (not working), which in every way is identical except one. This zone had a 4.3TB filesystem. The working zone had a zfs quota set on it at 900GB. I changed the quota to 900GB and tried the domainjoin again and voila, it worked! Not sure what the limitation is but I wanted to share the update.

**Comment by rbest-bt** [comment]
Thanks for that information. I'm not sure why that would be the case. I'll keep this open as a bug until we can have a look and see what is going on.
