### ISSUE TITLE
lsass failure after reboot

### ISSUE THREAD

**Issue by steven-tjan** [BeyondTrust/pbis-open#136]
**Version**: 8.6.427.243473
**OS/Distro**: Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-128-generic x86_64)
**Issue/Impact**:
I found that some Ubuntu servers fail to authenticate domain users after reboot.

The error messages range from:
* LW_ERROR_PASSWORD_MISMATCH,
* User is not in RequireMembership group
to
* error: PAM: User not known to the underlying authentication module for illegal user

Output of get-status is as usual. Enum-users is also working.

How I fix this:
1. kdestroy krb5cc_ files, delete ad-cache, restart lwsmd.
2. Sometimes, I have to rejoin the server to the domain.
3. Other times, completely remove and reinstall pbis-open, rejoin to the domain.

Observation: as root user, run the command "service lwsmd stop", occasionally, the service doesn't stop at all. There is no error message or return errors. Only by using /opt/pbis/bin/lwsm stop [service] then /opt/pbis/bin/lwsm shutdown, that the entire process would shutdown cleanly.

Assumption: pbis-open fails to stop cleanly when the user reboots the server. The process later comes back in a bad state.

How to reproduce: Unsure. This is happening on some servers but not others even in the same environment.

If you'd like to see certain log files, try certain things, etc, please let me know and I can gather them next time this happens.

**Comment by rbest-bt** [comment]
This sounds like there is an issue with the computer object in AD or the timeskew is getting too far apart. Next time this happens confirm that the ubuntu machine and DC times match up. I would also confirm that there are no replication issues between DC's within the domain.

Is LW_ERROR_PASSWORD_MISMATCH occurring on user login or a domainjoin-cli query?

**Comment by rbest-bt** [comment]
no response closure
