### ISSUE TITLE
Ubuntu 18.04 joined to AD, sudo problem

### ISSUE THREAD

**Issue by LaurenzBo** [BeyondTrust/pbis-open#137]
**Version**:  8.6.1.455
**OS/Distro**: Ubuntu desktop 18.04 - gnome desktop
**Issue/Impact**:
Cannot elevate AD users for sudo.
AD User _unixadm_ is added to group admin (/etc/group: admin:x:115:EFMS\\unixadm). This user **sometimes** can execute sudo.
AD User _manager_ is added to group sudo by visudo either via user name or AD group (with or without domain):
- EFMS\\\\manager ALL=(ALL) ALL
- manager ALL=(ALL) ALL
- %EFMS\\\\unix-admin ALL=(ALL) ALL
- %unix-admin ALL=(ALL) ALL
Nothing works (each option tried).
Strange issue:
_groups manager_ or _groups EFMS\\\\manager_ lists only the AD groups (although added in /etc/sudoers by any of the options above)
_groups unixadm_ lists only the AD groups but _groups EFMS\\\\unixadm_ lists both AD groups and local group admin (added to group admin via /etc/group).

UserDomainPrefix set to EFMS
AssumeDefaultDomain set to True

Login as AD user works without domain prefix, all AD users and groups are present.

 1. systemctl status lwsmd.service
 lwsmd.service - BeyondTrust PBIS Service Manager
   Loaded: loaded (/lib/systemd/system/lwsmd.service; enabled; vendor preset: en
   Active: active (running) since Fri 2018-06-29 10:33:21 CEST; 47min ago
  Process: 906 ExecStart=/opt/pbis/sbin/lwsmd --start-as-daemon (code=exited, st
 Main PID: 992 (lwsmd)
    Tasks: 177 (limit: 4553)
   CGroup: /system.slice/lwsmd.service
           ├─ 992 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─1015 lw-container lwreg
           ├─1047 lw-container eventlog
           ├─1128 lw-container netlogon
           ├─1167 lw-container lwio
           ├─1203 lw-container lsass
           └─1255 lw-container reapsysl

Jun 29 10:33:20 pc1 eventlog[1047]: Logging started
Jun 29 10:33:21 pc1 netlogon[1128]: Logging started
Jun 29 10:33:21 pc1 lwio[1167]: Logging started
Jun 29 10:33:21 pc1 lsass[1203]: Logging started
Jun 29 10:33:21 pc1 reapsysl[1255]: Logging started
Jun 29 10:33:21 pc1 systemd[1]: Started BeyondTrust PBIS Service Manager.
Jun 29 10:33:21 pc1 lsass[1203]: [lsass] Domain 'efms.intern' is now offli
Jun 29 10:34:21 pc1 lsass[1203]: [lsass] Domain 'efms.intern' is now onlin
Jun 29 10:36:47 pc1 lsass[1203]: [lsass] Failed to find user, group, or do
Jun 29 11:11:52 pc1 lsass[1203]: Logging redirected

 2. /opt/pbis/bin/lwsm list

lwreg          running (container: 1015)
dcerpc         stopped
eventlog       running (container: 1047)
lsass          running (container: 1203)
lwio           running (container: 1167)
netlogon       running (container: 1128)
rdr            running (io: 1167)
reapsysl       running (container: 1255)
usermonitor    stopped

 3. /opt/pbis/bin/domainjoin-cli query

Name = pc1
Domain = EFMS.INTERN
Distinguished Name = CN=PC1,CN=Computers,DC=efms,DC=intern

 4. pbis status
[Authentication provider: lsa-activedirectory-provider]

	Status:        Online
	Mode:          Un-provisioned
	Domain:        EFMS.INTERN
	Domain SID:    S-1-5-21-4219085671-..-..
	Forest:        efms.intern
	Site:          efms-Kat1-BA
	Online check interval:  300 seconds
	[Trusted Domains: 1]

	[Domain: EFMS]

		DNS Domain:       efms.intern
		Netbios name:     EFMS
		Forest name:      efms.intern
		Trustee DNS name: 
		Client site name: efms-Kat1-BA
		Domain SID:       S-1-5-21-..-..-..
		Domain GUID:      00000000-0000-0000-0000-000000000000
		Trust Flags:      [0x001d]
		                  [0x0001 - In forest]
		                  [0x0004 - Tree root]
		                  [0x0008 - Primary]
		                  [0x0010 - Native]
		Trust type:       Up Level
		Trust Attributes: [0x0000]
		Trust Direction:  Primary Domain
		Trust Mode:       In my forest Trust (MFT)
		Domain flags:     [0x0001]
		                  [0x0001 - Primary]

		[Domain Controller (DC) Information]

			DC Name:              efms-dc.efms.intern
			DC Address:           141.13.166.[]
			DC Site:              efms-Kat1-BA
			DC Flags:             [0x000003fd]
			DC Is PDC:            yes
			DC is time server:    yes
			DC has writeable DS:  yes
			DC is Global Catalog: yes
			DC is running KDC:    yes

		[Global Catalog (GC) Information]

			GC Name:              efms-dc.efms.intern
			GC Address:           141.13.166.[]
			GC Site:              efms-Kat1-BA
			GC Flags:             [0x000003fd]
			GC Is PDC:            yes
			GC is time server:    yes
			GC has writeable DS:  yes
			GC is running KDC:    yes

**Output/Error**:
manager is not in the sudoers list...

**Steps to Reproduce**:
 1. install command
./pbis-open-8.6.1.455.linux.x86_64.deb.sh
 2. Domainjoin command
/opt/pbis/bin/domainjoin-cli join EFMS.INTERN ad_admin   ->SUCCESS
 3. Command that returns issue
manager@pc1:~$ sudo cat /etc/sudoers

**Comment by rbest-bt** [comment]
> manager ALL=(ALL) ALL

This should work with your setup. Make sure the sudoers entry matches the output of enum-users. What does the following output:

>/opt/pbis/bin/enum-users | grep manager
