### ISSUE TITLE
[lsass-pam] [module:pam_lsass][LsaNssGetPwNam() /builder/src-buildserver/Platform-8.3/src/linux/lsass/interop/nsswitch/aix/lam-user.c:273] Lsass queried by getpwnam for [NOUSER]

### ISSUE THREAD

**Issue by EJIEHA** [BeyondTrust/pbis-open#14]
Hello all,

I'm facing the following problem with pbis-8.3 and same with pbis-8.5 on AIX 6.1:
I cannot authenticate with the AD account, but I can get all information from the AD - user info, groups, AD status, all info, but not to authenticate. I turned on the debug module and thats what i observe:
Feb 17 15:25:10 test02 authpriv:err|error sshd[10092576]: [lsass-pam] [module:pam_lsass][LsaNssGetEntry() /builder/src-buildserver/Platform-8.3/src/linux/lsass/interop/nsswitch/aix/lam-main.c:212] Getentry finishing with code 40008
Feb 17 15:25:10 test02 authpriv:err|error sshd[10092576]: [lsass-pam] [module:pam_lsass][LsaNssGetPwNam() /builder/src-buildserver/Platform-8.3/src/linux/lsass/interop/nsswitch/aix/lam-user.c:273] Lsass queried by getpwnam for [NOUSER]
------------------------------------------------------------
Feb 17 15:25:10 test02 auth|security:info sshd[10092576]: Failed password for invalid user TEST.LOC\\aesa0015 from XX:XX:XX:XX port 51733 ssh2
Feb 17 15:25:10 test02 auth|security:info sshd[10092576]: Failed password for invalid user TEST.LOC\\aesa0015 from XX:XX:XX:XX port 51733 ssh2
Feb 17 15:25:10 test02 auth|security:info syslog: ssh: failed login attempt for UNKNOWN_USER from XX:XX:XX:XX
Feb 17 15:25:10 test02 auth|security:info syslog: ssh: failed login attempt for UNKNOWN_USER from XX:XX:XX:XX

I checked the file: /etc/methods.cfg - LSASS is there, i have configured /etc/resolv.conf, ntp is working, /etc/netsvc.conf is configured..

If someone have any idea, please share... how this could be solved

**Comment by RBoulton-BT** [comment]
Looking up the 40008 error it means no such user. 

Can you do an "id" for the user? I.e. login as a local user and type id TEST.LOC\aesa0015

Does /opt/pbis/bin/enum-users show the user?

**Comment by EJIEHA** [comment]
The command  /opt/pbis/bin/enum-users return my user information:
User info (Level-0):
====================
Name:              AUTOSERVICE\aesa0015
Uid:               494404755
Gid:               494404097
Gecos:             Elena Aleksandrova
Shell:             /bin/sh
Home dir:          /home/local/AUTOSERVICE/aesa0015

But id does not:
[root@test02:/opt/pbis/bin ]# id AUTOSERVICE\aesa0015
/opt/freeware/bin/id: AUTOSERVICEaesa0015: No such user
[root@test02 :/opt/pbis/bin ]#

**Comment by RBoulton-BT** [comment]
It's difficult to tell using this GitHub markup, are you using id AUTOSERVICE\aesa0015 or id AUTOSERVICE\\\\aesa0015?

You'll need to escape the \ in the shell so use \\\\

**Comment by EJIEHA** [comment]
[root@glsdb02:~ ]# id AUTOSERVICE\\aesa0015
/opt/freeware/bin/id: AUTOSERVICE\aesa0015: No such user
[root@glsdb02:~ ]#

With "\\"

**Comment by RBoulton-BT** [comment]
So if I edit your comment I can see you are saying \\\\, but it looks like \\ as GitHub is doing the same escaping.

**Comment by EJIEHA** [comment]
how can i fix this, to not "escape" the two \\?

**Comment by rbest-bt** [comment]
In Github use "insert code" to not escape slashes
`id DOMAIN\\USER`

**Comment by rbest-bt** [comment]
Can you please try the latest version - [8.5.4](https://github.com/BeyondTrust/pbis-open/releases/tag/8.5.4) - and let us know if it still occuring

**Comment by rbest-bt** [comment]
no updates - closing
