### ISSUE TITLE
Very short SSH sessions - minute or less

### ISSUE THREAD

**Issue by jghcypa** [BeyondTrust/pbis-open#140]
**Version**: 8.6.0.427
**OS/Distro**: Ubuntu server 16.04.4
**Issue/Impact**:
Ubuntu server 16.04.4 member of AD domain 2012 R2.
Server joined domain using domainjoin-cli without any error, after reboot domain user can ssh to it.
Problem - inactivity timeout is very short, around 1 minute.
How this can be changed?

 1. systemctl status lwsmd.service

lwsmd.service - BeyondTrust PBIS Service Manager
   Loaded: loaded (/lib/systemd/system/lwsmd.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2018-07-16 07:41:11 IDT; 10h ago
  Process: 1156 ExecStart=/opt/pbis/sbin/lwsmd --start-as-daemon (code=exited, status=0/SUCCESS)
 Main PID: 1193 (lwsmd)
    Tasks: 182
   Memory: 25.2M
      CPU: 6.803s
   CGroup: /system.slice/lwsmd.service
           ├─1193 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─1219 lw-container lwreg
           ├─1279 lw-container eventlog
           ├─1305 lw-container netlogon
           ├─1334 lw-container lwio
           ├─1365 lw-container lsass
           └─1409 lw-container reapsysl

 2. /opt/pbis/bin/lwsm list

lwreg          running (container: 1219)
dcerpc         stopped
eventlog       running (container: 1279)
lsass          running (container: 1365)
lwio           running (container: 1334)
netlogon       running (container: 1305)
rdr            running (io: 1334)
reapsysl       running (container: 1409)
usermonitor    stopped

**Steps to Reproduce**:
Join domain
Reboot Ubuntu server
Login using domain credentials or public key
Wait around a minute
Press Enter and see that you already dropped out of session

**Comment by RBoulton-BT** [comment]
PBIS wouldn't generally be involved with SSH session idle timeout. Do you have any settings in your /etc/ssh/sshd_config file that could be causing this? E.g. ClientAliveInterval?

**Comment by jghcypa** [comment]
I cannot find anything related. Here is my sshd_conf:

[sshd_conf.txt](https://github.com/BeyondTrust/pbis-open/files/2201319/sshd_conf.txt)

**Comment by RBoulton-BT** [comment]
Yes that looks fine based on a quick look. 

So is it just AD users that are getting disconnected or all users accessing that box using SSH (i.e. users in the /etc/passwd file too)?

Could there be any firewalls at play dropping inactive sessions?

You could try playing with the SSH client ServerAliveInterval, ServerAliveCountMax and see if that helps.
