### ISSUE TITLE
Azure AD Support

### ISSUE THREAD

**Issue by AaronFaby** [BeyondTrust/pbis-open#142]
Does PB currently or have plans to support binding to Azure AD?

https://azure.microsoft.com/en-us/services/active-directory/

Thanks!

**Comment by sonfrau** [comment]
I'm interested into the same question.

We were using PBIS with Classic Azure AD but we are not able to use it with the new version

**Comment by tangeloservices** [comment]
also interested in some feedback on this. is it covered in documentation somewhere i've been unable to find?

**Comment by rbest-bt** [comment]
We are playing to add support for the enterprise version in the new year.
