### ISSUE TITLE
How can I build the testcases residing in the 'test' directory for each component

### ISSUE THREAD

**Issue by viralmutant** [BeyondTrust/pbis-open#143]
If I make changes to the code, I wish to execute the testcases that are present in the directory for each of the components.
How can I do that ? I am using CentOS 7.2 for development

**Comment by viralmutant** [comment]
Any suggestions on this one ?

**Comment by dmorash-BT** [comment]
Those tests use [moonunit](https://github.com/bkoropoff/moonunit).  As those tests only get built if moonunit is installed, you'll need to first build and install it:
1. `cd moonunit`
2. `mkdir dist`
3. `cd dist` 
4. `configure`
5. `make` 
6. `sudo make install`

Then you can configure and build pbis, and then build and run the tests with `make test`

**Comment by viralmutant** [comment]
Thanks for the pointers.
I was also looking in the 'tests' and 'testsuites' directories. Those seem to be functional tests.

These 'moonunit' ones are unit ones(like DCE RPC, LSA RPC, SAMR RPC etc) or functional ?

**Comment by dmorash-BT** [comment]
Yes the moonunit ones are unit tests, and it won't execute the tests in lsass/tests/test_authenticate/main.c. The lsass tests for example, are integration style test programs, i.e. they test against a working PBIS instance.  

If you wanted to build select tests, the simplest way is to create your own Makefile for that test to compile and link against an installed PBIS.
