### ISSUE TITLE
how to modify IP in active directory 

### ISSUE THREAD

**Issue by vpekelis28** [BeyondTrust/pbis-open#145]
how do I change the IP in DNS and update pbis? I had joined the domain on a server with a temporary IP, I am ready to re-assign an ip on this host, how do I update it without reboot in pbis? 

Are these the correct commands? Does this update or just add another IP ?
/opt/pbis/bin/update-dns --show
/opt/pbis/bin/update-dns --ipaddress x.x.x.x --fqdn xxxxxxxxxx

**Comment by rbest-bt** [comment]
It just adds a new address. We do not have an option to update or delete records. 

Update-dns does not require any restart. Only restart would be in regards to the network adapters ip.

**Comment by vpekelis28** [comment]
so if I modify the ip and reboot the host, will the new ip be visible in active directory? and will I be able to reuse the old ip elsewhere? or will they now both be added into the domain for this host?

**Comment by rbest-bt** [comment]
IP addresses are not tied to computer objects in Active Directory. That connection is made in dns. If the computer can resolve the domain then it will be able to find it's own computer object in the domain. The old ip address can be used if no other computers are using that ip. You may just want to clean up the old dns record. But for the most part ip changes should not impact much for the agent as long as dns is up-to-date.

Hostname is a different story. If that gets changed then you will need to reissue a domainjoin as it would not match the AD computer object and break it's joined state.
