### ISSUE TITLE
Users getting logged into root folder when using domain credentials

### ISSUE THREAD

**Issue by cwhitsbm** [BeyondTrust/pbis-open#146]
Hello,

One of our people was playing with our PBIS config to try to enable AD authentication through Postgres.  In that process, PBIS was broken, removed and then reinstalled.

The server is now joined to the domain again and it is allowing logins with user credentials.  However, when the user logs in, they are being dropped right in the root folder $.  They are no longer being redirected to their home folders /home/local/DOMAIN/jortiz3.

Is anyone aware of how this can be fixed?  I'm assuming that there is a config file somewhere for this, but am not sure.

Thanks for the help.

**Version**:  8.5.385.1
**OS/Distro**: Ubuntu desktop 16.04 - Server
**Issue/Impact**:  Users cannot find home folders.  
*Note: replace content with your own*
When reporting an issue it's important that we have as much detail as you can provide. The following is a list of commands to check.
 1. systemctl status lwsmd.service
 lwsmd.service - BeyondTrust PBIS Service Manager
   Loaded: loaded (/lib/systemd/system/lwsmd.service; enabled; vendor preset: en
   Active: active (running) since Fri 2018-08-03 14:48:57 PDT; 5min ago
  Process: 1212 ExecStart=/opt/pbis/sbin/lwsmd --start-as-daemon (code=exited, s
 Main PID: 1227 (lwsmd)
    Tasks: 317
   Memory: 25.0M
      CPU: 698ms
   CGroup: /system.slice/lwsmd.service
           ├─1227 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─1270 lw-container lwreg
           ├─1361 lw-container eventlog
           ├─1430 lw-container netlogon
           ├─1504 lw-container lwio
           ├─1587 lw-container lsass
           └─1750 lw-container reapsysl

Aug 03 14:48:57 devawsdwlx2 systemd[1]: Starting BeyondTrust PBIS Service Manage
Aug 03 14:48:57 devawsdwlx2 /opt/pbis/sbin/lwsmd[1227]: Logging started
Aug 03 14:48:57 devawsdwlx2 lwreg[1270]: Logging started
Aug 03 14:48:57 devawsdwlx2 eventlog[1361]: Logging started
Aug 03 14:48:57 devawsdwlx2 netlogon[1430]: Logging started
Aug 03 14:48:57 devawsdwlx2 lwio[1504]: Logging started

 2. /opt/pbis/bin/lwsm list
lwreg          running (container: 1270)
dcerpc         stopped
eventlog       running (container: 1361)
lsass          running (container: 1587)
lwio           running (container: 1504)
netlogon       running (container: 1430)
rdr            running (io: 1504)
reapsysl       running (container: 1750)
usermonitor    stopped

 3. /opt/pbis/domainjoin-cli query
Name = devawsdwlx2
Domain = DOMAIN.LOCAL
Distinguished Name = CN=DEVAWSDWLX2,CN=Computers,DC=domain,DC=local

 4. pbis status
LSA Server Status:
Compiled daemon version: 8.5.7.385
Packaged product version: 8.5.385.1
Uptime:        0 days 0 hours 3 minutes 41 seconds

[Authentication provider: lsa-activedirectory-provider]

        Status:        Online
        Mode:          Un-provisioned
        Domain:        domain.LOCAL
        Domain SID:    S-1-5-21-823518204-776561741-1801674531
        Forest:        domain.local
        Site:          AWS-ITOPS-EC2-Network
        Online check interval:  300 seconds
        [Trusted Domains: 1]

        [Domain: DOMAIN]

                DNS Domain:       domain.local
                Netbios name:     DOMAIN
                Forest name:      domain.local
                Trustee DNS name:
                Client site name:
                Domain SID:       S-1-5-21-823518204-776561741-1801674531
                Domain GUID:      8f1f7f91-58f7-9545-8f90-ae719f783713
                Trust Flags:      [0x001d]
                                  [0x0001 - In forest]
                                  [0x0004 - Tree root]
                                  [0x0008 - Primary]
                                  [0x0010 - Native]
                Trust type:       Up Level
                Trust Attributes: [0x0000]
                Trust Direction:  Primary Domain
                Trust Mode:       In my forest Trust (MFT)
                Domain flags:     [0x0001]
                                  [0x0001 - Primary]

                [Domain Controller (DC) Information]

                        DC Name:              AWSDC1.domain.local
                        DC Address:           xx.xxx.xxx.xxx
                        DC Site:              AWS Network
                        DC Flags:             [0x0000f17c]
                        DC Is PDC:            no
                        DC is time server:    yes
                        DC has writeable DS:  yes
                        DC is Global Catalog: yes
                        DC is running KDC:    yes

 5. /opt/pbis/bin/enum-users
 6. attach logs
  - /opt/pbis/bin/lwsm set-log-target -p lsass -  file /tmp/lsass.log
  - /opt/pbis/bin/lwsm set-log-level -p lsass - debug
  - attach log

**Output/Error**:

**Steps to Reproduce**:
 1. install command
 2. Domainjoin command
 3. Command that returns issue - Login

**Comment by dmorash-BT** [comment]
You should be able to correct that by using the /opt/pbis/bin/config command.  You want to set the HomeDirTemplate setting to the default of %H/local/%D/%U

Running /opt/pbis/bin/config with no options will display its help.

If that doesn't work, the simplest thing may be to uninstall pbis via 'sudo /opt/pbis/bin/uninstall.sh purge', reinstall and rejoin the domain.   The purge option completely removes all pbis configuration files including the registry database which holds these configuration settings.

**Comment by cwhitsbm** [comment]
We have tried all of those things.  We have done the purge twice.  And have also tries using the command for the homedir template.

It is still dropping us at the root.  We have rebooted and restarted the services.   Below is a dump of my config.

AllowDeleteTo ""
AllowReadTo ""
AllowWriteTo ""
MaxDiskUsage 104857600
MaxEventLifespan 90
MaxNumEvents 100000
DomainSeparator "\\"
SpaceReplacement "^"
EnableEventlog false
SaslMaxBufSize 16777215
Providers "ActiveDirectory"
DisplayMotd false
PAMLogLevel "error"
UserNotAllowedError "Access denied"
AssumeDefaultDomain true
CreateHomeDir true
CreateK5Login true
SyncSystemTime true
TrimUserMembership true
LdapSignAndSeal false
LogADNetworkConnectionEvents true
NssEnumerationEnabled true
NssGroupMembersQueryCacheOnly true
NssUserMembershipQueryCacheOnly false
RefreshUserCredentials true
CacheEntryExpiry 14400
DomainManagerCheckDomainOnlineInterval 300
DomainManagerUnknownDomainCacheTimeout 3600
MachinePasswordLifespan 2592000
ServicePrincipalName "host"
MemoryCacheSizeCap 0
HomeDirForceLowercase false
HomeDirPrefix "/home"
HomeDirTemplate "%H/local/%D/%U"
RemoteHomeDirTemplate ""
HomeDirUmask "022"
LoginShellTemplate "/bin/bash"
SkeletonDirs "/etc/skel"
UserDomainPrefix "domain"
DomainManagerIgnoreAllTrusts false
DomainManagerIncludeTrustsList
DomainManagerExcludeTrustsList "na.msmps.net"
RequireMembershipOf
Local_AcceptNTLMv1 true
Local_HomeDirTemplate "%H/local/%D/%U"
Local_HomeDirUmask "022"
Local_LoginShellTemplate "/bin/sh"
Local_SkeletonDirs "/etc/skel"
UserMonitorCheckInterval 1800
LsassAutostart true
EventlogAutostart true
BlacklistDC

**Comment by rbest-bt** [comment]
Can you get gather lsass logs at the time of login? This should report issues with the users home dir.
-  /opt/pbis/bin/lwsm set-log-target -p lsass - file /tmp/lsass.log
- /opt/pbis/bin/lwsm set-log-level -p lsass - debug
- attach log

**Comment by cwhitsbm** [comment]
The log is attached.  It ran a little longer than I would have liked because I had to go to a meeting.  But you should see a login very early in the log file.  I logged in with an affected user with 30 seconds of the log file creation.

[lsass.log](https://github.com/BeyondTrust/pbis-open/files/2267354/lsass.log)

**Comment by dmorash-BT** [comment]
I don't see any failures in the lsass log that would indicate what is happening, so some further questions:

- For domain users where their home directory already exists, is it owned by them and can they access it after logging in? 
- Is there a difference if the home directory doesn't exist on the initial login? 
- Does '/opt/pbis/bin/find-user-by-name <username>' show the correct home directory? Does that match what '/opt/pbis/bin/enum-users' shows as the users home directory?
- Does '/opt/pbis/bin/list-groups-for-user <username>' correctly list all the users groups?

**Comment by ricardoteixeiraduarte** [comment]
I have the same issue. The root of the share is mounted, instead of the user folder.
PBIS 8.7.0.478

**Comment by cwhitsbm** [comment]
Sorry, I forget to get back to this.  My problem was indeed that after PBIS was removed and then reinstalled the users no longer had permissions to their home directories.  Changing the permissions resolved the issue.  Thank you for your help!
