### ISSUE TITLE
PBIS can not list groups for user 

### ISSUE THREAD

**Issue by jelayeb** [BeyondTrust/pbis-open#148]
**Version**: 8.5.6-375
**OS/Distro**: Centos 7.4.1708
**Issue/Impact**: User Groups Memberships and ACLs
**Issue:**
we are using PBIS-open on a fileserver Samba/NFS, which works fine until some users were complaining that they can not access some shares where they are in the right group for this share and their other colleagues who are in the same group can.
while checking I found that PBIS can not list groups for the complaint people. so I tried to clean the ad cache, but then I got domain offline message. 
to overcome this problem I have to do as follow
1. restart LWSMD service. 
2. delete ad cache
3. enum-users
4. enum-groups.

**Comment by rbest-bt** [comment]
We are aware of group-enumeration and cache problems. We are trying to figure out, how to address them.

**Comment by rbest-bt** [comment]
Give 9.0.1 a try and see if that addresses the issue

**Comment by jelayeb** [comment]
how to get the vers 9, i can only find version 8.8.0 as latest version on
this repo

https://repo.pbis.beyondtrust.com/yum/pbiso/x86_64

Thanks

**Comment by rbest-bt** [comment]
Repos will be updated along side the Enterprise release which will be later this week. Currently it can be downloaded here:
https://github.com/BeyondTrust/pbis-open/releases/tag/9.0.1

**Comment by rbest-bt** [comment]
repos have been updated.

**Comment by jelayeb** [comment]
thanks Sent from my Mobile-------- Original Message --------Subject: Re: [BeyondTrust/pbis-open] PBIS can not list groups for user  (#148)From: rbest-bt To: BeyondTrust/pbis-open CC: jelayeb ,Author repos have been updated.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/BeyondTrust/pbis-open/issues/148?email_source=notifications\u0026email_token=AFO2BVH6UHWNBABLL5GXKFLPVFN3BA5CNFSM4FOGD4R2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVIFIAY#issuecomment-491803651",
"url": "https://github.com/BeyondTrust/pbis-open/issues/148?email_source=notifications\u0026email_token=AFO2BVH6UHWNBABLL5GXKFLPVFN3BA5CNFSM4FOGD4R2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVIFIAY#issuecomment-491803651",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
