### ISSUE TITLE
Packaging issue on Debian

### ISSUE THREAD

**Issue by mariokamenjak** [BeyondTrust/pbis-open#149]
**Version**: 8.5.4.334
**OS/Distro**: Debian stable and testing
**Issue/Impact**: Packaging
*Note: 

When installing pbis-open on Debian it is missing libncurses5.so.

**Output/Error**:
libncurses5.so not in path.

**Steps to Reproduce**:
 1. install pbis-open

**temporary fix:
apt install libncurses5

**Comment by mariokamenjak** [comment]
I have tested it on debian testing and on stable.

Other than that, I must say I just found your tool and I <3 it.

**Comment by rbest-bt** [comment]
Fixed in the latest release of [8.7.1](https://github.com/BeyondTrust/pbis-open/releases/tag/8.7.1)
