### ISSUE TITLE
NFS server not seeing all groups

### ISSUE THREAD

**Issue by pfcapp** [BeyondTrust/pbis-open#15]
Have a RHEL 6.7 NFS server running PBIS-Open  8.3.0.3287.  CentOS 7 clients are running the same version of Open.  Most of the time everything works fine.  Lately been having different users not being able to access an NFS mounted directory on the client due to group protections.  The user will be listed in the group on the client but it seems the server doesn't know they should be a member of that group so it gives a "permission denied" error when trying to access the directory.  This could be related to the other cases of group membership I've seen here but since it involves NFS I figured I'd ask.  Also looks like 8.5.3 will be coming out soon that may address this as well.  Thanks for any info/suggestions.

**Comment by winkaway** [comment]
You may want to look into the NFS 16 group limit as outlined in the following link: http://www.xkyle.com/solving-the-nfs-16-group-limit-problem/
