### ISSUE TITLE
DNS_ERROR_BAD_PACKET when attempting to join 8.5.3 to Server 2016 domain

### ISSUE THREAD

**Issue by cliftyman** [BeyondTrust/pbis-open#150]
**Version**: 8.5.385
**OS/Distro**: Mac OS 10.12.3 (Sierra)

Both when attempting to join the Mac to the domain utilizing the UI or the CLI utility I receive DNS_ERROR_BAD_PACKET after inputting my domain admin credentials.

I have checked /etc/hosts and I can ping the domain name.  I have tried upper and lower-case versions of the DOMAIN to account for unix/linux case-sensitive to no avail.

Is there a log that can give me a better idea what the problem is?  Has anyone experienced this before?

**Comment by rbest-bt** [comment]
If the mac is resolving the domain via the hosts file it might not be getting all the required DNS entries for Active Directory to work.

Have a look at the "Check DNS Connectivity" section of the [Troubleshooting guide](https://github.com/BeyondTrust/pbis-open/wiki/docs/Troubleshooting_Guide.pdf)
