### ISSUE TITLE
ERROR_BAD_FORMAT [code 0x0000000b] RHEL 7.4

### ISSUE THREAD

**Issue by ShishNik** [BeyondTrust/pbis-open#152]
**Version**: 
PBIS Version 8.7.478 installed
VERSION=8.7.478
BUILD=478
REVISION=50eb066a67bbcdd4842b659bac888d7835e08781

**OS/Distro**: Red Hat Enterprise Linux Server release 7.4 (Maipo)
**Issue/Impact**:
*Note: replace content with your own*
When reporting an issue it's important that we have as much detail as you can provide. The following is a list of commands to check.
 1. systemctl status lwsmd.service
# systemctl status lwsmd.service
● lwsmd.service - BeyondTrust PBIS Service Manager
   Loaded: loaded (/usr/lib/systemd/system/lwsmd.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2018-08-29 16:05:04 MSK; 21s ago
 Main PID: 13370 (lwsmd)
   CGroup: /system.slice/lwsmd.service
           ├─13370 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─13413 lw-container lwreg
           ├─13461 lw-container eventlog
           ├─13506 lw-container netlogon
           ├─13551 lw-container lwio
           ├─13598 lw-container lsass
           └─13655 lw-container reapsysl

Aug 29 16:05:04 host-10 systemd[1]: Starting BeyondTrust PBIS Service Manager...
Aug 29 16:05:04 host-10 /opt/pbis/sbin/lwsmd[13370]: Logging started
Aug 29 16:05:04 host-10 lwreg[13413]: Logging started
Aug 29 16:05:04 host-10 eventlog[13461]: Logging started
Aug 29 16:05:04 host-10 netlogon[13506]: Logging started
Aug 29 16:05:04 host-10 lwio[13551]: Logging started
Aug 29 16:05:04 host-10 lsass[13598]: Logging started
Aug 29 16:05:04 host-10 lsass[13598]: Logging redirected
Aug 29 16:05:04 host-10 reapsysl[13655]: Logging started
Aug 29 16:05:04 host-10 systemd[1]: Started BeyondTrust PBIS Service Manager.

 2. /opt/pbis/bin/lwsm list
# # /etc/pbis/redhat/lwsmd status
lwsmd (pid 13655 13598 13551 13506 13461 13413 13370) is running...
# /opt/pbis/bin/lwsm list
lwreg          running (container: 13413)
dcerpc         stopped
eventlog       running (container: 13461)
lsass          running (container: 13598)
lwio           running (container: 13551)
netlogon       running (container: 13506)
rdr            running (io: 13551)
reapsysl       running (container: 13655)
usermonitor    stopped

 3. /opt/pbis/domainjoin-cli query
# /opt/pbis/bin/domainjoin-cli query

Error: LW_ERROR_KRB5KDC_ERR_C_PRINCIPAL_UNKNOWN [code 0x0000a309]

Client not found in Kerberos database

 4. pbis status
# pbis status
LSA Server Status:

Compiled daemon version: 8.7.0.478
Packaged product version: 8.7.478.50
Uptime:        0 days 21 hours 41 minutes 0 seconds

[Authentication provider: lsa-activedirectory-provider]

        Status:        Unknown
        Mode:          Unknown

 5. /opt/pbis/bin/enum-users
 /opt/pbis/bin/enum-users
TotalNumUsersFound: 0

 6. attach logs
  - /opt/pbis/bin/lwsm set-log-target -p lsass -  file /tmp/lsass.log
  - /opt/pbis/bin/lwsm set-log-level -p lsass - debug
  - attach log

**Output/Error**:

**Steps to Reproduce**:
 1. install command
#sh pbis-open-8.7.0.478.linux.x86_64.rpm.sh
 2. Domainjoin command

A momentary error:

# /opt/pbis/bin/domainjoin-cli join --disable hostname --ou UNIX/LINUX eor.local joinadmin

Error: ERROR_BAD_FORMAT [code 0x0000000b]

 3. Command that returns issue

**Comment by ShishNik** [comment]
A solution has been found.
File /etc/krb5.conf contained special characters.

**Comment by rbest-bt** [comment]
Thanks for posting your solution. This error can also happen for bad OU or domain name. For both of those there is a better error.

I'm going to log a task to see about improving the krb.conf check to indicate the file.
