### ISSUE TITLE
Slow authentication of new users

### ISSUE THREAD

**Issue by alecom** [BeyondTrust/pbis-open#153]
**Version**: 8.7.0.478
**OS/Distro**: Mint 18.3 Mate (Ubuntu desktop 16.04)
**Issue/Impact**: New users are not able to login for some minuntes after reboot.

**Steps to Reproduce**:
- /opt/pbis/bin/ad-cache --delete-all   [cached users are not impacted by the issue]
- reboot
- try to login with ad user: fail (ssh/lightdm/tty)
- wait a couple of minutes
- try to login with ad user: ok

during those minutes, if you run:
/opt/pbis/bin/find-user-by-name domainuser

[edit] it doesn't work (no differences between domainuser, domainname\\domainuser, domainuser@domainname..)

auth.log reports:
Aug 29 19:17:03 cm185e77164 sshd[1279]: Received SIGHUP; restarting.
Aug 29 19:17:03 cm185e77164 sshd[1279]: Server listening on 0.0.0.0 port 22.
Aug 29 19:17:03 cm185e77164 sshd[1279]: Server listening on :: port 22.
Aug 29 19:17:20 cm185e77164 login[1599]: pam_unix(login:auth): authentication failure; logname=LOGIN uid=0 euid=0 tty=/dev/tty1 ruser= rhost=  user=domainuser
Aug 29 19:17:23 cm185e77164 login[1599]: FAILED LOGIN (1) on '/dev/tty1' FOR 'domainuser', Authentication failure

if you login with local user and run
su domainuser
you have:
No passwd entry for user 'domainuser'

Some suggested commands (I've cut most of them, tell me if more details are needed)

 1. systemctl status lwsmd.service
```
 lwsmd.service - BeyondTrust PBIS Service Manager
   Loaded: loaded (/lib/systemd/system/lwsmd.service; enabled; vendor preset: en
   Active: active (running) since mer 2018-08-29 19:09:45 CEST; 24s ago
```

 2. /opt/pbis/bin/lwsm list
```
lwreg          running (container: 1072)
dcerpc         stopped
eventlog       running (container: 1110)
lsass          running (container: 1192)
lwio           running (container: 1165)
netlogon       running (container: 1140)
rdr            running (io: 1165)
reapsysl       running (container: 1227)
usermonitor    stopped
```

 3. /opt/pbis/domainjoin-cli query
name/domain/DN are ok

 4. pbis status
 ```
Status:        Online
        Mode:          Un-provisioned
        Domain:        MYDOMAIN.LOCAL
        Domain SID:    S-1-5-21-2511633152-3860124696-1951440016
        Forest:        mydomain.local
        Site:          Default-First-Site-Name
        Online check interval:  300 seconds
        [Trusted Domains: 1]

```
 5. /opt/pbis/bin/enum-users
[edit]
```
Failed to enumerate users.  Error code 40121 (LW_ERROR_DOMAIN_IS_OFFLINE).
The domain is offline
```

**Comment by ShishNik** [comment]
Check DNS setting.
Chech /etc/ssh/sshd_config
show /opt/pbis/bin/config --dump

**Comment by alecom** [comment]
I supposed it's related to network race condition, so I found issue 6# I'm checking if in that topic there's suggestion to speed-up the reconnection.

**Comment by alecom** [comment]
It seems that my issue is strictly related to #6 

as a workaround, I made a (horrible) startup script:

```
c=0; stripped=$(ifconfig | grep 192.168); while [ "$stripped" == "" -a $c -lt 1200 ]; do sleep 1; stripped=$(ifconfig | grep 192.168); ((c++)); done;
/opt/pbis/bin/lwsm restart netlogon
```
It seems that issue is solved, but I don't know if there could be some side effects.
I suppose that there's a better solution, so I'm leaving open that issue.

Note on my script: I set a timeout of 1200 sec to avoid the script runs forever in the background. I suppose that there could be some more elegant way to check the "routability" of network than checking "192.168" (that, of course, it's not generic, but suitable only to some networks)

**Comment by rbest-bt** [comment]
Thanks for the update. We'll try and have a look to see if we can address this better in the product. 

Any additional information on your network could help us reproduce this issue. 
- Is the issue on wireless?
- How many network interfaces do you have?
- Is 192.168 the desired network to reach the domain?
- Mint 18.3 using DHCP?
- How long does it usually take to get an IP address?

**Comment by notlimahrelyt** [comment]
> Hi, I've some different environments. Some are wired, and some wireless. In wireless environment the issue is more frequent (not a surprise).
> To restrict the variables, I made most of my tests in a wired environment, single network interface, DHCP enabled.
> 192.168 is part of the domain network
> During some tests, I tried to log the "c" variable. In most cases, it takes the IP in less of 5 seconds.
> 
> after applying this workaround, sometimes it fails to log me in at first attempt (if I insert credential quickly), but it always works at second one. Without it, it could take minutes.

I'm in the same boat here running Ubuntu 20.04 Desktop - After reboot, it can take anywhere from 30 sec to several minutes before a domain user can authenticate. I receive 'Access Denied' for users that have already logged in previously.

I have not tried the workaround above yet.

**Comment by MPilloni** [comment]
Dear all,
I'm an IT Specialist working in a company running Active Directory for user authentication and recently we had to integrate also Ubuntu clients.

I'm running Ubuntu both 18.04 and 20.04 with PBIS 9.1.0 and I can rarely login correctly without restarting lwsmd.service which is annoying.
So, this is to say that currently the issue persists.
I'm testing different solution, like downgrading PBIS open, running scripts after ubuntu boot, and I'll let you know if anything can be useful.
PBIS open seem very cool for the domain join but this issue makes it unusable.

If you find a solution before, please update this thread.

Thanks.

**Comment by rbest-bt** [comment]
Please upgrade to Active Directory Bridge Enterprise. If the issue still exists then please submit a ticket to our service team and we’ll have a look for you.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
