### ISSUE TITLE
Samba Share Group/User names in Security Properties

### ISSUE THREAD

**Issue by jelayeb** [BeyondTrust/pbis-open#154]
I have a samba share on centos7 joined the domain with pbis-open, 
everything works fine but when I check the directory properties from windows I can see that it is owned and permitted to Unix Group\groupname and Unix User\username. 
those usernames and groups are domain members and not exist under Linux. 
how can I make them appear as just Username and Groupname, as some applications now recognize them as cross-domain users and groups? 

Thanks

**Comment by rbest-bt** [comment]
I'm a little confused on your information. The domain prefix Unix Group/User shows up when the file/directory is owned by a local group/user as the domain is unknown. If it is a domain member then it should show with the domain prefix of the domain they are from.

The shares owner comes from the shares POSIX attributes on the directory/file. To change the ownership you would need to just change the permissions on the server. Setting the owner as an AD user/group might solve your issue. This is something samba controls.

Possible helpful [link](https://access.redhat.com/discussions/1217783)

**Comment by jelayeb** [comment]
it is completely different from the issue explained in the link. other than the screenshot he is sharing,
I don't have a problem with the share, I can change its attributes from windows and works fine. 

my question is why it shows the permissions from windows as **Unix Group\GroupName** other shares from windows file server, shows **DOMAIN\GroupName**
GroupName is a windows domain group it doesn't exist locally on the Samba Server it is resolved from the domain.

**Comment by rbest-bt** [comment]
When you list the samba share folder what does the ownership show?

**Comment by jelayeb** [comment]
[root@sha6130 data]# getfacl MAU/
# file: MAU/
# owner: root
# group: root
# flags: -s-
user::rwx
group::rwx
group:ha.resfs.fileaccess:rwx
group:ha.resfs.linux.data.mau:rwx
group:ha.resfs.linux.data.mau_r:r-x
mask::rwx
other::---
default:user::rwx
default:group::rwx
default:group:ha.resfs.fileaccess:rwx
default:group:ha.resfs.linux.data.mau:rwx
default:group:ha.resfs.linux.data.mau_r:r-x
default:mask::rwx
default:other::---

**Comment by jelayeb** [comment]
![mau](https://user-images.githubusercontent.com/22913236/45154135-cf124980-b1d6-11e8-9ccd-0dab9f3e14f3.png)

**Comment by rbest-bt** [comment]
pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
