### ISSUE TITLE
single sign on problem

### ISSUE THREAD

**Issue by 4thomasmueller** [BeyondTrust/pbis-open#156]
Hi,
at customer we have a AD setup of cross-forest domains which are transitive trusted.
machine accounts (server1, server2) and usergroups resides in Domain B, admin accounts resides in Domain A.
With pbis we are able to join both SLES12 servers (server1, server2) into Domain B and we are able to logon with accounts from Domain A and mapping groups from Domain B for sudo - alright so far.
But, if we try to logon via ssh from one server to another we'll always asked for password. If we enter this, loin is succesful. It is not really sso ...
Config /etc/ssh/sshd_config was created by setup routine from pbis.

sshd log of the machine we want to connect to says "Postponed keyboard-interactive for <user> from <ip> ssh2 [preauth]

ssh log of the machine we try to connect from says: "Unspecified GSS failure. Minor code may provide more information
No Kerberos credentials available.
Is it possible, that no kerberos tickets can be found because a "normal" klist shows no principals, but /opt/pbis/bin/klist does?

Regards, Thomas

**Comment by ShishNik** [comment]
Hi Thomas.

You are using SLES. 
It's all about sshd settings.
pbis is modify /etc/ssh/sshd_config, not create new.

**Comment by 4thomasmueller** [comment]
Hi ShishNik,
it works now. I can login from a windows machine via putty to the sles servers with AD account and w/o password.

Relevant settings in sshd_config are:
Protocol 2
RSAAuthentication no
Pubkey Authentication no
PasswordAuthentication yes
ChallengeResponseAuthentication no
GSSAPIAuthentication yes
GSSAPICleanupCredentials yes
UsePAM yes
KbdInteractiveAuthentication no

Thanks again and kind regards,
Thomas

**Comment by rbest-bt** [comment]
@ShishNik Thanks for the post. You are correct.

@4thomasmueller Thanks for posting your solution. This is good info that can help others someday.
