### ISSUE TITLE
RemoteHomeDirTemplate mounts the root of the share, not the user folder

### ISSUE THREAD

**Issue by ricardoteixeiraduarte** [BeyondTrust/pbis-open#157]
**Version**: 8.7.0.478
**OS/Distro**: Ubuntu desktop 16.04 - unity desktop
**Issue/Impact**:
- User homeDir attribute from Active Directory is \\\server\home\username
- PBIS has /opt/pbis/bin/config RemoteHomeDirTemplate "%H/local/%D/%U/Z"
- After users logs in, the "%H/local/%D/%U/Z" has \\\server\home and not \\\server\home\username. Syslog shows that lsass only tried to mount \\\server\home, and not the full path
- Systemctl shows an error when mounting, but the folder is still mounted.

**1. systemctl status lwsmd.service**
● lwsmd.service - BeyondTrust PBIS Service Manager
   Loaded: loaded (/lib/systemd/system/lwsmd.service; enabled; vendor preset: enabled)
   Active: active (running) since Qua 2018-09-05 09:21:30 WEST; 6h ago
  Process: 924 ExecStart=/opt/pbis/sbin/lwsmd --start-as-daemon (code=exited, status=0/SUCCESS)
 Main PID: 943 (lwsmd)
   CGroup: /system.slice/lwsmd.service
           ├─ 943 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─ 956 lw-container lwreg
           ├─1002 lw-container eventlog
           ├─1020 lw-container netlogon
           ├─1037 lw-container lwio
           ├─1058 lw-container lsass
           └─1123 lw-container reapsysl

Set 05 15:26:30 machine01 lsass[1058]: [lsass] Failed mount of //server/home on /home/local/DOMAIN/username/Z with data prefixpath=%username%,sec=krb5,user=username@DOMAIN.LOCAL,uid=1111111116,gid=1111111111,cruid=11113
Set 05 15:26:30 machine01 lsass[1058]: [lsass] Failed mount of //server/home on /home/local/DOMAIN/username/Z with data prefixpath=%username%,sec=krb5i,user=username@DOMAIN.LOCAL,uid=1111111116,gid=1111111111,cruid=11113
Set 05 15:26:30 machine01 lsass[1058]: [lsass] Failed mount of //server/home on /home/local/DOMAIN/username/Z, error 3355449760 (errno 40170)
Set 05 15:26:30 machine01 lsass[1058]: [lsass] Failed to mount directory for user (username), actual error 40170
Set 05 15:26:30 machine01 lsass[1058]: [lsass] Failed to open session for user (name = 'username') -> error = 40170, symbol = LW_ERROR_ERRNO_EBUSY, client pid = 13372

**2. /opt/pbis/bin/lwsm list**
lwreg          running (container: 956)
dcerpc         stopped
eventlog       running (container: 1002)
lsass          running (container: 1058)
lwio           running (container: 1037)
netlogon       running (container: 1020)
rdr            running (io: 1037)
reapsysl       running (container: 1123)
usermonitor    stopped

**Steps to Reproduce**:
 1. bash pbis-open-8.7.0.478.linux.x86_64.deb.sh
 2. /opt/pbis/bin/domainjoin-cli join DOMAIN.LOCAL admin
 3. /opt/pbis/bin/config RemoteHomeDirTemplate "%H/local/%D/%U/Z"
 4. Login with user with home \\\server\home\username

**Comment by ricardoteixeiraduarte** [comment]
This seems to be due to prefixpath not working for me.

From cifs man:

prefixpath=
    It's possible to mount a subdirectory of a share. **The preferred way to do this is to append the path to the UNC when mounting**. However, it's also possible to do the same by setting this option and providing the path there. 

Mount with the path on UNC (and without prefixpath) works from command line. 
So, it's the prefixpath that is not working. Maybe PBIS should move to the preferred way of using the full path.


This will fix it for my scenario:

```
diff -Naur pbis-open.orig/lsass/server/auth-providers/ad-open-provider/mount.c pbis-open/lsass/server/auth-providers/ad-open-provider/mount.c
--- pbis-open.orig/lsass/server/auth-providers/ad-open-provider/mount.c 2018-09-05 16:49:52.388031550 +0100
+++ pbis-open/lsass/server/auth-providers/ad-open-provider/mount.c      2018-09-05 16:53:13.847845362 +0100
@@ -450,9 +450,10 @@
     {
         dwError = LwAllocateStringPrintf(
                     &pszRemotePathWithoutPrefix,
-                    "//%s/%s",
+                    "//%s/%s/%s",
                     pszServerName,
-                    pszShare);
+                    pszShare,
+                   pszPath);
         BAIL_ON_LSA_ERROR(dwError);

         dwError = LwAllocateStringPrintf(

```

**Comment by rbest-bt** [comment]
pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
