### ISSUE TITLE
"--assumeDefaultDomain yes"  no longer works

### ISSUE THREAD

**Issue by jlmagee** [BeyondTrust/pbis-open#158]
**Version**: 8.7.0
**OS/Distro**: CentOS 7.5
**Issue/Impact**:
Several existing scripts must be updated because 'yes' is no longer evaluated as enabled for assumeDefaultDomain

/opt/pbis/bin/domainjoin-cli --loglevel verbose join --assumeDefaultDomain yes --notimesync mydomain myusername@mydomain
results in usage display instead of joining the domain

PR 6261: Merge enhancements/46508-assume-default-cell-mode to …
added static BOOLEAN function isOptionValueEnabled which evaluates 'auto', 'automatic', 'dynamic', and 'on' as enabled

The previous inline code for assumeDefaultDomain evaluated 'yes', 'true', and 'on' as enabled

The usage/help still prints {yes|no} as options for assumeDefaultDomain

**Comment by polivon-rms** [comment]
Same issue here:
Version: 8.7.0
OS/Distro: CentOS 7.5
Issue/Impact:
Several existing scripts must be updated because 'yes' is no longer evaluated as enabled for assumeDefaultDomain

**Comment by rbest-bt** [comment]
Thanks for reporting this issue. We are working to address this.

**Comment by dmorash-BT** [comment]
In the interim, to avoid changing scripts, you can enable AssumeDefaultDomain via the config tool
`sudo /opt/pbis/bin/config AssumeDefaultDomain true`   and verify the setting via `sudo /opt/pbis/bin/config --show AssumeDefaultDomain`

**Note**: after setting the AssumeDefaultDomain value, the config tool will attempt to clear the ad-cache.  If any of your domains are offline, this hangs to prevent a situation where AD users can't login.  You can just Ctrl-C that, AssumeDefaultDomain will still have been set.

**Comment by rbest-bt** [comment]
Fix released in [8.7.1](https://github.com/BeyondTrust/pbis-open/releases/tag/8.7.1)
