### ISSUE TITLE
Issue Signing into Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by W00glin** [BeyondTrust/pbis-open#159]
**Version**: 87.0.478
**OS/Distro**: Ubuntu desktop 16.04 - unity desktop
**Issue/Impact**: Issue Signing into Ubuntu 16.04 LTS

Apologies if the formatting is bad. Copying and pasting from PUTTY is a nightmare. I also redacted some information for security purposes.

Issue: I am able to join the domain and I can see the computer in my domain but whenever I attempted to login with AD credentials it would not work. I am however able to switch users via command line to AD account without any issues.

 1. systemctl status lwsmd.service
lwsmd.service - BeyondTrust PBIS Service Manager
   Loaded: loaded (/lib/systemd/system/lwsmd.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2018-08-27 14:57:36 EDT; 51min ago
  Process: 1204 ExecStart=/opt/pbis/sbin/lwsmd --start-as-daemon (code=exited, status=0/SUCCESS)
 Main PID: 1225 (lwsmd)
   CGroup: /system.slice/lwsmd.service
           ├─1225 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─1247 lw-container lwreg
           ├─1279 lw-container eventlog
           ├─1305 lw-container netlogon
           ├─1432 lw-container lwio
           ├─1479 lw-container lsass
           └─1620 lw-container reapsysl

Aug 27 14:57:42 DEV-HB-NIX01 lsass[1479]: [lsass] Failed to find user, group, or domain by name (name = 'dev-hb-nix01', searched host = 'PRD-HB-DC01.healthbridge.org') -> error = 40071, symbol = LW_ERROR_NO_SUCH_OBJECT
Aug 27 15:18:23 DEV-HB-NIX01 lsass[1479]: [lsass] Failed to find user, group, or domain by name (name = 'adm_bfraley@healthbrige.org', searched host = 'PRD-HB-DC01.healthbridge.org') -> error = 40071, symbol = LW_ERROR_NO_SUCH_OBJECT

 2. /opt/pbis/bin/lwsm list
lwreg          running (container: 1248)
dcerpc         stopped
eventlog       running (container: 1368)
lsass          running (container: 1482)
lwio           running (container: 1453)
netlogon       running (container: 1397)
rdr            running (io: 1453)
reapsysl       running (container: 1556)
usermonitor    stopped

 3. /opt/pbis/domainjoin-cli query
Name = COMPUTER_HOST_NAME
Domain = DOMAINNAME.ORG

 4. pbis status
LSA Server Status:

Compiled daemon version: 8.7.0.478
Packaged product version: 8.7.478.50
Uptime:        9 days 21 hours 30 minutes 11 seconds

[Authentication provider: lsa-activedirectory-provider]

        Status:        Online
        Mode:          Un-provisioned
        Domain:        DOMAINNAME.ORG
        Domain SID:    S-1-5-21-1715567821-1214440339-1177238915
        Forest:        forestname.org
        Site:          SiteName
        Online check interval:  300 seconds
        [Trusted Domains: 1]

        [Domain: DOMAINNAME]

                DNS Domain:       DOMAINNAME.ORG
                Netbios name:     DOMAINNAME
                Forest name:      FORESTNAME.ORG
                Trustee DNS name:
                Client site name: Location
                Domain SID:       S-1-5-21-1715567821-1214440339-1177238915
                Domain GUID:      d200611d-16dd-4f48-931e-1d53f6e60636
                Trust Flags:      [0x001d]
                                  [0x0001 - In forest]
                                  [0x0004 - Tree root]
                                  [0x0008 - Primary]
                                  [0x0010 - Native]
                Trust type:       Up Level
                Trust Attributes: [0x0000]
                Trust Direction:  Primary Domain
                Trust Mode:       In my forest Trust (MFT)
                Domain flags:     [0x0001]
                                  [0x0001 - Primary]

                [Domain Controller (DC) Information]

                        DC Name:              DC-NAME.DOMAINNAME.ORG
                        DC Address:           X.X.X.X
                        DC Site:              Location
                        DC Flags:             [0x0000f1fc]
                        DC Is PDC:            no
                        DC is time server:    yes
                        DC has writeable DS:  yes
                        DC is Global Catalog: yes
                        DC is running KDC:    yes

                [Global Catalog (GC) Information]

                        GC Name:              DC-NAME.DOMAINNAME.ORG
                        GC Address:           X.X.X.X
                        GC Site:              Location
                        GC Flags:             [0x0000f1fd]
                        GC Is PDC:            yes
                        GC is time server:    yes
                        GC has writeable DS:  yes
                        GC is running KDC:    yes

 5. /opt/pbis/bin/enum-users
Outputs a large number of AD users. Will not be posting for obvious reasons.

**Comment by rbest-bt** [comment]
What does your nsswitch.conf look like?

**Comment by W00glin** [comment]
> 
> 
> What does your nsswitch.conf look like?
Where is that stored?

**Comment by W00glin** [comment]
> 
> 
> /etc/nsswitch.conf

@rbest-bt 

###/etc/nsswitch.conf
###
###Example configuration of GNU Name Service Switch functionality.
###If you have the `glibc-doc-reference' and `info' packages installed, try:
###info libc "Name Service Switch"' for information about this file.

passwd:         compat sss lsass
group:          compat sss lsass
shadow:         compat sss
gshadow:        files

hosts:          files mdns4_minimal [NOTFOUND=return] dns
networks:       files

protocols:      db files
services:       db files sss
ethers:         db files
rpc:            db files

netgroup:       nis sss
sudoers:        files sss

**Comment by rbest-bt** [comment]
Try moving lsass before sss on the group and passwd lines. It could be interfering

**Comment by W00glin** [comment]
> 
> 
> Try moving lsass before sss on the group and passwd lines. It could be interfering

I changed it from:
passwd: compat sss lsass
group: compat sss lsass
shadow: compat sss
gshadow: files

To:

passwd: compat lsass sss
group: compat lsass sss
shadow: compat sss
gshadow: files

Rebooting the server and it worked. Any idea what caused this issue?

**Comment by rbest-bt** [comment]
lsass - From PBIS-open
sss - from sssd 

Both are AD bridge solutions. Since they are both trying to do the same thing conflicts occur. I would guess that sssd was configured on that machine before trying out PBIS-open. If you would like to keep using PBIS I would recommend removing the sssd setup to prevent future conflicts.

[Information on sssd setup for ubuntu](https://help.ubuntu.com/lts/serverguide/sssd-ad.html)

**Comment by W00glin** [comment]
> 
> 
> lsass - From PBIS-open
> sss - from sssd
> 
> Both are AD bridge solutions. Since they are both trying to do the same thing conflicts occur. I would guess that sssd was configured on that machine before trying out PBIS-open. If you would like to keep using PBIS I would recommend removing the sssd setup to prevent future conflicts.
> 
> [Information on sssd setup for ubuntu](https://help.ubuntu.com/lts/serverguide/sssd-ad.html)

Most likely the case. I was trying to get SSSD configured and could not get it to work. You should be able to close this issue now.
Thanks!
