### ISSUE TITLE
Cannot join the domain 

### ISSUE THREAD

**Issue by vpekelis28** [BeyondTrust/pbis-open#16]
I am in the domain join group however unable to join a new system to domain in solaris10

domainjoin-cli join resldap.net vpekelis@idldap.net 
Error: ERROR_ACCESS_DENIED [code 0x00000005]

Access is denied 

-bash-3.2$ id -a
uid=1344800290(IDLDAP\vpekelis) gid=1344799233(IDLDAP\domain^users) groups=1344799233(IDLDAP\domain^users),145753179(dl^icc^admins),1344803336(IDLDAP\gg^bms^admins),145753180(dl^iccdatabaseadmins),1344803337(IDLDAP\ug^bms^admins),1344799838(IDLDAP\ug^icc^admins),1344801901(IDLDAP\sudo_ug^ews^engineer),1344801899(IDLDAP\sudo_gg^ews^engineer),1344799839(IDLDAP\ug^iccdatabaseadmins),1344803470(IDLDAP\safenet_ug^security^sync^agent),1344801903(IDLDAP\sudo_gg^system^engineer),145753278(dl^domain^join),1344801905(IDLDAP\sudo_ug^system^engineer),1344801907(IDLDAP\sudo_gg^operator^support),145753189(dl^iccsystemadmin),145755178(dl^bms^admins)

**Comment by RBoulton-BT** [comment]
Are you running the domainjoin-cli join with the root account?

**Comment by vpekelis28** [comment]
Yes I am as there are no ldap users yet so I log in with a local admin user then become root (su - ), then run the command.

Then I use my idldap account to try to join


uid=1344800290(IDLDAP\vpekelis) gid=1344799233(IDLDAP\domain^users) groups=1344799233(IDLDAP\domain^users),145753179(dl^icc^admins),1344803336(IDLDAP\gg^bms^admins),145753180(dl^iccdatabaseadmins),1344803337(IDLDAP\ug^bms^admins),1344799838(IDLDAP\ug^icc^admins),1344801901(IDLDAP\sudo_ug^ews^engineer),1344801899(IDLDAP\sudo_gg^ews^engineer),1344799839(IDLDAP\ug^iccdatabaseadmins),1344803470(IDLDAP\safenet_ug^security^sync^agent),1344801903(IDLDAP\sudo_gg^system^engineer),145753278(dl^domain^join),1344801905(IDLDAP\sudo_ug^system^engineer),1344801907(IDLDAP\sudo_gg^operator^support),145753189(dl^iccsystemadmin),145755178(dl^bms^admins)


Thanks,

Vitaly Pekelis
Unix Systems Administration | IT Operations
Phone:  (732) 652-3769
Mobile: (609) 933-7064
vpekelis@opentext.com<mailto:vpekelis@opentext.com>
www.opentext.com<http://www.opentext.com/>

[http://www.opentext.com/2/emailsupport-logo-opentext-2010.gif]<http://www.opentext.com/2/email-signature-logo>

This email message is confidential, may be privileged, and is intended for the exclusive use of the addressee. Any other person is strictly prohibited from disclosing or reproducing it. If the addressee cannot be reached or is unknown to you, please inform the sender by return email and delete this email message and all copies immediately.

**Comment by RBoulton-BT** [comment]
There should be a domainjoin-cli.log file created in /var/log, does that have anything useful in it?

**Comment by vpekelis28** [comment]
It might be because the environmental variable was set..  orrr nsswitch.conf file needs to be edited. Either way I cannot test this now as it is already joined.

# cat domainjoin-cli.log
20160203134200:ERROR:Manual configuration required [code 0x0000a606]

The configuration stage 'enable/disable PowerBroker Identity Services nsswitch module' cannot be completed automatically. Please manually perform the following steps and rerun the domain join:

Remove the passwd_compat and/or group_compat lines and use passwd and group instead. This cannot be done automatically because your system has a non-default nsswitch configuration.
The following steps are required and can be performed automatically:
        * Edit nsswitch apparmor profile to allow libraries in the /opt/pbis/lib  and /opt/pbis/lib64 directories
        * List lwidentity module in /usr/lib/security/methods.cfg (AIX only)
        * Add lwidentity to passwd and group/groups line /etc/nsswitch.conf or /etc/netsvc.conf
If any changes are performed, then the following services must be restarted:
        * GDM
        * XDM
        * Cron
        * Dbus
        * Nscd

Stack Trace:
/builder/src-buildserver/Platform-8.3/src/linux/domainjoin/domainjoin-cli/src/main.c:1160
/builder/src-buildserver/Platform-8.3/src/linux/domainjoin/domainjoin-cli/src/main.c:544
/builder/src-buildserver/Platform-8.3/src/linux/domainjoin/libdomainjoin/src/djmodule.c:286
20160203134358:WARNING:Unsupported loader flags set
LD_LIBRARY_PATH and/or LD_PRELOAD are currently set on your system. Best practices for Unix and Linux administration strongly recommend not to use these environmental variables. PowerBroker Identity Services does not support environments where either variable is set.

If this operation fails you should stop all PowerBroker Identity Services daemons, clear the environmental variable, then retry the join operation.

For more information, see the PowerBroker Identity Services guide online at:
http://www.beyondtrust.com/Technical-Support/Downloads/files/pbiso/Manuals/likewise-open-guide.html#AgentRequirements

Or a local PDF file is available in:
/opt/pbis/docs/likewise-open-guide.pdf (See section 4.2 Requirements for the Agent
20160203134457:WARNING:System restart required
Your system has been configured to authenticate to Active Directory for the first time.  It is recommended that you restart your system to ensure that all applications recognize the new settings.
20160203134457:ERROR:Nothing seems to be protecting logins for service other
20160203134457:ERROR:Unknown PAM module [code 0x0000a609]

The PowerBroker Identity Services PAM module cannot be configured for the other service. This service uses the 'pam_unix_cred.so.1' module, which is not in this program's list of known modules. Please email PowerBroker Identity Services technical support and include a copy of /etc/pam.conf or /etc/pam.d.

Stack Trace:
/builder/src-buildserver/Platform-8.3/src/linux/domainjoin/domainjoin-cli/src/main.c:1160
/builder/src-buildserver/Platform-8.3/src/linux/domainjoin/domainjoin-cli/src/main.c:554
/builder/src-buildserver/Platform-8.3/src/linux/domainjoin/libdomainjoin/src/djmodule.c:345
/builder/src-buildserver/Platform-8.3/src/linux/domainjoin/libdomainjoin/src/djpamconf.c:4093
/builder/src-buildserver/Platform-8.3/src/linux/domainjoin/libdomainjoin/src/djpamconf.c:3774
/builder/src-buildserver/Platform-8.3/src/linux/domainjoin/libdomainjoin/src/djpamconf.c:3100
20160203135603:WARNING:Unsupported loader flags set
LD_LIBRARY_PATH and/or LD_PRELOAD are currently set on your system. Best practices for Unix and Linux administration strongly recommend not to use these environmental variables. PowerBroker Identity Services does not support environments where either variable is set.

If this operation fails you should stop all PowerBroker Identity Services daemons, clear the environmental variable, then retry the join operation.





Thanks,

Vitaly Pekelis
Unix Systems Administration | IT Operations
Phone:  (732) 652-3769
Mobile: (609) 933-7064
vpekelis@opentext.com<mailto:vpekelis@opentext.com>
www.opentext.com<http://www.opentext.com/>

[http://www.opentext.com/2/emailsupport-logo-opentext-2010.gif]<http://www.opentext.com/2/email-signature-logo>

This email message is confidential, may be privileged, and is intended for the exclusive use of the addressee. Any other person is strictly prohibited from disclosing or reproducing it. If the addressee cannot be reached or is unknown to you, please inform the sender by return email and delete this email message and all copies immediately.

**Comment by vpekelis28** [comment]
I am still unable to join the domain now on a redhat 6 box...

[root@tf-vwsbm-b01 log]# domainjoin-cli join resldap.net vpekelis@idldap.net
Joining to AD Domain:   resldap.net
With Computer DNS Name: tf-vwsbm-b01.resldap.net

vpekelis@IDLDAP.NET's password: 

Error: ERROR_ACCESS_DENIED [code 0x00000005]

Access is denied


cat  domainjoin-cli.log

Stack Trace:
/builder/src-git/Platform/src/linux/domainjoin/domainjoin-cli/src/main.c:1211
/builder/src-git/Platform/src/linux/domainjoin/domainjoin-cli/src/main.c:480
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djmodule.c:254
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djdaemonmgr.c:68
20170420102930:ERROR:ERROR_ACCESS_DENIED [ERROR_ACCESS_DENIED]

Access is denied

Stack Trace:
/builder/src-git/Platform/src/linux/domainjoin/domainjoin-cli/src/main.c:1211
/builder/src-git/Platform/src/linux/domainjoin/domainjoin-cli/src/main.c:583
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djmodule.c:355
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djauthinfo.c:857
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djauthinfo.c:1255
20170420103156:ERROR:ERROR_ACCESS_DENIED [ERROR_ACCESS_DENIED]

Access is denied

Stack Trace:
/builder/src-git/Platform/src/linux/domainjoin/domainjoin-cli/src/main.c:1211
/builder/src-git/Platform/src/linux/domainjoin/domainjoin-cli/src/main.c:583
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djmodule.c:355
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djauthinfo.c:857
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djauthinfo.c:1255
[root@tf-vwsbm-b01 log]#

**Comment by vpekelis28** [comment]
i figured out i had to leave the domain twice as this was a clone and was only then able to rejoin.
