### ISSUE TITLE
[lsass] Failed to find memberships for user 'DOMAIN\Username' (error = 40318)

### ISSUE THREAD

**Issue by jelayeb** [BeyondTrust/pbis-open#160]
**Version**: 8.5.6.375
**OS/Distro**: Centos7 3.10.0-693.17.1.el7.x86_64
**Issue/Impact**:
users lost thier access to samba/nfs shares instantly and they lost many hours of work because of that.
in log files i found those messages on the same time where the user work was lost.
```
[lsass] Failed to find memberships for user 'DOMAIN\Username' (error = 40318)
[lsass] Failed to find memberships for user 'DOMAIN\XX.ResRDS.Workplace.Users' (error = 40318)
```

sometimes after few minutes when i check i find everything works fine and fileserver can find the user and list his/her groups.

i had this issue before and i had to clear the ad-cache and enum-users and groups then restart lwsmd service to list the user again.

**Comment by jelayeb** [comment]
any comments here

**Comment by rbest-bt** [comment]
Can you accurately reproduce the issue consistently? Can you confirm at the time of the issue that there were no networking problems or outage?

**Comment by jelayeb** [comment]
the issue happens during the day randomly and can not be reproduced. but i have 24x7 monitoring on the file server and on the exact time where the problem happens i can see on the logs the messages i posted up, but there is no network outages on that time. 

it happend before and i had to stop lwsmd and start again then clear the ad cache and enum users and groups again to make it work again, but if i leave it alone it will start working again by itself but we found that when it happens at night and no one there the simulation jobs of the user will fail because the user will lose his write access to the share as his group is not recognized anymore.

**Comment by rbest-bt** [comment]
pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
