### ISSUE TITLE
powerbroker open limitations

### ISSUE THREAD

**Issue by soujith** [BeyondTrust/pbis-open#161]
are there any limitations of this software in terms of no.of computers can be joined or no. of users can accessed with?

**Comment by rbest-bt** [comment]
524,288 users and groups.

See the [RID Pool Error in the PBIS_Troubleshooting_Guide](https://github.com/BeyondTrust/pbis-open/wiki/docs/PBIS_Troubleshooting_Guide.pdf)

**Comment by soujith** [comment]
so, no limitation on number of machines right

**Comment by soujith** [comment]
i mean for powerbroker open edition are there any limitations of this software in terms of no.of computers can be joined or no. of users can accessed with?
i am only looking for Open source software and not enterprise edition. please let me know if there is a limitation for no.of users

**Comment by rbest-bt** [comment]
Actually the previous number includes computers too. Total number of users, groups and computers over 524,288 run into issues of UID conflicts.
