### ISSUE TITLE
pbis status issues/login issues

### ISSUE THREAD

**Issue by W00glin** [BeyondTrust/pbis-open#164]
**Version**: 8.5.4.334
**OS/Distro**: Ubuntu desktop 16.04 - unity desktop
**Issue/Impact**:
Cannot login with AD creds. Trying to get a repeatable process down for integrating AD into our GNU/Linux servers. Running into a few issues.
*Note: replace content with your own*
When reporting an issue it's important that we have as much detail as you can provide. The following is a list of commands to check.
 1. systemctl status lwsmd.service
`● lwsmd.service - BeyondTrust PBIS Service Manager
   Loaded: loaded (/lib/systemd/system/lwsmd.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2018-09-18 14:17:05 EDT; 3 weeks 5 days ago
 Main PID: 1179 (lwsmd)
   CGroup: /system.slice/lwsmd.service
           ├─1179 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─1203 lw-container lwreg
           ├─1283 lw-container eventlog
           ├─1347 lw-container netlogon
           ├─1397 lw-container lwio
           ├─1501 lw-container lsass
           └─1648 lw-container reapsysl
nix01@DEV-HB-NIX01:/opt/pbis$`
 2. /opt/pbis/bin/lwsm list
`nix01@DEV-HB-NIX01:/opt/pbis$ /opt/pbis/bin/lwsm list`
`lwreg          running (container: 1203)`
`dcerpc         stopped`
`eventlog       running (container: 1283)`
`lsass          running (container: 1501)`
`lwio           running (container: 1397)`
`netlogon       running (container: 1347)`
`rdr            running (io: 1397)`
`reapsysl       running (container: 1648)`
`usermonitor    stopped`
`nix01@DEV-HB-NIX01:/opt/pbis$`

 3. /opt/pbis/domainjoin-cli query
```
nix01@DEV-HB-NIX01:/opt/pbis$ sudo domainjoin-cli query
Name = DEV-HB-NIX01
Domain = HEALTHBRIDGE.ORG
Distinguished Name = CN=DEV-HB-NIX01,OU=Information Security,OU=Data Center,OU=Servers,OU=TRIORG,DC=healthbridge,DC=org
nix01@DEV-HB-NIX01:/opt/pbis$
```
 4. pbis status
`LSA Server Status:

Compiled daemon version: 8.7.0.478
Packaged product version: 8.7.478.50
Uptime:        26 days 21 hours 22 minutes 39 seconds

[Authentication provider: lsa-activedirectory-provider]

        Status:        Online
        Mode:          Un-provisioned
        Domain:        DOMAIN.ORG
        Domain SID:    S-1-5-21-1715567821-1214440339-1177238915
        Forest:      forest.org
        Site:          DC
        Online check interval:  300 seconds
        [Trusted Domains: 1]

        [Domain: DOMAIN]

                DNS Domain:       DOMAIN.org
                Netbios name:     DOMAIN
                Forest name:      forest.org
                Trustee DNS name:
                Client site name: DataCenter
                Domain SID:       S-1-5-21-1715567821-1214440339-1177238915
                Domain GUID:      d200611d-16dd-4f48-931e-1d53f6e60636
                Trust Flags:      [0x001d]
                                  [0x0001 - In forest]
                                  [0x0004 - Tree root]
                                  [0x0008 - Primary]
                                  [0x0010 - Native]
                Trust type:       Up Level
                Trust Attributes: [0x0000]
                Trust Direction:  Primary Domain
                Trust Mode:       In my forest Trust (MFT)
                Domain flags:     [0x0001]
                                  [0x0001 - Primary]

                [Domain Controller (DC) Information]

                        DC Name:              DC-SERVER-NAME.org
                        DC Address:           X.X.X.X
                        DC Site:              DataCenter
                        DC Flags:             [0x0000f1fc]
                        DC Is PDC:            no
                        DC is time server:    yes
                        DC has writeable DS:  yes
                        DC is Global Catalog: yes
                        DC is running KDC:    yes

                [Global Catalog (GC) Information]

                        GC Name:               DC-SERVER-NAME.org
                        GC Address:          X.X.X.X
                        GC Site:              DataCenter
                        GC Flags:             [0x0000f1fd]
                        GC Is PDC:            yes
                        GC is time server:    yes
                        GC has writeable DS:  yes
                        GC is running KDC:    yes
`

 5. /opt/pbis/bin/enum-users
Not going to list. A lot of users.

**Comment by rbest-bt** [comment]
We need more information. Everything looks fine from your outputs. How are you authenticating?

**Comment by W00glin** [comment]
> 
> 
> We need more information. Everything looks fine from your outputs. How are you authenticating?

Whoops. I probably should have included that. Yes so I am trying to authenticate via a console session, ssh and rpd. I also tried all three again on a previously working server and it does not seem to be working.

For all three I am entering: admin_username@DOMAIN.ORG followed by the password.

**Comment by W00glin** [comment]
Any update?

**Comment by rbest-bt** [comment]
There is not enough information listed to identify a problem. We need enough details that we can try and reproduce the issue.

If it was working then check and make sure the network and DNS are still ok.

**Comment by rbest-bt** [comment]
No Response. Closing
