### ISSUE TITLE
ubuntu 18.04 - cannot find user login info on domain controller

### ISSUE THREAD

**Issue by antoniotvr** [BeyondTrust/pbis-open#165]
**Version**: 8.7.478.50
**OS/Distro**: Ubuntu desktop 18.04
**Issue/Impact**: information on functionality

Hi. I've successfully install pbis-open on Ubuntu 18.04 and now my client is joined to AD domain.

Also with File Manager I can connect to usr network shares and credential are passed (so I have not to re enter the credential evry time).

I have only one issue: our Firewall reads Active Directory logs (to look at all user logins and logouts) to match AD username with current assigned IP of client with that user logged in. In this way we can do firewall rules by AD users and groups.

When I login with my domain user on Ubuntu, I can not find any login event on the domain controller side.

Do you have any idea of ​​the reason?

Thank you,
Antonio

**Comment by cboutilier-bt** [comment]
Have you checked the Security logs under Event viewer? I am currently seeing logon events along with Kerberos events. However, I don't believe that the specific user information is captured in those events.

**Comment by antoniotvr** [comment]
Hi.

When I login on my windows desktop with my user account on domain
controller I can see the event.

On Linux machine I can login with my windows user too, but no event is
created on dc.

Regards

Il giorno gio 18 ott 2018 alle 20:23 cboutilier-bt <notifications@github.com>
ha scritto:

**Comment by antoniotvr** [comment]
The event that is created is 4624.

Antonio

Il giorno gio 18 ott 2018 alle 20:33 Antonio Taverna <antonio.tvr@gmail.com>
ha scritto:

**Comment by rbest-bt** [comment]
Please upgrade to Active Directory Bridge Enterprise. If the issue still exists then please submit a ticket to our service team and we’ll have a look for you.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
