### ISSUE TITLE
PBIS problem with 32CPUs and SLES12

### ISSUE THREAD

**Issue by rbirkenhake** [BeyondTrust/pbis-open#166]
**Version: 8.7.0-478**
**OS: SLES 12 SP3 - Latest OS-Updates from 16.10.2018**

**Issue**: Cannot login with SSH and AD-Account to SLES12-System with 32CPUs. No problem running same System with 16CPUs. What can I do, running PBIS with 32CPUs?

_1. Output from "systemctl status lwsmd.service":_
lwsmd.service - BeyondTrust PBIS Service Manager
   Loaded: loaded (/usr/lib/systemd/system/lwsmd.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2018-10-16 14:35:55 CEST; 18min ago
 Main PID: 2301 (lwsmd)
    Tasks: 483 (limit: 512)
   CGroup: /system.slice/lwsmd.service
           ├─2301 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─2383 lw-container lwreg
           ├─2484 lw-container eventlog
           ├─2561 lw-container netlogon
           ├─2664 lw-container lwio
           ├─2745 lw-container lsass
           └─2894 lw-container reapsysl

Oct 16 14:35:54 system lwreg[2383]: Logging started
Oct 16 14:35:54 system eventlog[2484]: Logging started
Oct 16 14:35:54 system netlogon[2561]: Logging started
Oct 16 14:35:54 system lwio[2664]: Logging started
Oct 16 14:35:55 system lsass[2745]: Logging started
Oct 16 14:35:55 system reapsysl[2894]: Logging started
Oct 16 14:35:55 system systemd-coredump[3014]: Process 3004 (lwsmd) of user 0 dumped core.
Oct 16 14:35:55 system systemd[1]: Started BeyondTrust PBIS Service Manager.
Oct 16 14:35:55 system /opt/pbis/sbin/lwsmd[2301]: Service failed to start: usermonitor
Oct 16 14:35:55 system /opt/pbis/sbin/lwsmd[2301]: Service failed to start: usermonitor

_2. Output from "/opt/pbis/bin/lwsm list":_
lwreg          running (container: 2383)
dcerpc         stopped
eventlog       running (container: 2484)
lsass          running (container: 2745)
lwio           running (container: 2664)
netlogon       running (container: 2561)
rdr            running (io: 2664)
reapsysl       running (container: 2894)
usermonitor    dead

_3. Output from "/opt/pbis/bin/domainjoin-cli query"_ 
shows System is joined to domain

_4. Output from "/opt/pbis/bin/pbis-status":_
LSA Server Status:

Compiled daemon version: 8.7.0.478
Packaged product version: 8.7.478.50
Uptime:        0 days 0 hours 22 minutes 1 seconds

[Authentication provider: lsa-activedirectory-provider]

        Status:        Unknown
        Mode:          Unknown

_5. Output from "/opt/pbis/bin/enum-users":_
TotalNumUsersFound: 0

6. In /var/log/messages I found several segfaults like this - everytime after a system-reboot:
lwsmd[3878]: segfault at 7ffff2bf99d0 ip 00007ffff6a6c941 sp 00007fffffffeb10 error 4 in libpthread-2.22.so[7ffff6a63000+18000]
lwsmd[3004]: segfault at 2d0 ip 00007ffff6a6c941 sp 00007fffffffeb10 error 4 in libpthread-2.22.so[7ffff6a63000+18000]

7. Output from "/opt/pbis/bin/list-groups-for-user ##AD##\\##USER##":
Failed to find groups for user '####'.  Error code 40008 (LW_ERROR_NO_SUCH_USER).
No such user

What additional output can I provide, to help identifying the problem?

THANKS!

**Comment by cboutilier-bt** [comment]
We have looked into this issue. There does appear to be an issue running PBIS on 32CPUs. It has been logged as a bug and we will address it in the future.

**Comment by rbirkenhake** [comment]
ok, thank you for looking at this!

Is a simple workaround possible?

**Comment by cboutilier-bt** [comment]
It appears that there is a task limit of 512 on SLES machines. In doing some research, I have been able to set the TasksMax to infinity in the service file for PBIS. Alternatively, you can change the global service file to include this. However, I have used the one that is installed by PBIS to keep the changes localized.  

**Workaround Steps:**
- shutdown the lwsmd service **(systemctl stop lwsmd)**
- edit the /usr/lib/systemd/system/lwsmd.service file and add TasksMax=infinity
- start the lwsmd service if it isn't running **(systemctl start lwsmd)**
- you may be required to reload the daemon **(systemctl daemon-reload)**
- reboot the machine 

Try using PBIS as normal. On my end, I am able to authenticate and do all of the PBIS related tasks that I was unable to do previously.

**Comment by rbirkenhake** [comment]
Great Workaround! This is working for me too!

**Comment by rbest-bt** [comment]
This information will be added to the [Troubleshooting guide](https://github.com/BeyondTrust/pbis-open/wiki/Documentation) in the next release.
