### ISSUE TITLE
list password expirations

### ISSUE THREAD

**Issue by mmiat** [BeyondTrust/pbis-open#168]
i've searched on documentation, but i cant find info about this...

I want to know when expire the password of an account, if I run:

```
/opt/pbis/bin/find-user-by-name mydomain\\username --level 2
```

I see

```
Password never expires:       FALSE
Password expired:             FALSE
Prompt for password change:   NO
User can change password:     YES
Days till password expires:   0
```

but I know this user has password expiring (3 days from now)
what's wrong?
thanks

**Comment by cboutilier-bt** [comment]
Thank you for this. I have reproduced this on our side. It looks like it is a bug and we will address it in a future release.

**Comment by rbest-bt** [comment]
Update: This is a bug in regards to displaying false information when there is no cache for the user. If there is cache(user has logged in) then it will display the correct information as that is where it's looking. We have a bug logged to investigate how to make this better.

**Comment by mmiat** [comment]
why closed? solved?

**Comment by rbest-bt** [comment]
We have logged something into our backlog to address it as it's working as intended but could be better. Currently, it's not on our roadmap so I'm marking as won't fix.

**Comment by minli1** [comment]
Hi, @rbest-bt 
Base on the comment above https://github.com/BeyondTrust/pbis-open/issues/168#issuecomment-447353256, I'm not sure why the information is right when there is **cache**?  If the info is wrong here why the cached info is right? Thanks.
