### ISSUE TITLE
Powerbroker adjoin bringing virtual ips down

### ISSUE THREAD

**Issue by Prakashadapala** [BeyondTrust/pbis-open#169]
adjoin is impacting the network on linux servers.
When we tried to join the AD all the virtual IP's on the network are coming downor) reloading

Currently we are on below level:
VERSION=8.5.372
BUILD=372
REVISION=607f43b5524a6a1121e116c7f671f3dc63a878fe
QFE=5

**Comment by rbest-bt** [comment]
I would need more details about your issues
