### ISSUE TITLE
Can't login after user used to bind changes password

### ISSUE THREAD

**Issue by bgtron** [BeyondTrust/pbis-open#17]
Consider this case: A machine is bound to AD with User1's account. SSH is configured to allow domain users to connect and User2 can SSH into the server.  User1 then changes their password.  At that point, User 2 can no longer log in to the server.

This issue does not affect Windows servers, but it affect *nix server bound with open-pbis.  Is there a way around this?  I'd rather not create service accounts for binding that can never have their passwords changed.

**Comment by RBoulton-BT** [comment]
I'm not sure I understand what you are asking. 

When you join a UNIX/Linux host to AD, a new Computer object is created with a sAMAccountName of the form hostname$. It's this Computer object that PBIS-Open uses for authentication and other functions going forward.

The account you pass on the domainjoin-cli is only used only to create the Computer object hostname$.

If you have 2 hosts with the same sAMAccountNam,e PBIS-Open will attempt to create a Computer object by hashing the hostname to get a unique sAMAccountName so you should not see any issue with one computer changing another computers password.

**Comment by bgtron** [comment]
We were having authentication issues with a specific server and did some testing.  If we bind a linux server using a specific user, then change the password of that user, we are no longer able to authenticate as any other AD user on that server.

It's almost as if the credentials are being cached to verify every user that wants to authenticate.

Is there anything I can provide to help debug this?

**Comment by bgtron** [comment]
Also...once the user password is changed, pbis-open has to be completely uninstalled because it breaks.  We're unable to run the "domainjoin-cli leave".  Once the pbis-open is reinstalled, then we can bind again using the user's new password.

**Comment by RBoulton-BT** [comment]
Just to clarify what you are saying is happening, could you confirm the exact steps you're performing to reproduce this? 

I'm assuming it's something like:

1. Install PBIS-Open
2. domainjoin-cli join domain.com user1 Password1
3. Perform logons etc all good, domainjoin-cli query all good etc
4. On AD change user1 password from Password1 to Password2
5. Perform logons all fail, domainjoin-cli query fails

**Comment by bgtron** [comment]
That is correct.  To resolve the issue on the server, we have to completely uninstall pbis-open and then reinstall it. I'm sure deleting all the confs would word too, but uninstalling and reinstalling is faster.

**Comment by RBoulton-BT** [comment]
I don't see how that sequence could affect the status of the agent. I've confirmed on my test boxes that changing the user account after joining has no effect on the functionality of the agent. 

Are you able to reproduce this behavior?

If you can then please use the /opt/pbis/libexec/pbis-support.pl script to collect logs of the problem happening and send them in to openproject@beyondtrust.com.

In one terminal as root run:
- /opt/pbis/libexec/pbis-support.pl -o -c

In another terminal:

- Show logons working.
- Change the AD users password
- Show the logons failing

In the first terminal:

- Type "done<enter>" to complete the support logging and then send us the /tmp/pbis-support-<host>-<tstamp>.tar.gz file.

**Comment by RBoulton-BT** [comment]
One thing that would affect the agent status like you describe would be if you joined 2 hosts with the same FQDN. The second host would pick up the same computer account and change the password.
