### ISSUE TITLE
get-status always online?

### ISSUE THREAD

**Issue by Tobias-V** [BeyondTrust/pbis-open#170]
**Version**: 8.6.427
**OS/Distro**: Ubuntu desktop 16.04 - unity desktop

The issue: get-status reports online when there is no chance on earth it is actually online
LSA Server Status:

Compiled daemon version: 8.6.0.427
Packaged product version: 8.6.427.243473
Uptime:        3 days 8 hours 24 minutes 30 seconds

[Authentication provider: lsa-activedirectory-provider]

    Status:        Online
	Mode:          Un-provisioned
	Domain:       xxx
	Domain SID:    xxx
	Forest:        xxx
	Site:         xxx
	Online check interval:  300 seconds
	[Trusted Domains: 8]

**Steps to Reproduce**:
1. Have a working installation of PBIS where the connection to Active Directory is fine.
2. Pull out the network cord (or if using wireless, place computer in a faraday cage)
3. Wait for longer than 300 seconds (optional)
4. Run get-status and see that it still reports the status as online, even though you don't have a network connection.

Alternative:
1. Have a working installation of PBIS where the connection to Active Directory is fine.
2. Edit your host and add an entry for every DC that points to nowhere
3. Wait for longer than 300 seconds (optional)
4. Run get-status and see that it still reports the status as online, even though PBIS clearly can't access Active Directory.

2nd alternatively:
1. Have a working installation of PBIS where the connection to Active Directory is fine.
2. Ifdown the network interface that has access to Active Directory
3. Wait for longer than 300 seconds (optional)
4. Run get-status and see that it still reports the status as online, even though PBIS clearly can't access Active Directory.

3rd alternative:
1. Have a working installation of PBIS where the connection to Active Directory is fine.
2. Disconnect from the network, and connect to another network that does not have access to the DCs.
3. Wait for longer than 300 seconds (optional)
4. Run get-status and see that it still reports the status as online, even though PBIS clearly can't access Active Directory.

I'm guessing it doesn't recheck once it's switched to online status? Does 'Online check interval' only apply if it was offline last check?

I would like to be able to run a script that checks whether PBIS is working or not and connected to AD so that I can report that to a remote dashboard. Is it not possible to do this using lwsm and get-status?

**Comment by Tobias-V** [comment]
This seems to affect CentOS 7 as well, multiple versions of PBIS.

Is my understanding of what 'Online check interval' is supposed to do wrong? Is it only supposed to check until it comes online the first time?

**Comment by rbest-bt** [comment]
It's a check as to whether the Provider is online. In this case - Authentication provider: lsa-activedirectory-provider. If you joined to a domain it will pretty much always return online.
