### ISSUE TITLE
Unable to Uninstall  8.6.0-427 from Cent OS 6.10

### ISSUE THREAD

**Issue by ericb0813** [BeyondTrust/pbis-open#172]
**Version**: 8.6.0-427
**OS/Distro**: Cent OS 6.10
**Issue/Impact**:
Not able to uninstall PBIS open with yum or uninstall script provided

/opt/pbis/bin/uninstall.sh purge
The file /var/lib/pbis/uninstall/MANIFEST cannot be found and
is required for this uninstall procedure.

**or** 

sudo yum remove pbis-open.x86_64
Loaded plugins: fastestmirror, security
Setting up Remove Process
Resolving Dependencies
--> Running transaction check
---> Package pbis-open.x86_64 0:8.6.0-427 will be erased
--> Finished Dependency Resolution

Dependencies Resolved
Removing:
 pbis-open                                                         x86_64                                                         8.6.0-427                                                          @local-centos-pbiso                                                          40 M

Remove        1 Package(s)

Installed size: 40 M
Is this ok [y/N]: y
Downloading Packages:
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction

**Gets stuck at running transaction**

**Steps to Reproduce**:
Installed via rpm using yum. 

Tried to uninstall and got the output above.

**Comment by rbest-bt** [comment]
uninstall.sh only works when installed with the script installers. When uninstalling from the repo make sure to remove pbis-open-upgrade as it has a dependency on pbis-open.
