### ISSUE TITLE
PBIS-OPEN escapes "" in domainjoin-cli

### ISSUE THREAD

**Issue by therealfabby** [BeyondTrust/pbis-open#173]
**Version**: 8.7.494.0
**OS/Distro**: CentOS 7
**Issue/Impact**:
When using double pings around my OU in domainjoin-cli I get a DNS Bad packet error.
Using single pings solves the issue. Double pings have worked in the past.
It looks like spaces are not being escaped.

**Steps to Reproduce**:
Does not work and results in BAD DNS packet error:
sudo domainjoin-cli join –-ou “AD/Windows 10.X/Deploy” example.com adminaccount

Works:
sudo domainjoin-cli join –-ou 'AD/Windows 10.X/Deploy' example.com adminaccount

**Comment by cboutilier-bt** [comment]
I would suggest upgrading to the latest version. I am currently unable to reproduce this issue on 8.7 or 9.0.
