### ISSUE TITLE
Unable to join to Active Directory using pbis domainjoin-cli command

### ISSUE THREAD

**Issue by coderbunty** [BeyondTrust/pbis-open#174]
**Version**: 7.4
**OS/Distro**: RHEL
**Issue/Impact**: Unable to join to Active Directory using pbis domainjoin-cli command
*Note: replace content with your own*
When reporting an issue it's important that we have as much detail as you can provide. The following is a list of commands to check.
 1. systemctl status lwsmd.service
     Active

 2. /opt/pbis/bin/lwsm list
     lwreg          running (container: 5757)
autoenroll     stopped
dcerpc         stopped
eventfwd       stopped
eventlog       running (container: 5775)
gpagent        stopped
lsass          running (container: 5824)
lwio           running (container: 5807)
lwpkcs11       stopped
lwpkcs11r      stopped
lwsc           stopped
netlogon       running (container: 5792)
rdr            running (io: 5807)
reapsysl       running (container: 5851)
usermonitor    stopped

 3. /opt/pbis/domainjoin-cli query
     Name = jupiter-vm303
     Domain =

 4. pbis status
     LSA Server Status:

Compiled daemon version: 8.6.0.427
Packaged product version: 8.6.423.9
Uptime:        0 days 1 hours 17 minutes 36 seconds

[Authentication provider: lsa-activedirectory-provider]

        Status:        Unknown
        Mode:          Unknown

 5. /opt/pbis/bin/enum-users
     TotalNumUsersFound: 0

 6. attach logs
  - /opt/pbis/bin/lwsm set-log-target -p lsass -  file /tmp/lsass.log
  - /opt/pbis/bin/lwsm set-log-level -p lsass - debug
  - attach log

**Output/Error**:
**Error: DNS_ERROR_BAD_PACKET [code 0x0000251e]

A bad packet was received from a DNS server. Potentially the requested address does not exist.**

**Steps to Reproduce**:
I am running the command - 
"domainjoin-cli join --ou OU=Users,OU=Prod,OU=ads_pvc_ou1,DC=adssecurity,DC=local adssecurity.local Administrator"

Before entering the password, it displays the below info,
Joining to AD Domain:   adssecurity.local
With Computer DNS Name: jupiter-vm303.adssecurity.local

Here jupiter-vm303 is the hostname of the system which I want to join to AD. (Or the hostname of the system where I am running this command).

jupiter-vm494 is the hostname of the AD which I assume should have been taken in that field "With Computer DNS Name" making it jupiter-vm494.adssecurity.local

How do I change this? or I am doing things wrong somewhere else?

I have already added ip of AD (jupiter-vm494) in /etc/resolv.conf as "nameserver <ip of vm494>"

Any inputs will be very much appreciated.

**Comment by rbest-bt** [comment]
`With Computer DNS Name: jupiter-vm303.adssecurity.local`

This is correct. That is the DNS name of the current computer trying to join the domain. Is jupiter-vm494 hosting a DNS server? Can jupiter-vm303 resolve adssecurity.local.

Also 8.7.1 was released. I recommend using the latest version.

**Comment by coderbunty** [comment]
> `With Computer DNS Name: jupiter-vm303.adssecurity.local`
> 
> This is correct. That is the DNS name of the current computer trying to join the domain. Is jupiter-vm494 hosting a DNS server? Can jupiter-vm303 resolve adssecurity.local.
> 
> Also 8.7.1 was released. I recommend using the latest version.

jupiter-vm494 is hosting a dns

**Comment by coderbunty** [comment]
jupiter-vm494 is where Active Directory is. I am able to join my other similar systems to this AD with Centrify (another identity & privilege management tool). So, I guess its hosting a dns server. 
Also, jupiter-vm303 should be able to resolve adssecurity.local as I have added ip od AD in /etc/resolv.conf. This is what I had done with Centrify setup.

**Comment by rbest-bt** [comment]
Confirm nslookup returns the right ip.
`nslookup adssecurity.local`

Have a look at the [Installation Guide](https://github.com/BeyondTrust/pbis-open/wiki/docs/PBIS_Installation_Guide.pdf) for the section 'Configure Firewall Ports'. Confirm they are open.

**Comment by coderbunty** [comment]
nslookup wasn't returning the right ip. I then shifted the "nameserver <ip_of_AD>" up the order in /etc/resolv.conf. Now nslookup returns the right ip. When I tried running domainjoin-cli, I get the below error,

Error: ERROR_GEN_FAILURE [code 0x0000001f]

**Comment by rbest-bt** [comment]
Just realized you have an enterprise edition installed. If so then the issue is in regards to not having a cell configured on the windows side. 8.7.1 has a better error in regards to this.

**Comment by recrislip** [comment]
Hope this is not redundant, I too am receiving 'DNS_ERROR_BAD_PACKET [code 0x0000251e]' Except I using Mint 19. Here's the command I'm using "sudo domainjoin-cli join --disable ssh BossHogg.RandBGraphics.local richard". This is a private non-enterprise setup. I can ping the network "BossHogg.RandBGomputerGraphics.local". Any and all suggestions would be appreciated. TIA
