### ISSUE TITLE
authentication service cannot retrieve authentication info

### ISSUE THREAD

**Issue by Matteo9815** [BeyondTrust/pbis-open#176]
**Version**: 8.7.1
**OS/Distro**: Ubuntu desktop 18.04 - unity desktop

When i try to Join to the domain it let me access without limitation but when i restart the pc and i try to access with a domain's account the PC tell "authentication service cannot retrieve authentication info".
When i return to the login screen i can see the account name and surname so i suppose it can contact the domain. Any solution?
thanks,
Matteo

**Comment by rbest-bt** [comment]
Are you talking about the first gui login? When you can see your account can you authenticate at that time?

**Comment by Matteo9815** [comment]
@rbest-bt from login screen i have an error "it doesn't work" so i try from a console doing "su myuser" and i have the error i posted before.

**Comment by mmiat** [comment]
if I try from ssh I've

> mar 04 14:09:42 an-nb06321lnx sshd[1911]: error: PAM: User account has expired for miatello.mauro from 192.168.10.31
mar 04 14:09:42 an-nb06321lnx sshd[1911]: fatal: monitor_read: unpermitted request 104

**Comment by mmiat** [comment]
I solved copying /etc/pam.d/common-* from a working client
