### ISSUE TITLE
Client has high CPU in certain cases. 

### ISSUE THREAD

**Issue by wimo7083** [BeyondTrust/pbis-open#177]
**Version**: 7.4.0.0
**OS/Distro**: Windows 10  Enterprise
**Issue/Impact**:

I'm not sure where to raise this issue, but I'm having trouble with the windows client on my development machine. My employer uses this application and whenever I do any file intensive activities (compile, zip, copy, move, linking, console output) BeyondTrust Shared Service goes from < 1 percent to 18-30 percent, and I've seen it as high as 40-50. 

If you could point me in the right direction, I'd appreciate it.

**Comment by rbest-bt** [comment]
That is seems to be BeyondTrust PowerBroker for Windows and we have a support team that can assist you. I would recommend you reach out to your system administrator as they should be able to raise the issue to the BeyondTrust support team.

**Comment by corderoau** [comment]
I have the same issue - is there a solution yet?
