### ISSUE TITLE
Samba idmap range not specified for domain 

### ISSUE THREAD

**Issue by jelayeb** [BeyondTrust/pbis-open#179]
**Version**: pbis-open-8.7.1-494.x86_64
**OS/Distro**: Centos 7.4.1708
**Issue/Impact**:
 
actually i dont know if this is a problem or not, as my machine is joined the domain and samba works fine with out any problems other than the annoying big issue with group members explained the issue  #160 . 
on the integration document after installing integration component and configuring samba you mentioned that we need to run testparm and make sure there is no error in the output, but in my case i configured samba exactly as in the document and there is no line for idmaping config, and i always receive this error 

**Output/Error from testparam**:
```
idmap range not specified for domain '*'
ERROR: Invalid idmap range for domain *
```

samba works fine by my logs are filled with the message 

**Output/Error in log files**:
```
2018-12-12T10:03:54.153545+01:00 sha6130 smbd[12557]: [2018/12/12 10:03:54.153512,  1] ../source3/param/loadparm.c:2458(lp_idmap_range)
2018-12-12T10:03:54.153566+01:00 sha6130 smbd[12557]:   idmap range not specified for domain '*'
2018-12-12T10:03:54.484216+01:00 sha6130 smbd[10847]: [2018/12/12 10:03:54.484178,  1] ../source3/param/loadparm.c:2458(lp_idmap_range)
2018-12-12T10:03:54.484225+01:00 sha6130 smbd[10847]:   idmap range not specified for domain '*'
2018-12-12T10:03:55.271499+01:00 sha6130 smbd[10853]: [2018/12/12 10:03:55.271464,  1] ../source3/param/loadparm.c:2458(lp_idmap_range)
2018-12-12T10:03:55.271507+01:00 sha6130 smbd[10853]:   idmap range not specified for domain '*'
2018-12-12T10:04:25.521451+01:00 sha6130 smbd[11188]: [2018/12/12 10:04:25.521413,  1] ../source3/param/loadparm.c:2458(lp_idmap_range)
2018-12-12T10:04:25.521471+01:00 sha6130 smbd[11188]:   idmap range not specified for domain '*'

```

so should i simply ignore this messahe and filter it out from my rsyslog? or is there a solution for this.

**Comment by jelayeb** [comment]
my smb.conf
```

[global]
        security                = ads
        workgroup               = DOMAIN
        realm                   = DOMAIN.LOCAL
        netbios name            = sha6130
        machine password timeout= 0

        logging                 =  syslog@1 file
        log level               = 1 smb:4 acls:4 locking:4
        log file                = /var/log/samba/clients/%m.log
        smbd profiling level    = on

        load printers           = no
        printing                = bsd
        printcap name           = /dev/null
        disable spoolss         = yes
       
        template homedir        = /export/home/%U
        acl allow execute always = yes
        min protocol            = SMB2
        include  = /etc/samba/shares.conf

```

**Comment by jelayeb** [comment]
are you talking here about the testparam message or the log entries, as the same message i have it on other samba server. both of them centos7 and Samba version 4.6.2
. 
on older centos6.7 samba server  version 4.2.10 i dont have this error on testparam. 

Thanks

**Comment by jelayeb** [comment]
i found this link 
https://lists.samba.org/archive/samba/2017-March/207154.html

it looks like a samba bug, i will try to update samba to 4.7 on next possible time. and see how it looks after.

**Comment by bsulli01** [comment]
I am getting this same error.  I am connecting to AD through SSSD.  My configuration is similar.  Please advise?  My config file looks like this.

[global]
        security = ADS
        realm = FREDNET.COM
        workgroup = FREDNET
        netbios name = lnx-1234
        machine password timeout = 0

        local master = no
        password server = svr-dca.frednet.com
        passdb backend = tdbsam

**Comment by rbest-bt** [comment]
Try upgrading samba or reaching out to the sssd project
