### ISSUE TITLE
auto generated keytab file enteries

### ISSUE THREAD

**Issue by jelayeb** [BeyondTrust/pbis-open#18]
Hi 
i'm trying to understand how pbis works with krb5, and how it generate the keytab file when joining the domain, because i can seen enteries like host/fqdn@realm and cifs/fqdn@realm on the krb5.keytab.
is there a way to control those enteries like type of encryption and principle names?
why only host and cifs? why there is no HTTP?
on some old winbind hosts where they had keytab files with HTTP service on it, i found that when i used pbis to join the domain it includes the HTTP in the auto generated krb5.keytab. 

my aim is to use pbis for apache single sign on,, is that possible??

Thanks
Jasem

**Comment by rbest-bt** [comment]
We are working on providing this and addition documentation on github in the future. We are currently updating our Integration guide, which has information on apache SSO. If you would like an early review copy please send an email to openproject@beyondtrust.com.

**Comment by Abyss777** [comment]
Hello,
I'm using pbis generated keytab on some web servers with following lines in apache config:
````
Krb5KeyTab /etc/krb5.keytab
KrbServiceName Any
````
Works OK.

**Comment by rbest-bt** [comment]
Added [Documentation](https://github.com/BeyondTrust/pbis-open/wiki/Documentation) to github.

See Integration Guide for information on apache
