### ISSUE TITLE
osx no route to host when try to change password

### ISSUE THREAD

**Issue by mmiat** [BeyondTrust/pbis-open#180]
**Version**: 8.7.1.493
**OS/Distro**: OSX 10.14.1
**Issue/Impact**:

when I try to change password from gui, I receive "The password for the account was not changed. The server is not available. Change your password when your server becomes available."
when I try to change password from console, I receive "general error" or "authentication server could not be contacted"
same issues without pbis, with native osx authentication
"smbutil status antea.bogus" or "nslookup antea.bogus" work fine, while "smbutil lookup antea.bogus" says "no route to host"

**commands to check**
I attach some output
[domainjoin_query.txt](https://github.com/BeyondTrust/pbis-open/files/2676028/domainjoin_query.txt)
[lwsm_list.txt](https://github.com/BeyondTrust/pbis-open/files/2676029/lwsm_list.txt)
[pbis_status.txt](https://github.com/BeyondTrust/pbis-open/files/2676030/pbis_status.txt)

**Comment by mmiat** [comment]
during my tests, I tried to change my password and I receive an error, I dont remember exactly, something like "general error", but it CHANGED my password
i dont understand what the hell osx is doing

**Comment by rbest-bt** [comment]
I've tested this and I'm not able to reproduce the issue. Both Local and AD accounts are able to change their password via the "Users & Groups" change password option. 

I'm also not having luck with smbutil but I also do not have much experience with it. Your outputs look fine but judging from the error it seems like the connection to the DC goes down.

> same issues without pbis, with native osx authentication

Does this mean without PBIS installed or just a local account?

**Comment by mmiat** [comment]
I had the problem without PBIS installed, so I tried to install it, but issue remains. so I think there is some trouble in os, but how understand what? can I do some trace/debug with pbis? thanks

**Comment by rbest-bt** [comment]
Was it joined with a previous product and not removed from the domain?

**Comment by mmiat** [comment]
was joined with default osx app, then I leave, install pbis, re-join

**Comment by rbest-bt** [comment]
Doing a little searching it seems to be an issue with unbinding from the domain when the domain was unavailable. Best option is to remove PBIS then rejoin with Directory Utility and unbind again. Confirm password reset is working then reinstall PBIS. 

Resources:
- https://apple.stackexchange.com/questions/233505/el-capitan-with-network-authentication-change-password-not-working?rq=1
- https://apple.stackexchange.com/questions/309523/change-password-fails-with-server-not-available

**Comment by mmiat** [comment]
I've made this try:

1. unbind, removed pbis, rebooted
2. deleted profiles, rebooted
3. bind with default directory utility, rebooted
4. changed password succesfully

now the question is: how long it will work ? :D 
I'll do some other tests next days

**Comment by rbest-bt** [comment]
If it's bond and passwords are working then you should be ok. From there you should be ok to leave again and join with pbis. I would do the following
1. unbind
2. reboot
3. test password reset
4. install pbis and join domain
5. reboot and test

**Comment by mmiat** [comment]
unbind reboot and join again fixed all
thanks
