### ISSUE TITLE
NFS4/Kerberos not working with AD

### ISSUE THREAD

**Issue by Tobias-V** [BeyondTrust/pbis-open#181]
**Version**: 8.8.0.506, 8.6.0.427, 8.7.0.478, 8.7.1.494, 8.6.1.455 and possibly others
**OS/Distro**: CentOS 7 server
**Issue/Impact**:

I can not use Kerberos authentication on an NFS server. 

Following the integration guide, I succesfully installed an NFS server and integrated it with AD using version 8.6.0.427 a little over half a year ago. This one is still running and works as expected.

For about four months I have been unable to recreate such a server.
I have tried many different version of PBIS open, and have tried configuring things slightly different, but no matter what I do, any time I try to mount an NFS export with Kerberos, I get a 'Permission denied', as far as I can tell from months of debugging, a -13 error is generated by RPC, which indicates that something is wrong with the credentials.

I installed a brand new Windows server and set up a new domain for testing purposes, and I am unable to get this to work with the new domain either.

If I use SSSD, I can get the same NFS configuration to work. I also set up a Red Hat Identity Management server and got that to work - so the NFS packages definitely work.

I installed six CentOS servers today, five of them with various versions of PBIS Open, and all of them result in permission denied. The sixth server I joined to the domain using realmd, and manually added an SPN to the AD object - this server works. The file hierarchy and NFS configurations are identical on all six.

In all my testing, I am trying to mount the export from the same server that is exporting it.

As far as I can tell (from Wireshark and checking the tickets with klist) there is nothing wrong with the credentials. If there is any other information I can provide, please let me know.

**Steps to reproduce**:
Install CentOS (and enable networking)
login with admin account
sudo yum update
download and install pbis-open
sudo /opt/pbis/bin/config ServicePrincipalName "host" "nfs"
sudo /opt/pbis/bin/domainjoin-cli join --ou "OU" DOMAIN USERACC (replace capitalised part with relevant information)
sudo yum install nfs-utils
sudo mkdir /export
chmod 777 /export
edit /etc/exports to look like this: /export *(rw,sec=krb5)
sudo service nfs-server start

Now try to mount with: sudo mount -t nfs4 -o sec=krb5 FQDN:/export /mnt (replace FQDN with the fully qualified domain name, or IP address)
This always results in 'permission denied'
rpcdebug -m -s nfs reveals that setclientid throws an error -13, which as far as I can tell from following the source code is generated by rpc, and is this error: RPCSEC_GSS_CREDPROBLEM = 13, /* no credentials for user *
With wireshark I can tell that credentials are being sent.

If I replace pbis-open with sssd or if I install and configure my own KDC, this works - and a slight variation of this even worked six months ago.

**Comment by rbest-bt** [comment]
Checking against the integration guide there are a few pieces missing. Review the nfs integration section.

**Comment by Tobias-V** [comment]
I am sorry if it wasn't clear, I have followed the NFS integration section to the letter, it doesn't work.
I have simplified these instructions and removed irrelevant parameters. 
Sync, nohide and allowing other security options should not affect this - and the result is the same whether I enable them or not. 
Adding cifs as an SPN is also irrelevant, and adding this does not give a different result.
And installing the ACL tools also really aren't relevant, but I have tried that too.

Also please note that none of the above is required to set up an NFS4 server with Kerberos if I'm not using PBIS.

I have given you complete steps to reproduce the problem from installation of the operating system - and noted that following the integration guide reproduces the problem too. 
Are you unable to reproduce it?

**Comment by rbest-bt** [comment]
Nothing has changed in this area in the recent releases. We'll have a look to see if we can reproduce this.

**Comment by Tobias-V** [comment]
I have tried using the exact same version that is installed on the working server, in fact I think I've tried pretty much every available version with the same result.

Other than the operating system (CentOS), I've tried replacing pretty much every major component of the setup, one at a time - and only when I replace PBIS does it work - I am puzzled as to why this is the case.

If you are unable to reproduce, I would appreciate if you could share the details of your setup, as I have spent well over 100 hours trying to get this to work by now.

**Comment by rbest-bt** [comment]
Please upgrade to Active Directory Bridge Enterprise. If the issue still exists then please submit a ticket to our service team and we’ll have a look for you.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
