### ISSUE TITLE
Error: ERROR_CONNECTION_REFUSED [code 0x000004c9]

### ISSUE THREAD

**Issue by pankaj9492** [BeyondTrust/pbis-open#184]
I am facing error, can you please have look.....i am using over ubuntu 18

unicode@client1:~$ sudo /opt/pbis/bin/domainjoin-cli --loglevel info --logfile . join UNICODESYSTEMS.IN Administrator
20190116194506:INFO:Domainjoin invoked with the join command (remaining arguments will be printed later):
20190116194506:INFO: [/opt/pbis/bin/domainjoin-cli]
20190116194506:INFO: [--loglevel]
20190116194506:INFO: [info]
20190116194506:INFO: [--logfile]
20190116194506:INFO: [.]
20190116194506:INFO: [join]
20190116194506:INFO:Validating join options.
20190116194506:INFO:Domainjoin invoked with 2 arg(s) to the join command:
20190116194506:INFO: [UNICODESYSTEMS.IN]
20190116194506:INFO: [Administrator]
20190116194506:INFO:Adding client10 (fqdn client10.unicodesystems.in) to /etc/hosts ip 127.0.1.1, removing client10, client10.unicodesystems.in, client10, client10.unicodesystems.in
20190116194506:INFO:Reading krb5 file /tmp/likewisetmpIGeNFj/etc/krb5.conf
20190116194506:INFO:Reading nsswitch file /etc/nsswitch.conf
20190116194506:INFO:Reading krb5 file /tmp/likewisetmpWlSUFQ/etc/krb5.conf
20190116194506:INFO:Distro Version 18.04
20190116194506:INFO:Found config file /etc/ssh/sshd_config
20190116194506:INFO:Found binary /usr/sbin/sshd
20190116194506:INFO:Reading ssh file /etc/ssh/sshd_config
20190116194506:INFO:Found open sshd version 7.6.-1p1
20190116194506:INFO:Testing option ChallengeResponseAuthentication
20190116194506:INFO:Testing option UsePAM
20190116194506:INFO:Testing option PAMAuthenticationViaKBDInt
20190116194506:INFO:Option PAMAuthenticationViaKBDInt not supported
20190116194506:INFO:Testing option KbdInteractiveAuthentication
20190116194506:INFO:Testing option GSSAPIAuthentication
20190116194506:INFO:Option GSSAPIAuthentication supported
20190116194506:INFO:Testing option GSSAPICleanupCredentials
20190116194506:INFO:Found config file /etc/ssh/ssh_config
20190116194506:INFO:Found binary /usr/bin/ssh
20190116194506:INFO:Reading ssh file /etc/ssh/ssh_config
20190116194506:INFO:Testing option GSSAPIAuthentication
20190116194506:INFO:Option GSSAPIAuthentication supported
20190116194506:INFO:Testing option GSSAPIDelegateCredentials
20190116194506:INFO:Option GSSAPIDelegateCredentials supported
Joining to AD Domain: UNICODESYSTEMS.IN
With Computer DNS Name: client10.unicodesystems.in

Administrator@UNICODESYSTEMS.IN's password:
20190116194512:INFO:Using user entered password
20190116194512:INFO:Running module join

Error: ERROR_CONNECTION_REFUSED [code 0x000004c9]

20190116194526:ERROR:ERROR_CONNECTION_REFUSED [ERROR_CONNECTION_REFUSED]

Stack Trace:
/builder/src-git/Platform/src/linux/domainjoin/domainjoin-cli/src/main.c:1640
/builder/src-git/Platform/src/linux/domainjoin/domainjoin-cli/src/main.c:894
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djmodule.c:356
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djauthinfo.c:858
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djauthinfo.c:1271

**Comment by rbest-bt** [comment]
Seems the DC rejected the join. Try and have a look at the domains event logs.
