### ISSUE TITLE
gpagent.so 

### ISSUE THREAD

**Issue by bamusse** [BeyondTrust/pbis-open#185]
**Version**: 8.8.0
**OS/Distro**: CentOS 7
**Issue/Impact**: lwsmd won't start, hangs on gpagent.so "File not found"

I can find no reference to gpagent anywhere... 

I've edited the reg which has it listed:
HKLM\services\gpagent 
REG_DWORD Value 0x00000001 
default 0x00000000
path /opt/pbis/lib64/lw-svcm/gpagent.so 

to "value 0x00000000"
and lwsmd then starts but...

It comes back after restart. 
Where is this Group Policy Agent so??? 
Also is this the cause of the PAM module not updating pam.d? 

Thanks!

**Comment by rbest-bt** [comment]
Did you install Enterprise before open?

I recommend downloading the script installer and using the purge option to clean up the install.

**Comment by bamusse** [comment]
Not me, however I did notice a pbis-enteprise-install.log. I had a feeling someone else had installed it, and this may have been the reason. 
The last time I used the pbis-open uninstall.sh it died as it couldn't find the MANIFEST. I have a feeling enterprise was installed with yum will a script install and then uninstall.sh --purge take care of both installs?

**Comment by bamusse** [comment]
Thanks for your help! This help request has been fixed!

**Comment by rbest-bt** [comment]
The MANIFEST file is created with the script installer. We are looking into fixing the packages to handle this better. For now the script installer with the purge option should clean things up.
