### ISSUE TITLE
How to turn off debug mode for PBIS authentication

### ISSUE THREAD

**Issue by a2steven** [BeyondTrust/pbis-open#188]
**Version**: 8.5.4.334
**OS/Distro**: Ubuntu desktop 16.04 - unity desktop
**Issue/Impact**:
*Note: replace content with your own*
When reporting an issue it's important that we have as much detail as you can provide. The following is a list of commands to check.
 1. systemctl status lwsmd.service
 2. /opt/pbis/bin/lwsm list
 3. /opt/pbis/domainjoin-cli query
 4. pbis status
 5. /opt/pbis/bin/enum-users
 6. attach logs
  - /opt/pbis/bin/lwsm set-log-target -p lsass -  file /tmp/lsass.log
  - /opt/pbis/bin/lwsm set-log-level -p lsass - debug
  - attach log

**Output/Error**:

**Steps to Reproduce**:
 1. install command
 2. Domainjoin command
 3. Command that returns issue

**Comment by a2steven** [comment]
Thank you David

**Comment by a2steven** [comment]
Error: LW_ERROR_INVALID_PARAMETER (40041)
Invalid parameter

**Comment by dmorash-BT** [comment]
You might have a typo in your set-log-level line. 
/opt/pbis/bin/lwsm set-log-level -p lsass - warning

You can also set the service back to its default log level with 
/opt/pbis/bin/lwsm reset-log-defaults lsass

Then you will need to restart the service for it to pick up the new log level
/opt/pbis/bin/lwsm restart lsass

**Comment by a2steven** [comment]
it works. Thank you 
[root@server bin]# /opt/pbis/bin/lwsm reset-log-defaults lsass
Log defaults for service lsass were reset.
You will need to restart lsass to pick up the new defaults.
[root@server bin]# /opt/pbis/bin/lwsm  restart lsass
Stopping service: lsass
Starting service: lsass
