### ISSUE TITLE
Use configurable mappings

### ISSUE THREAD

**Issue by NdK73** [BeyondTrust/pbis-open#19]
Hello.

IIUC, currently PBIS uses a fixed mapping of users and groups from SID to UID/GID (by taking some bits from the domain SID and others from the object SID).
While it could be a good default for most situations, I find it quite limiting relative to winbind, where I used
        idmap config DOM1:backend = rid
        idmap config DOM1:base_rid  = 500
        idmap config DOM1:range = 100000 - 49999999
        idmap config DOM2:backend = rid
        idmap config DOM2:base_rid  = 500
        idmap config DOM2:range = 50000000 - 99999999
This way it's possible to "squeeze" domains known to have lesser users/groups in smaller ranges, reserving more space for bigger domains and avoid collisions.
I already saw about a dozen mapping collisions in one of our domains (with abount 400k users and 600-800k groups), and I'd like to avoid this situation, if possible. But I'm only allowed to join machines in a single OU and can't alter the schema.

Tks.

**Comment by NdK73** [comment]
Lately the issue became worse.
/var/log/syslog gets spammed by a couple GB/day of messages like:
`lsass: [lsass] Conflict discovered for UID 620849230. User DOMAIN\name.surname had this UID at time 2019/02/06 06:25:14, but now (2019/02/06 06:30:01) user DOMAIN\othername.othersurname has the UID. Please check that these users are not currently conflicting in Active Directory. This could also happen (safely) if the UIDs were swapped between these users.`
Is there a way to at least "silence" lsass?

**Comment by rbest-bt** [comment]
We have a plan to address this in the future allowing the ranges to be configurable. For now the only solution is to use Enterprise and provision(assign UIDs and GIDs) the accounts that are needed.

**Comment by NdK73** [comment]
Eagerly waiting for configurable ranges, since any other solution wouldn't fit our scenario :(

**Comment by NdK73** [comment]
Still no news re: configurable ranges?

**Comment by NdK73** [comment]
The problem is getting worse: I have at least a dozen conflicting users...
Still no workaround? Enterprise is not an option since I can not modify the directory...

**Comment by adcpdk** [comment]
Same here...

**Comment by PaulVanSchayck** [comment]
I've switched from pbis-open to SSSD with AD support since a couple of years to overcome this. There you can configure the ID mapping. See the `ldap_idmap_range_*` options.

https://linux.die.net/man/5/sssd-ad

**Comment by rbest-bt** [comment]
BeyondTrust Active Directory Bridge now has the storage option called ID Range. This method allows you to configure ID ranges for each and any domain. 

More information can be found here in our storage documentation:
https://www.beyondtrust.com/docs/ad-bridge/getting-started/installation/schema-nonschema-mode.htm

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
