### ISSUE TITLE
unable to switch dc for domain in forest

### ISSUE THREAD

**Issue by nadavtoledo** [BeyondTrust/pbis-open#191]
**Version**: 8.8.0
**OS/Distro**: Ubuntu server 16.04 
**Issue/Impact**:
We are using pbis-open to auth users from AD domain into linux servers.
The scenario is as follow:
the server is joined successfully to A domain, and users allowed via RequireMemberOf A\\group1
A\\group1 is global scope group and its members are usernames from domain **B**
UserDomainPrefix = "B"

All the above setting was working so far for several months.
problem started when **one** of dc's of domain B went down.
I couldn't make pbis switch to the other dc. and so users cannot log in.

**Output/Error**:

**/var/log/syslog:**
 lsass: [lsass] Domain 'B' is now offline

**excerpt from pbis-status**
               Domain flags:     [0x0002]
                                  [0x0002 - Offline]
                [Domain Controller (DC) Information]
DC Name:              dc2

The reported dc for B domain is : dc2 which is indeed offline!

**/opt/pbis/bin/get-dc-list B**
Got 1 DCs:

DC 1: Name = 'dc1', Address = 'correct ip'

tried to config:
BlacklistDC "dc2"

Didn't work.

Is there a way to set the dc for specific domain in the forest?
Please note, B domain is not the domain the server is joined to.
Thanks in advance.

**Comment by rbest-bt** [comment]
There is a blacklist config option that could help with this.

**Comment by nadavtoledo** [comment]
I believe Blacklist is only for dc that control the domain you actually join to, and not to other domains in the forest.
I already rtied it with dc name, dc ip, both, neither worked.

**Comment by hasanakgoz** [comment]
I have a same issue. Do you have a any solution ? BlacklistDC config not working well.

**Comment by rbest-bt** [comment]
Please upgrade to Active Directory Bridge Enterprise which has a fix for this. If the issue still exists then please submit a ticket to our service team and we’ll have a look for you.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
