### ISSUE TITLE
"LW_ERROR_LADAP_LOCAL_ERROR [code 0x00009d5f]"

### ISSUE THREAD

**Issue by bigbizze** [BeyondTrust/pbis-open#192]
**Version**: 8.8.0.506
**OS/Distro**: Ubuntu 18.10 cosmic
**Issue/Impact**:

I am attempting to connect a linux virtualbox machine to a windows 10 server active directory domain controller using pbis.

I followed this guide: https://linoxide.com/ubuntu-how-to/configure-pbis-join-ubuntu-windows-ad/ to do so and have run into a problem that I can't seem to mitigate.

The purpose of the virtual network I've set up is to test sendmail configurations and be able to use the active domain name for doing so instead of a FQDM. It has two primary machines - the active domain controller itself using this guide: https://www.psattack.com/articles/20160718/setting-up-an-active-directory-lab-part-1/ and a firewall (also set up using this guide) using PFSense.

I've added the linux machine to the same host adapter that the firewall and domain controller are connected to and have no issues pinging back and forth, my linux machine was also assigned an IP from the DHCP also set up on the same machine as the domain controller.

When I attempt to use sudo domainjoin-cli join example.com administrator and answer the subsequent prompt requesting a password I am getting the error "LW_ERROR_LADAP_LOCAL_ERROR [code 0x00009d5f]".

My linux machine then shows up in my active directory administrative center as a machine in the active directory, but is not assigned a DNS name and thus can't be used for SMTP testing over this network (at least as far as I'm aware).

The only other reference to this error on the entire internet is some dude asking about it in Russian (https://forum.ubuntu.ru/index.php?topic=291204.0) and getting no response so I'm struggling to identify how to approach the problem.

I've tried editing /etc/resolv.conf and changing the IP address from the default (which in my case is the IP of the firewall) to the IP of the domain controller and still get the same error.

I've tried using the 4 latest versions of PBIS to no effect.

I've also tried most of the recommendations found in this thread: https://github.com/BeyondTrust/pbis-open/issues/51 considering it seemed the most similar to my problem to no effect.

I've also ensured that the outbound ports: 80, 443 are open per this: https://www.beyondtrust.com/docs/privileged-remote-access/getting-started/deployment/dmz/ports-firewalls.htm documentation.

All of these attempts were performed on a new clone of the machine that had only ran the command "sudo apt-get install openssh-server" prior to cloning

I'm doing all of this as a student for a machine learning project involving emails and am relatively inexperienced with networking in general so I apologize if this is a simple issue I'm missing.

I've also had no issues connecting other virtual machines to this active directory where they both receive a DNS name from it and are able to email eachother etc.

Thanks in advance for any help! Please let me know if I can provide any additional details. The suggested logging options for this post contained nothing pertinent to my problem as far as I can tell as the only relevant error is the one in the title.

**Comment by rbest-bt** [comment]
For ports have a look at the installation guide section on [Configure Firewall Ports](https://github.com/BeyondTrust/pbis-open/wiki/docs/PBIS_Installation_Guide.pdf). 

As for the resolv.conf this needs to be the ip of the domains DNS server in order for the agent machine to resolve all the ldap queries. With Ubuntu by default this is managed via the Network Manager, so any changes to the file can get reset.
