### ISSUE TITLE
Auth requisite pam_unix.so nullok try_first_pass - Access Denied (PBIS-Open + MFA)

### ISSUE THREAD

**Issue by Joshc5** [BeyondTrust/pbis-open#194]
**Version**: 8.8.0.506
**OS/Distro**: Oracle Linux OEL-R5-U6-x86_64 (modified version of RHEL)
**Issue/Impact**: When implementing PingID MFA, auth requisite pam_unix.so nullok try_first_pass must be set within the /etc/pam.d/system-auth file. It is normally set to "sufficient". However, when I make the change for auth pam_unix.so from sufficient to requisite, authentication via AD accounts receives "Access Denied" (SSH). Is there a work around?

When setting this to requisite, local accounts on the Linux server continue to authenticate and function properly (with PingID MFA working fine too). However AD accounts receive access denied.

Note: If I do change the 'auth pam_unix.so nullok try_first_pass' back to "sufficient", then AD accounts will authenticate fine, and PingID MFA works successfully with them. However, if I do that, local accounts on the Linux Server won't be prompted for MFA, which is an issue. 

The AD Integration/status is 100% working. It's just this authentication configuration breaks AD Account authentication. 

**Output/Error**: Access Denied

**Steps to Reproduce**:
 1. sudo vim /etc/pam.d/system-auth
2. Replace this line:   auth  sufficient  pam_unix.so   nullok   try_first_pass
With this:  auth    requisite   pam_unix.so   nullok   try_first_pass
 3. sudo service sshd restart

Why does this change cause it to not work? Is there a work around? Thank you.

**Comment by rbest-bt** [comment]
Requisite prevents the AD accounts from authenticating, as pam_unix is unaware of those accounts. AD accounts need to precede to pam_lsass which sits after.

See
http://linux-pam.org/Linux-PAM-html/sag-configuration-file.html

**Comment by Joshc5** [comment]
> Requisite prevents the AD accounts from authenticating, as pam_unix is unaware of those accounts. AD accounts need to precede to pam_lsass which sits after.
> 
> See
> http://linux-pam.org/Linux-PAM-html/sag-configuration-file.html

The way you put that into words, allowed me to wrap my mind around it better and I was able to implement a solution to allow for Authentication via AD users, and local users, with both having MFA enforced. Thank you.

**Comment by rbest-bt** [comment]
That is great to hear. Any chance you could provide the pam stack here so to others might find the same solution in the future. If you don't want to post it you can also email it to me at openproject@beyondtrust.com. From there I can work on documenting the solution in our integration guide.

**Comment by Joshc5** [comment]
> That is great to hear. Any chance you could provide the pam stack here so to others might find the same solution in the future. If you don't want to post it you can also email it to me at [openproject@beyondtrust.com](mailto:openproject@beyondtrust.com). From there I can work on documenting the solution in our integration guide.

Of course. To get the AD Integration (PBIS-Open) along with our MFA solution (PingID), I had to configure /etc/pam.d/system-auth as follows...

`#%PAM-1.0
# This file is auto-generated.
# User changes will be destroyed the next time authconfig is run.
auth        required      pam_env.so
auth        requisite     pam_lsass.so    smartcard_prompt    try_first_pass
auth        sufficient     pam_pingid.so
auth        requisite      pam_unix.so nullok try_first_pass
auth        sufficient     pam_pingid.so
auth        requisite      pam_succeed_if.so uid >= 500 quiet
auth        required      pam_deny.so

account     required      pam_lsass.so      unknown_ok
account     sufficient     pam_lsass.so
account     required      pam_unix.so
account     sufficient     pam_succeed_if.so uid < 500 quiet
account     required      pam_permit.so

password    sufficient     pam_lsass.so
password    requisite     pam_cracklib.so try_first_pass retry=5 minlen=7 lcredit=-1 ucredit=-1 dcredit=-1 difok=1
password    sufficient    pam_unix.so md5 shadow nullok try_first_pass use_authtok remember=5
password    required      pam_deny.so

session     optional      pam_keyinit.so revoke
session     required      pam_limits.so
session     [success=1 default=ignore] pam_succeed_if.so service in crond quiet use_uid
session     required      pam_unix.so`
