### ISSUE TITLE
OpenPBIS on SLES 12SP3

### ISSUE THREAD

**Issue by vladaurosh** [BeyondTrust/pbis-open#195]
**Version**: 8.8.0.506
**OS/Distro**: SLES 12SP3
**Issue/Impact**:

Hello. We are starting to use SLES 12SP3, we have couple of dozens of SLES servers, on most of them PBIS works fine but we are having issues on some of them. I am trying to troubleshoot but I am stuck so far.
These are troubleshooting steps:
**1. systemctl status lwsmd.service**
● lwsmd.service - BeyondTrust PBIS Service Manager
   Loaded: loaded (/usr/lib/systemd/system/lwsmd.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2019-01-25 22:37:48 +08; 3 weeks 6 days ago
 Main PID: 79219 (lwsmd)
    Tasks: 483 (limit: 1024)
   CGroup: /system.slice/lwsmd.service
           ├─79219 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─79285 lw-container lwreg
           ├─79357 lw-container eventlog
           ├─79429 lw-container netlogon
           ├─79498 lw-container lwio
           ├─79569 lw-container lsass
           └─79655 lw-container reapsysl

Feb 21 15:36:30 test-server lsass[79569]: [LwKrb5GetTgtImpl /builder/src-git/Platform/src/linux/lwadvapi/threaded/krbtgt.c:346] KRB5 Error code: -1765328360 (Message: Preauthentication failed)
Feb 21 15:36:30 test-server lsass[79569]: [lsass] Failed to authenticate user (name = 'admin\vlad') -> error = 40022, symbol = LW_ERROR_PASSWORD_MISMATCH, client pid = 130416

**2. /opt/pbis/bin/lwsm list**
lwreg          running (container: 79285)
dcerpc         stopped
eventlog       running (container: 79357)
lsass          running (container: 79569)
lwio           running (container: 79498)
netlogon       running (container: 79429)
rdr            running (io: 79498)
reapsysl       running (container: 79655)
usermonitor    stopped

**3. domainjoin-cli query**
Name = test-server
Domain = ADMIN.MYDOMAIN.COM
Distinguished Name = CN=TEST-SERVER,OU=Linux,DC=admin,DC=mydomain,DC=com

**4. pbis status**
LSA Server Status:

Compiled daemon version: 8.8.0.506
Packaged product version: 8.8.506.0
Uptime:        26 days 23 hours 20 minutes 23 seconds

[Authentication provider: lsa-activedirectory-provider]

        Status:        Online
        Mode:          Un-provisioned
        Domain:        admin.mydomain.com
        Domain SID:    S-1-5-21-3989831553-3321466967-4128181549
        Forest:        admin.mydomain.com
        Site:          IAD
        Online check interval:  300 seconds
        [Trusted Domains: 1]

        [Domain: ADMIN]

                DNS Domain:       admin.mydomain.com
                Netbios name:     ADMIN
                Forest name:      admin.mydomain.com
                Trustee DNS name:
                Client site name: IAD
                Domain SID:       S-1-5-21-3989831553-3321466967-4128181549
                Domain GUID:      89e9c8ef-35af-7848-9d94-f2d8d512af79
                Trust Flags:      [0x001d]
                                  [0x0001 - In forest]
                                  [0x0004 - Tree root]
                                  [0x0008 - Primary]
                                  [0x0010 - Native]
                Trust type:       Up Level
                Trust Attributes: [0x0000]
                Trust Direction:  Primary Domain
                Trust Mode:       In my forest Trust (MFT)
                Domain flags:     [0x0001]
                                  [0x0001 - Primary]

                [Domain Controller (DC) Information]

                        DC Name:              dc-1.admin.mydomain.com
                        DC Address:           10.21.16.70
                        DC Site:              IAD
                        DC Flags:             [0x0001f1fc]
                        DC Is PDC:            no
                        DC is time server:    yes
                        DC has writeable DS:  yes
                        DC is Global Catalog: yes
                        DC is running KDC:    yes

                [Global Catalog (GC) Information]

                        GC Name:              dc-2.admin.mydomain.com
                        GC Address:           10.21.16.71
                        GC Site:              IAD
                        GC Flags:             [0x0001f1fc]
                        GC Is PDC:            no
                        GC is time server:    yes
                        GC has writeable DS:  yes
                        GC is running KDC:    yes
						
**5. /opt/pbis/bin/enum-users**
User info (Level-0):
====================
Name:              ADMIN\vlad
Uid:               1107300641
Gid:               1107296769
Gecos:             Vlad Vlad
Shell:             /bin/bash
Home dir:          /home/ADMIN.vlad
...
TotalNumUsersFound: 369

**6. id admin\\vlad**
id: ‘admin\\vlad’: no such user

**7. This is what I see in messages when I try to login:**
2019-02-21T21:57:38.033275+08:00 test-server sshd [93103]: Invalid user admin\\vlad from 10.28.6.64
2019-02-21T21:57:38.033512+08:00 test-server sshd[93103]: input_userauth_request: invalid user admin\\\\vlad [preauth]
2019-02-21T21:57:38.256481+08:00 test-server sshd[93103]: Postponed keyboard-interactive for invalid user admin\\\\vlad from 10.28.6.64 port 58549 ssh2 [preauth]
2019-02-21T21:57:41.811621+08:00 test-server lsass: [LwKrb5GetTgtImpl /builder/src-git/Platform/src/linux/lwadvapi/threaded/krbtgt.c:346] KRB5 Error code: -1765328360 (Message: Preauthentication failed)
2019-02-21T21:57:41.812220+08:00 test-server lsass: [lsass] Failed to authenticate user (name = 'admin\vlad') -> error = 40022, symbol = LW_ERROR_PASSWORD_MISMATCH, client pid = 93112
2019-02-21T21:57:41.812333+08:00 test-server sshd[93112]: [lsass-pam] [module:pam_lsass]pam_sm_authenticate error [login:admin\vlad][error code:40022]
2019-02-21T21:57:41.812575+08:00 test-server sshd[93103]: error: PAM: Authentication failure for illegal user admin\\vlad from 10.28.6.64
2019-02-21T21:57:41.813041+08:00 test-server sshd[93103]: Failed keyboard-interactive/pam for invalid user admin\\vlad from 10.28.6.64 port 58549 ssh2
2019-02-21T21:57:42.019921+08:00 test-server sshd[93103]: Postponed keyboard-interactive for invalid user admin\\\\vlad from 10.28.6.64 port 58549 ssh2 [preauth]

Any help would be greatly appreciated.

Thanks,
Vlad

**Comment by rbest-bt** [comment]
Is /bin/bash a valid path to BASH?

**Comment by vladaurosh** [comment]
Thank for quick reply rbest-bt .
Yes, bash is installed.
bash-4.3-82.1.x86_64
which bash
/bin/bash

This doesn't look like password issue, since id command says no such user (!?).

**Comment by rbest-bt** [comment]
Can you confirm that NSCD cache is disabled. Also what does the nsswitch file look like?

**Comment by vladaurosh** [comment]
Here's /etc/nsswitch file:
passwd: compat lsass
group:  compat lsass

hosts:          files dns
networks:       files dns

services:       files
protocols:      files
rpc:            files
ethers:         files
netmasks:       files
netgroup:       files nis
publickey:      files

bootparams:     files
automount:      files nis
aliases:        files

It is same as on other SLES12 SP3 server that has same openpbis version running, without issues.

Here's /etc/nscd.conf file on both server (default, not touched):

        server-user             nscd
        debug-level             0
        paranoia                no

        enable-cache            passwd          yes
        positive-time-to-live   passwd          600
        negative-time-to-live   passwd          20
        suggested-size          passwd          211
        check-files             passwd          yes
        persistent              passwd          yes
        shared                  passwd          yes
        max-db-size             passwd          33554432
        auto-propagate          passwd          yes

        enable-cache            group           yes
        positive-time-to-live   group           3600
        negative-time-to-live   group           60
        suggested-size          group           211
        check-files             group           yes
        persistent              group           yes
        shared                  group           yes
        max-db-size             group           33554432
        auto-propagate          group           yes

        enable-cache            hosts           yes
        positive-time-to-live   hosts           600
        negative-time-to-live   hosts           0
        suggested-size          hosts           211
        check-files             hosts           yes
        persistent              hosts           no
        shared                  hosts           yes
        max-db-size             hosts           33554432

        enable-cache            services        yes
        positive-time-to-live   services        28800
        negative-time-to-live   services        20
        suggested-size          services        211
        check-files             services        yes
        persistent              services        yes
        shared                  services        yes
        max-db-size             services        33554432

        enable-cache            netgroup        yes
        positive-time-to-live   netgroup        28800
        negative-time-to-live   netgroup        20
        suggested-size          netgroup        211
        check-files             netgroup        yes
        persistent              netgroup        yes
        shared                  netgroup        yes
        max-db-size             netgroup        33554432

**Comment by rbest-bt** [comment]
nscd is enabled. Clear or disable it as it will impact pbis own caching.

**Comment by vladaurosh** [comment]
That was great advise.
I did this:
nscd --invalidate={passwd,hosts,group,netgroup,services}
Still didn't work but then restarted nscd service and now all looks good, id command returns expected output, and I am able to login with AD account.

rbest-bt, your help is very appreciated. I think we can close this one.
