### ISSUE TITLE
choose which domain controller to join

### ISSUE THREAD

**Issue by mmiat** [BeyondTrust/pbis-open#196]
**Version**:8.8.0.506
**OS/Distro**: Ubuntu desktop 18.04
**Issue/Impact**:
i've done some error with hostname, so i want to leave domain and re-join with correct hostname, but i cant. can I force it in some way?

**Output/Error**:
Error: LW_ERROR_KRB5KDC_ERR_C_PRINCIPAL_UNKNOWN [code 0x0000a309]
Client not found in Kerberos database

**Comment by mmiat** [comment]
I've solved with uninstall.sh purge but now I've a new issue
when I join, pbis adds my host to backup domain controller
this is not good because it overwrites configuration every 1 hour, copying from primary dc
can i specify, when join, to which server join?
thanks

**Comment by rbest-bt** [comment]
This sounds like you talking about Active Directory replication. What ever you create/delete on one dc in a domain is replicated to the others in the same domain. PBIS does not manage that. We do count on it working in the case that the first DC goes down.

As for your first issue try domainjoin-cli setname

**Comment by mmiat** [comment]
I've solved with a "workaround": I power off BDC, so when i joined domain it creates machine account in PDC, however i can't login, in auth.log I've this error:

> mar 04 14:09:42 an-nb06321lnx sshd[1911]: error: PAM: User account has expired for miatello.mauro from 192.168.10.31
mar 04 14:09:42 an-nb06321lnx sshd[1911]: fatal: monitor_read: unpermitted request 104

**Comment by mmiat** [comment]
i close, the machine is the same of #176
