### ISSUE TITLE
Trusted domain login issues

### ISSUE THREAD

**Issue by Cchokri97** [BeyondTrust/pbis-open#197]
**Version**: 8.8.4.334
**OS/Distro**:redhat 7.4 enterprise 
**Issue/Impact**:
*Note: not able to authenticate to users domain  over servers domain with AD trusted link. 

Is it possible to authenticate users on a trusted domain across a trusted link with  a production domain? 

Hello all,
Concerning authentication across trusted domain
We have 2 domains one for servers and one for users and a trusted one way relation is established between the 2 forests.
My question!
To make my authentication working does the client must access directly to the users domain or it can connect over the trusted link?
How firewalls have to be configured about client access.
Our configuration work now only if ports are opened from client to users domain and to servers domain too.
When we closed ports from client to users domain only cached local users can connect
Thank you for your help!

**Output/Error**:

**Comment by rbest-bt** [comment]
In your description are both the servers and clients the same thing? Which way is your trust going?

Simple answer is yes you need ports open to access the appropriate information. I would recommend reading the install guide for more details on trusts and ports.

**Comment by Cchokri97** [comment]
Hello,
Right clients are servers.
And we get answers from Microsoft about windows authentication.
When kerberos is used in case of trusted domains clients need to access to
both domains.
Regards
