### ISSUE TITLE
Unable to join into Domain post configuring OpenOTP 2MFA

### ISSUE THREAD

**Issue by saichand04** [BeyondTrust/pbis-open#198]
**Version**: 8.8.0
**OS/Distro**: CentOS-7
**Issue/Impact**: High
*Note: Unable to join into Domain with PBIS post configuring PAM OpenOTP MFA Plugin*

 1. systemctl status lwsmd.service
[root@pamlinux ~]# systemctl status lwsmd.service
● lwsmd.service - BeyondTrust PBIS Service Manager
   Loaded: loaded (/usr/lib/systemd/system/lwsmd.service; enabled; vendor preset                                                                                                                     : disabled)
   Active: active (running) since Mon 2019-03-18 16:47:26 IST; 2h 34min ago
  Process: 16547 ExecStart=/opt/pbis/sbin/lwsmd --start-as-daemon (code=exited,                                                                                                                      status=0/SUCCESS)
 Main PID: 16549 (lwsmd)
    Tasks: 76
   CGroup: /system.slice/lwsmd.service
           ├─16549 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─16557 lw-container lwreg
           ├─16570 lw-container eventlog
           ├─16582 lw-container netlogon
           ├─16592 lw-container lwio
           ├─16604 lw-container lsass
           └─16618 lw-container reapsysl

Mar 18 16:47:26 PAMLINUX systemd[1]: Started BeyondTrust PBIS Service Manager.
Mar 18 17:11:39 pamlinux lsass[16604]: [lsass] Failed to run provider speci...12
Mar 18 17:33:15 pamlinux lsass[16604]: [lsass] Failed to sync system time [...5]
Mar 18 17:48:20 pamlinux lsass[16604]: [lsass] Failed to sync system time [...5]
Mar 18 18:03:25 pamlinux lsass[16604]: [lsass] Failed to sync system time [...5]
Mar 18 18:18:29 pamlinux lsass[16604]: [lsass] Failed to sync system time [...5]
Mar 18 18:33:34 pamlinux lsass[16604]: [lsass] Failed to sync system time [...5]
Mar 18 18:48:38 pamlinux lsass[16604]: [lsass] Failed to sync system time [...5]
Mar 18 19:02:45 pamlinux lsass[16604]: [lsass] Failed to sync system time [...5]
Mar 18 19:17:49 pamlinux lsass[16604]: [lsass] Failed to sync system time [...5]
Hint: Some lines were ellipsized, use -l to show in full.

 2. /opt/pbis/bin/lwsm list
[root@pamlinux ~]# /opt/pbis/bin/lwsm list
lwreg          running (container: 16557)
dcerpc         stopped
eventlog       running (container: 16570)
lsass          running (container: 16604)
lwio           running (container: 16592)
netlogon       running (container: 16582)
rdr            running (io: 16592)
reapsysl       running (container: 16618)
usermonitor    stopped

 3. /opt/pbis/domainjoin-cli query
 4. pbis status
[root@pamlinux ~]# pbis status
LSA Server Status:

Compiled daemon version: 8.8.0.506
Packaged product version: 8.8.506.0
Uptime:        0 days 2 hours 36 minutes 4 seconds

[Authentication provider: lsa-activedirectory-provider]

        Status:        Online
        Mode:          Un-provisioned
        Domain:        LOLLIPOP.COM
        Domain SID:    S-1-5-21-1925420108-1042707617-3058074848
        Forest:        lollipop.com
        Site:          Default-First-Site-Name
        Online check interval:  300 seconds
        [Trusted Domains: 1]

        [Domain: LOLLIPOP]

                DNS Domain:       lollipop.com
                Netbios name:     LOLLIPOP
                Forest name:      lollipop.com
                Trustee DNS name:
                Client site name: Default-First-Site-Name
                Domain SID:       S-1-5-21-1925420108-1042707617-3058074848
                Domain GUID:      059d44f7-e4e7-e848-b9d9-d95628db3f99
                Trust Flags:      [0x001d]
                                  [0x0001 - In forest]
                                  [0x0004 - Tree root]
                                  [0x0008 - Primary]
                                  [0x0010 - Native]
                Trust type:       Up Level
                Trust Attributes: [0x0000]
                Trust Direction:  Primary Domain
                Trust Mode:       In my forest Trust (MFT)
                Domain flags:     [0x0001]
                                  [0x0001 - Primary]

                [Domain Controller (DC) Information]

                        DC Name:              sandbox.lollipop.com
                        DC Address:           10.100.71.247
                        DC Site:              Default-First-Site-Name
                        DC Flags:             [0x0000f3fd]
                        DC Is PDC:            yes
                        DC is time server:    yes
                        DC has writeable DS:  yes
                        DC is Global Catalog: yes
                        DC is running KDC:    yes

 5. /opt/pbis/bin/enum-users
[root@pamlinux ~]# /opt/pbis/bin/enum-users
User info (Level-0):
====================
Name:              LOLLIPOP\administrator
Uid:               416809460
Gid:               416809473
Gecos:             <null>
Shell:             /bin/sh
Home dir:          /home/local/LOLLIPOP/administrator

User info (Level-0):
====================
Name:              LOLLIPOP\guest
Uid:               416809461
Gid:               416809474
Gecos:             <null>
Shell:             /bin/sh
Home dir:          /home/local/LOLLIPOP/guest

User info (Level-0):
====================
Name:              LOLLIPOP\krbtgt
Uid:               416809462
Gid:               416809473
Gecos:             <null>
Shell:             /bin/sh
Home dir:          /home/local/LOLLIPOP/krbtgt

User info (Level-0):
====================
Name:              LOLLIPOP\saichand_r
Uid:               416810064
Gid:               416809473
Gecos:             saichand
Shell:             /bin/sh
Home dir:          /home/local/LOLLIPOP/saichand_r

TotalNumUsersFound: 4
 6. attach logs
  - /opt/pbis/bin/lwsm set-log-target -p lsass -  file /tmp/lsass.log
  - /opt/pbis/bin/lwsm set-log-level -p lsass - debug
  - attach log

**Output/Error**:

**Steps to Reproduce**:
 1. install command
 2. Domainjoin command
      /opt/pbis/bin/domainjoin-cli join LOLLIPOP.COM saichand_r
 3. Command that returns issue
      /opt/pbis/bin/domainjoin-cli join LOLLIPOP.COM saichand_r
![root@pamlinuxetcpam d_2019-03-18_19-02-03](https://user-images.githubusercontent.com/48683188/54535514-b1f3da00-49b4-11e9-9115-cae338b5efe6.png)
[lsass.log](https://github.com/BeyondTrust/pbis-open/files/2978492/lsass.log)

**Comment by rbest-bt** [comment]
It's best to join the domain before you configure other pam modules that might not been known to PBIS. If not then join with --disable PAM and add the pam_lsass modules in manually. This is not recommended unless you have a strong understanding of PBIS and PAM.

**Comment by saichand04** [comment]
Hi rbest-bt, thanks for your swift help.
We've just followed your instructions and it worked perfectly.
we first added thr target Linux server into Domain by PBIS and then configured our PAM OpenOTP plugins.
worked perfectly. thankyou for your support.
