### ISSUE TITLE
Incompatibility with samba4

### ISSUE THREAD

**Issue by ABlueCasket** [BeyondTrust/pbis-open#2]
Using pbis for Domain authentication seems to be a great way to include Systems into AD. While I was testing a configuration, I realised that samba4 isn’t supported
```
user@tst-lu1604-dcl:/opt/pbis/bin$ sudo ./samba-interop-install --check-Version
[sudo] password for user:
Found smbd version 4.3.11-Ubuntu
Unsupported smbd version 4.3.11-Ubuntu
Error: ERROR_PRODUCT_VERSION
```
Especially Ubuntu Server supports samba4 only since 14.04.
Is there any chance to use pbis with samba4?

Thank you in advance.

**Comment by RBoulton-BT** [comment]
Support for these versions of Samba is scheduled for inclusion in the upcoming 8.5.2 release. This should hopefully be available end of November/ early December.

**Comment by ABlueCasket** [comment]
I'm dying to check the new version :)

**Comment by rbest-bt** [comment]
The plan is to get a release out before the end of the year holidays. You can compile from source now and have the samba fix if it's urgent

link to commit
99c88f9e3c307cae5d002aa6fe48e9651e978a6d

**Comment by rbest-bt** [comment]
8.5.2 has been uploaded. Please give it a try and let me know if it works for you.

**Comment by ABlueCasket** [comment]
Hi,
I tested it out using Windows Server 2016 TP5 DC an Ubuntu Server 1604. 
It seems to work perfectly, samba-interop-install was successfuly installed.
Thank you very, very much.

Offtopic: Is there some Documentation or even an example where i could find hints for an working samba share for an Domain Group?

**Comment by rbest-bt** [comment]
Thanks for the confirmation
