### ISSUE TITLE
Licensing not clear

### ISSUE THREAD

**Issue by BobBall** [BeyondTrust/pbis-open#20]
https://github.com/BeyondTrust/pbis-open/blob/master/package/open/rpm/open.spec.in however suggests that the license is "Likewise Proprietary", but this does not match with the wiki which states that the license is GPLv2.

No general LICENSE file exists in https://github.com/BeyondTrust/pbis-open which leaves users to consult the wiki (which is potentially out of date WRT code) at https://github.com/BeyondTrust/pbis-open/wiki/Licensing
Note that some sub-trees (e.g. https://github.com/BeyondTrust/pbis-open/tree/master/lsass) do include a LICENSE file bit many do not.

**Comment by rbest-bt** [comment]
we are working to clear this up

**Comment by rbest-bt** [comment]
Addressed in e5a3b82

I'll update the wiki later to point to these files

**Comment by BobBall** [comment]
That's awesome, many thanks for the clarifications!
