### ISSUE TITLE
pbis with pam_slurm_adopt

### ISSUE THREAD

**Issue by nadavtoledo** [BeyondTrust/pbis-open#200]
**Version**: 8.5.4.334
**OS/Distro**: Ubuntu server 16.04
**Issue/Impact**:
in cluster environment managed by slurm, users are auth against AD via pbis. it's require to let users have ssh access to nodes they have running jobs on. this achieved via a module to slurm the manipulate pam.d files in a way that sshing end up inside the job context in the node.
context meaning same resources (cpu,ram,gpu etc).

while this module works perfectly when pbis is not installed. it doesn't succeed forcing the right context when pbis doing the authenticating. The user end up inside the node (ssh successfully) but not in the context, but as if the above module doesn't exist at all.

**Details**:

**scenario1**: pbis was never installed (adopt succeed)

login server$ srun -c1 --pty bash
compA$ ssh slurm-node
slurm-node$ nproc
1

auth.log on slurm-node:
Mar  7 08:54:29 slurm-node pam_slurm_adopt[**7329**]: Connection by user temp: user has only one job 5
Mar  7 08:54:29 slurm-node pam_slurm_adopt[**7329**]: Process 7329 adopted into job 5
Mar  7 08:54:29 slurm-node sshd[**7329**]: Accepted password for temp from IP_HERE port 57052 ssh2
Mar  7 08:54:29 slurm-node sshd[**7329**]: pam_unix(sshd:session): session opened for user temp by (uid=0)

I bolded process number, it consistent.

**sceanrio2**: pbis installed (adopt failed)

login server$ srun -c1 --pty bash
compA$ ssh slurm-node
slurm-node$ nproc
2

*two is the total amount of cpus on slurm-node

auth.log on slurm-node:
Mar  7 09:00:52 slurm-node pam_slurm_adopt[**1595**]: Connection by user temp: user has only one job 8
Mar  7 09:00:53 slurm-node pam_slurm_adopt[**1595**]: Process 1595 adopted into job 8
Mar  7 09:00:53 slurm-node sshd[**1593**]: Accepted keyboard-interactive/pam for temp from IP_HERE port 33218 ssh2
Mar  7 09:00:53 slurm-node sshd[**1593**]: pam_unix(sshd:session): session opened for user temp by (uid=0)

here the process number changed! the adoption is for one process and eventually we successfully getting ssh access but with different process number and context.

ps -ef |grep 1595
no output

ps -ef |grep 1593
root      1593  1093  0 14:57 ?        00:00:00 sshd: temp [priv]
temp    1627  1593  0 14:57 ?        00:00:00 sshd: temp@pts/2

Notes:
sceanrio2 haven't changed when i tried:
a. stopping pbis service (lwsmd)
b. restore all pam.d files to scenario1 state
c. sudo apt purge pbis-open & reboot didnt help!!
d. pbis in itself works correctly (authenticating wise)
e. as said, pam_slurm_adopt on itself works correctly

My conclusion is that pbis changed something in the way linux pam works outside pam.d folder,  but i can't figure out where

If anyone got an idea, will be glad to hear.

**Steps to Reproduce**:
 1.installe via deb file
 2. ssh from remote via local user and see the process number changed!

Thanks in advance for any help provided.
Nadav

**Comment by rbest-bt** [comment]
We have a team that assists with this type of deployment on the enterprise side.
