### ISSUE TITLE
Unable for AD user to log in to Ubuntu desktop via GUI, log in via ssh successfull

### ISSUE THREAD

**Issue by blazejmarciniak** [BeyondTrust/pbis-open#202]
**Version**: 8.8.0.506
**OS/Distro**: Linux Ubuntu desktop 18.04.2 - Gnome 3.28.2
**Issue/Impact**: 

Unable for AD user to log in to Ubuntu desktop via XRDP nor GUI, log in via ssh successfull. Ubuntu is installed on KVM guest machine.

When reporting an issue it's important that we have as much detail as you can provide. The following is a list of commands to check.
 1. systemctl status lwsmd.service: active (running)
 2. /opt/pbis/bin/lwsm list:

lwreg          running (container: 9154)
dcerpc         stopped
eventlog       running (container: 9224)
lsass          running (container: 9429)
lwio           running (container: 9360)
netlogon       running (container: 9293)
rdr            running (io: 9360)
reapsysl       running (container: 9505)
usermonitor    stopped

 3. /opt/pbis/domainjoin-cli query
 4. pbis status: Online
 5. /opt/pbis/bin/enum-users: working
 6. attach logs
  - /opt/pbis/bin/lwsm set-log-target -p lsass -  file /tmp/lsass.log
  - /opt/pbis/bin/lwsm set-log-level -p lsass - debug
  - attach log
[lsass.log](https://github.com/BeyondTrust/pbis-open/files/3047224/lsass.log)

**Output/Error**:

**Steps to Reproduce**:
 1. install command
sudo ./pbis-open-8.8.0.506.linux.x86_64.deb.sh
 2. Domainjoin command
sudo domainjoin-cli join DOMAIN.NAME domain.admin.user
 3. Command that returns issue
log in via GUI

**Comment by rbest-bt** [comment]
Have you setup lightdm to allow manual logins? What is the behavior of the GUI login? Is there an error or does it just jump back to the login screen?

**Comment by blazejmarciniak** [comment]
Yes manual logins are set. Passing user creditionals it goes back to login screan. It started to work I am waiting for info from AD admin if he have changed settings.

**Comment by javier-izquierdo-visualfy** [comment]
i have same problem.

**Comment by rbest-bt** [comment]
Please upgrade to Active Directory Bridge Enterprise. If the issue still exists then please submit a ticket to our service team and we’ll have a look for you.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
