### ISSUE TITLE
The adtool Utility Does Not Appear to Work When "LDAP sign and seal" Enabled on Domain

### ISSUE THREAD

**Issue by ferricoxide** [BeyondTrust/pbis-open#203]
**Version**: 8.5.3
**OS/Distro**: RHEL7 / CentOS7
**Issue/Impact**:
Prevents PBIS-initiated object-cleanup

**Output/Error**:

When attempting to re-join a node to the domain or when replacing a system with a new system of the same name, the `adtool` failes with "Stronger authentication required" message.

**Steps to Reproduce**:
 1. Join first system to domain
 2. Destroy joined system
 3. Build new system with same hostname
 4. Attempt to join new system to domain - resolving object-collision using the `adtool` utility

**Overview**:

Recently started deploying systems to a new AD domain. Tooling for resolving object-name collisions do not work on new AD domain. Still waiting word back from new domain's administrators, but appears that the new domain implements mandatory LDAP sign-and-seal. The `adtool` utility does not appear to support this – either as a default or as a flag-settable option.

**Comment by ferricoxide** [comment]
Ran the `adtool` utility under `strace`. Looks like:

1. Sends out a DNS query for the _ldap SRV records
1. Attempts to provide user/password credentials to the LDAP endpoints returned in the first step over unencrypted LDAP (TCP/389). Appears to eithe make multiple attempts against one target or iterates over all of the endpoints returned in the DNS query (difficult to suss out which)
1. After failing on the LDAP, it falls back to trying Kerberos authentication (TCP/88). It quickly fails
1. It spits out a `ERROR: 500008: Strong(er) authentication required` message and exits.

_Supposition:_ The TCP/88 failure is likely because, as a client that has never been a member of the domain, it doesn't have a Kerberos token to present to the Kerberos-auth service. I'm assuming that sign-and-seal is enabled (awaiting verification) and that's why it's disallowing the authentication attempt.

**Comment by ferricoxide** [comment]
Further diagnostics using `ldapsearch` utility from the `openldap-clients` RPM:

- If I do `ldapsearch -x -D <BIND_DN> -w <PASSWORD> -h <DOMAIN_CONTROLLER> -s sub -b <SEARCH_TOP> samAccountName <USER>` I get a `server requires bind to turn on integrity checking` error
- If I do `ldapsearch -Z -x -D <BIND_DN> -w <PASSWORD> -h <DOMAIN_CONTROLLER> -s sub -b <SEARCH_TOP> samAccountName <USER>` I get back the expected search result
- If I do `ldapsearch -x -D <BIND_DN> -w <PASSWORD> -H ldaps://<DOMAIN_CONTROLLER> -s sub -b <SEARCH_TOP> samAccountName <USER>` I get back the expected search result

Looking at the SRV records for my domain, it looks like it's only returning `<CONTROLLER>/389` responses (I'm not an AD guru, so this could be perfectly normal and I wouldn't know).

Given all of the above, I'm assuming that the failed connects by `adtool` on port 389 are due to it not attempting to TLS-encapsulate the connection on either the initial attempt or on a retry?

**Comment by ferricoxide** [comment]
Note: Updated my PBIS test version to 8.8.0 in my test environment. `adtool` still lacks the ability to interact with domains that have `LdapSignAndSeal` enabled.

**Comment by ferricoxide** [comment]
Also: tried using the PBIS-bundled `ldapsearch` utility. When I try to use it with TLS-mode enabled, I get the error:

~~~
ldapsearch: not compiled with TLS support
~~~

So, appears that the PBIS-bundled utilities that use LDAP connection-methods are generically not usable in domains with LdapSignAndSeal enabled.

**Comment by rbest-bt** [comment]
Try enabling the config option for Sign and Seal

$ sudo /opt/pbis/bin/config --detail LdapS
Name: LdapSignAndSeal
Description: Whether all LDAP traffic should be sent both signed and sealed
Type: boolean
Current Value: false
Accepted Values: true, false
Current Value is determined by local policy.

**Comment by ferricoxide** [comment]
Quick query:

Since my test environment doesn't have SignAndSeal enabled and only _one_ of my production environments does (why I've not encountered this issue over the past 2+ years), I can only test _without_ LdapSignAndSeal enabled. When I run an strace of adtool, it appears to walks through the:

~~~
tcp/53 (DNS) → tcp/389 (LDAP) → tcp/88 (Kerberos-auth)
~~~

Sequence regardless of setting. Presumably since the bundled LDAP routines are not TLS-enabled, that second step is going to continue to fail in my problematic production environment. If so, would such a failure be fatal to the overall operation? I'm asking because, if said failure is non-fatal, it essentially means that the LDAP step is optional ...and if the LDAP step _is_ (essentially) optional, why does it happen at all?

At any rate, won't be able to validate the suggestion on the problem domain till this coming Monday. In the mean time, thank you for the suggestion.

**Comment by ferricoxide** [comment]
Just checked a few seconds ago. Even with `LdapS` set to `true`, I get the `ERROR: 500008: Strong(er) authentication required` error message. The `adtool` utility does not seem to be effected by that setting.

**Comment by ferricoxide** [comment]
@rbest-bt 

Is this an issue that is unlikely to be addressed? I've had to move on to using OpenLDAP to do the things that `adtool` is incapable of. I'm just looking to get some kind of closure on this, even if it's `WONTFIX`

**Comment by rbest-bt** [comment]
Active Directory Bridge Enterprise will be addressing this.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
