### ISSUE TITLE
domainjoin-cli join to rodc problem

### ISSUE THREAD

**Issue by xzxzard** [BeyondTrust/pbis-open#204]
**Version**: 8.6.427
**OS/Distro**: Ubuntu 18.04
**Issue/Impact**: domainjoin-cli join to rodc problem
**checklist:**
 1. systemctl status lwsmd.service

> lwsmd.service - BeyondTrust PBIS Service Manager
>    Loaded: loaded (/lib/systemd/system/lwsmd.service; enabled; vendor preset: enabled)
>    Active: active (running) since Fri 2019-04-26 14:52:18 MSK; 1 weeks 3 days ago
>  Main PID: 816 (lwsmd)
>     Tasks: 204 (limit: 4915)
>    CGroup: /system.slice/lwsmd.service
>            ├─  816 /opt/pbis/sbin/lwsmd --start-as-daemon
>            ├─  847 lw-container lwreg
>            ├─  924 lw-container eventlog
>            ├─  952 lw-container netlogon
>            ├─23445 lw-container dcerpc
>            ├─29857 lw-container lwio
>            ├─29882 lw-container reapsysl
>            └─29912 lw-container lsass

> may 06 15:29:56 hostname lwio[29857]: [lwio] GSS-API error calling gss_init_sec_context: -1765328228 (Cannot contact any KDC for realm 'EXAMPLE.COM')
> may 06 15:29:56 hostname lsass[29912]: [lsass] Failed to run provider specific request (request code = 8, provider = 'lsa-activedirectory-provider') -> error = 31, symbol = ERROR_GEN_FAILURE, client pid = 32
> may 06 15:35:26 hostname lwio[29857]: [lwio] GSS-API error calling gss_init_sec_context: 851968 (Unspecified GSS failure.  Minor code may provide more information)
> may 06 15:35:26 hostname lwio[29857]: [lwio] GSS-API error calling gss_init_sec_context: -1765328228 (Cannot contact any KDC for realm 'EXAMPLE.COM')
> may 06 15:35:26 hostname lsass[29912]: [lsass] Failed to run provider specific request (request code = 8, provider = 'lsa-activedirectory-provider') -> error = 31, symbol = ERROR_GEN_FAILURE, client pid = 46
> may 06 15:36:11 hostname lsass[29912]: [LwKrb5GetTgtImpl /builder/src-git/Platform/src/linux/lwadvapi/threaded/krbtgt.c:346] KRB5 Error code: -1765328228 (Message: Cannot contact any KDC for realm 'EXAMPLE.COM')
> may 06 15:36:11 hostname lsass[29912]: [lsass] Failed to run provider specific request (request code = 8, provider = 'lsa-activedirectory-provider') -> error = 40121, symbol = LW_ERROR_DOMAIN_IS_OFFLINE, cli
> may 06 15:37:34 hostname lwio[29857]: [lwio] GSS-API error calling gss_init_sec_context: 851968 (Unspecified GSS failure.  Minor code may provide more information)
> may 06 15:37:34 hostname lwio[29857]: [lwio] GSS-API error calling gss_init_sec_context: -1765328228 (Cannot contact any KDC for realm 'EXAMPLE.COM')
> may 06 15:37:34 hostname lsass[29912]: [lsass] Failed to run provider specific request (request code = 8, provider = 'lsa-activedirectory-provider') -> error = 31, symbol = ERROR_GEN_FAILURE, client pid = 89

 2. /opt/pbis/bin/lwsm list

> lwreg          running (container: 847)
> dcerpc         running (container: 23445)
> eventlog       running (container: 924)
> lsass          running (container: 29912)
> lwio           running (container: 29857)
> netlogon       running (container: 952)
> rdr            running (io: 29857)
> reapsysl       running (container: 29882)
> usermonitor    stopped

 3. /opt/pbis/domainjoin-cli query

> Name = hostname
> Domain =

 4. pbis status

> LSA Server Status:
> 
> Compiled daemon version: 8.6.0.427
> Packaged product version: 8.6.427.243473
> Uptime:        0 days 0 hours 55 minutes 45 seconds
> 
> [Authentication provider: lsa-activedirectory-provider]
> 
> 	Status:        Unknown
> 	Mode:          Unknown
> 

 5. /opt/pbis/bin/enum-users

> TotalNumUsersFound: 0

 6. attach logs
[https://drive.google.com/file/d/1g6WQtx7FMxp5tCVA-WdN0eaWFRr-X7vP/view?usp=sharing](url)

**Output/Error**:

> ERROR_GEN_FAILURE
> LW_ERROR_DOMAIN_IS_OFFLINE

**Steps to Reproduce**:
 1. Just trying to join with
 `sudo /opt/pbis/bin/domainjoin-cli join example.com user
`

**Comment by rbest-bt** [comment]
We are looking to add this functionality directly into the domainjoin-cli in the future. For now the script can be found here:

`/opt/pbis/libexec/offline-join.pl --help`

**Comment by xzxzard** [comment]
offline-join.pl worked without errors, but nothing happen.
`pbis-status 
`

> LSA Server Status:
> 
> Compiled daemon version: 8.6.0.427
> Packaged product version: 8.6.427.243473
> Uptime:        0 days 0 hours 3 minutes 36 seconds
> 
> [Authentication provider: lsa-activedirectory-provider]
> 
> 	Status:        Unknown
> 	Mode:          Unknown
>

**Comment by rbest-bt** [comment]
No Response. Closing issue.
