### ISSUE TITLE
error: variable ‘pFuseContext’ set but not used [-Werror=unused-but-set-variable]

### ISSUE THREAD

**Issue by hzxie** [BeyondTrust/pbis-open#206]
**Version**: 9.0.1
**OS/Distro**: Arch Linux with GNOME Desktop Environment
**Issue/Impact**:
When I compiling the source code, I got an error message saying
```
error: variable ‘pFuseContext’ set but not used [-Werror=unused-but-set-variable]
```

**Steps to Reproduce**:
```
mkdir debug && cd debug
./configure --debug=yes --build-isas=x86_64 --fail-on-warn=no
make -j8
```

**Comment by Tetrokun** [comment]
I'm also having this issue
OS/Distro: Arch Linux with KDE Desktop environment. 

@hzxie Were you able to find a work arround?

**Comment by hzxie** [comment]
@Tetrokun 
No.

**Comment by rbest-bt** [comment]
pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
