### ISSUE TITLE
Trusted Domain Users Have No Groups

### ISSUE THREAD

**Issue by KoZm0kNoT** [BeyondTrust/pbis-open#21]
I have downloaded and installed the newest 8.5.3 release. However, I am still having issues with group memberships that involve accounts from an AD trust. Specifically, I have joined an AD domain PrimaryDomain which has a trust to another domain TrustedDomain. I have added a sudoers drop-in file to grant root access to an account in TrustedDomain. This part works fine...I can logon as the TrustedDomain account and elevate that account to root with sudo.

I do not want to have to explicitly place user into the sudoers drop-in. I want to use a TrustedDomain group account that has the user accounts as members and create a drop-in for the group.

However, if I remove the explicit account from the drop-in and instead create a drop-in for the group, the account is no longer able to be granted sudo permissions. If I examine the groups the TrustedDomain account belongs to I get "0":

```
[root@ip-10-22-13-249 ~]# /opt/pbis/bin/list-groups-for-user TRUSTEDDOMAIN\\someaccount
Number of groups found for user 'TRUSTEDDOMAIN\\someaccount' : 0
```
I used to see this behavior in the previous version if I cleared the cache and the group memberships will all start returning no results, but the groups will mysteriously repopulate itself at some point during the day.

Is there a way to initiate this or force a synchronization so all the groups are populated?

This is not an issue with PrimaryDomain accounts, only TrustedDomain accounts.

**Comment by mawe-net** [comment]
Hi KoZm0kNoT,

Having the same effect... 
try #id TRUSTEDDOMAIN\\someaccount
In our setup it synchronizes the cache again.
For me it looks like an authorization Problem via ldap.

regards

**Comment by KoZm0kNoT** [comment]
No luck using id to refresh here...still shows zero groups after running id command.

**Comment by rbest-bt** [comment]
What I'm reading this as, is an issue with the group membership populating. When you mentioned previous versions do you mean that the previous versions didn't have this issue? If so which one? Can you give the latest release a try(8.5.6) to confirm it still exists for you?
