### ISSUE TITLE
ERROR_INTERNAL_DB_CORRUPTION

### ISSUE THREAD

**Issue by mmiat** [BeyondTrust/pbis-open#213]
**Version**: 9.0.1
**OS/Distro**: OSX 10.14.4

my coleague Mac was joind with osx default method, but one days it started giving error "error during connection with server idrogeno.antea.bogus". so I leave domain, and install pbis
when I try to join, I have error:

Error: ERROR_INTERNAL_DB_CORRUPTION [code 0x0000054e]

and cant join, what I can try to do? thanks

![img_20190515_153914](https://user-images.githubusercontent.com/11910225/57781743-115b3580-772b-11e9-92a4-9cb8895dae8f.jpg)

**Comment by rbest-bt** [comment]
I would check on your Domain Controllers and hope you have backups. Review the windows systems event viewer for errors.

[System Error Codes (1300-1699)](https://docs.microsoft.com/en-us/windows/desktop/Debug/system-error-codes--1300-1699-)

> ERROR_INTERNAL_DB_CORRUPTION
    1358 (0x54E)
    Unable to complete the requested operation because of either a catastrophic media failure or a data structure corruption on the disk.

**Comment by mmiat** [comment]
uhm strange, but I'll check
I've 2 domain controllers, I'll try turning off the corrupted one and trying to join to the other
I'll update you tomorrow
thanks

**Comment by mmiat** [comment]
as you wrote, the db corrupted was the server one
sorry

**Comment by rbest-bt** [comment]
No worries. Thanks for the update.
