### ISSUE TITLE
Cached Credentials Issue

### ISSUE THREAD

**Issue by ramindas** [BeyondTrust/pbis-open#214]
**Version**: 8.5.4.334
**OS/Distro**: Ubuntu desktop 16.04 LTS
**Cached Credentials Issue**:
*Note: Cannot logon to the PC using Cached Credentials when network not available*

**Username or Password incorrect**:

**Comment by rbest-bt** [comment]
Try upgrading to 9.0.1

**Comment by ramindas** [comment]
Thanks a lot it is working
