### ISSUE TITLE
GUI options

### ISSUE THREAD

**Issue by ktsonevski** [BeyondTrust/pbis-open#216]
Compiled daemon version: 9.0.1.525
Packaged product version: 9.0.525

Linux Mint 19.3 - last upgrade
CLI works fine, the machine is added successfully, there is no problem. The problem is when I want to compile GUI with the following error:

---
Configuration summary
---

Host system:                  linux (x86_64)
Device profile:               default
Feature level:                full
Bundled libraries:            tomlc99 linenoise-mob libuuid openssl krb5 cyrus-sasl openldap sqlite curl popt libtdb libxml2 opensoap
Threadpool backend:           epoll
FUSE support:                 no
EA support:                   no
Domain join GUI:              gtk
Samba interoperability:       yes
SELinux support:              yes
Package types:                rpm deb

---
There are 10 types of people in this world: those who understand ternary, those who don't, and those who mistake it for binary.
---

debug $ make
           [symlink] /usr/bin/pbis -> /opt/pbis/bin/lsa
           [symlink] /usr/bin/domainjoin-cli -> /opt/pbis/bin/domainjoin-cli
              [link] /opt/pbis/bin/domainjoin-gui (host/x86_64)
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libglade-2.0.so: undefined reference to `xmlDocSetRootElement@LIBXML2_2.4.30'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libglade-2.0.so: undefined reference to `xmlGetPredefinedEntity@LIBXML2_2.4.30'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libglade-2.0.so: undefined reference to `xmlNewNode@LIBXML2_2.4.30'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libglade-2.0.so: undefined reference to `xmlAddChild@LIBXML2_2.4.30'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libglade-2.0.so: undefined reference to `xmlFreeDoc@LIBXML2_2.4.30'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libglade-2.0.so: undefined reference to `xmlNodeAddContent@LIBXML2_2.4.30'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libglade-2.0.so: undefined reference to `xmlNewDoc@LIBXML2_2.4.30'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libglade-2.0.so: undefined reference to `xmlSaveFileEnc@LIBXML2_2.4.30'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libglade-2.0.so: undefined reference to `xmlNodeSetContent@LIBXML2_2.4.30'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libglade-2.0.so: undefined reference to `xmlCreateIntSubset@LIBXML2_2.4.30'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libglade-2.0.so: undefined reference to `xmlSAXUserParseMemory@LIBXML2_2.4.30'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libglade-2.0.so: undefined reference to `xmlSAXUserParseFile@LIBXML2_2.4.30'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libglade-2.0.so: undefined reference to `xmlSetProp@LIBXML2_2.4.30'
collect2: error: ld returned 1 exit status
              [link] FAILED: 'gcc' '-o' 'stage/opt/pbis/bin/domainjoin-gui' 'object/domainjoin/domainjoin-gui/gtk/common.domainjoin-gui.host.x86_64.o' 'object/domainjoin/domainjoin-gui/gtk/joindialog.domainjoin-gui.host.x86_64.o' 'object/domainjoin/domainjoin-gui/gtk/joinprogress.domainjoin-gui.host.x86_64.o' 'object/domainjoin/domainjoin-gui/gtk/statusdialog.domainjoin-gui.host.x86_64.o' 'object/domainjoin/domainjoin-gui/gtk/joinauth.domainjoin-gui.host.x86_64.o' 'object/domainjoin/domainjoin-gui/gtk/joinerror.domainjoin-gui.host.x86_64.o' 'object/domainjoin/domainjoin-gui/gtk/main.domainjoin-gui.host.x86_64.o' '-pthread' '-Lstage/opt/pbis/lib' '-m64' '-Wl,--no-as-needed' '-Wall' '-Werror' '-fno-strict-aliasing' '-Wl,-rpath,/opt/pbis/lib' '-Wl,-rpath-link,stage/opt/pbis/lib' '-lcentutils' '-ldomainjoin' '-llwadvapi' '-llwadvapi_nothr' '-llwsm' '-lgthread-2.0' '-lglade-2.0' '-lgtk-x11-2.0' '-lgdk-x11-2.0' '-lpangocairo-1.0' '-latk-1.0' '-lcairo' '-lgdk_pixbuf-2.0' '-lgio-2.0' '-lpangoft2-1.0' '-lpango-1.0' '-lgobject-2.0' '-lglib-2.0' '-lfontconfig' '-lfreetype' '-lxml2'
Makefile:11963: recipe for target 'stage/opt/pbis/bin/domainjoin-gui' failed
make: *** [stage/opt/pbis/bin/domainjoin-gui] Error 1

**Comment by rbest-bt** [comment]
It's having issues finding xml2. The domainjoin-gui is not required and has less functionality then the CLI. We have stopped compiling it as it needs some updating which we are not focusing on at this time.
