### ISSUE TITLE
PBIS and Ubuntu 16.04 stops working

### ISSUE THREAD

**Issue by pfcapp** [BeyondTrust/pbis-open#22]
Have server with Ubuntu 16.04 and PBIS Open 8.5.3.  PBIS stops working after a while and gets the following errors in syslog.  Restarting doesn't fix the issue.  Seems like rejoining the domain is only fix for a bit then fails again.

Mar 31 07:37:59 SERVER lsass: [LwKrb5GetTgtImpl /builder/src-git/Platform/src/linux/lwadvapi/threaded/krbtgt.c:276] KRB5 Error code: -1765328360 (Message: Preauthentication failed)
Mar 31 07:37:59 SERVER lsass: [lsass] Error: Failed to refresh machine TGT for EXAMPLE.COM (error = 40022)
Mar 31 07:38:57 SERVER lsass: [lsass] Domain 'example.com' is now online
Mar 31 07:40:31 SERVER lsass: GSS API error calling gss_init_sec_context(): majorStatus = 0x000d0000 (Unspecified GSS failure.  Minor code may provide more information), minorStatus = 0x96c73a20 (Ticket expired)
Mar 31 07:40:32 SERVER lsass: [LwKrb5GetTgtImpl /builder/src-git/Platform/src/linux/lwadvapi/threaded/krbtgt.c:276] KRB5 Error code: -1765328360 (Message: Preauthentication failed)
Mar 31 07:40:32 SERVER lsass: [lsass] Domain 'example.com' is now offline
Mar 31 07:42:59 SERVER lsass: [LwKrb5GetTgtImpl /builder/src-git/Platform/src/linux/lwadvapi/threaded/krbtgt.c:276] KRB5 Error code: -1765328360 (Message: Preauthentication failed)
Mar 31 07:42:59 SERVER lsass: [lsass] Error: Failed to refresh machine TGT for EXAMPLE.COM (error = 40022)

**Comment by igeorgie** [comment]
I have the same experience. After rejoining it works for a day.

**Comment by rbest-bt** [comment]
Something is preventing the ticket from renewing. We have seen this with /var being full

Try increasing the lsass log level to see if there is more information around the time of renewal

**Comment by igeorgie** [comment]
I didn't read the [manual](https://www.google.nl/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjnh47evefTAhXQZ1AKHbQ9Cj0QFggnMAA&url=https%3A%2F%2Fwww.beyondtrust.com%2Fwp-content%2Fuploads%2Fdocumentation-pbis-samba-integration-guide.pdf%3F1456510450&usg=AFQjCNEdLgo0YbFXmkT4R99JDJJxKRHpjw&sig2=StiA254uIxO2XraU8g1ZTQ) well enough. Pbis in combination with samba you have to add in smb.conf:

`[global]
security = ADS
  ...
machine password timeout = 0
`
Now it's working.

**Comment by rbest-bt** [comment]
I'm glade you got it working. Without that samba would be changing the password and breaking the connection with AD. 

@pfcapp Is your issue also in regards to samba integration?

**Comment by pfcapp** [comment]
No, for a couple weeks AD login auth would just stop working with those errors and the only way to fix it would be to rejoin it to the domain.  Not sure what I may have changed but it seems to be working now (at least it has been fine for a couple weeks now).
