### ISSUE TITLE
Autoenrollment in pbis-open not available ?

### ISSUE THREAD

**Issue by flolivaud** [BeyondTrust/pbis-open#220]
**Version**: 9.0.1
**OS/Distro**: Ubuntu desktop 18.04 - unity desktop
**Issue/Impact**:
Hi all,
I try to configure auto enrollment, but in my version it seems i can't configure it. I tried to install older version but still the same.

In the wiki : https://github.com/BeyondTrust/pbis-open/wiki/Release-Notes PowerBroker Identity Services Open 8.3.0.3287 there is a point about it :
- Autoenrollment can now just enroll certificates

Does Autoenrollment still available in pbis-open ? If yes how can i use it ?

**Comment by rbest-bt** [comment]
Actually that information is incorrect. Certificate autoenrollment in only available in Enterprise as we need to have a GPO in place to configure which templates we pull down. Information on it can be found in the GPO reference guide.
