### ISSUE TITLE
Alternative to /etc/resolv.conf?

### ISSUE THREAD

**Issue by Koltsz** [BeyondTrust/pbis-open#221]
Is there any other way for pbis not to use **/etc/resolv.conf** for the namservers?
Openshift overwrites the file and effectively killing access for pbis.

Cheers in advance.

**Comment by rbest-bt** [comment]
How would your system be resolving DNS queries? As long as the system can resolve the domain and hosts it should be ok.

**Comment by Koltsz** [comment]
I was under the assumption that pbis uses the resolv.conf file; when thsi file gets recreated by Openshift it takes out the dns entries.

I was hoping there might be a command or something I can pass into pbis to use an alternative file or pass the dns directly into pbis config without the need to use the resolv.conf file

**Comment by rbest-bt** [comment]
Nothing to specify a different file. This would be done at the host level. Can you setup Openshift first then install/join ADB(new name for PBIS) after?

**Comment by Koltsz** [comment]
Yeah thats what I have done, Openshift will delete the resolv.conf file. It has got something to do with dnsmaq and Network Manager. I was hoping there was an alternative way to get ADB to connect to the right servers without the need of the resolv.conf file.
I appreciate all the help

**Comment by rbest-bt** [comment]
We are using the systems name resolution which would come down to what is defined in the nsswitch file by hosts. I would start looking into what you could do with that to have both domain resolution and openshift.
