### ISSUE TITLE
Wiki shortcut link for quick start guide is pointing to a 404

### ISSUE THREAD

**Issue by dhardyuk** [BeyondTrust/pbis-open#223]
Wiki shortcut link for quick start guide is out of date. Its currently pointing to a 404 error

**Comment by rbest-bt** [comment]
Try clearing your cache. The documentation has been rebranded and the names of the files have changed. Make sure your url matches the below version.

https://github.com/BeyondTrust/pbis-open/wiki/docs/adb-quick-start-guide.pdf

**Comment by dhardyuk** [comment]
Please see attached image.
![Capture](https://user-images.githubusercontent.com/12430945/60525227-e3837d80-9ce5-11e9-9d8f-86b59fd8c10c.PNG)

**Comment by rbest-bt** [comment]
Thanks for the clarification. I seemed to have forgotten that link in the update. I've correct it.
