### ISSUE TITLE
10.14 MacOS Mojave Home folders on NAS - broken but Sierra works fine

### ISSUE THREAD

**Issue by dbgbl** [BeyondTrust/pbis-open#225]
High, bit of an odd one here. 

I have relocated the Mac users home folders to an NFS share which has been working for ages. Have upgraded to Mojave (forced by app updates) and the Sierra clients, configured in the same way, work fine and create homes etc.

The Mojave clients when logging in get the attached message. Really cannot see why this could be. Any ideas anyone please.

thanks Duncan
![Screen Shot 2019-07-10 at 13 11 35](https://user-images.githubusercontent.com/52541901/60968962-3d073000-a316-11e9-9e77-859225b86ef1.png)
![Screen Shot 2019-07-10 at 13 12 23](https://user-images.githubusercontent.com/52541901/60968970-3f698a00-a316-11e9-8c75-6d5960be3cd6.png)

**Comment by cboutilier-bt** [comment]
We are currently investigating.

**Comment by dbgbl** [comment]
Thanks, this is using PBIS as the authentication source as per my previous post.

**Comment by rbest-bt** [comment]
Mojava - and now Catalina - is making changes that break this functionality. We are aware of these issues but they are low on the backlog. If we address this, it will be noted in the changelog. For know I'll be making as won't fix.
