### ISSUE TITLE
Cached Passwords expire after 4 hours. 

### ISSUE THREAD

**Issue by cadmins** [BeyondTrust/pbis-open#226]
I have users running Ubuntu Laptops and they are on and off the domain.  It appears that their cached credentials expire after 4 hours off the domain.  This could be a configuration issue.  The MachinePasswordLifespan is set at the default of 30 days.  Is there another setting that needs to be adjusted or is this a bigger issue?

**Comment by rbest-bt** [comment]
Have a look at increasing the config option CacheEntryExpiry. The default is 14400 which is 4 hours.

**Comment by mzs114** [comment]
@rbest-bt, thanks, but it seems we cannot increase this beyond 24hrs or set it to indefinite(set value to -1) like in Windows? 

seconds = 3600 * hours.

```
# /opt/pbis/bin/config CacheEntryExpiry 86400

# /opt/pbis/bin/config CacheEntryExpiry 86401
Error: Value not in accepted range
```
I am not sure about Windows, just taking a guess as I could not find anything conclusive, seems like Windows users can use their AD credentials even when disconnected from the Domain Controller for prolonged periods.

**Comment by rbest-bt** [comment]
Offline logins will still work with the expired cache. All this means is that it will try and refresh the cache after that period once it comes back online. 24 hours is the limit as you would not want to go much longer without checking with AD for changes. 

Much like windows, you would limit the time they can be offline with the account password expiry policy or the machine password lifespan(30 days).

**Comment by semidark** [comment]
For how long will the offline logins be possible? 
How can i check or set this behaviour on client side or in the AD?

**Comment by mzs114** [comment]
@semidark I was able to login past 24hrs. I think we did not change much, its been some months now, leave it with the defaults and it should work ok.

**Comment by semidark** [comment]
@mzs114 Thanks for the quick answer. But we have very technical interested End-users 👾. Linux Administrator and Software Developers . I will be asked this question and would like to be able to answer it if possible.

@rbest-bt Could you enlighten me how long the a login is Possible and how to configure this on the Client?
