### ISSUE TITLE
Need command to add 2nd AD group from same domain to allow login in Suse Linux server through PBIS

### ISSUE THREAD

**Issue by KoyelPaul** [BeyondTrust/pbis-open#227]
**Version**: sles_sap:12:sp1"
**OS/Distro**: SUSE Linux Enterprise Server for SAP Applications 12 SP1
**Issue/Impact**: Unable to add additional AD group to allow login in this Suse Linux box
We already have one AD group, all users belonging to that group can login to this Suse server
a new second AD group has been added and we want to add that group too in PBIS config to allow users belongs to the new AD group to get login access to this Linux servers. Please help me with the correct commands to add the 2nd group in PBIS. both the groups are added in same AD domain.
==========================================
*Note: replace content with your own*
When reporting an issue it's important that we have as much detail as you can provide. The following is a list of commands to check.
 1. systemctl status lwsmd.service
 2. /opt/pbis/bin/lwsm list
 3. /opt/pbis/domainjoin-cli query
 4. pbis status
 5. /opt/pbis/bin/enum-users
 6. attach logs
  - /opt/pbis/bin/lwsm set-log-target -p lsass -  file /tmp/lsass.log
  - /opt/pbis/bin/lwsm set-log-level -p lsass - debug
  - attach log

**Output/Error**:

**Steps to Reproduce**:
 1. install command
 2. Domainjoin command
 3. Command that returns issue
======================================
iptprdsmt101:~ # systemctl status lwsmd.service
lwsmd.service - BeyondTrust PBIS Service Manager
   Loaded: loaded (/usr/lib/systemd/system/lwsmd.service; enabled)
   Active: active (running) since Thu 2017-07-27 16:25:17 AEST; 2 years 0 months ago
 Main PID: 1568 (lwsmd)
   CGroup: /system.slice/lwsmd.service
           ├─1568 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─1591 lw-container lwreg
           ├─1632 lw-container eventlog
           ├─1668 lw-container netlogon
           ├─1725 lw-container lwio
           ├─1804 lw-container reapsysl
           └─1887 lw-container lsass

iptprdsmt101:~ # domainjoin-cli query
Name = iptprdsmt101
Domain = INTERNAL.QR.COM.AU
Distinguished Name = CN=IPTPRDSMT101,OU=SMT,OU=Applications,OU=PRD,OU=SLES,OU=Domain Corp Servers Linux,DC=internal,DC=qr,DC=com,DC=au
iptprdsmt101:~ #

**Comment by rbest-bt** [comment]
Are you talking about requiremembershipof?
##########
[testuser@cent7 ~]$ sudo /opt/pbis/bin/config --details require
Name: RequireMembershipOf
Description: Restrict logon access to computer to specific users or group members, or SIDs
Type: multistring
Current Values:
Current Value is determined by local policy.
[testuser@rbest-cent7 ~]$ sudo /opt/pbis/bin/config require groupa groupb
[testuser@rbest-cent7 ~]$ sudo /opt/pbis/bin/config --details require
Name: RequireMembershipOf
Description: Restrict logon access to computer to specific users or group members, or SIDs
Type: multistring
Current Values:
"groupa"
"groupb"
Current Value is determined by local policy.

**Comment by KoyelPaul** [comment]
Yes I have tried to run "RequireMembershipof " commands, but received below error - 

iptprdsmt101:~ # /opt/pbis/bin/config RequireMembershipof INTERNAL\\FUJ_TFSNowDiscovery
iptprdsmt101:~ # /opt/pbis/bin/config AssumeDefaultDomain false
Problem executing '/opt/pbis/bin/ad-cache --delete-all >/dev/null 2>/dev/null'
Error: Error returned by external program
iptprdsmt101:~ # /opt/pbis/bin/config UserDomainPrefix INTERNAL
Problem executing '/opt/pbis/bin/ad-cache --delete-all >/dev/null 2>/dev/null'
Error: Error returned by external program
iptprdsmt101:~ # /opt/pbis/bin/config RequireMembershipof INTERNAL\\FUJ_LinuxEng
iptprdsmt101:~ #

Please check current status.
iptprdsmt101:~ # /opt/pbis/bin/config --details require
Name: RequireMembershipOf
Description: Restrict logon access to computer to specific users or group members, or SIDs
Type: multistring
Current Values:
"INTERNAL\\FUJ_LinuxEng"
Current Value is determined by local policy.
iptprdsmt101:~ # 

So here my groupa is "FUJ_LinuxEng" can I add the additional (new) group using below command ?

sudo /opt/pbis/bin/config require groupa groupb

**Comment by KoyelPaul** [comment]
sudo /opt/pbis/bin/config require groupa groupb -->this command worked successfully. now users from the groupb also can successfully login. can we add groupc also in similar way with same command ?

**Comment by rbest-bt** [comment]
Yes, but you will need to repeat the previous ones. There is no "add" option:

> sudo /opt/pbis/bin/config require groupa groupb groupc

In regards to the error:
Problem executing '/opt/pbis/bin/ad-cache --delete-all >/dev/null 2>/dev/null'
Error: Error returned by external program

Most of the time it's just failing to clear the ad-cache. This would be caused by an offline domain. This does not prevent it from getting set, you'll just need to clear it manually with /opt/pbis/bin/ad-cache
