### ISSUE TITLE
Set users primary group to a local linux group

### ISSUE THREAD

**Issue by airinaga** [BeyondTrust/pbis-open#23]
This isn't really an issue, just looking for advice as I'm sure someone has ran into this before.

Using PBIS-open, authenticating AD users against Linux machines just fine.

Need to set the AD user's primary group to a local linux group rather than an AD one. 

Thanks!
Adam

**Comment by rbest-bt** [comment]
We have a feature in the [Enterprise version](https://www.beyondtrust.com/products/powerbroker-identity-services-ad-bridge/) that can do this, called account-override .

See wiki for link to get a free trial/demo/quote.

**Comment by mattmc-hc** [comment]
Similar question:  Need to change a users (perhaps all users) primary group to an AD group other than domain_users.  How?

**Comment by rbest-bt** [comment]
In Active Directory there is a concept of **Primary Group** of POSIX applications and Mac clients. This should be what your looking for. There is a [button](https://serverfault.com/questions/518608/purpose-of-primary-group#518932url) under users **member of** tab to change it.

**Comment by mattmc-hc** [comment]
Thank you for the quick reply.  Sorry, my question lacked detail.  I would like to change the primary group on a per-server basis.  For example, when the user logs into a database server (running Red Hat), have a primary group of DOMAINA\db_admins, but when they login to an NFS server, have a primary group of DOMAINB\storage_admins.

**Comment by rbest-bt** [comment]
Again I would recommend the [Enterprise version](https://www.beyondtrust.com/products/powerbroker-identity-services-ad-bridge/) as you can do this with group-override feature.
