### ISSUE TITLE
One-Way-Trust with Kerberos: Resolution of Domain Local Groups?

### ISSUE THREAD

**Issue by andreasbergen** [BeyondTrust/pbis-open#230]
**Version**: 9.0
**OS/Distro**: SLES 12
**Issue/Impact**: Don't get Group-Info from Trusting Domain in a OneWay-Kerberos-only scenario

Hello,

the following is written in the installation documentation (see for example here: https://www.beyondtrust.com/docs/archive/ad-bridge/documents/8-8-0/pbis-installation-8-8-0.pdf): "In a one-way trust in which Forest A trusts Forest B, a computer in Forest A cannot get group information from Forest B, because Forest B does not trust Forest A. The computer in Forest A can obtain group information if the user logs on with a password for a domain user, but not if the user logs on with Kerberos single sign-on credentials. Only the primary group information, not the secondary group information, is obtained."

Due to the nature of a one-way trust this is totally logical and expected. Anyway I'd expect domain local groups from the trusting domain (A in the example above) to be resolvable.
So if user U is in Global Group B\GG which is member of A\DLG then I'd expect to see A\DLG in U's group list on the Linux-host. But unfortunately the list only shows the primary group from B, but no other group, even though A\DLG should be part of the PAC of the Kerberos-Token.

Can this be fixed?

Thanks a lot in advance
  Andreas Bergen

**Comment by rbest-bt** [comment]
This has been investigated extensively many times and it can not without specific use case workarounds. This is why it's documented that the first auth attempt needs a password.

**Comment by andreasbergen** [comment]
Hello rbest-bt,

I'm sorry to follow up on this once more. What do you mean by "use case workarounds"? Are there any workarounds to make this possible?

We have a very important use-case which would really benefit from this scenario being possible: User-Accounts in an account domain managing untrusted servers in a resource-domain. Having to enter the password at first login just is no option as this would compromise the admin account on a compromised machine in the resource domain. 

In order to be able to use Kerberos to its full benefit I need to be able to logon to the target machine without having to enter the password.
And I don't want the target machine to be able to read the account domain as it would be possible in a two-way-trust-scenario.
Wouldn't it be possible to just make pbis ignore group memberships from the account-domain which can't be resolved and just list the group-memberships from the resource-domain and don't error out in that case?
For me this sounds like not too big of an effort.

Best regards
  Andreas

**Comment by rbest-bt** [comment]
Sorry, what I meant by use case workaround does require a code change to make it work. The proposed solutions would work in specific scenarios that are not great for everyone. The effort involved would distract from needed improvements we are working on.
