### ISSUE TITLE
Can PBIS Open join AD without sending join account password in clear text?

### ISSUE THREAD

**Issue by sgroening** [BeyondTrust/pbis-open#231]
Security has informed us that the username and password of our join account is being sent in clear text from PBIS Open.

Is there a way to get around this or does this indeed require PBIS Enterprise?

**Comment by rbest-bt** [comment]
How was the password passed into the domainjoin command?

**Comment by sgroening** [comment]
It is passed interactively through an expect script. Apparently this makes the password visible during the join process, but the question seems to be how domainjoin-cli itself passes the credentials to the DC?

**Comment by rbest-bt** [comment]
Credentials are secure with the domainjoin-cli. Is the script run remotely? How do you secure the password with the script?
