### ISSUE TITLE
[Enhancement]  Add support for Armv7l architecture

### ISSUE THREAD

**Issue by hydrian** [BeyondTrust/pbis-open#235]
Please add support for the ArmV7l architecture. This would give support to current Raspberry Pis and many other small board computers.

**Comment by rbest-bt** [comment]
Thanks for the request. We have had a few people ask about this but the demand is not high enough to be on our development roadmap.

**Comment by phoenyx762** [comment]
+1

**Comment by rbest-bt** [comment]
pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
