### ISSUE TITLE
Samba always asks for username/password

### ISSUE THREAD

**Issue by pfcapp** [BeyondTrust/pbis-open#236]
Running PBIS Open version 8.7.0.478 on RHEL 6.10 box.  Have this working on many other servers but can't seem to get this one to work.  smb.conf is default version from OS with only the following lines changed:
security = ADS
workgroup = EXAMPLE
machine password timeout = 0

From windows 10 box I run "\\servername" which would usually open up the available shares from that server.  All I get is prompt for username/password.  Anything I put in there fails.

Again, compared config to a working server with no blatant differences.  

Any ideas?

**Comment by pfcapp** [comment]
FInally figured this out.  Newer Windows clients are expecting SMBv2 and RHEL 6 runs SMBv1 by default.  Adding the following line to the "global" section fixed the problem:
max protocol = SMB2

**Comment by rbest-bt** [comment]
Thanks for posting the resolution.
