### ISSUE TITLE
Joined proble executing ad-cache --delete-all /dev/null when trying to config 

### ISSUE THREAD

**Issue by FrancoisBourget** [BeyondTrust/pbis-open#237]
Hello
I have version 9.0.2
successfully added to domain
when trying to change the config, I always have this error
Problem executing '/opt/pbis/bin/ad-cache --delete-all >/dev/null 2>/dev/null'
erro: error returned by extternal program

any ideas ?

Thanks in advance

ps: i am a linux novice

Francois

**Comment by strigona-worksight** [comment]
What errors do you get when you run (this is a safe command to run):

/opt/pbis/bin/ad-cache --delete-all

**Comment by FrancoisBourget** [comment]
I get an error
Failed to empty cache. Error code 40121 (LW_ERROR_DOMAIN_IS_OFFLINE).
The domain is offline

**Comment by strigona-worksight** [comment]
Then you need to investigate connection issues to your AD/DC.
