### ISSUE TITLE
remotehomedir - Mount Options

### ISSUE THREAD

**Issue by pavalenta** [BeyondTrust/pbis-open#238]
Compiled daemon version: 9.0.2.534
Packaged product version: 9.0.534.497
CentOS Linux release 7.6.1810

Using the remotehomedir option with AD user home drives. The homedirtemplate makes the remotehomedir the users root home directory. So far Google Chrome is the only app that won't open due to various errors, remounting (or doing so manually) the home share with the following options Chrome will open (with other errors but it at least opens) username=<username>,mfsymlinks,uid=$(id -u),gid=$(id -g)

The real question, is there a way with PBIS-Open to specify what options are used when mounting a users remotehomedir?

**Comment by rbest-bt** [comment]
Currently, there is not a method to prove your own mount options with remotehomedir.

**Comment by pavalenta** [comment]
Ok figured but wasn't 100 percent sure. Is there any plans to investigate feasibility of providing CIFS mount options?

**Comment by rbest-bt** [comment]
Not at this time. Enterprise has some options for mounting via Group Policies.
