### ISSUE TITLE
Limit users listed to only members of the "RequireMembershipOf" group

### ISSUE THREAD

**Issue by chobbs-** [BeyondTrust/pbis-open#24]
Hello,

This works great for my Ubuntu systems. I have a group of the users that I want to be able to use the box that I set in RequireMembershipOf setting and that works fine, they can login. The shell is set via LoginShellTemplate and that looks good too. 

But, when I do 'getent passwd', I see ALL users in the domain, even disabled ones, and they ALL have the shell set from the LoginShellTemplate.

`$ getent passwd | wc -l
23375`

I only have about 20 users in the group, but over 23,000 accounts are active on the box. 

How do I fix this? Is this a bug? Is this a feature request? How can I make sure that random disabled account from 2004 doesn't have /bin/bash on my Linux hosts?

**Comment by chobbs-** [comment]
Sure, NssEnumerationEnabled can be set to false and then I don't get any domain users in getent, but still I can do id on any account in AD and it will show that it still has /bin/bash. Limiting the shell is the goal, not just hiding the accounts from getent.

**Comment by ferricoxide** [comment]
The account visibility (effectively) means nothing: when you've got the `RequireMembershipOf` defined, PBIS will refuse to allow people not in the "required" group(s) to login.

**Comment by chobbs-** [comment]
That's true, and I can't SSH as those users, but I can do this: 

`sudo su - RandomOfficePrinter
Access Denied
Access Denied
RandomOfficePrinter@localhost:~$ ls -lah
total 20K
drwxr-xr-x  2 RandomOfficePrinter domain^users 4.0K Apr  6 15:08 .
drwxr-xr-x 15 root     root         4.0K Apr  6 15:08 ..
-rw-r--r--  1 RandomOfficePrinter domain^users  220 Apr  6 15:08 .bash_logout
-rw-r--r--  1 RandomOfficePrinter domain^users 3.7K Apr  6 15:08 .bashrc
-rw-r--r--  1 RandomOfficePrinter domain^users   52 Apr  6 15:08 .k5login
-rw-r--r--  1 RandomOfficePrinter domain^users  655 Apr  6 15:08 .profile`

It says "Access Denied" twice but I still have a shell where I can check things out. I can also drop in an SSH key and then SSH as that user no problem. I mean sure I can tweak other pam files or something and maybe disable SSH key access too, but is this really working as intended?

**Comment by rbest-bt** [comment]
This is an issue with open's unprovisioned mode. The accounts are not managed and ID's are generated for everything. The better method is to use Enterprise in Default Cell mode where you can provision only the account you need to map to *nix machines.
