### ISSUE TITLE
LSASS process using 200% CPU

### ISSUE THREAD

**Issue by pfunkylol** [BeyondTrust/pbis-open#240]
**Version**: 9.0.2.534
**OS/Distro**: Ubuntu 18.04
*Issue/Impact**: High CPU Usage of LSASS 

 1. systemctl status lwsmd.service

● lwsmd.service - BeyondTrust AD Bridge Service Manager
   Loaded: loaded (/lib/systemd/system/lwsmd.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-09-19 14:16:28 EEST; 1h 38min ago
  Process: 1290 ExecStart=/opt/pbis/sbin/lwsmd --start-as-daemon (code=exited, status=0/SUCCESS)
 Main PID: 1599 (lwsmd)
    Tasks: 194 (limit: 9471)
   CGroup: /system.slice/lwsmd.service
           ├─1599 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─1678 lw-container lwreg
           ├─1759 lw-container eventlog
           ├─1813 lw-container netlogon
           ├─1849 lw-container lwio
           └─2003 lw-container reapsysl

 2. /opt/pbis/bin/lwsm list
lwreg          running (container: 1678)
dcerpc         stopped
eventlog       running (container: 1759)
lsass          stopped
lwio           running (container: 1849)
netlogon       running (container: 1813)
rdr            running (io: 1849)
reapsysl       running (container: 2003)
usermonitor    stopped
 3. /opt/pbis/domainjoin-cli query

Name = rodcbslxdms
Domain = DG.CARREFOUR.COM
Distinguished Name = CN=RODCBSLXDMS,OU=LINUX,OU=ROMANIA,OU=SERVERS,DC=dg,DC=carrefour,DC=com

 4. pbis status

LSA Server Status:

Compiled daemon version: 9.0.2.534
Packaged product version: 9.0.534.497
Uptime:        0 days 0 hours 0 minutes 37 seconds

[Authentication provider: lsa-activedirectory-provider]

	Status:        Unknown
	Mode:          Unknown

 5. /opt/pbis/bin/enum-users
TotalNumUsersFound: 0

 6. attach logs ( attached )

[lsass.log](https://github.com/BeyondTrust/pbis-open/files/3631324/lsass.log)

  - /opt/pbis/bin/lwsm set-log-target -p lsass -  file /tmp/lsass.log
  - /opt/pbis/bin/lwsm set-log-level -p lsass - debug
  - attach log

**Output/Error**:

**Comment by rbest-bt** [comment]
Logs are just showing enumeration. The above output is empty since lsass has been stopped. Try disabling NssEnumerationEnabled.
> /opt/pbis/bin/config NssEnumerationEnabled false

**Comment by pfunkylol** [comment]
Apparently, this resolved my issue.
I will keep it under monitoring, but for now it seems to ok.
