### ISSUE TITLE
How to avoid local and AD users conflicts?

### ISSUE THREAD

**Issue by andrescontilde** [BeyondTrust/pbis-open#241]
Hello. 

I'm currently having issues with one of my AIX servers which has about 50 local users with the same name than AD users. 

When I join this server to the domain the users can't log in with either their local or AD user.  

I tried turning AssumeDefaultDomain to false hoping that I could distinguish between the two users forcing to use the DOMAIN\username form for AD users but it didn't work. 

I also tried setting the same UID for both local and AD users but that it didn't work well, the results were somewhat unexpected because even using the AD credentials it redirected me to the local user's home directory. 

I tried registering users in /etc/pbis/user-ignore file, but it didn't make any difference. 

Deleting local users is not an option.

So, at this point, my question is: What is the best way to overcome this behavior? Is there any config option that I could set to solve this?

**Comment by cboutilier-bt** [comment]
There are a couple of things that you can try. 

1. Try setting AssumeDefaultDomain to true. 
2. Try setting the UID's of the LOCAL users to be **different** than the AD users. 

From the way the above is stated, it sounds like you are mapping local to AD accounts given that you are setting AssumeDefaultDomain to false, and setting the UIDS to the same for each of the accounts. This would in turn, set them to map to each other.

**Comment by andrescontilde** [comment]
Thanks for your answer. 

I've already tried that. That's my default setup. Given that my common configuration was not working I gave a try to the scenarios stated in my first post, with the described results.

**Comment by rbest-bt** [comment]
user-ignore is the method to achieve this. user-ignore meant to list the local accounts that you would like lsass to ignore. If this is not working then you may need to debug lsass to see what is happening at authentication. Make sure the user-ignore file is updated with an account on a new line and match exactly with the local account.

**Comment by andrescontilde** [comment]
Thanks for your answer @rbest-bt 

After editing the user-ignore file is it necessary to restart lsass services or something else? I couldn't find documentation regarding user-ignore file, is there any reference about how to use the user-ignore file?

**Comment by andrescontilde** [comment]
I'm doing some testing with the user-ignore file. Indeed right now it is possible to log in with the local user credentials and I have no problem resetting this user's password, I run an id command and it shows the local user's info. 

What's somewhat odd is that it let me log in using the domain credentials too, and it access as the local user, so even when I use domain credentials in this scenario and run the id command it shows the local user info too. This behavior is fine, these local users are logged in the server but I don't know if it is working as designed or maybe it's a bug. 

Is it OK that users included in the user-ignore file could log in with their domain credentials to their local accounts?

**Comment by rbest-bt** [comment]
Options to correct this are limited in Open due to the lack of its configurations.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
