### ISSUE TITLE
Can't install pbis-open-9.0.2-534.x86_64 on CentOS 8

### ISSUE THREAD

**Issue by francisleemondia** [BeyondTrust/pbis-open#242]
**Version**: pbis-open-9.0.2-534.x86_64
**OS/Distro**: CentOS Linux release 8.0.1905
**Issue/Impact**:
Mentioned version fails to install on CentOS 8. I've encountered the error below on Red Hat 8 while using the older package, which prompted me to use the package version mentioned above. 

**Output/Error**:

An appropriate SELinux policy [/opt/pbis/share/rhel/unknown/pbis.pp] was not included in this package. You may provide a policy at /opt/pbis/share/pbis.pp

SELinux found to be present, enabled, and enforcing. You may either provide a policy at /opt/pbis/share/pbis.pp --OR-- SELinux must be disabled or set to permissive mode by editing the file /etc/selinux/config and rebooting. For instructions on how to edit the file to disable SELinux, see the SELinux man page.

BeyondTrust AD Bridge will not install without an appropriate policy for SELinux.

warning: %post(pbis-open-9.0.2-534.x86_64) scriptlet failed, exit status 1

Installing Packages was successful

**Steps to Reproduce**:
 1. install package after extracting the file and you will get the error output above

**Comment by francisleemondia** [comment]
UPDATE: Latest version (9.1.0) also spits out the same error.

**Comment by frayber** [comment]
Same problem, I have selinux disabled but got another error when joining domain.
I think this package is not yet ready for centos 8

**Comment by rbest-bt** [comment]
Centos 8 check has not been added to the rpm yet. This is used to map to the selinux policy file. For now run the following and reinstall.
> cp /opt/pbis/share/rhel/8.0/pbis.pp /opt/pbis/share/

**Comment by francisleemondia** [comment]
> Same problem, I have selinux disabled but got another error when joining domain.
> I think this package is not yet ready for centos 8

That's odd.. I re-installed it after setting SELINUX to permissive and it joined the machine to AD fine.

**Comment by frayber** [comment]
With version 9.1.0 I can join domain.

**Comment by rbest-bt** [comment]
Please upgrade to Active Directory Bridge Enterprise which contains fixes for centos 8. If the issue still exists then please submit a ticket to our service team and we’ll have a look for you.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
