### ISSUE TITLE
[Enhancement] add option for SPNs to domainjoin-cli

### ISSUE THREAD

**Issue by grueni** [BeyondTrust/pbis-open#243]
domainjoin-cli has no option to define SPNs.
With adtools SPNs can be added when a new compuet account is created.

I need computer accounts with SPNs for HTTP, NFS and CIFS.
Actually I do:
1) /opt/pbis/bin/domainjoin-cli join --ou "Member Server Solaris" Domain  Account
2) delete account in Windows MMC
3) /opt/pbis/bin/adtool -a new-computer --dn "OU=.." --name HOSTNAME --password password --keytab-file /etc/krb5/krb5.keytab --spn="HOST, NFS, HTTP, cifs"

It would be great if domainjoin-cli would have the same feature for SPNs as adtool.

**Comment by rbest-bt** [comment]
There is a config option for this called ServicePrincipalName that was added in 8.5.5. This should be what you're looking for:
https://www.beyondtrust.com/docs/ad-bridge/how-to/configuration-tool/lsass-active-directory.htm

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
