### ISSUE TITLE
Replace __uint32_t with unsigned long

### ISSUE THREAD

**Issue by grueni** [BeyondTrust/pbis-open#244]
I compiled pbis-open 9.1.0 from git with OpenIndiana  and gcc6 and gcc8
I had to use the attached patch to replace the '__uint32'.

__unit32 is used just once in the whole source.
It would be better to use unsigned long.

`diff --git a/lwbase/src/threadpool-epoll.c b/lwbase/src/threadpool-epoll.c
index 5a4ecc91d..007a3ff83 100644
^[[200~diff --git a/lwbase/src/threadpool-epoll.c b/lwbase/src/threadpool-epoll.c
index 5a4ecc91d..007a3ff83 100644
--- a/lwbase/src/threadpool-epoll.c
+++ b/lwbase/src/threadpool-epoll.c
@@ -159,7 +159,7 @@ UpdateEventWait(
     )
 {
     NTSTATUS status = STATUS_SUCCESS;
-    __uint32_t events = 0;
+    unsigned long events = 0;
     struct epoll_event event;

     if ((pTask->EventWait & FD_EVENTS) != (pTask->EventLastWait & FD_EVENTS) && pTask->Fd >= 0)`

**Comment by dmorash-BT** [comment]
A long may not be 32 bits on all platforms so simply replacing __uint32_t with an unsigned long isn't portable.  That code should be updated to use the standard fix sized types, i.e. stdint.h where it is available.

**Comment by grueni** [comment]
If I add 
#ifndef _GCC_STDINT_H
typedef unsigned int    __uint32_t;
#endif
the code compiles too.

May I ask how do you compile the code for Solaris?
With a Solaris system? 
And which compiler options are used?

**Comment by dmorash-BT** [comment]
We build on a couple of Solaris machines but we don't explicitly specify any CFLAGS, we use the ones that configure determines.  You can see these by running ./configure --help.  These defaults come from makekit/mk/module/compiler.sh

**Comment by grueni** [comment]
I compile pbis with the batch attached below to produce 32- and 64bit-binaries.
Apache 2.4 ist 64bit and so I need thet 64bit version of mod_auth_kerb.
Maybe my definitions are wrong.
But if I don't set the settings for Apache or apr ACCEPT_INFERIOR_RM_PROGRAM the compilation fails.

But when I search like this
# find pbis-open-9.1.0/ -iname '*.c'|xargs grep -irn 'uint32_t ' |wc -l
360
# find pbis-open-9.1.0/ -iname '*.c'|xargs grep -irn '__uint32_t ' |wc -l
1
I found only one occurence of '__uint32_t'.

In my private patch I replaced now '__uint32_t with 'uint32_t'.

export PATH=/usr/bin:/usr/sbin:/usr/gnu/bin:/opt/sbin:/opt/bin
export CC="gcc-8 -static-libgcc"
export CXX=g++-8
export LD=/usr/bin/ld
export CFLAGS="-I/usr/apr/include -I/usr/apr-util/include"
export CXXFLAGS=$CFLAGS
export ACCEPT_INFERIOR_RM_PROGRAM=yes
export BUILD_X86_32_LDFLAGS="-L/usr/apr/lib -L/usr/apr-util/lib"
export BUILD_X86_64_LDFLAGS="-L/usr/apr/lib/amd64 -L/usr/apr-util/lib/amd64"
export HOST_X86_32_LDFLAGS="-L/usr/apr/lib -L/usr/apr-util/lib"
export HOST_X86_64_LDFLAGS="-L/usr/apr/lib/amd64 -L/usr/apr-util/lib/amd64"
export DESTDIR=/export/builds/pbis-open/debug/p

[ -f Makefile ] && gmake scrub
[ -d p ] && rm -rf p
mkdir p
../configure --debug=yes --apache2.4-prefix=/usr/apache2/2.4 > c32.log 2>&1
gmake default -j12
gmake install -j12
gmake package -j12
#exit
[ -f Makefile ] && gmake scrub
../configure --debug=yes --build-isas="x86_64" --apache2.4-prefix=/usr/apache2/2.4 > c64.log 2>&1
gmake default -j12
gmake install -j12
gmake package -j12

**Comment by rbest-bt** [comment]
pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
