### ISSUE TITLE
Differences between git repository and source code tarball

### ISSUE THREAD

**Issue by grueni** [BeyondTrust/pbis-open#245]
**Version**: 9.1.0
**OS/Distro**: Any
**Issue/Impact**: Unable to compile from source code tarball

I compiled pbis-open with OpenIndiana and gc6 and gcc8.
Compilation was successfull with the git repository but not with the tar ball.

thread-epoll.c was patched by me.
 ../pbis-open => git (git clone .. && git checkout 9.1.0)
pbis-open => latest tarball from releases (9.1.0)
The output from /usr/gnu/bin/diff --recursive --brief pbis-open/ ../pbis-open/:

Only in ../pbis-open/curl: Makefile.in
Only in ../pbis-open/curl: aclocal.m4
Only in ../pbis-open/curl: autom4te.cache
Files pbis-open/curl/compile and ../pbis-open/curl/compile differ
Only in ../pbis-open/curl: config.guess
Only in ../pbis-open/curl: config.sub
Only in ../pbis-open/curl: configure
Only in ../pbis-open/curl: depcomp
Only in ../pbis-open/curl/docs: Makefile.in
Only in ../pbis-open/curl/docs/examples: Makefile.in
Only in ../pbis-open/curl/docs/libcurl: Makefile.in
Only in ../pbis-open/curl/include: Makefile.in
Only in ../pbis-open/curl/include/curl: Makefile.in
Only in ../pbis-open/curl: install-sh
Only in ../pbis-open/curl/lib: Makefile.in
Only in ../pbis-open/curl/lib: curl_config.h.in
Only in ../pbis-open/curl: ltmain.sh
Only in ../pbis-open/curl/m4: libtool.m4
Only in ../pbis-open/curl/m4: ltoptions.m4
Only in ../pbis-open/curl/m4: ltsugar.m4
Only in ../pbis-open/curl/m4: ltversion.m4
Only in ../pbis-open/curl/m4: lt~obsolete.m4
Only in ../pbis-open/curl/packages/AIX: Makefile.in
Only in ../pbis-open/curl/packages/AIX/RPM: Makefile.in
Only in ../pbis-open/curl/packages/EPM: Makefile.in
Only in ../pbis-open/curl/packages/Linux: Makefile.in
Only in ../pbis-open/curl/packages/Linux/RPM: Makefile.in
Only in ../pbis-open/curl/packages: Makefile.in
Only in ../pbis-open/curl/packages/Solaris: Makefile.in
Only in ../pbis-open/curl/packages/Win32: Makefile.in
Only in ../pbis-open/curl/packages/Win32/cygwin: Makefile.in
Only in ../pbis-open/curl/packages/vms: Makefile.in
Only in ../pbis-open/curl/src: Makefile.in
Only in ../pbis-open/curl/tests: Makefile.in
Only in ../pbis-open/curl/tests/data: Makefile.in
Only in ../pbis-open/curl/tests/libtest: Makefile.in
Only in ../pbis-open/curl/tests/server: Makefile.in
Only in ../pbis-open/cyrus-sasl: Makefile.in
Only in ../pbis-open/cyrus-sasl: aclocal.m4
Only in ../pbis-open/cyrus-sasl: autom4te.cache
Only in ../pbis-open/cyrus-sasl/config: compile
Only in ../pbis-open/cyrus-sasl/config: config.guess
Only in ../pbis-open/cyrus-sasl/config: config.sub
Files pbis-open/cyrus-sasl/config/depcomp and ../pbis-open/cyrus-sasl/config/depcomp differ
Only in ../pbis-open/cyrus-sasl/config: install-sh
Only in ../pbis-open/cyrus-sasl/config: libtool.m4
Only in ../pbis-open/cyrus-sasl/config: ltmain.sh
Only in ../pbis-open/cyrus-sasl/config: ltoptions.m4
Only in ../pbis-open/cyrus-sasl/config: ltsugar.m4
Only in ../pbis-open/cyrus-sasl/config: ltversion.m4
Only in ../pbis-open/cyrus-sasl/config: lt~obsolete.m4
Files pbis-open/cyrus-sasl/config/missing and ../pbis-open/cyrus-sasl/config/missing differ
Only in ../pbis-open/cyrus-sasl: config.h.in
Only in ../pbis-open/cyrus-sasl: configure
Only in ../pbis-open/cyrus-sasl/doc: Makefile.in
Only in ../pbis-open/cyrus-sasl/include: Makefile.in
Only in ../pbis-open/cyrus-sasl/java/CyrusSasl: Makefile.in
Only in ../pbis-open/cyrus-sasl/java: Makefile.in
Only in ../pbis-open/cyrus-sasl/java/Test: Makefile.in
Only in ../pbis-open/cyrus-sasl/java/javax: Makefile.in
Only in ../pbis-open/cyrus-sasl/java/javax/security: Makefile.in
Only in ../pbis-open/cyrus-sasl/java/javax/security/auth: Makefile.in
Only in ../pbis-open/cyrus-sasl/java/javax/security/auth/callback: Makefile.in
Only in ../pbis-open/cyrus-sasl/lib: Makefile.in
Only in ../pbis-open/cyrus-sasl/man: Makefile.in
Only in ../pbis-open/cyrus-sasl/plugins: Makefile.in
Only in ../pbis-open/cyrus-sasl/pwcheck: Makefile.in
Only in ../pbis-open/cyrus-sasl/sample: Makefile.in
Only in ../pbis-open/cyrus-sasl/saslauthd: Makefile.in
Only in ../pbis-open/cyrus-sasl/saslauthd: aclocal.m4
Only in ../pbis-open/cyrus-sasl/saslauthd: autom4te.cache
Only in ../pbis-open/cyrus-sasl/saslauthd/config: compile
Only in ../pbis-open/cyrus-sasl/saslauthd/config: config.guess
Only in ../pbis-open/cyrus-sasl/saslauthd/config: config.sub
Files pbis-open/cyrus-sasl/saslauthd/config/depcomp and ../pbis-open/cyrus-sasl/saslauthd/config/depcomp differ
Only in ../pbis-open/cyrus-sasl/saslauthd/config: install-sh
Only in ../pbis-open/cyrus-sasl/saslauthd/config: ltmain.sh
Files pbis-open/cyrus-sasl/saslauthd/config/missing and ../pbis-open/cyrus-sasl/saslauthd/config/missing differ
Only in ../pbis-open/cyrus-sasl/saslauthd: configure
Only in ../pbis-open/cyrus-sasl/saslauthd: saslauthd.h.in
Only in ../pbis-open/cyrus-sasl/sasldb: Makefile.in
Only in ../pbis-open/cyrus-sasl/utils: Makefile.in
Only in ../pbis-open/: debug
Only in ../pbis-open/krb5/src: autom4te.cache
Only in ../pbis-open/krb5/src: configure
Only in ../pbis-open/krb5/src/include: autoconf.h.in
Only in ../pbis-open/libxml2: INSTALL
Only in ../pbis-open/libxml2: Makefile.in
Only in ../pbis-open/libxml2: aclocal.m4
Only in ../pbis-open/libxml2: autom4te.cache
Only in ../pbis-open/libxml2: compile
Only in ../pbis-open/libxml2: config.guess
Only in ../pbis-open/libxml2: config.h.in
Only in ../pbis-open/libxml2: config.sub
Only in ../pbis-open/libxml2: configure
Files pbis-open/libxml2/depcomp and ../pbis-open/libxml2/depcomp differ
Only in ../pbis-open/libxml2/doc: Makefile.in
Only in ../pbis-open/libxml2/doc/devhelp: Makefile.in
Only in ../pbis-open/libxml2/doc/examples: Makefile.in
Only in ../pbis-open/libxml2/example: Makefile.in
Only in ../pbis-open/libxml2/include: Makefile.in
Only in ../pbis-open/libxml2/include/libxml: Makefile.in
Only in ../pbis-open/libxml2: install-sh
Only in ../pbis-open/libxml2: ltmain.sh
Only in ../pbis-open/libxml2: missing
Only in ../pbis-open/libxml2/python: Makefile.in
Only in ../pbis-open/libxml2/python/tests: Makefile.in
Only in ../pbis-open/libxml2/xstc: Makefile.in
Files pbis-open/lwbase/src/threadpool-epoll.c and ../pbis-open/lwbase/src/threadpool-epoll.c differ
Only in ../pbis-open/openldap: aclocal.m4
Only in ../pbis-open/openldap/build: config.guess
Only in ../pbis-open/openldap/build: config.sub
Only in ../pbis-open/openldap/build: install-sh
Only in ../pbis-open/openldap/build: ltmain.sh
Only in pbis-open/openldap/build: missing
Only in ../pbis-open/openldap: configure
Only in ../pbis-open/openldap/include: portable.hin
Only in ../pbis-open/popt: autom4te.cache

**Comment by rbest-bt** [comment]
What is the build error your experiencing? My diff is not showing any difference between the two methods. The tarballs are generated within Github and should be exact copies as we have no control over them.

**Comment by grueni** [comment]
You are right.
The folders are identical. 
I observed the differences yesterday.
Today we had unexplainable errors with the network in an other zone of the host and rebooted the host.
After the reboot the Makefile of my IPS package runs without a problem and built a 32- and a 64-bit version of pbis-open. 
Obviously a corrupted system.
Sorry for the noise.

**Comment by rbest-bt** [comment]
Thank you for resolution.
