### ISSUE TITLE
How to build a release version?

### ISSUE THREAD

**Issue by krizex** [BeyondTrust/pbis-open#246]
**Version**: 9.1.0
**OS/Distro**: Ubuntu desktop 18.04 
**gcc version**: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
**Issue/Impact**:
I want to build a release version pbis-open, but I got some errors when compiling.

**Output/Error**:
```
......
           [compile] dcerpc/ncklib/cnassoc.c (host/x86_64)
           [compile] dcerpc/ncklib/cnbind.c (host/x86_64)
           [compile] dcerpc/ncklib/cncall.c (host/x86_64)
../dcerpc/ncklib/cncall.c: In function ‘rpc__cn_call_start’:
../dcerpc/ncklib/cncall.c:368:46: error: array subscript is above array bounds [-Werror=array-bounds]
             call_rep->buffered_output.iov.elt[i].buff_addr = NULL;
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
../dcerpc/ncklib/cncall.c:369:46: error: array subscript is above array bounds [-Werror=array-bounds]
             call_rep->buffered_output.iov.elt[i].buff_dealloc = NULL;
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
cc1: all warnings being treated as errors
           [compile] FAILED: 'gcc' '-m64' '-O2' '-g' '-Wall' '-Wall' '-Werror' '-fno-strict-aliasing' '-I../dcerpc/ncklib/.' '-Iobject/dcerpc/ncklib/.' '-I../dcerpc/ncklib/../include' '-Iobject/dcerpc/ncklib/../include' '-I../dcerpc/ncklib/include/linux-gnu' '-Iobject/dcerpc/ncklib/include/linux-gnu' '-DNDEBUG=1' '-D_GNU_SOURCE' '-D_BSD' '-D_XOPEN_SOURCE=500' '-D__EXTENSIONS__' '-D_POSIX_PTHREAD_SEMANTICS' '-D_ALL_SOURCE=1' '-D_REENTRANT' '-Istage/opt/pbis/include' '-DHAVE_CONFIG_H' '-D_MK_HOST_X86_64' '-D_MK_HOST' '-fPIC' '-MMD' '-MP' '-MF' '.MakeKitDeps/object_dcerpc_ncklib_cncall.prot_ncacn.host.x86_64.dep' '-o' 'object/dcerpc/ncklib/cncall.prot_ncacn.host.x86_64.o' '-c' '../dcerpc/ncklib/cncall.c'
Makefile:6619: recipe for target 'object/dcerpc/ncklib/cncall.prot_ncacn.host.x86_64.o' failed
make: *** [object/dcerpc/ncklib/cncall.prot_ncacn.host.x86_64.o] Error 1
```

**Steps to Reproduce**:
1. clone the repo
2. mkdir release && cd release
3. ../configure
4. make package

Please note I do **NOT** put `--debug` in step 3.
If add `--debug` in step 3 I can get rid of this problem, but I want to build the release version.

**Comment by krizex** [comment]
@rbest-bt Do you have a recommanded gcc version to build PBIS on ubuntu?

**Comment by mikeym88** [comment]
I'm getting this error too.

**Comment by rbest-bt** [comment]
Open was built with a very old compiler to support older versions of distributions. Using newer compilers you'll need to remove the -Werror flags to get around the warnings.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
