### ISSUE TITLE
Allow specific AD group only deny domain users

### ISSUE THREAD

**Issue by jkinning** [BeyondTrust/pbis-open#247]
**Version**: pbis-open-9.1.0-551.x86_64
**OS/Distro**: Oracle Linux 8
**Issue/Impact**: I am looking at leveraging pbis-open over Centrify and SSSD. I was reading various articles and it sounds like pbis-open is the way to go. SSSD isn't quite there yet for AD bridging and AD group restrictions and Samba. Centrify is only good for a limited amount of hosts and is quite costly. So I am looking at pbis-open but unable to restrict access to just an AD group.  I am trying to deny all domain users and only allow domain users within a specific AD group to SSH or connect to a Samba share. I haven't started looking at configuring pbis-open for Samba so not sure how difficult that would be either.

I joined using this command - /opt/pbis/bin/domainjoin-cli join --assumeDefaultDomain yes --userDomainPrefix DM 'DM.DOMAIN.NET' \!domain_admin_account (we use ! in front of our domain admin accounts). This joined it just fine but it seems like no matter what I try I cannot get the AD group I specify to have access while denying domain users.

 1.  systemctl status lwsmd.service
● lwsmd.service - BeyondTrust AD Bridge Service Manager
   Loaded: loaded (/usr/lib/systemd/system/lwsmd.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2019-10-16 09:56:51 EDT; 41min ago
  Process: 927 ExecStart=/opt/pbis/sbin/lwsmd --start-as-daemon (code=exited, status=0/SUCCESS)
 Main PID: 948 (lwsmd)
    Tasks: 73 (limit: 12543)
   Memory: 50.8M
   CGroup: /system.slice/lwsmd.service
           ├─ 948 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─ 959 lw-container lwreg
           ├─ 983 lw-container eventlog
           ├─1002 lw-container netlogon
           ├─1018 lw-container lwio
           ├─1059 lw-container reapsysl
           └─1812 lw-container lsass

Oct 16 10:02:31 vmjkoralinl3t lsass[1637]: Logging started
Oct 16 10:02:52 vmjkoralinl3t lsass[1637]: [lsass] Global catalog server for domain 'DOMAIN.NET' is now online
Oct 16 10:03:31 vmjkoralinl3t lsass[1637]: [lsass] Global catalog server for domain 'DOMAIN.NET' is now online
Oct 16 10:05:07 vmjkoralinl3t lsass[1637]: [lsass] Global catalog server for domain 'DOMAIN.NET' is now online
Oct 16 10:08:31 vmjkoralinl3t lsass[1637]: [lsass] Global catalog server for domain 'DOMAIN.NET' is now online
Oct 16 10:17:23 vmjkoralinl3t lsass[1637]: [lsass] Global catalog server for domain 'DOMAIN.NET' is now online
Oct 16 10:18:31 vmjkoralinl3t lsass[1637]: [lsass] Global catalog server for domain 'DOMAIN.NET' is now online
Oct 16 10:20:15 vmjkoralinl3t lsass[1812]: Logging started
Oct 16 10:20:45 vmjkoralinl3t lsass[1812]: [lsass] Global catalog server for domain 'DOMAIN.NET' is now online
Oct 16 10:21:16 vmjkoralinl3t lsass[1812]: [lsass] Global catalog server for domain 'DOMAIN.NET' is now online

 2.  /opt/pbis/bin/lwsm list
lwreg          running (container: 959)
dcerpc         stopped
eventlog       running (container: 983)
lsass          running (container: 1812)
lwio           running (container: 1018)
netlogon       running (container: 1002)
rdr            running (io: 1018)
reapsysl       running (container: 1059)
usermonitor    stopped

 3. /opt/pbis/bin/domainjoin-cli query
Name = vmjkoralinl3t
Domain = DM.DOMAIN.NET
Distinguished Name = CN=VMJKORALINL3T,OU=Test,OU=Servers,OU=Home,OU=DM,DC=DM,DC=DOMAIN,DC=NET

 4. /opt/pbis/bin/domainjoin-cli query
Name = vmjkoralinl3t
Domain = DM.DOMAIN.NET
Distinguished Name = CN=VMJKORALINL3T,OU=Test,OU=Servers,OU=Home,OU=DM,DC=DM,DC=DOMAIN,DC=NET
[root@vmjkoralinl3t ~]# pbis status
LSA Server Status:

Compiled daemon version: 9.1.0.551
Packaged product version: 9.1.551.2
Uptime:        0 days 0 hours 19 minutes 36 seconds

[Authentication provider: lsa-activedirectory-provider]

        Status:        Online
        Mode:          Un-provisioned
        Domain:        DM.DOMAIN.NET
        Domain SID:    S-1-5-21-2227140336-3464044649-1275312582
        Forest:        DOMAIN.NET
        Site:          NYC
        Online check interval:  300 seconds
        [Trusted Domains: 2]

        [Domain: WS]

                DNS Domain:       DM.DOMAIN.NET
                Netbios name:     DM
                Forest name:      DOMAIN.NET
                Trustee DNS name:
                Client site name: NYC
                Domain SID:       S-1-5-21-2227140336-3464044649-1275312582
                Domain GUID:      712d32be-8f13-4060-8849-fb2d6baf0dfa
                Trust Flags:      [0x0019]
                                  [0x0001 - In forest]
                                  [0x0008 - Primary]
                                  [0x0010 - Native]
                Trust type:       Up Level
                Trust Attributes: [0x0000]
                Trust Direction:  Primary Domain
                Trust Mode:       In my forest Trust (MFT)
                Domain flags:     [0x0001]
                                  [0x0001 - Primary]

                [Domain Controller (DC) Information]

                        DC Name:              OURDC.DM.DOMAIN.NET
                        DC Address:           123.456.789.10
                        DC Site:              NYC
                        DC Flags:             [0x0000f1fc]
                        DC Is PDC:            no
                        DC is time server:    yes
                        DC has writeable DS:  yes
                        DC is Global Catalog: yes
                        DC is running KDC:    yes

        [Domain: DOMAIN]

                DNS Domain:       DOMAIN.NET
                Netbios name:     DOMAIN
                Forest name:      DOMAIN.NET
                Trustee DNS name: DM.DOMAIN.NET
                Client site name: CIN
                Domain SID:       S-1-5-21-1735605682-4062788989-1466315041
                Domain GUID:      cb847190-3b17-441b-afdd-9f3fadb37c42
                Trust Flags:      [0x0027]
                                  [0x0001 - In forest]
                                  [0x0002 - Outbound]
                                  [0x0004 - Tree root]
                                  [0x0020 - Inbound]
                Trust type:       Up Level
                Trust Attributes: [0x0020]
                                  [0x0020 - Within forest]
                Trust Direction:  Twoway Trust
                Trust Mode:       In my forest Trust (MFT)
                Domain flags:     [0x0000]

                [Domain Controller (DC) Information]

                        DC Name:              OURDC.DOMAIN.NET
                        DC Address:           123.456.789.10
                        DC Site:              NYC
                        DC Flags:             [0x0000f1fc]
                        DC Is PDC:            no
                        DC is time server:    yes
                        DC has writeable DS:  yes
                        DC is Global Catalog: yes
                        DC is running KDC:    yes

 5. /opt/pbis/bin/enum-users
 6. attach logs
  - /opt/pbis/bin/lwsm set-log-target -p lsass -  file /tmp/lsass.log
  - /opt/pbis/bin/lwsm set-log-level -p lsass - debug
  - attach log

**Output/Error**:

**Steps to Reproduce**:
 1. install command
 2. Domainjoin command
 3. Command that returns issue

**Comment by cboutilier-bt** [comment]
There are 2 documents you can take a look at. 
1. **Quick Start guide**:  https://www.beyondtrust.com/docs/ad-bridge/documents/adb-quick-start-guide.pdf 

2. **Config Tool Reference Guide** (Specifically RequireMembershipOf - This will allow you to set the users who are able to login): https://www.beyondtrust.com/docs/ad-bridge/documents/adb-config-tool-reference-guide.pdf
