### ISSUE TITLE
Domain Join error: LW_ERROR_LDAP_CONSTRAINT_VIOLATION

### ISSUE THREAD

**Issue by 29217321** [BeyondTrust/pbis-open#248]
This issue does not appear on pbis-8.5.0 and 8.5.3 but appears from 8.5.4

looks like it was introduced in https://github.com/beyondtrust/pbis-open/commit/66debf03a9aac07e1002156b52933ab04c75b6d7 and around https://github.com/BeyondTrust/pbis-open/blob/master/lsass/server/auth-providers/ad-open-provider/join/join.c#L773

When we call `domainjoin-cli` to join testdomain.net we will get the error output:

Joining to AD Domain:   testdomain.net
With Computer DNS Name: active-directory-service.testdomain.net

xxx's password:
Warning: A resumable error occurred while processing the 'hostname' module
LW_ERROR_ERRNO_EBUSY [code 0x00009cea]
Error: LW_ERROR_LDAP_CONSTRAINT_VIOLATION [code 0x00009d7b]

Why PBIS creates a disabled computer account when domain join and move the computer
account and enable it when domain join successed? However it violates some
restrictions of some domain, so it will fail a domain join progress as above?

Could anyone help to clarify? can we remove the logic inside pbis to create this computer account?

**Comment by krizex** [comment]
Verbose log of `domainjoin-cli join`
`20191101040015:INFO:Domainjoin invoked with the join command (remaining arguments will be printed later):
20191101040015:INFO:    [domainjoin-cli]
20191101040015:INFO:    [--loglevel]
20191101040015:INFO:    [verbose]
20191101040015:INFO:    [join]
20191101040015:INFO:Validating join options.
20191101040015:INFO:Domainjoin invoked with 2 arg(s) to the join command:
20191101040015:INFO:    [citrite.net]
20191101040015:INFO:    [svcacct_nanjing]
20191101040015:INFO:Adding fefdee511dc1 (fqdn fefdee511dc1.citrite.net) to /etc/hosts ip 172.17.0.19, removing fefdee511dc1, fefdee511dc1.citrite.net, fefdee511dc1, fefdee511dc1
20191101040015:INFO:Creating blank krb5.conf
20191101040015:INFO:Reading krb5 file /tmp/likewisetmpGwu7IH/etc/krb5.conf
20191101040015:INFO:Reading nsswitch file /etc/nsswitch.conf
20191101040015:INFO:Creating blank krb5.conf
20191101040015:INFO:Reading krb5 file /tmp/likewisetmpMygm8D/etc/krb5.conf
20191101040015:INFO:Distro Version 18.04
20191101040015:INFO:Using user entered password
20191101040015:INFO:Running module hostname
20191101040015:INFO:Adding fefdee511dc1 (fqdn fefdee511dc1.citrite.net) to /etc/hosts ip 172.17.0.19, removing fefdee511dc1, fefdee511dc1.citrite.net, fefdee511dc1, fefdee511dc1
20191101040015:INFO:Writing out updated /etc/hosts file
20191101040015:INFO:Adding fefdee511dc1 (fqdn fefdee511dc1.citrite.net) to /etc/hosts ip 172.17.0.19, removing fefdee511dc1, fefdee511dc1.citrite.net, fefdee511dc1, fefdee511dc1
20191101040015:WARNING:A resumable error occurred while processing the 'hostname' module
LW_ERROR_ERRNO_EBUSY [code 0x00009cea]


20191101040015:WARNING:LW_ERROR_ERRNO_EBUSY [LW_ERROR_ERRNO_EBUSY]



Stack Trace:
../domainjoin/libdomainjoin/src/djhostinfo.c:1287
../domainjoin/libdomainjoin/src/djhostinfo.c:1494
20191101040015:INFO:Running module join
20191101040016:VERBOSE:eventlog:LwEvtOpenEventlog():../eventlog/client/eventlog.c:174: client::eventlog.c OpenEventlog server=<null>)

20191101040016:ERROR:LW_ERROR_LDAP_CONSTRAINT_VIOLATION [LW_ERROR_LDAP_CONSTRAINT_VIOLATION]



Stack Trace:
../domainjoin/domainjoin-cli/src/main.c:1640
../domainjoin/domainjoin-cli/src/main.c:894
../domainjoin/libdomainjoin/src/djmodule.c:356
../domainjoin/libdomainjoin/src/djauthinfo.c:858
../domainjoin/libdomainjoin/src/djauthinfo.c:1271
`

**Comment by rbest-bt** [comment]
pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
