### ISSUE TITLE
MacOS "allow user to administer this computer" flag doesn't survive on reboot

### ISSUE THREAD

**Issue by sgargel** [BeyondTrust/pbis-open#249]
**Version**: 9.1.0
**OS/Distro**: MacOS 10.15 (Catalina)
**Issue/Impact**: User can correctly log-on but can't be set as admin because "allow user to administer this computer" flag doesn't survive on reboot.

![mac_allow_user_to_administer](https://user-images.githubusercontent.com/24651376/67847885-eb242900-fb03-11e9-9774-71a44a39b677.png)

**Comment by rbest-bt** [comment]
Have a look at the config option "AllowAdministrationBy"

See the Mac Admin guide for more details

**Comment by Miene-Lx** [comment]
Hi,
I have same issue as sgarcel on Catalina.
@sgargel : Is this issue solved for you ?

Thanks

**Comment by sgargel** [comment]
I've still the same issue. Sadly we are moving away from pbis to the native "domain join" our MacOS.
Linux is working very well instead.
