### ISSUE TITLE
Squid

### ISSUE THREAD

**Issue by michelaegue** [BeyondTrust/pbis-open#250]
How to control user authentication in squid, as well as access by groups?

**Comment by dmorash-BT** [comment]
ad bridge (nee pbis) provides a pam module, so if squid supports authentication by pam that might work.

**Comment by rbest-bt** [comment]
Please upgrade to Active Directory Bridge Enterprise and someone from support should be able to assist.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
