### ISSUE TITLE
PBIS -"I have no name!" : after the addition to the domain and the configuration of the groups the user returns "I have no name!"

### ISSUE THREAD

**Issue by steanodesantis** [BeyondTrust/pbis-open#251]
During the installation of pbis and the join to the domain no problems emerge, but by logging in with the user, he cannot get the id and the user group by returning "I have no name!"

PS: for security reasons I blocked the IP with xxx

##########################################################
**Version**: 9.1.0.551
**OS/Distro**: Red Hat Enterprise Linux Server release 6.10
**Issue/Impact**:
*Note: replace content with your own*
When reporting an issue it's important that we have as much detail as you can provide. The following is a list of commands to check.
 1. [root@pprospectsvil ~]# ps -efa|grep lwsmd
	root      6024 30789  0 08:23 pts/0    00:00:00 grep lwsmd
	root     30145     1  0 Oct30 ?        00:00:00 /opt/pbis/sbin/lwsmd --start-as-daemon
 2. [root@pprospectsvil ~]# /opt/pbis/bin/lwsm list
	lwreg          running (container: 30168)
	dcerpc         stopped
	eventlog       running (container: 30196)
	lsass          running (container: 30928)
	lwio           running (container: 30247)
	netlogon       running (container: 30222)
	rdr            running (io: 30247)
	reapsysl       running (container: 30306)
	usermonitor    stopped
 3. [root@pprospectsvil ~]# /opt/pbis/bin/domainjoin-cli query
	Name = pprospectsvil
	Domain = xxxxxxx
	Distinguished Name = CN=PPROSPECTSVIL,CN=Computers,DC=gmt,DC=xxxxx,DC=it
 4. [root@pprospectsvil ~]# pbis status
	LSA Server Status:

	Compiled daemon version: 9.1.0.551
	Packaged product version: 9.1.551.2
	Uptime:        0 days 19 hours 22 minutes 9 seconds

	[Authentication provider: lsa-activedirectory-provider]

        Status:        Online
        Mode:          Un-provisioned
        Domain:        xxxxxxxx
        Domain SID:    xxxxxxxx
        Forest:        xxxxxxxx
        Site:          VI
        Online check interval:  300 seconds
        [Trusted Domains: 5]

        [Domain: GMT]

                DNS Domain:       xxxxxxxx
                Netbios name:     xxxxxxxx
                Forest name:      xxxxxxxx
                Trustee DNS name: 
                Client site name: VI
                Domain SID:       xxxxxxxx
                Domain GUID:      xxxxxxxx
                Trust Flags:      [0x001d]
                                  [0x0001 - In forest]
                                  [0x0004 - Tree root]
                                  [0x0008 - Primary]
                                  [0x0010 - Native]
                Trust type:       Up Level
                Trust Attributes: [0x0000]
                Trust Direction:  Primary Domain
                Trust Mode:       In my forest Trust (MFT)
                Domain flags:     [0x0001]
                                  [0x0001 - Primary]

                [Domain Controller (DC) Information]

                        DC Name:              xxxxxxxx
                        DC Address:           xxxxxx
                        DC Site:              xxxxxxxx
                        DC Flags:             [0x0001f1fc]
                        DC Is PDC:            no
                        DC is time server:    yes
                        DC has writeable DS:  yes
                        DC is Global Catalog: yes
                        DC is running KDC:    yes

                [Global Catalog (GC) Information]

                        GC Name:              xxxxxxxx
                        GC Address:           xxxxxx
                        GC Site:              xxxxxxxx
                        GC Flags:             [0x0001f1fc]
                        GC Is PDC:            no
                        GC is time server:    yes
                        GC has writeable DS:  yes
                        GC is running KDC:    yes

        [Domain: CRIGA]

                DNS Domain:      xxxxxxxx
                Netbios name:     xxxxxxxx
                Forest name:      xxxxxxxx
                Trustee DNS name: xxxxxxxx
                Client site name: PD
                Domain SID:       xxxxxxxx
                Domain GUID:      xxxxxxxx
                Trust Flags:      [0x0022]
                                  [0x0002 - Outbound]
                                  [0x0020 - Inbound]
                Trust type:       Up Level
                Trust Attributes: [0x0048]
                                  [0x0008 - Forest transitive]
                Trust Direction:  Twoway Trust
                Trust Mode:       In other forest Trust (OFT)
                Domain flags:     [0x0000]

                [Domain Controller (DC) Information]

                        DC Name:              xxxxxxxx
                        DC Address:           xxxxxx
                        DC Site:              PD
                        DC Flags:             [0x0000f1fc]
                        DC Is PDC:            no
                        DC is time server:    yes
                        DC has writeable DS:  yes
                        DC is Global Catalog: yes
                        DC is running KDC:    yes

                [Global Catalog (GC) Information]

                        GC Name:              xxxxxxxx
                        GC Address:           xxxxxx
                        GC Site:              PD
                        GC Flags:             [0x0000f1fc]
                        GC Is PDC:            no
                        GC is time server:    yes
                        GC has writeable DS:  yes
                        GC is running KDC:    yes

        [Domain: INTRALOT]

                DNS Domain:       xxxxxxxx
                Netbios name:     xxxxxxxx
                Forest name:      xxxxxxxx
                Trustee DNS name: xxxxxxxx
                Client site name: 
                Domain SID:       xxxxxxxx
                Domain GUID:      xxxxxxxx
                Trust Flags:      [0x0022]
                                  [0x0002 - Outbound]
                                  [0x0020 - Inbound]
                Trust type:       Up Level
                Trust Attributes: [0x0048]
                                  [0x0008 - Forest transitive]
                Trust Direction:  Twoway Trust
                Trust Mode:       In other forest Trust (OFT)
                Domain flags:     [0x0000]

        [Domain: BETOS]

                DNS Domain:       xxxxxxxx
                Netbios name:     xxxxxxxx
                Forest name:      
                Trustee DNS name: GMT.GAMENETGROUP.IT
                Client site name: 
                Domain SID:       S-1-5-21-461410778-2417026049-1146536909
                Domain GUID:      00000000-0000-0000-0000-000000000000
                Trust Flags:      [0x0020]
                                  [0x0020 - Inbound]
                Trust type:       Up Level
                Trust Attributes: [0x0000]
                Trust Direction:  Zeroway Trust
                Trust Mode:       External Trust (ET)
                Domain flags:     [0x0000]

        [Domain: WINCO]

                DNS Domain:       xxxxxxxx
                Netbios name:     xxxxxxxx
                Forest name:      xxxxxxxx
                Trustee DNS name: xxxxxxxx
                Client site name: 
                Domain SID:       S-1-5-21-2458678039-2337093563-2379887208
                Domain GUID:      00000000-0000-0000-0000-000000000000
                Trust Flags:      [0x0022]
                                  [0x0002 - Outbound]
                                  [0x0020 - Inbound]
                Trust type:       Up Level
                Trust Attributes: [0x0048]
                                  [0x0008 - Forest transitive]
                Trust Direction:  Twoway Trust
                Trust Mode:       In other forest Trust (OFT)
                Domain flags:     [0x0000]
 5. [root@pprospectsvil ~]# /opt/pbis/bin/enum-users | grep s.desantis
	Name:              s.desantis
	Home dir:          /home/GMT/s.desantis
	Name:              s.desantis.admin
	Home dir:          /home/GMT/s.desantis.admin
 6. attach logs
  - /opt/pbis/bin/lwsm set-log-target -p lsass -  file /tmp/lsass.log
  - /opt/pbis/bin/lwsm set-log-level -p lsass - debug
  - attach log

**Output/Error**:

[root@pprospectsvil tmp]# su - s.desantis.admin
/usr/bin/id: cannot find name for user ID 1656238626
/usr/bin/id: cannot find name for group ID 1656226305
/usr/bin/id: cannot find name for user ID 1656238626
[I have no name!@pprospectsvil ~]$ id
uid=1656238626 gid=1656226305 groups=1656226305,1656226304,1656226310,1656226311,1656226364,1656226899,1656227014,1656227015,1656227016,1656227017,1656227021,1656227377,1656227411,1656227509,1656227724,1656227797,1656227849,1656228415,1656228539,1656228609,1656228652,1656228654,1656228659,1656234744,1656234823,1656236524

[I have no name!@pprospectsvil ~]$

[lsass.log](https://github.com/BeyondTrust/pbis-open/files/3793033/lsass.log)

**Comment by dmorash-BT** [comment]
Can you verify that your /etc/nsswitch.conf file has the lsass in the passwd: and group: entries?
e.g.  passwd:  compat lsass

**Comment by steanodesantis** [comment]
they are present  : 

passwd:     files lsass
shadow:     files 
group:      files lsass

#hosts:     db files nisplus nis dns
hosts:      files dns myhostname

# Example - obey only what nisplus tells us...
#services:   nisplus [NOTFOUND=return] files
#networks:   nisplus [NOTFOUND=return] files
#protocols:  nisplus [NOTFOUND=return] files
#rpc:        nisplus [NOTFOUND=return] files
#ethers:     nisplus [NOTFOUND=return] files
#netmasks:   nisplus [NOTFOUND=return] files     

bootparams: nisplus [NOTFOUND=return] files

ethers:     files
netmasks:   files
networks:   files
protocols:  files
rpc:        files
services:   files 
netgroup:   files 
publickey:  nisplus
automount:  files
aliases:    files nisplus

**Comment by rbest-bt** [comment]
Were you able to figure out the issue?
