### ISSUE TITLE
PBIS - Login with trusted domain

### ISSUE THREAD

**Issue by nbattista89** [BeyondTrust/pbis-open#253]
**Version**: 9.10
**OS/Distro**: Centos 7.7

I would like to know if pbis supports login with a domain that is in turn trusted.
I've some server joined at the domain winco but i need also login with the domain users gmt.

with command pbis status i see all domains.
[Authentication provider: lsa-activedirectory-provider]

	Status:        Online
	Mode:          Un-provisioned
	Domain:        WINCO
	Forest:        winco
	Online check interval:  300 seconds
	[Trusted Domains: 2]

	[Domain: WINCO]

		DNS Domain:       winco
		Netbios name:     WINCO
		Forest name:      winco
		Trustee DNS name: 
		Domain SID:       S-1-5-21-2458678039-2337093563-2379887208
		Domain GUID:      addb15f3-85ad-4dff-b471-4fa2b73a6193
		Trust Flags:      [0x001d]
		                  [0x0001 - In forest]
		                  [0x0004 - Tree root]
		                  [0x0008 - Primary]
		                  [0x0010 - Native]
		Trust type:       Up Level
		Trust Attributes: [0x0000]
		Trust Direction:  Primary Domain
		Trust Mode:       In my forest Trust (MFT)
		Domain flags:     [0x0001]
		                  [0x0001 - Primary]

[Domain: GMT]
		DNS Domain:      xxx.xxxx.xxx
		Netbios name:     GMT
		Forest name:     xxx.xxx.xxx
		Trustee DNS name: WINCO
		Trust Flags:      [0x0022]
                 [0x0002 - Outbound]
                 [0x0020 - Inbound]
		Trust type:       Up Level
		Trust Attributes: [0x0048]
                 [0x0008 - Forest transitive]
		Trust Direction:  Twoway Trust
		Trust Mode:       In other forest Trust (OFT)
		Domain flags:     [0x0000]

/opt/pbis/bin/enum-users --level 2 | grep GMT but not returned the users inside domain gmt.
Is there any additional parameter to implement?

Thanks,
Regards

**Comment by srinureddy52** [comment]
//any idea about this error , while trying to join to RODC getting below error
systemctl status lwsmd.service
shows below error
[lsass] The cached machine account password was rejected by the DC.

**Comment by rbest-bt** [comment]
@srinureddy52, please log a new issue.

@nbattista89, Authentication should work fine. Enum-users only list the users from the current domain. I recommend using adtool to search users in the other domain.
