### ISSUE TITLE
AD account SSH access only

### ISSUE THREAD

**Issue by LarryBetson** [BeyondTrust/pbis-open#254]
**Version**: pbis-open-9.1.0-551.x86_64
**OS/Distro**: CentOS-7
**Issue/Impact**:
Its not really an issue I just can't seem to find this in the documentation. Is there a way to just grant an AD user just SSH access and not giving them sudo? I was looking for a command, etc. I am new to this product so pleas excuse my ignorance.

**Comment by dmorash-BT** [comment]
PBIS open does not modify the sudoers file, so whether AD users have access depends on how sudo is configured.  If sudo is configured to allow all users to sudo then AD users will automatically be included. 

For reference the system configuration modifications pbis makes happen once you join a domain.  These are performed by the domainjoin modules described in the domainjoin-cli man page.  So for example, pbis modifies the pam stack, nsswitch etc., but we don't touch sudo. 

The Linux Admin guide at https://www.beyondtrust.com/docs/ad-bridge/documents/9-1/adb-linux-administration-guide-9-1.pdf, page 40 does cover how to add AD users to sudo.  It also discusses the sudo group policy support in PBIS Enterprise.

**Comment by LarryBetson** [comment]
Can I add multiple groups the ability to login with the RequireMembershipOf or is it only limited to one group? Thank you.

**Comment by dmorash-BT** [comment]
You can set multiple groups like so:  /opt/pbis/bin/config RequireMembershipOf  MYDOMAIN\\Group1 MYDOMAIN\\Group2 

n.b. the group names you use need to match the output of enum-groups.  

We really need to add some examples to the config reference guide or the tool itself as its not obvious. /opt/pbis/bin/config --details RequireMembershipOf shows its a multi string but that is the only hint.
