### ISSUE TITLE
Unable to find ssh binary on Oracle Linux 6.10 with pbis-open-9.1.0-551.x86_64

### ISSUE THREAD

**Issue by sgargel** [BeyondTrust/pbis-open#256]
**Version**: 9.1.0-551
**OS/Distro**: Oracle Linux 6.10
**Issue/Impact**:
Can't join domain because *Error: Unable to find ssh binary [code 0x00000436]*

```
[root@myserver ~]# /opt/pbis/bin/domainjoin-cli join MYDOMAIN.COM Administrator

Error: Unable to find ssh binary [code 0x00000436]

A ssh config file was at {nowhere}, and a ssh binary file was found at {nowhere}. Exactly one config file and one binary must exist on the system in a standard location. Uninstall any unused copies of ssh.
Please see the documentation related to sshd configuration options required and re-attempt the join with "domainjoin-cli join/leave --disable ssh <domain> <username>"
```
but sshd is installed:
```
[root@myserver ~]# ls -la /etc/ssh/sshd_config 
-rw-------. 1 root root 3879 Apr 10  2019 /etc/ssh/sshd_config

[root@myserver ~]# rpm -qa openssh
openssh-5.3p1-124.el6_10.x86_64
```

**Comment by rbest-bt** [comment]
Is sshd running and in is ssd your path?

**Comment by sgargel** [comment]
> Is sshd running and in is ssd your path?

sshd is up and running

`root       9414  0.0  0.0  66348  2672 ?        Ss   Dec02   0:00 /usr/sbin/sshd`

Do you mean `sshd` or `sssd` ?

`sshd` is in my path:

```
[root@myserver ~]# which sshd
/usr/sbin/sshd
```

**Comment by rbest-bt** [comment]
Not sure why this would be. This Oracle 6 is a tested distribution. Please upgrade to Active Directory Bridge Enterprise. If the issue still exists then please submit a ticket to our service team and we’ll have a look for you.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
