### ISSUE TITLE
PBIS to authenticate AD users through Radius Server

### ISSUE THREAD

**Issue by francesco-ficarola** [BeyondTrust/pbis-open#257]
**Version**: 9.0.1.525
**OS/Distro**: Ubuntu server 14.04
**Issue/Impact**: Unable to authenticate AD users through Radius Server

We have a Linux machine properly joined to our AD domain thanks to pbis-open v9.0.1.525. This machine has a Radius Server (FreeRadius 2.x) that we use to authenticate users against several web applications. We'd like to add a Radius module in order to use pbis-open with AD authentication. Indeed, the FreeRadius documentation refers to `ntlm_auth` command to authenticate AD users; however, since we are using pbis-open, the Samba/Winbind cannot be used (and `ntlm_auth` is a command of the Winbind package). I thought that the alternative could be a custom `exec` module running the `/usr/bin/pbis authenticate-user` command.

Testing such a command, it properly works:

    ~# /usr/bin/pbis authenticate-user --user 'myuser' --domain 'mydomain.com' --password 'mypassword'
    Success

So, we created a **pbis** module in the FreeRadius configuration:

    ~# cat /etc/freeradius/modules/pbis
    exec pbis {
        wait = yes
        program = "/usr/bin/pbis authenticate-user --user '%{Stripped-User-Name}' --domain 'mydomain.com' --password '%{User-Password}'"
    }

and added the realm in the `/etc/freeradius/proxy.conf` file:

    realm mydomain.com {
        strip
        home_server     = LOCAL
    }

Then, we call this module in the default FreeRadius site `/etc/freeradius/sites-enabled/default`:

    authorize {
        if (User-name =~ /^(.*)@mydomain\.com$/) {
            update control {
                Auth-Type := pbis
            }
        }
    }

    authenticate {
        Auth-Type PBIS {
            pbis
        }
    }

However, when we test the authentication using radtest:

    ~# radtest "myuser@mydomain.com" "mypassword" localhost 0 mysecret

the output of `freeradius -X` (debug mode), returns:

    rad_recv: Access-Request packet from host 127.0.0.1 port 50451, id=83, length=112
    	User-Name = "myuser@mydomain.com"
    	User-Password = "mypassword"
    	NAS-IP-Address = 192.168.66.151
    	NAS-Port = 0
    	Message-Authenticator = 0xa168b825a36f543759ea004f7c49df1e
    # Executing section authorize from file /etc/freeradius/sites-enabled/default
    +- entering group authorize {...}
    ++[chap] returns noop
    ++[mschap] returns noop
    [suffix] Looking up realm "mydomain.com" for User-Name = "myuser@mydomain.com"
    [suffix] Found realm "mydomain.com"
    [suffix] Adding Stripped-User-Name = "myuser"
    [suffix] Adding Realm = "mydomain.com"
    [suffix] Authentication realm is LOCAL.
    ........
    ? Evaluating (User-name =~ /^(.*)@mydomain\.com$/) -> TRUE
    ++? elsif (User-name =~ /^(.*)@mydomain\.com$/) -> TRUE
    ++- entering elsif (User-name =~ /^(.*)@mydomain\.com$/) {...}
    ........
    Found Auth-Type = PBIS
    # Executing group from file /etc/freeradius/sites-enabled/default
    +- entering group PBIS {...}
    [pbis] 	expand: '%{Stripped-User-Name}' -> 'myuser'
    [pbis] 	expand: '%{User-Password}' -> 'mypassword'
    Exec-Program output: Error: LW_ERROR_NOT_HANDLED (0x9c51) 
    Exec-Program-Wait: plaintext: Error: LW_ERROR_NOT_HANDLED (0x9c51) 
    Exec-Program: returned: 1
    ++[pbis] returns reject
    Failed to authenticate the user.
    Login incorrect: [myuser@mydomain.com] (from client localhost port 0)

So the output error is **LW_ERROR_NOT_HANDLED** and the login failed.

The syslog file just records:

    Dec  3 10:37:14 radius1 freeradius[26191]: Login incorrect: [myuser@mydomain.com] (from client localhost port 0).

What's the issue?

Thanks,
Francesco

**Comment by francesco-ficarola** [comment]
If this can help, I've enabled debug mode on pbis-open logging:

    ~# /opt/pbis/bin/config PAMLogLevel debug

and now `/var/log/syslog` shows an additional information:

    Dec  3 11:26:41 radius1 lsass: [lsass] Failed to find user, group, or domain by name (name = ''mydomain.com'', searched host = 'mydc.mydomain.com') -> error = 40071, symbol = LW_ERROR_NO_SUCH_OBJECT
    Dec  3 11:26:41 radius1 freeradius[26410]: Login incorrect: [myuser@mydomain.com] (from client localhost port 0)

So, the error stored in syslog is **LW_ERROR_NO_SUCH_OBJECT**

**Comment by francesco-ficarola** [comment]
Ok, I understood that the **LW_ERROR_NO_SUCH_OBJECT** error depends on the `--domain` parameter in the `pbis authenticate-user` command. Indeed, I tried to remove that parameter and the error disappeared . However, the command under FreeRadius still does not work.

**Comment by francesco-ficarola** [comment]
Ok, I've just solved the issue. The problem was the `'` around the parameter. The correct command is:

    program = "/usr/bin/pbis authenticate-user --user %{Stripped-User-Name} --domain mydomain.com --password %{User-Password}"

Contrary to the command executed into the shell, the values of the parameters do not need `'` because FreeRadius arguments are already parametrized.

**Comment by JasonEverling** [comment]
Just what I needed, thank you for doing the leg-work. We just migrated off Microsoft NPS into FreeRADIUS for some technical reasons but we still wanted to use PBIS on our server because that's the standard for our servers. I really didn't want to use winbind either so thanks!

**Comment by JasonEverling** [comment]
@francesco-ficarola Did you also get EAP working? Having trouble with getting it to work with the mschap module :(
