### ISSUE TITLE
PBIS - Unknown PAM configuration

### ISSUE THREAD

**Issue by steanodesantis** [BeyondTrust/pbis-open#258]
**Version**: 9.1.0.551
**OS/Distro**: Red Hat Enterprise Linux Server release 6.10

before joining the domain it fails to enable the pam module
can you help me
thanks

--------------------------------------------------------------
domainjoin-cli configure --enable pam  
                           
Warning: Unknown PAM configuration
The PAM module cannot be configured for the atd service.  Either this service is unprotected (does not require a valid password for
access), or it is using a PAM module that this program is unfamiliar with.  Please email technical support and include a copy of
/etc/pam.conf or /etc/pam.d.

Warning: Unknown PAM configuration
The PAM module cannot be configured for the ppp service.  Either this service is unprotected (does not require a valid password for
access), or it is using a PAM module that this program is unfamiliar with.  Please email technical support and include a copy of
/etc/pam.conf or /etc/pam.d.

Error: Unknown PAM configuration [code 0x0000a609]

The PAM module cannot be configured for the sshd service.  Either this service is unprotected (does not require a valid password for
access), or it is using a PAM module that this program is unfamiliar with.  Please email technical support and include a copy of
/etc/pam.conf or /etc/pam.d.

--------------------------------------------------------------------

**Comment by rbest-bt** [comment]
There is a pam module in those files that are unknown to our module. There are two methods to address this.
1. Remove those and add them back in after the domainjoin
2. Use --ignore-pam and manually add lsass into your pam files

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
