### ISSUE TITLE
Error: LW_ERROR_NOT_HANDLED (0x9c51) 

### ISSUE THREAD

**Issue by ndroftheline** [BeyondTrust/pbis-open#260]
**Version**: 
Compiled daemon version: 9.1.0.551
Packaged product version: 9.1.551.2

**OS/Distro**: Ubuntu server 18.04
**Issue/Impact**: unable to login with ad users. domain join works fine, status reports OK. 

When reporting an issue it's important that we have as much detail as you can provide. The following is a list of commands to check.
 1. systemctl status lwsmd.service
root@pbisopen1:~# ping ad.oftheline.net
PING ad.oftheline.net (10.1.42.11) 56(84) bytes of data.
64 bytes from nsdc.oftheline.net (10.1.42.11): icmp_seq=1 ttl=64 time=5.73 ms
* lwsmd.service - BeyondTrust AD Bridge Service Manager
   Loaded: loaded (/lib/systemd/system/lwsmd.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2019-12-15 09:25:02 UTC; 1h 2min ago
  Process: 150 ExecStart=/opt/pbis/sbin/lwsmd --start-as-daemon (code=exited, status=0/SUCCESS)
 Main PID: 162 (lwsmd)
    Tasks: 372 (limit: 4915)
   CGroup: /system.slice/lwsmd.service
           |-162 /opt/pbis/sbin/lwsmd --start-as-daemon
           |-214 lw-container lwreg
           |-300 lw-container eventlog
           |-355 lw-container netlogon
           |-409 lw-container lwio
           |-465 lw-container lsass
           `-538 lw-container reapsysl

Dec 15 09:25:02 pbisopen1 lwio[409]: Logging started
Dec 15 09:25:02 pbisopen1 lsass[465]: Logging started
Dec 15 09:25:02 pbisopen1 reapsysl[538]: Logging started
Dec 15 09:25:02 pbisopen1 systemd[1]: Started BeyondTrust AD Bridge Service Manager.
Dec 15 09:25:14 pbisopen1 lsass[465]: Unable to set up credentials cache with tgt for uid 992478292
Dec 15 09:25:14 pbisopen1 lsass[465]: [lsass] Failed to authenticate user (name = 'otl\micah') -> error = 2
Dec 15 09:25:25 pbisopen1 lsass[465]: Unable to set up credentials cache with tgt for uid 992478292
Dec 15 09:25:25 pbisopen1 lsass[465]: [lsass] Failed to authenticate user (name = 'micah@ad.oftheline.net')
Dec 15 09:41:45 pbisopen1 lsass[465]: Unable to set up credentials cache with tgt for uid 992478292
Dec 15 09:41:45 pbisopen1 lsass[465]: [lsass] Failed to authenticate user (name = 'micah@ad.oftheline.net')

 2. /opt/pbis/bin/lwsm list

root@pbisopen1:~# /opt/pbis/bin/lwsm list
lwreg          running (container: 214)
dcerpc         stopped
eventlog       running (container: 300)
lsass          running (container: 465)
lwio           running (container: 409)
netlogon       running (container: 355)
rdr            running (io: 409)
reapsysl       running (container: 538)
usermonitor    stopped

 3. /opt/pbis/domainjoin-cli query

root@pbisopen1:/opt/pbis# domainjoin-cli query
Name = pbisopen1
Domain = AD.OFTHELINE.NET
Distinguished Name = CN=PBISOPEN1,CN=Computers,DC=ad,DC=oftheline,DC=net

 4. pbis status

root@pbisopen1:/opt/pbis# pbis status
LSA Server Status:

Compiled daemon version: 9.1.0.551
Packaged product version: 9.1.551.2
Uptime:        0 days 1 hours 5 minutes 35 seconds

[Authentication provider: lsa-activedirectory-provider]

        Status:        Online
        Mode:          Un-provisioned
        Domain:        AD.OFTHELINE.NET
        Domain SID:    S-1-5-21-379574143-1487284089-3310628308
        Forest:        ad.oftheline.net
        Site:          Default-First-Site-Name
        Online check interval:  300 seconds
        [Trusted Domains: 1]

        [Domain: OTL]

                DNS Domain:       ad.oftheline.net
                Netbios name:     OTL
                Forest name:      ad.oftheline.net
                Trustee DNS name: 
                Client site name: Default-First-Site-Name
                Domain SID:       S-1-5-21-379574143-1487284089-3310628308
                Domain GUID:      ceb050e1-ea43-4382-99dc-9fb561005eb6
                Trust Flags:      [0x001d]
                                  [0x0001 - In forest]
                                  [0x0004 - Tree root]
                                  [0x0008 - Primary]
                                  [0x0010 - Native]
                Trust type:       Up Level
                Trust Attributes: [0x0000]
                Trust Direction:  Primary Domain
                Trust Mode:       In my forest Trust (MFT)
                Domain flags:     [0x0001]
                                  [0x0001 - Primary]

                [Domain Controller (DC) Information]

                        DC Name:              nsdc-neth1.ad.oftheline.net
                        DC Address:           10.1.42.11
                        DC Site:              Default-First-Site-Name
                        DC Flags:             [0x000013fd]
                        DC Is PDC:            yes
                        DC is time server:    yes
                        DC has writeable DS:  yes
                        DC is Global Catalog: yes
                        DC is running KDC:    yes

 5. /opt/pbis/bin/enum-users

I mean, this spits out all the users in my domain. Do I really need to post this? 

example: User info (Level-0):
====================
Name:              OTL\micah
Uid:               992478292
Gid:               992477697
Gecos:             Micah Roth
Shell:             /bin/sh
Home dir:          /home/local/OTL/micah

 6. attach logs
  - /opt/pbis/bin/lwsm set-log-target -p lsass -  file /tmp/lsass.log

root@pbisopen1:/opt/pbis# /opt/pbis/bin/lwsm set-log-target -p lsass
Error: LW_ERROR_INVALID_PARAMETER (40041)
Invalid parameter

  - /opt/pbis/bin/lwsm set-log-level -p lsass -debug

root@pbisopen1:/opt/pbis# /opt/pbis/bin/lwsm set-log-level -p lsass -debug
Error: LW_ERROR_INVALID_PARAMETER (40041)
Invalid parameter

**Output/Error**:

Error: LW_ERROR_NOT_HANDLED (0x9c51) 

**Steps to Reproduce**:
0. install a lxc template of ubuntu 18.04 on proxmox
 1. install command

apt-get install pbis-open

 2. Domainjoin command

domainjoin-cli join ad.oftheline.net

 3. Command that returns issue

pbis authenticate-user --user micah

**Comment by semidark** [comment]
I got the same issue here, with a kind of identical setup. I was testing Ubuntu Desktop ,Kubuntu Desktop and Ubuntu Server, all in 18.04 Versions. Everything except the Server flavour is working. The Server was just installed fresh from an Server ISO.

**Comment by rbest-bt** [comment]
I've put it on our list to investigate.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
