### ISSUE TITLE
Cannot change AD user passwords

### ISSUE THREAD

**Issue by dvosbury** [BeyondTrust/pbis-open#262]
**Version**: 9.1.0
**OS/Distro**: CENTOS 7.7.1908
**Issue/Impact**: Major
**Notes** AD users unable to change passwords from command like on domain joined systems. The following are samples from one of the affected systems.

 1. systemctl status lwsmd.service
● lwsmd.service - BeyondTrust AD Bridge Service Manager
   Loaded: loaded (/usr/lib/systemd/system/lwsmd.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2020-01-02 21:13:41 UTC; 18h ago
  Process: 1393 ExecStart=/opt/pbis/sbin/lwsmd --start-as-daemon (code=exited, status=0/SUCCESS)
 Main PID: 1406 (lwsmd)
   CGroup: /system.slice/lwsmd.service
           ├─1406 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─1419 lw-container lwreg
           ├─1450 lw-container eventlog
           ├─1470 lw-container netlogon
           ├─1497 lw-container lwio
           ├─1522 lw-container lsass
           └─1643 lw-container reapsysl

Jan 03 14:40:36 utilawssy02 lsass[1522]: [lsass] Restricted login list - couldn't resolve adawssy\nosudo_all [40071]
Jan 03 14:40:37 utilawssy02 lsass[1522]: [lsass] Restricted login list - couldn't resolve adawssy\utilawssy02 [40071]
Jan 03 14:40:37 utilawssy02 lsass[1522]: [lsass] Restricted login list - couldn't resolve adawssy\utilawssy02_nosudo [40071]
Jan 03 14:40:37 utilawssy02 lsass[1522]: [lsass] Restricted login list - couldn't resolve adawssy\nosudo_all [40071]
Jan 03 14:40:37 utilawssy02 lsass[1522]: [lsass] Restricted login list - couldn't resolve adawssy\utilawssy02 [40071]
Jan 03 14:40:37 utilawssy02 lsass[1522]: [lsass] Restricted login list - couldn't resolve adawssy\utilawssy02_nosudo [40071]
Jan 03 14:40:37 utilawssy02 lsass[1522]: [lsass] Restricted login list - couldn't resolve adawssy\nosudo_all [40071]
Jan 03 14:42:04 utilawssy02 lsass[1522]: [lsass] Failed to change password of user (name = 'tuser') -> error = 31, symbol = ERROR_GEN_FAILURE, client pid = 5805
Jan 03 14:42:16 utilawssy02 lsass[1522]: LwSmSetMaxLogLevel():lwsm/server/logger.c:662: Log level changed to DEBUG
Jan 03 14:42:16 utilawssy02 lsass[1522]: LwSmSetLogger():lwsm/server/logger.c:476: Logging redirected

 2. /opt/pbis/bin/lwsm list
lwreg          running (container: 1419)
dcerpc         stopped
eventlog       running (container: 1450)
lsass          running (container: 1522)
lwio           running (container: 1497)
netlogon       running (container: 1470)
rdr            running (io: 1497)
reapsysl       running (container: 1643)
usermonitor    stopped

 3. /opt/pbis/domainjoin-cli query
Name = utilawssy02
Domain = ADAWSSY.AEROBAHN.COM
Distinguished Name = CN=UTILAWSSY02,CN=Computers,DC=adawssy,DC=aerobahn,DC=com

 4. pbis status
LSA Server Status:

Compiled daemon version: 9.1.0.551
Packaged product version: 9.1.551.2
Uptime:        0 days 18 hours 33 minutes 8 seconds

[Authentication provider: lsa-activedirectory-provider]

        Status:        Online
        Mode:          Un-provisioned
        Domain:        ADAWSSY.AEROBAHN.COM
        Domain SID:    S-1-5-21-2190095725-827635058-1767731504
        Forest:        adawssy.aerobahn.com
        Site:          Default-First-Site-Name
        Online check interval:  300 seconds
        [Trusted Domains: 1]

        [Domain: ADAWSSY]

                DNS Domain:       adawssy.aerobahn.com
                Netbios name:     ADAWSSY
                Forest name:      adawssy.aerobahn.com
                Trustee DNS name:
                Client site name: Default-First-Site-Name
                Domain SID:       S-1-5-21-2190095725-827635058-1767731504
                Domain GUID:      4d238184-0faf-4f45-a2d2-7c11206ed625
                Trust Flags:      [0x001d]
                                  [0x0001 - In forest]
                                  [0x0004 - Tree root]
                                  [0x0008 - Primary]
                                  [0x0010 - Native]
                Trust type:       Up Level
                Trust Attributes: [0x0000]
                Trust Direction:  Primary Domain
                Trust Mode:       In my forest Trust (MFT)
                Domain flags:     [0x0001]
                                  [0x0001 - Primary]

                [Domain Controller (DC) Information]

                        DC Name:              adawssy01.adawssy.aerobahn.com
                        DC Address:           10.13.3.164
                        DC Site:              Default-First-Site-Name
                        DC Flags:             [0x0001f1fd]
                        DC Is PDC:            yes
                        DC is time server:    yes
                        DC has writeable DS:  yes
                        DC is Global Catalog: yes
                        DC is running KDC:    yes

                [Global Catalog (GC) Information]

                        GC Name:              adawssy01.adawssy.aerobahn.com
                        GC Address:           10.13.3.164
                        GC Site:              Default-First-Site-Name
                        GC Flags:             [0x0001f1fd]
                        GC Is PDC:            yes
                        GC is time server:    yes
                        GC has writeable DS:  yes
                        GC is running KDC:    yes

 5. /opt/pbis/bin/enum-users
User info (Level-0):
====================
Name:              krbtgt
Uid:               239075830
Gid:               239075841
Gecos:             <null>
Shell:             /bin/bash
Home dir:          /home/AD/krbtgt

User info (Level-0):
====================
Name:              dvosburyadadmin
Uid:               239076938
Gid:               239075841
Gecos:             David Vosbury Domain Admin
Shell:             /bin/bash
Home dir:          /home/AD/dvosburyadadmin

User info (Level-0):
====================
Name:              dvosbury
Uid:               239076939
Gid:               239075841
Gecos:             David Vosbury Linux user
Shell:             /bin/bash
Home dir:          /home/AD/dvosbury

User info (Level-0):
====================
Name:              dvosburylocaladm
Uid:               239076940
Gid:               239075841
Gecos:             David Vosbury Local Admin
Shell:             /bin/bash
Home dir:          /home/AD/dvosburylocaladm

User info (Level-0):
====================
Name:              astevens
Uid:               239076447
Gid:               239075841
Gecos:             Amanda Stevens Domain and Linux user account
Shell:             /bin/bash
Home dir:          /home/AD/astevens

User info (Level-0):
====================
Name:              tuser
Uid:               239076448
Gid:               239075841
Gecos:             Test User
Shell:             /bin/bash
Home dir:          /home/AD/tuser

 6. attach logs

[lsass.log](https://github.com/BeyondTrust/pbis-open/files/4019776/lsass.log)

**Steps to Reproduce**:
 1. Attempt to change a user password with the passwd command
 2. Expire a password and attempt to change the password
 3. Always returns passwd: Authentication token manipulation error

**Comment by dmorash-BT** [comment]
What does your pam configuration look like?

**Comment by rbest-bt** [comment]
Are both AssumeDefaultDomain and RequireMembershipOf in use?

**Comment by dvosbury** [comment]
rbest-bt, both AssumeDefaultDomain and RequireMembershipOf are in use.

> 
> 
> What does your pam configuration look like?
dmorash-BT,
Which PAM configuration files did you want to see?

**Comment by rbest-bt** [comment]
Try dropping the domain prefix from RequireMembershipOf (adawssy\). The group matching needs to match the same output as enum-groups.

**Comment by dvosbury** [comment]
I tried removing the domain prefix and then I’m unable to login. After adding it back I can login. I verified that the AssumeDefaultDomain true is set.

David Vosbury
SAAB Sensis Corporation
david.vosbury@saabsensis.com<mailto:david.vosbury@saabsensis.com>
Main: 315-234-3761
Cell: 315-751-2675

**Comment by rbest-bt** [comment]
Please upgrade to Active Directory Bridge Enterprise. If the issue still exists then please submit a ticket to our service team and we’ll have a look for you.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
