### ISSUE TITLE
Installing pbis-open-9-1-0-551.pkg on MacBook Pro MacOS Catalina version 10.15.2

### ISSUE THREAD

**Issue by jsmith-armada** [BeyondTrust/pbis-open#263]
I am attempting to get a MacBook to join to our Windows-based domain. Using the standard Apple method did not allow for domain logins. I tried to install the Installing pbis-open-9-1-0-551.pkg (MacBook Pro MacOS Catalina version 10.15.2) and after installation, there is nothing I can access to run the command to add to the domain., I am an Apple novice.

**Comment by dmorash-BT** [comment]
You'll need to use a terminal to join; check out the [Quick Start Guide](https://www.beyondtrust.com/docs/ad-bridge/documents/adb-quick-start-guide.pdf) it covers joining a domain.

**Comment by jsmith-armada** [comment]
The 2nd step to run the Ad Bridge Open .mpkg file is not able to be completed, because the file is actually pbis-open-9-1-0-551.pkg (.pkg file) and runs but does not actually install anything under Applications. Once the wizard is done, it does not bring up any other pages.

**Comment by dmorash-BT** [comment]
I don't believe anything shows up in Applications. Can you check that pbis got installed, i.e does /opt/pbis/bin/domainjoin-cli exist and can you run it?  If so, than you just need to follow the instructions to join a domain. 

I'll make a note to verify those instructions in the Quick Start Guide and update them as necessary for the mac.

**Comment by rbest-bt** [comment]
To connect to a domain the domainjoin-cli needs to be used from terminal. Please refer to either:
[Quick Start Guide](https://github.com/BeyondTrust/pbis-open/wiki/docs/adb-quick-start-guide.pdf) - section: Step 3: Join Active Directory
[Mac Admin Guide](https://github.com/BeyondTrust/pbis-open/wiki/docs/adb-mac-administration-guide-9-0.pdf) - section: Join a Mac Computer to an Active Directory Domain

**Comment by jsmith-armada** [comment]
I will try later today. My recollection is trying previously failed. I’ll need to verify the failure information and post.

Sent from my iPhone

James Smith
ARMADA
Information Technology Infrastructure
641 Alpha Drive<x-apple-data-detectors://0/0>
Pittsburgh, PA 15238<x-apple-data-detectors://0/0>
412 447-6012<tel:412%20447-6012> (P) | 412 354-1140<tel:412%20354-1140> (C)
24/7 Technical Assistance 412 406-5420<tel:412%20406-5420>
Support E-mail support@armada.net<mailto:support@armada.net>
jsmith@armada.net<mailto:jsmith@armada.net>| www.armada.net<http://www.armada.net/>




On Jan 6, 2020, at 11:28 AM, rbest-bt <notifications@github.com> wrote:

﻿

To connect to a domain the domainjoin-cli needs to be used from terminal. Please refer to either:
Quick Start Guide<https://protect-us.mimecast.com/s/0fjYC2krQqFLgEInlRjK?domain=github.com> - section: Step 3: Join Active Directory
Mac Admin Guide<https://protect-us.mimecast.com/s/pSSYC31vPrCjORIqUe4A?domain=github.com> - section: Join a Mac Computer to an Active Directory Domain

**Comment by jsmith-armada** [comment]
Continuing to get this error:
Incorrect access attempt
LW_ERROR_ACCESS_DENIED (code 0x00009cde)

James Smith
ARMADA
Information Technology Infrastructure
641 Alpha Drive, Pittsburgh, PA 15238
412 447 6012 (P) | 412 354 1140 (M)
jsmith@armada.net<mailto:jsmith@armada.net>| www.armada.net<http://www.armada.net/>

[cid:image002.png@01CED979.501EA960]

**Comment by jsmith-armada** [comment]
I have still been unable to get the installation to work. If there are any other suggestions, I would appreciate it.

James Smith
ARMADA
Information Technology Infrastructure
641 Alpha Drive, Pittsburgh, PA 15238
412 447 6012 (P) | 412 354 1140 (M)
jsmith@armada.net<mailto:jsmith@armada.net>| www.armada.net<http://www.armada.net/>

[cid:image001.png@01D5D511.D28835C0]

From: Smith, James
Sent: Tuesday, January 7, 2020 10:09 AM
To: BeyondTrust/pbis-open <reply@reply.github.com>
Cc: BeyondTrust/pbis-open <pbis-open@noreply.github.com>; Author <author@noreply.github.com>
Subject: RE: [BeyondTrust/pbis-open] Installing pbis-open-9-1-0-551.pkg on MacBook Pro MacOS Catalina version 10.15.2 (#263)

Continuing to get this error:
Incorrect access attempt
LW_ERROR_ACCESS_DENIED (code 0x00009cde)

James Smith
ARMADA
Information Technology Infrastructure
641 Alpha Drive, Pittsburgh, PA 15238
412 447 6012 (P) | 412 354 1140 (M)
jsmith@armada.net<mailto:jsmith@armada.net>| www.armada.net<http://www.armada.net/>

[cid:image002.png@01CED979.501EA960]

**Comment by rbest-bt** [comment]
Make sure you have both local admin rights to make the changes to the system and a domain admin account to perform the join.

**Comment by jsmith-armada** [comment]
I have both.

James Smith
ARMADA
Information Technology Infrastructure
641 Alpha Drive, Pittsburgh, PA 15238
412 447 6012 (P) | 412 354 1140 (M)
jsmith@armada.net<mailto:jsmith@armada.net>| www.armada.net<http://www.armada.net/>

[cid:image001.png@01D5D515.3C189090]

**Comment by rbest-bt** [comment]
pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
