### ISSUE TITLE
Samba authentication stops working after a while

### ISSUE THREAD

**Issue by pfcapp** [BeyondTrust/pbis-open#265]
Hi,

Have a RHEL 7.6 box (actually 2 of them) running PBIS 8.7.0.478.  Samba version 4.8.3 is installed.  The samba-interop script has been executed.  All works fine.

Days later Samba authentication stops working.  Restarting either smb or lwsmd doesn't fix the problem.

I need to rerun the samba-interop script and restart smb for it to work again.  Through all this normal PBIS auth works fine.

Any idea what I should be looking at to solve this?

**Comment by pfcapp** [comment]
Update, I don't even have to restart smb to fix the problem, just a rerun of the samba-interop script will do it.

**Comment by rbest-bt** [comment]
Update to 9.1.0 as it has fixes for the latest versions of Samba. See the [9.1.0 release notes](https://github.com/BeyondTrust/pbis-open/releases/tag/9.1.0)

- Addresses issues with the latest version of winbind 4.6.2+ when integrating with Samba

**Comment by pfcapp** [comment]
Just getting back to this problem.  Still happening with 9.1.0.551.  Same thing, Samba stops working every couple days, run the interop script and its fixed.  Any idea where the problem could be?  What I should be looking at?

**Comment by rbest-bt** [comment]
Sounds like the secrets file is getting updated by smb. Make sure to set the machine password timeout in the smb.conf.
> machine password timeout = 0
