### ISSUE TITLE
AD login OK, but asks for local account password when updating OS through GUI

### ISSUE THREAD

**Issue by cloud81** [BeyondTrust/pbis-open#266]
**Version**: 9.1.0.551
**OS/Distro**: Ubuntu desktop 18.04
**Issue/Impact**:
I can login with AD and all works fine, but when I try to install updates with GUI (through update-manager) it asks me for the **local** account password instead of the password of the user I'm logged in (my domain user, that is one of the admins of the domain).
 1. systemctl status lwsmd.service
lwsmd.service - BeyondTrust AD Bridge Service Manager
   Loaded: loaded (/lib/systemd/system/lwsmd.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-01-10 11:40:59 CET; 3h 38min ago
  Process: 1138 ExecStart=/opt/pbis/sbin/lwsmd --start-as-daemon (code=exited, status=0/SUCCESS)
 Main PID: 1306 (lwsmd)
    Tasks: 179 (limit: 4915)
   CGroup: /system.slice/lwsmd.service
           ├─ 1306 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─ 1329 lw-container lwreg
           ├─ 1418 lw-container eventlog
           ├─ 1661 lw-container netlogon
           ├─ 1732 lw-container lwio
           ├─ 2016 lw-container reapsysl
           └─13334 lw-container lsass
 2. /opt/pbis/bin/lwsm list
lwreg          running (container: 1329)
dcerpc         stopped
eventlog       running (container: 1418)
lsass          running (container: 13334)
lwio           running (container: 1732)
netlogon       running (container: 1661)
rdr            running (io: 1732)
reapsysl       running (container: 2016)
usermonitor    stopped
 3. /opt/pbis/domainjoin-cli query
Error: LW_ERROR_ACCESS_DENIED [code 0x00009cde]

Incorrect access attempt

**IF I USE SUDO IT WORKS CORRECTLY.**

 4. pbis status
```
LSA Server Status:

Compiled daemon version: 9.1.0.551
Packaged product version: 9.1.551.2
Uptime:        0 days 2 hours 50 minutes 53 seconds

[Authentication provider: lsa-activedirectory-provider]

	Status:        Online
	Mode:          Un-provisioned
	Domain:        xxx
	Domain SID:    S-1-5-21-3265065474-103705482-3169833920
	Forest:        xxx
	Site:          Nome-predefinito-primo-sito
	Online check interval:  300 seconds
	[Trusted Domains: 1]

	[Domain: xxx]

		DNS Domain:       xxx
		Netbios name:     xxx
		Forest name:      xxx
		Trustee DNS name: 
		Client site name: Nome-predefinito-primo-sito
		Domain SID:       S-1-5-21-3265065474-103705482-3169833920
		Domain GUID:      dda0c8f9-26af-4298-94cd-82954e737497
		Trust Flags:      [0x001d]
		                  [0x0001 - In forest]
		                  [0x0004 - Tree root]
		                  [0x0008 - Primary]
		                  [0x0010 - Native]
		Trust type:       Up Level
		Trust Attributes: [0x0000]
		Trust Direction:  Primary Domain
		Trust Mode:       In my forest Trust (MFT)
		Domain flags:     [0x0001]
		                  [0x0001 - Primary]

		[Domain Controller (DC) Information]

			DC Name:              xxx
			DC Address:           192.168.x.xxx
			DC Site:              Nome-predefinito-primo-sito
			DC Flags:             [0x000031fc]
			DC Is PDC:            no
			DC is time server:    yes
			DC has writeable DS:  yes
			DC is Global Catalog: yes
			DC is running KDC:    yes

		[Global Catalog (GC) Information]

			GC Name:              xxx
			GC Address:           192.168.x.xxx
			GC Site:              Nome-predefinito-primo-sito
			GC Flags:             [0x000031fd]
			GC Is PDC:            yes

```
5. /opt/pbis/bin/enum-users
IT WORKS.
 6. attach logs
Can't produce logs with commands provided.

**Output/Error**:
Jan 10 09:24:33 xxx lsass: [LwKrb5GetTgtImpl /builder/src-git/Platform/src/linux/lwadvapi/threaded/krbtgt.c:346] KRB5 Error code: -1765328360 (Message: Preauthentication failed)
Jan 10 09:24:33 xxx lsass: [lsass] Failed to authenticate user (name = 'xxx') -> error = 40022, symbol = LW_ERROR_PASSWORD_MISMATCH, client pid = 8665

**Comment by rbest-bt** [comment]
This sounds correct. The "domain user, that is one of the admins of the domain" is not the same thing as a local admin. This account would not have the rights to perform an update. Sudo will elevate their rights to allow them to perform the update but the gui does not tie into sudo.

**Comment by cloud81** [comment]
Ok, so I will use the local account to perform the updates. Thanks

**Comment by Miene-Lx** [comment]
I got same issue and solved it with editing this file on Ubuntu 18.04:
/var/lib/polkit-1/localauthority/10-vendor.d/com.ubuntu.desktop.pkla

(Modify sections like below:)

[Mounting, checking, etc. of internal drives]
Identity=unix-group:admin;unix-group:domain^users
...
...
[Setting the clock]
Identity=unix-group:admin;unix-group:domain^users
...
...
[Adding or changing system-wide NetworkManager connections]
Identity=unix-group:admin;unix-group:domain^users
...
...
[Update already installed software]
Identity=unix-group:admin;unix-group:domain^users
...
...
[Printer administration]
Identity=unix-group:lpadmin;unix-group:admin;unix-group:domain^users
...
...

Good luck !

**Comment by sylvainpasquet** [comment]
you need to grant admin right to your AD User, in ubuntu user manager.

**Comment by cloud81** [comment]
> you need to grant admin right to your AD User, in ubuntu user manager.

Hi, this was the first thing I just tried but I can't modify the admin rights for AD users, it is greyed out:
![image](https://user-images.githubusercontent.com/16636044/73001755-3d26d300-3e03-11ea-8e63-74aa0c4d5ff0.png)

**Comment by sylvainpasquet** [comment]
try sudo usermod -aG sudo "YOURAD\your.login"

**Comment by cloud81** [comment]
> try sudo usermod -aG sudo "YOURAD\your.login"

great!! it works like a charm :-)

**Comment by sylvainpasquet** [comment]
cool, next step have my "loosing session" bug ;-) lol

**Comment by mmiat** [comment]
I've a similar problem but it's a gnome issue
if I'm logged in with a standard user, gnome doesnt ask me which user to use to grant authorization. I mean, I'm in a domain and I've some domain admins, but gnome ask me local administrator password. KDE and Cinnamon don't have this issue
do anyone know how to fix?

**Comment by rbest-bt** [comment]
pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
