### ISSUE TITLE
Losing session in Ubuntu 19.10 / 18.04

### ISSUE THREAD

**Issue by sylvainpasquet** [BeyondTrust/pbis-open#267]
**Version**: 
Compiled daemon version: 9.1.0.551
Packaged product version: 9.1.551.2
**OS/Distro**: Ubuntu desktop 19.10 - unity desktop
**Issue/Impact**: Major
*Note: replace content with your own*
When reporting an issue it's important that we have as much detail as you can provide. The following is a list of commands to check.
 1. systemctl status lwsmd.service

● lwsmd.service - BeyondTrust AD Bridge Service Manager
   Loaded: loaded (/lib/systemd/system/lwsmd.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-01-23 09:04:59 CET; 7h ago
  Process: 1332 ExecStart=/opt/pbis/sbin/lwsmd --start-as-daemon (code=exited, status=0/SUCCESS)
 Main PID: 1354 (lwsmd)
    Tasks: 317 (limit: 4915)
   Memory: 38.8M
   CGroup: /system.slice/lwsmd.service
           ├─1354 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─1397 lw-container lwreg
           ├─1481 lw-container eventlog
           ├─1527 lw-container netlogon
           ├─1575 lw-container lwio
           ├─1627 lw-container lsass
           └─1689 lw-container reapsysl

 2. /opt/pbis/bin/lwsm list
lwreg          running (container: 1397)
dcerpc         stopped
eventlog       running (container: 1481)
lsass          running (container: 1627)
lwio           running (container: 1575)
netlogon       running (container: 1527)
rdr            running (io: 1575)
reapsysl       running (container: 1689)
usermonitor    stopped

 3. /opt/pbis/domainjoin-cli query
 4. pbis status
LSA Server Status:

Compiled daemon version: 9.1.0.551
Packaged product version: 9.1.551.2
Uptime:        0 days 7 hours 4 minutes 11 seconds

[Authentication provider: lsa-activedirectory-provider]

	Status:        Online
	Mode:          Un-provisioned
	Domain:        MIOS.XXX.DOMAINS
	Domain SID:    S-1-5-21-2855029267-296984015-312817316
	Forest:        mios.xxx.domains
	Site:          Default-First-Site-Name
	Online check interval:  300 seconds
	[Trusted Domains: 1]

	[Domain: MIOSAD01]

		DNS Domain:       mios.xxx.domains
		Netbios name:     MIOSAD01
		Forest name:      mios.xxx.domains
		Trustee DNS name: 
		Client site name: Default-First-Site-Name
		Domain SID:       S-1-5-21-2855029267-296984015-312817316
		Domain GUID:      00000000-0000-0000-0000-000000000000
		Trust Flags:      [0x001d]
		                  [0x0001 - In forest]
		                  [0x0004 - Tree root]
		                  [0x0008 - Primary]
		                  [0x0010 - Native]
		Trust type:       Up Level
		Trust Attributes: [0x0000]
		Trust Direction:  Primary Domain
		Trust Mode:       In my forest Trust (MFT)
		Domain flags:     [0x0001]
		                  [0x0001 - Primary]

		[Domain Controller (DC) Information]

			DC Name:              WinSrvAd02.mios.xxxx.domains
			DC Address:           10.0.1.11
			DC Site:              Default-First-Site-Name
			DC Flags:             [0x0001f1fc]
			DC Is PDC:            no
			DC is time server:    yes
			DC has writeable DS:  yes
			DC is Global Catalog: yes
			DC is running KDC:    yes

		[Global Catalog (GC) Information]

			GC Name:              WinSrvAd01.mios.xxxx.domains
			GC Address:           10.0.1.10
			GC Site:              Default-First-Site-Name
			GC Flags:             [0x0001f3fd]
			GC Is PDC:            yes
			GC is time server:    yes
			GC has writeable DS:  yes
			GC is running KDC:    yes

 5. /opt/pbis/bin/enum-users
 6. attach logs
  - /opt/pbis/bin/lwsm set-log-target -p lsass -  file /tmp/lsass.log
  - /opt/pbis/bin/lwsm set-log-level -p lsass - debug
  - attach log

**Output/Error**:

**Steps to Reproduce**:
Sometimes, ubuntu lose the AD user and dont propose anymore the login screen ( if we dont have any local user ), we need to recreate a local user for have the login screen again and after we can login again and retreive the desktop.

-> Boot and no login screen, start directly gnome-initial-setup like we have no user at all.
-> Need to create a local user to have the login screen again.
-> Relogin with AD user and it work again.

We have the problem on all ubuntu installed with pbis open.

What can I do to avoid this problem ? We would like to keep the setup with no local user and only have the AD User in login screen.

Thanks.

**Comment by sylvainpasquet** [comment]
Hello, i have trigger how to reproduce the loosing session bug, you need a laptop.
Let this laptop open until the battery is empty, the laptop will shutdown and at reboot you dont have the session anymore in login manager.

For the moment, the only solution i have, is to have a "recovery account", because if the AD session is the only one on the laptop, at reboot we have the 'initial-gnome-setup' but no login manager.
If we have a remaining local account, we can click on "not in list" button and enter the login ADDOMAIN\user.

This bug is very frustrating.

Thanks

**Comment by rbest-bt** [comment]
Please upgrade to Active Directory Bridge Enterprise. If the issue still exists then please submit a ticket to our service team and we’ll have a look for you.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
