### ISSUE TITLE
Cannot Login with AD user 

### ISSUE THREAD

**Issue by amalcp** [BeyondTrust/pbis-open#27]
Hi ,

I have installed and configured PowerBroker Identity Services Open 8.5.0.153 successfully but I cannot login to the ubuntu desktop using the AD user.

Then I have issued a command 

   $ _domainjoin-cli query_

I got

  Name = acp-box16
  Domain = DOMAIN.LOCAL
  Distinguished Name = CN=ACP-BOX16,CN=Computers,DC=DOMAIN,DC=local

Also, the computer name is added to the active directory.

I'm not sure why I cannot login to the desktop with this AD user.

Should I configure anything on AD itself or? Any help will be appreciated.

Thanks 
Amal

**Comment by RBoulton-BT** [comment]
Running "pbis status" will give you an indication of whether the agent is joined correctly and able to communicate with AD.

If that looks good I'd check that "id domain\\user" command returns information you'd expect for your user.

You can also use the "pbis authenticate-user" command to confirm the actual underlying authentication is successful.

I think /var/log/messages is the default log location so you may also see something useful there.

**Comment by amalcp** [comment]
Thanks for the quick reply.

I have issued **pbis status** and it looks good.

But,
_root@acp-box16:~#  id domain\user
id: ‘domainuser’: no such user_

_root@acp-box16:~# pbis authenticate-user --user ubuntu --domain DOMAIN.local_
Password:*****
Success

 Still, it saying invalid password, please ty again

I couldn't find any PBIS related issues on syslog

**Comment by RBoulton-BT** [comment]
I keep forgetting this issues markup text loses the double \\\\. Make sure you're escaping your \ on the command line.

**Comment by amalcp** [comment]
Appreciate your help, But I didn't get any positive response 

_root@acp-box16:~# id domain\\user
id: ‘domainuser\\user’: no such user_

I have followed the below steps to **AD login settings**

- sudo /opt/pbis/bin/config UserDomainPrefix ubuntu
- sudo /opt/pbis/bin/config AssumeDefaultDomain true
- sudo /opt/pbis/bin/config LoginShellTemplate /bin/bash
- sudo /opt/pbis/bin/config HomeDirTemplate %H/%U
- sudo /opt/pbis/bin/config RequireMembershipOf ubuntu\\DomainUsers

I was wondering whether I have to change something on this?

**Comment by RBoulton-BT** [comment]
I was avoiding using real usernames in case they were sensitive but this is getting confusing. So I'm not sure if your user "ubuntu" is just an example or a real user. If it's the real username and not the Netbios domain name then it shouldn't be set as  UserDomainPrefix. The UserDomainPrefix is what is prepended to the username you type in, so it should be your netbios domain name.

So if your domain is DOMAIN.local with a netbios name DOMAIN, then the standard name for your AD user would be DOMAIN\\ubuntu. If you set "AssumeDefaultDomain true" then you can just use ubuntu and PBIS will automatically prepend DOMAIN\\. With a "UserDomainPrefix ubuntu" you will be getting ubuntu\\ubuntu.

To get an idea of which users are available for logon you can either try "getent passwd" or "pbis enum-users"

**Comment by amalcp** [comment]
Perfect. I got mistaken on the above commands and I have corrected with the help of your explanations.
I do really appreciate your time and support.

We, people, don't know the pbis commands like **getent passwd** or **pbis enum-users**
So, can you please help me to get basic troubleshooting commands for this AD-Linux integration? This will help me to fix issues in future

Thanks

**Comment by RBoulton-BT** [comment]
The command "getent passwd" calls the name service switch to list all the users that the Linux system recognizes. If you type this command at the command prompt you should see your local and AD users listed with the names you to type at the logon prompt. 

The command "pbis enum-users" is similar and will list the AD users PBIS recognizes. It talks directly with the PBIS services rather than the name service switch, so if this works but getent passwd doesn't we know there's an issue with the integration.

**Comment by dodinh** [comment]
We have the same problem:

- _pbis status_ shows it is connected
- _pbis authenticate-user --user myusername_ works
- _id myusername_: id: myusername: no such user

We have _UserDomainPrefix_ and _AssumeDefaultDomain_ set as well.

**Comment by dodinh** [comment]
When trying to connect via ssh using _myusername_, this gets logged in syslog:
```
May 31 10:39:50 myserver lsass: [LwKrb5GetTgtImpl /builder/src-git/Platform/src/linux/lwadvapi/threaded/krbtgt.c:276] KRB5 Error code: -1765328360 (Message: Preauthentication failed)
May 31 10:39:50 myserver lsass: [lsass] Failed to authenticate user (name = 'myusername') -> error = 40022, symbol = LW_ERROR_PASSWORD_MISMATCH, client pid = 15277
```

**Comment by AdminM1** [comment]
The same problem with one PC:
-     **pbis status** shows it is connected
-     **pbis authenticate-user --user myusername** works
-     **id myusername** -- "id: myusername: no such user"
-     **getent passwd** show only local users from /etc/passwd

**Comment by hatchetation** [comment]
We're troubleshooting an intermittent issue (on 8.5.3.293) with the same symptoms: status and queries with pbis commands looks OK and normal, but users aren't seen on newly-bootstrapped servers. 

The cause seems to be `/etc/nsswitch.conf` not being modified during the install process to activate lsass. On problematic servers, the file is stock:

```
# /etc/nsswitch.conf

passwd:         compat
group:          compat 
shadow:         compat
```

vs working:
```
# /etc/nsswitch.conf

passwd:         compat lsass
group:          compat lsass
shadow:         compat
```

Our bootstrap process is highly automated (cloud VMs), so I'm not sure what the root cause may be. Yesterday, everything worked fine. Today (same vanilla base ubuntu 14.04 image, same configuration/automation), all servers so far are failing. 

Perhaps there's some interaction with external systems during the install process which can silently timeout, or is timing dependant in some other way? Captured output looks entirely ordinary, all commands succeed with exit code of zero.

**Comment by bartwallace** [comment]
I'm having similar issue with version 8.5.4.334 amd64.

**uname -a**
- Linux 4.4.0-81-generic #104-Ubuntu SMP Wed Jun 14 08:17:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**cat /etc/nsswitch.conf**
`# /etc/nsswitch.conf
passwd:         compat lsass
group:          compat lsass
shadow:         compat
gshadow:        files

hosts:          files mdns4_minimal [NOTFOUND=return] dns myhostname
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis
`
**pbis status** - shows it is connected
**pbis authenticate-user --user myusername --domain mydomain** - works
**id myusername** -- "id: myusername: no such user"
**id msrs\\myusername** - works
**getent passwd** shows all AD users

**Comment by sfitsp** [comment]
hello everyone
I'm also facing same issue I followed the following steps

 Fresh install Ubuntu 16.04 and follow the following steps.
    
    1  apt-get upgrade
    2  apt-get dist-upgrade
    3  reboot
    4  nano /etc/avahi/avahi-daemon.conf
    5  apt-get install ssh
    6  wget -O - http://repo.pbis.beyondtrust.com/apt/RPM-GPG-KEY-pbis|sudo apt-key add - 
    7  wget -O /etc/apt/sources.list.d/pbiso.list http://repo.pbis.beyondtrust.com/apt/pbiso.list 
    8  apt-get update
    9  apt-get install pbis-open 
   10  service avahi-daemon restart
   11  sudo domainjoin-cli join smdomain.com administrator #close domainjoin-gui
   12  service ssh restart
   13  /opt/pbis/bin/config UserDomainPrefix smdomain
   14  /opt/pbis/bin/config AssumeDefaultDomain true
   15  /opt/pbis/bin/config LoginShellTemplate /bin/bash
   16  /opt/pbis/bin/config HomeDirTemplate %H/%U
   17  /opt/pbis/bin/config RequireMembershipOf smdomain\\linux
   18  nano /usr/share/lightdm/lightdm.conf.d/50-unity-greeter.conf 
   19  reboot

and after reboot I wasn't able to login with domain credential so I logged in back through local system user and run command "pbis status" it shows unknown then I tried it by restarting "lwsmd service" and the miracle is pbis status shows online, I have logged off from local user and login through domain user successfully BUT
after every restart I'm doing same thing...

is there any permanent solution?????

I hope you'll help,
please help.. your help will highly appreciated!
Thank you !!!

**Comment by rbest-bt** [comment]
I'm able to reproduce this issue and I'm investigating

**Comment by sfitsp** [comment]
@rbest-bt Thanks for the instant help.. I'm also trying,, please let me know if it's solved

**Comment by bartwallace** [comment]
I discovered after a reboot and upgrade that my /opt/pbis/bin/config settings were not set.  I reset those configs and have been good since.  I would check those and make sure they are written properly.

**Comment by rbest-bt** [comment]
When it's in a bad state check out the lwsmd status. 
`systemctl status lwsmd.service`

If there is an enumeration error, then add trustEnumerationWait to your domainjoin command
`sudo domainjoin-cli join --trustEnumerationWaitSeconds 30 smdomain.com administrator`

See Issue #6 for more information

**Comment by rbest-bt** [comment]
Note to everyone: There is an option in the domainjoin command to set assumeDefaultDomain. Saves you from needing to set it via config tool
`domainjoin-cli join --assumeDefaultDomain yes --trustEnumerationWaitSeconds 45 domain.local administrator`

**Comment by sfitsp** [comment]
Yes I have seen Issue #6  but not solved see the output  systemctl status lwsmd.service 
![screenshot from 2017-07-12 00-09-01](https://user-images.githubusercontent.com/29240393/28084632-d1d30010-6696-11e7-9225-3566e317c96b.png)

**Comment by rbest-bt** [comment]
try adding more time to trustEnumerationWaitSeconds. 45 or 60 seconds

**Comment by rbest-bt** [comment]
@dodinh LW_ERROR_PASSWORD_MISMATCH can get generated when you enter the correct password but ssh does not like a setting of the user. This is a known issue in ssh and I've seen it when the users shell is not available on the system.

**Comment by sfitsp** [comment]
Thank you so much @rbest-bt  
I think my issue is resolved I have tried and restarted couple of times and its showing the domain users that I logged.. what was the causes can you please share?

**Comment by rbest-bt** [comment]
We have an issue with systemd between the lwsmd and network services starting. lwsmd is trying to enumerate the domain before the network is up. We are still investigating a solution that will account for offline machine. trustEnumerationWaitSeconds is just adding a set delay.

**Comment by sfitsp** [comment]
the issue is still there 

![screenshot from 2017-07-12 02-08-51](https://user-images.githubusercontent.com/29240393/28089777-bafcc6a8-66a7-11e7-93cb-dc6caa424f5c.png)

**Comment by flegance** [comment]
Having a similar issue as dodinh: getting **LW_ERROR_PASSWORD_MISMATCH** in the lsass logs, in the same time, **pbis authenticate-user** works just fine. Seems like the issue is related to ssh not able to create a session for the user, like rbest-bt described above, just don't know how to troubleshoot this issue

**Comment by rbest-bt** [comment]
@sfitsp - Try increasing the trustEnumerationWaitSeconds again. We are looking into a better solution in Issue 6

@flegance - please create a new issue for this. For now try and confirm the users environment and make sure their options are available. Also increase the logging on lsass. Wait to log the issue till later today as I'm working on a template for logging issue.

**Comment by flegance** [comment]
thank you, @rbest-bt . We just got the issue resolved, hence I'm not going to create a new one for this. The issue was with **/etc/ssh/sshd_config** - we had **AllowedUser** setting configured and it was restricting everybody else. The way we found it out - looked into the **/var/log/secure** log, and saw this:
**User %username% from %hostname% not allowed because not listed in AllowUsers**
**input_userauth_request: invalid user**
we already had **lsass** in the debug logging level, and the only thing we were getting from it was:
**pre-authentication failed** and **LW_ERROR_PASSWORD_MISMATCH**
which was pretty misleading.
So, you were right about checking other options as PBIS was configured properly

**Comment by sfitsp** [comment]
@rbest-bt Thank youi It's working but I think its not a proper solution because we have wait for login and sometimes needs to restart...

**Comment by rbest-bt** [comment]
Yes we are working on a better fix. Follow Issue 6 for updates

**Comment by sfitsp** [comment]
team the following error shows by lwsmd

Jul 21 01:18:29 ubuntu lsass[905]: [lsass] Fatal error enumerating trusts for domain SMDOMAIN.COM. Error was ERROR_GEN_FAILURE (31)

**Comment by vijesh-raj** [comment]
HI all, 

I have a domain controller installed with 2016 server and having ubuntu\windows machines as clients. I have integrated ubuntu machines using PBIS. My question is what can I apply the same group policy configured over domain controller to Ubuntu machines? Or do  I need to have more configurations on PBIS

**Comment by rbest-bt** [comment]
Refer to answer in #129

**Comment by pankaj9492** [comment]
I am facing error, can you please have look.....i am using over ubuntu 18

unicode@client1:~$ sudo /opt/pbis/bin/domainjoin-cli --loglevel info --logfile .  join UNICODESYSTEMS.IN Administrator
20190116194506:INFO:Domainjoin invoked with the join command (remaining arguments will be printed later):
20190116194506:INFO:    [/opt/pbis/bin/domainjoin-cli]
20190116194506:INFO:    [--loglevel]
20190116194506:INFO:    [info]
20190116194506:INFO:    [--logfile]
20190116194506:INFO:    [.]
20190116194506:INFO:    [join]
20190116194506:INFO:Validating join options.
20190116194506:INFO:Domainjoin invoked with 2 arg(s) to the join command:
20190116194506:INFO:    [UNICODESYSTEMS.IN]
20190116194506:INFO:    [Administrator]
20190116194506:INFO:Adding client10 (fqdn client10.unicodesystems.in) to /etc/hosts ip 127.0.1.1, removing client10, client10.unicodesystems.in, client10, client10.unicodesystems.in
20190116194506:INFO:Reading krb5 file /tmp/likewisetmpIGeNFj/etc/krb5.conf
20190116194506:INFO:Reading nsswitch file /etc/nsswitch.conf
20190116194506:INFO:Reading krb5 file /tmp/likewisetmpWlSUFQ/etc/krb5.conf
20190116194506:INFO:Distro Version 18.04
20190116194506:INFO:Found config file /etc/ssh/sshd_config
20190116194506:INFO:Found binary /usr/sbin/sshd
20190116194506:INFO:Reading ssh file /etc/ssh/sshd_config
20190116194506:INFO:Found open sshd version 7.6.-1p1
20190116194506:INFO:Testing option ChallengeResponseAuthentication
20190116194506:INFO:Testing option UsePAM
20190116194506:INFO:Testing option PAMAuthenticationViaKBDInt
20190116194506:INFO:Option PAMAuthenticationViaKBDInt not supported
20190116194506:INFO:Testing option KbdInteractiveAuthentication
20190116194506:INFO:Testing option GSSAPIAuthentication
20190116194506:INFO:Option GSSAPIAuthentication supported
20190116194506:INFO:Testing option GSSAPICleanupCredentials
20190116194506:INFO:Found config file /etc/ssh/ssh_config
20190116194506:INFO:Found binary /usr/bin/ssh
20190116194506:INFO:Reading ssh file /etc/ssh/ssh_config
20190116194506:INFO:Testing option GSSAPIAuthentication
20190116194506:INFO:Option GSSAPIAuthentication supported
20190116194506:INFO:Testing option GSSAPIDelegateCredentials
20190116194506:INFO:Option GSSAPIDelegateCredentials supported
Joining to AD Domain:   UNICODESYSTEMS.IN
With Computer DNS Name: client10.unicodesystems.in

Administrator@UNICODESYSTEMS.IN's password: 
20190116194512:INFO:Using user entered password
20190116194512:INFO:Running module join

Error: ERROR_CONNECTION_REFUSED [code 0x000004c9]


20190116194526:ERROR:ERROR_CONNECTION_REFUSED [ERROR_CONNECTION_REFUSED]



Stack Trace:
/builder/src-git/Platform/src/linux/domainjoin/domainjoin-cli/src/main.c:1640
/builder/src-git/Platform/src/linux/domainjoin/domainjoin-cli/src/main.c:894
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djmodule.c:356
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djauthinfo.c:858
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djauthinfo.c:1271

**Comment by pankaj9492** [comment]
yes domain is resolving 

unicode@client1:~$ nslookup
> 192.168.1.232
232.1.168.192.in-addr.arpa	name = ad.unicodesystems.in.
> unicodesystems.in
Server:		192.168.1.232
Address:	192.168.1.232#53

Name:	unicodesystems.in
Address: 192.168.1.232
> ad.unicodesystems.in
Server:		192.168.1.232
Address:	192.168.1.232#53

Name:	ad.unicodesystems.in
Address: 192.168.1.232
> ^Cunicode@client1:~$ 


![image](https://user-images.githubusercontent.com/18568207/51255497-5f546c80-19c9-11e9-9e13-49614a6ea401.png)

**Comment by Mohiyoddin** [comment]
I am working as system admin and this is the best way for joining domain. here you can find the full installation file with setup by setup. download the pbis file and save it in download folder. 


Installation of PBIS and joining domain in ubuntu 14.04 & 16.04 ( may be could work for 18.04) 

* sudo apt-get update

* sudo apt-get upgrade

* sudo apt-get install ssh

* Download the file and save it in downloads folder

* cd Downloads/

* sudo chmod +x pbis-open-8.0.0.2016.linux.x86_64.deb.sh or ( file name )

* sudo ./pbis-open-8.0.0.2016.linux.x86_64.deb.sh (or file name)

           (In ubuntu 18.04 change 'nameserver ip' not for ubuntu 14.04 & 16.04 version)

* sudo nano /etc/resolv.conf 

nameserver ( your domain server IP )
search ( your domain name )

* sudo domainjoin-cli join dom.example.com Administrator ( close GUI login )

my domain name is - example 
and full name           - dom.example.com

* sudo /opt/pbis/bin/config UserDomainPrefix example
* sudo /opt/pbis/bin/config AssumeDefaultDomain true
* sudo /opt/pbis/bin/config LoginShellTemplate /bin/bash
* sudo /opt/pbis/bin/config HomeDirTemplate %H/%U

* sudo apt-get update

* sudo nano /etc/pam.d/common-session

*change the line that reads:

session sufficient pam_lsass.so

to

session [success=ok default=ignore] pam_lsass.so

if its not found the (session sufficient pam_lsass.so) run this command 

* sudo pam-auth-update

Finally edit lightdm configuration file by executing the following command

* sudo nano /usr/share/lightdm/lightdm.conf.d/50-unity-greeter.conf

delete everything and add this lines.

[SeatDefaults]
greeter-session=unity-greeter
allow-guest=false
        greeter-show-remote-login=false
        greeter-show-manual-login=true

* sudo reboot

if you got error - "no user found" just run this command.
 
* sudo service lwsmd restart


Uninstalling PBIS

* sudo /opt/pbis/bin/domainjoin-cli leave

* sudo /opt/pbis/bin/uninstall.sh uninstall



add this command extra for ubuntu 16.04

* sudo nano /etc/default/grub


find this

GRUB_CMDLINE_LINUX=""

change this to 

GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"

* sudo update-grub


* sudo reboot

**Comment by Mohiyoddin** [comment]
What error you getting?
