### ISSUE TITLE
Microsoft will be enforcing LDAP signing in March, 2020.

### ISSUE THREAD

**Issue by b3b0** [BeyondTrust/pbis-open#272]
This is likely going to be considered a duplicate of [Issue #162](https://github.com/BeyondTrust/pbis-open/issues/162).

In short time, [Microsoft will require all LDAP communications to be signed.](https://support.microsoft.com/en-us/help/4520412/2020-ldap-channel-binding-and-ldap-signing-requirement-for-windows) How can we prepare for this?

**Comment by rbest-bt** [comment]
Nothing is required. Follow Mircosoft's guide to enforce it now on your DCs and ADB will work fine. This has been enabled in our testing labs with no impact. LDAPS is not required for [ADV190023](https://support.microsoft.com/en-us/help/4520412/2020-ldap-channel-binding-and-ldap-signing-requirement-for-windows).

**Comment by b3b0** [comment]
Thank you!
