### ISSUE TITLE
Our Bomgar support portal show this error "ERR_CERT_REVOKED"

### ISSUE THREAD

**Issue by imichaelaustin** [BeyondTrust/pbis-open#274]
I have verified that our wild card cert is valid and there are not errors or warnings in the appliance console.

**Comment by dmorash-BT** [comment]
This is the GitHub project for the open-source portion of AD Bridge (nee pbis-open). It is not related to any other BeyondTrust or Bomgar products.  You should contact BeyondTrust support.
