### ISSUE TITLE
Problem with sftp Chroot

### ISSUE THREAD

**Issue by rokitoh** [BeyondTrust/pbis-open#275]
**Version**: 9.1.0-551
**OS/Distro**: CentOS Linux release 7.7.1908
**Issue/Impact**:

Hi!!

I have a problem with PBIS Open, when I configure a SFTP Chroot with user Active Directory and the user connected change the username used Capital letters the  SFTP Jail  breaks.

For example: 

sftp srv_usersftp@10.10.4.209
Password:
Connected to srv_usersftp@10.10.4.209.
sftp> ls
public  
sftp> cd /
sftp> ls
public  
sftp> 

user with Capital letters: 

 sftp srv_usersFTP@10.10.4.209
Password:
Connected to srv_usersFTP@10.10.4.209.
sftp> ls
public  
sftp> cd /
sftp> ls
bin    boot   dev    etc    home   lib    lib64  media  mnt    opt    proc   root   run    sbin   srv    sys    tmp    usr    var    
sftp> 

The configurate of the PBIS: 

 /opt/pbis/bin/config --dump
AllowDeleteTo ""
AllowReadTo ""
AllowWriteTo ""
MaxDiskUsage 104857600
MaxEventLifespan 90
MaxNumEvents 100000
DomainSeparator "\\"
SpaceReplacement "^"
EnableEventlog false
SaslMaxBufSize 16777215
Providers "ActiveDirectory"
DisplayMotd false
PAMLogLevel "error"
UserNotAllowedError "Access denied"
NssApplyAccessControl false
AssumeDefaultDomain true
CreateHomeDir true
CreateK5Login true
SyncSystemTime true
TrimUserMembership true
LdapSignAndSeal false
LogADNetworkConnectionEvents true
NssEnumerationEnabled true
NssGroupMembersQueryCacheOnly true
NssUserMembershipQueryCacheOnly false
RefreshUserCredentials true
CacheEntryExpiry 14400
DomainManagerCheckDomainOnlineInterval 300
DomainManagerUnknownDomainCacheTimeout 3600
MachinePasswordLifespan 2592000
ServicePrincipalName "host"
MemoryCacheSizeCap 0
HomeDirForceLowercase false
HomeDirPrefix "/home"
HomeDirTemplate "%H/%U"
RemoteHomeDirTemplate ""
HomeDirUmask "022"
LoginShellTemplate "/bin/false"
SkeletonDirs "/etc/skel"
UserDomainPrefix ""
DomainManagerIgnoreAllTrusts false
DomainManagerIncludeTrustsList
DomainManagerExcludeTrustsList
RequireMembershipOf "AD.TEST\\FTP_PRUEBA-SFTP_DEV"
Local_AcceptNTLMv1 true
Local_HomeDirTemplate "%H/local/%D/%U"
Local_HomeDirUmask "022"
Local_LoginShellTemplate "/bin/false"
Local_SkeletonDirs "/etc/skel"
UserMonitorCheckInterval 1800
LsassAutostart true
EventlogAutostart true
BlacklistDC

The configuration of the ssh: 

Subsystem sftp internal-sftp
Match user srv_usersftp
ChrootDirectory %h
X11Forwarding no
AllowTcpForwarding no
ForceCommand internal-sftp
KbdInteractiveAuthentication yes

Do we know how could  solve the FIX?
Regards!

**Comment by rbest-bt** [comment]
Please upgrade to Active Directory Bridge Enterprise. If the issue still exists then please submit a ticket to our service team and we’ll have a look for you.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
