### ISSUE TITLE
Power Broker is blocking the following python line python -c 'import pwd;  print(pwd.getpwall())' when access is being blocked because a hang state from part of the tool

### ISSUE THREAD

**Issue by manumorac** [BeyondTrust/pbis-open#276]
**Version**: 8.5.4.334
**OS/Distro**: Ubuntu desktop 16.04 - unity desktop
**Issue/Impact**:
*Note: replace content with your own*
When reporting an issue it's important that we have as much detail as you can provide. The following is a list of commands to check.
 1. systemctl status lwsmd.service
 2. /opt/pbis/bin/lwsm list
 3. /opt/pbis/domainjoin-cli query
 4. pbis status
 5. /opt/pbis/bin/enum-users
 6. attach logs
  - /opt/pbis/bin/lwsm set-log-target -p lsass -  file /tmp/lsass.log
  - /opt/pbis/bin/lwsm set-log-level -p lsass - debug
  - attach log

**Output/Error**:

**Steps to Reproduce**:
 1. install command
 2. Domainjoin command
 3. Command that returns issue

**Comment by rbest-bt** [comment]
Please upgrade to Active Directory Bridge Enterprise. If the issue still exists then please submit a ticket to our service team and we’ll have a look for you.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
