### ISSUE TITLE
Can not install pbis-open cause missing GPG key for pbis-open-upgrade-9.1.0-551.x86_64

### ISSUE THREAD

**Issue by devops2k9** [BeyondTrust/pbis-open#277]
> warning: /var/cache/yum/x86_64/7Server/pbiso/packages/pbis-open-upgrade-9.1.0-551.x86_64.rpm: Header V3 DSA/SHA1 Signature, key ID c9ceecef: NOKEY
>
>Retrieving key from https://repo.pbis.beyondtrust.com/yum/RPM-GPG-KEY-pbis
>
>
>The GPG keys listed for the "PBISO- local packages for x86_64" repository are already installed but they are not correct for this package.
>Check that the correct key URLs are configured for this repository.
>
>
 >Failing package is: pbis-open-upgrade-9.1.0-551.x86_64
 >GPG Keys are configured as: https://repo.pbis.beyondtrust.com/yum/RPM-GPG-KEY-pbis`

Current I faced this issue when install pbis-open on RedHat server.
From the log can saw that there is missing GPG key for `pbis-open-upgrade-9.1.0-551.x86_64`,  how can I fixed this issue?

Thanks

**Comment by rbest-bt** [comment]
The main key has been updated for the enterprise repo. The old key is still available at https://repo.pbis.beyondtrust.com/yum/RPM-GPG-KEY-pbis-1024

I've updated the pbiso.repo file to point to the correct file. It will need to be updated on local systems.

**Comment by devops2k9** [comment]
@rbest-bt: I can install pbis-open successfully.
Thanks
