### ISSUE TITLE
yum install : devel dependancy issue on lib from pbis-open

### ISSUE THREAD

**Issue by tcadeau** [BeyondTrust/pbis-open#281]
**Version**: 9.1.0.551

**OS/Distro**:Centos 7 / 3.10.0-957.27.2.el7.x86_64
**Issue/Impact**:
_Every commands are run as root_
After wget the repo and yum clean everything, 3 packages are visible:
$ yum search pbis
[...]
pbis-open.x86_64 : Identity Services for authenticating with Active Directory domains
pbis-open-devel.x86_64 : BeyondTrust AD Bridge Open (development)
pbis-open-upgrade.x86_64 : Upgrade helper package for BeyondTrust AD Bridge Open

I successfully install pbis-open with yum install.
For pbis-open-devel, I add to 

But I have an issue with pbis-open-devel:
(sorry for french ouput, I think you will even understand the key words)
$ yum install pbis-open-devel.x86_64 
[....]
Résolution des dépendances
--> Lancement de la transaction de test
---> Le paquet pbis-open-devel.x86_64 0:9.1.0-551 sera installé
--> Traitement de la dépendance : liblwiocommon.so.0()(64bit) pour le paquet : pbis-open-devel-9.1.0-551.x86_64
--> Traitement de la dépendance : libiomgr.so.0()(64bit) pour le paquet : pbis-open-devel-9.1.0-551.x86_64
--> Résolution des dépendances terminée
Erreur : Paquet : pbis-open-devel-9.1.0-551.x86_64 (pbiso)
             Requiert : **liblwiocommon**.so.0()(64bit)
Erreur : Paquet : pbis-open-devel-9.1.0-551.x86_64 (pbiso)
             Requiert : **libiomgr**.so.0()(64bit)
 Vous pouvez essayer d'utiliser --skip-broken pour contourner le problème
 Vous pouvez essayer d'exécuter : rpm -Va --nofiles --nodigest

$ yum install pbis-open-devel.x86_64 --skip-broken
[...]
Résolution des dépendances
--> Lancement de la transaction de test
---> Le paquet pbis-open-devel.x86_64 0:9.1.0-551 sera installé
--> Traitement de la dépendance : liblwiocommon.so.0()(64bit) pour le paquet : pbis-open-devel-9.1.0-551.x86_64
--> Traitement de la dépendance : libiomgr.so.0()(64bit) pour le paquet : pbis-open-devel-9.1.0-551.x86_64

Paquets omis en raison de problèmes de dépendances :
    pbis-open-devel-9.1.0-551.x86_64 depuis pbiso

$ ls /opt/pbis/lib64/*io*.so.0
/opt/pbis/lib64/libiomgr.so.0       /opt/pbis/lib64/liblwioshareinfo.so.0
/opt/pbis/lib64/liblwioclient.so.0  /opt/pbis/lib64/liblwiosmbcommon.so.0
/opt/pbis/lib64/liblwiocommon.so.0

If I add the correct path in ldconfig, I still have the exact same issue
$ echo /lib64 /usr/lib64 /opt/pbis/lib64 > /etc/ld.so.conf.d/pbis.conf
$ ldconfig
$ yum install pbis-open-devel.x86_64 --skip-broken
[...]
Résolution des dépendances
--> Lancement de la transaction de test
---> Le paquet pbis-open-devel.x86_64 0:9.1.0-551 sera installé
--> Traitement de la dépendance : liblwiocommon.so.0()(64bit) pour le paquet : pbis-open-devel-9.1.0-551.x86_64
--> Traitement de la dépendance : libiomgr.so.0()(64bit) pour le paquet : pbis-open-devel-9.1.0-551.x86_64

Paquets omis en raison de problèmes de dépendances :
    pbis-open-devel-9.1.0-551.x86_64 depuis pbiso

**Comment by rbest-bt** [comment]
That package is not needed for the main functionality. The devel package includes the development libraries and header files that supply the application programming interface for security and authentication.

A change should be coming soon to stop providing that by default

**Comment by tcadeau** [comment]
Thank you for your feedback.
I was thinking to play with the devel tools without compiling the whole thing.
Main functionality is already configured and used on my system.

Having the devel package available is quite usual, it doesn't mean it will be installedin general.
