### ISSUE TITLE
Ubuntu 19.10 Cannot sudo without su to same account

### ISSUE THREAD

**Issue by broyuken** [BeyondTrust/pbis-open#283]
**Version**: 
Compiled daemon version: 9.1.0.551
Packaged product version: 9.1.551.2
**OS/Distro**: Ubuntu 19.10 
**Issue/Impact**: Cannot sudo without su to same account

I have PBIS set up and everything works fine, I am able to log in, able to install packages via the software center, etc. The issue I am having is that if I open terminal and try to run a sudo command, it fails and says I am not in the sudoers group. If I su as that same user and run the command again it works.

```
broy@link-ubuntu:~$ sudo viduso
broy is not in the sudoers file.  This incident will be reported.
broy@link-ubuntu:~$ su broy
Password:
Your password will expire in 6 days

broy@link-ubuntu:~$ sudo visudo
Your password will expire in 6 days

broy@link-ubuntu:~$
```
Also I noticed that if I run groups, it doesn't return all my groups, but if I su as myself it does.
```
broy@link-ubuntu:~$ id
uid=202376276(broy) gid=202375681(domain^users) groups=202375681(domain^users)
broy@link-ubuntu:~$ id broy
uid=202376276(broy) gid=202375681(domain^users) groups=202375681(domain^users),202376280(local_admins),202376283(all^drive^maps),202376286(linux_admins),202376290(vpn_users),202376293(linux_users)
broy@link-ubuntu:~$ 
```
/etc/sudoers file
```
broy@link-ubuntu:~$ sudo cat /etc/sudoers
Your password will expire in 6 days

#
# This file MUST be edited with the 'visudo' command as root.
#
# Please consider adding local content in /etc/sudoers.d/ instead of
# directly modifying this file.
#
# See the man page for details on how to write a sudoers file.
#
Defaults	env_reset
Defaults	mail_badpass
Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"

# Host alias specification

# User alias specification

# Cmnd alias specification

# User privilege specification
root	ALL=(ALL:ALL) ALL

# Members of the admin group may gain root privileges
%admin ALL=(ALL) ALL

# Allow members of group sudo to execute any command
%sudo	ALL=(ALL:ALL) ALL
%linux_admins ALL=(ALL:ALL) ALL
# See sudoers(5) for more information on "#include" directives:

#includedir /etc/sudoers.d
broy@link-ubuntu:~$ 
```

**Comment by mmiat** [comment]
i have the opposite error
i can login, but can't do anything from gui: connect to wifi, to vpn, install, reboot
if i open console, i can do su or sudo and do anything
i've kubuntu 20.04 and everything happens tomorrow morning, yesterday there was an update, i dont know if this could be useful
other users aren't affected (both local and domain user)
i've also tried to remove home and let create a new one, same problem
i've also tried to remove from domain, remove pbis (with purge) and reinstall it, rejoin domain

**Comment by broyuken** [comment]
Didn't change anything other that apt upgrade and now it seems to work. Not sure if this is an intermittent issue or not but today it's working as expected. I can sudo just fine.
