### ISSUE TITLE
Kubuntu 20.04 not authorized from gui

### ISSUE THREAD

**Issue by mmiat** [BeyondTrust/pbis-open#285]
I've Kubuntu 20.04 and I've used pbis for about one month without big issues
but since yesterday, after an update, I can't do anything from gui that requires privileges or authentication, while in console I've no limitations
also, KDE ask me kwallet password when I run programs, this never happened before
today I formatted and reinstalled kubuntu and I have same error
some update has broken something (maybe libpam-systemd)

**Steps to Reproduce**:
 1. install kubuntu 20.04, update it
 2. join to your domain
 3. your user, even if in sudoers, can't do anything from gui, but has no issue in console

[lsass.log](https://github.com/BeyondTrust/pbis-open/files/4393396/lsass.log)

**Comment by mmiat** [comment]
I also opened https://bugs.launchpad.net/ubuntu/+bug/1869400 and https://bugs.kde.org/show_bug.cgi?id=419262

**Comment by timadams414** [comment]
Same issue here.
I also find that AD authenticated users have no sound. (Checking aplay or alsamixer reports no sound devices found).
If I log into the system as a local user, both elevating privileges and sound work fine.

**Comment by timadams414** [comment]
Many thanks for the info.

I've just run /opt/pbis/bin/config AssumeDefaultDomain true

I can confirm that on my systems, AD authenticated users now have working sound, and elevating privileges works as expected.

**Comment by timadams414** [comment]
As a follow-up, some of the systems here are configured to mount some Samba shares at logon, using pam-mount.

Which shares are mounted depends on which groups the user belongs to in AD.

After making the change above, it was also necessary to make some changes in the volume definitions section of /etc/security/pam_mount.conf.xml
<volume sgrp="AD\managers"
	user="*"
	fstype="cifs"
	server="jupiter"
	path="managers"
	mountpoint="/mnt/jupiter-managers"
For example:

<volume sgrp="AD\managers"
	user="*"
	fstype="cifs"
	server="jupiter"
	path="managers"
	mountpoint="/mnt/jupiter-managers"

Needs changing to

<volume sgrp="managers"
	user="*"
	fstype="cifs"
	server="jupiter"
	path="managers"
	mountpoint="/mnt/jupiter-managers"


Hope this may be of use to someone.......................

**Comment by mmiat** [comment]
> I also ran into this issue. I believe the issue lies with systemd:
> [systemd/systemd#15090](https://github.com/systemd/systemd/issues/15090)
> [systemd/systemd#15149](https://github.com/systemd/systemd/issues/15149)
> 
> I was able to login from GUI by setting:
> `/opt/pbis/bin/config AssumeDefaultDomain true`

this is already in my default config, maybe it works after the issue appears? now I can't try because I've reinstalled all and I don't want to update

**Comment by mmiat** [comment]
I've formatted and reinstalled, a clean 20.04 final installation works fine
for me this can be closed

**Comment by strigona-worksight** [comment]
Agreed. systemd did resolve the incompatibility they introduced.

**Comment by timadams414** [comment]
Agreed.

On a test machine, I ran /opt/pbis/bin/config AssumeDefaultDomain false

And reverted the changes to /etc/security/pam_mount.conf.xml

AD authenticated users have working sound, and elevating privileges works as expected on the test machine.
