### ISSUE TITLE
Error: Undocumented exception [code 0x00009efc] when joining from Ubuntu 18.04

### ISSUE THREAD

**Issue by alexditu** [BeyondTrust/pbis-open#286]
**Version**: 9.1.0.551
**OS/Distro**: Ubuntu 18.04.4 LTS
**Issue/Impact**:

 1. systemctl status lwsmd.service
```
lwsmd.service - BeyondTrust AD Bridge Service Manager
   Loaded: loaded (/lib/systemd/system/lwsmd.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-03-31 12:30:23 EEST; 4h 3min ago
 Main PID: 960 (lwsmd)
    Tasks: 105 (limit: 4666)
   CGroup: /system.slice/lwsmd.service
           ├─ 960 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─ 973 lw-container lwreg
           ├─1053 lw-container eventlog
           ├─1099 lw-container netlogon
           ├─1137 lw-container lwio
           ├─1161 lw-container lsass
           └─1184 lw-container reapsysl

mar 31 12:30:23 ad-ubuntu18-x64-02 netlogon[1099]: Logging started
mar 31 12:30:23 ad-ubuntu18-x64-02 lwio[1137]: Logging started
mar 31 12:30:23 ad-ubuntu18-x64-02 lsass[1161]: Logging started
mar 31 12:30:23 ad-ubuntu18-x64-02 reapsysl[1184]: Logging started
mar 31 12:30:23 ad-ubuntu18-x64-02 systemd[1]: Started BeyondTrust AD Bridge Service Manager.
mar 31 16:18:36 ad-ubuntu18-x64-02 lsass[1161]: [lsass] Failed to run provider specific request (request code = 8, provider = 'lsa-activedirectory-provider') -> error = 9502, symbol = DNS_ERROR_BAD_PACKET, client pid = 1992
mar 31 16:19:24 ad-ubuntu18-x64-02 lsass[1161]: [lsass] Error enumerating trusts for domain MYDOMAIN.LOCAL. Error was ERROR_GEN_FAILURE (31)
mar 31 16:19:24 ad-ubuntu18-x64-02 lsass[1161]: [lsass] Failed to run provider specific request (request code = 8, provider = 'lsa-activedirectory-provider') -> error = 40700, symbol = <null>, client pid = 2061
mar 31 16:22:50 ad-ubuntu18-x64-02 lsass[1161]: [lsass] Error enumerating trusts for domain MYDOMAIN.LOCAL. Error was ERROR_GEN_FAILURE (31)
mar 31 16:22:50 ad-ubuntu18-x64-02 lsass[1161]: [lsass] Failed to run provider specific request (request code = 8, provider = 'lsa-activedirectory-provider') -> error = 40700, symbol = <null>, client pid = 3372
```

 2. /opt/pbis/bin/lwsm list
```
lwreg          running (container: 973)
dcerpc         stopped
eventlog       running (container: 1053)
lsass          running (container: 1161)
lwio           running (container: 1137)
netlogon       running (container: 1099)
rdr            running (io: 1137)
reapsysl       running (container: 1184)
usermonitor    stopped
```

 3. sudo /opt/pbis/bin/domainjoin-cli query
```
Name = ad-ubuntu18-x64-02
Domain = MYDOMAIN.LOCAL
Distinguished Name = CN=AD-UBUNTU18-X64-02,CN=Computers,DC=mydomain,DC=local
```
 4. pbis-status 
```
LSA Server Status:

Compiled daemon version: 9.1.0.551
Packaged product version: 9.1.551.2
Uptime:        0 days 4 hours 6 minutes 56 seconds

[Authentication provider: lsa-activedirectory-provider]

	Status:        Unknown
	Mode:          Unknown
```
 5. /opt/pbis/bin/enum-users
`TotalNumUsersFound: 0`
 6. attach logs
  - /opt/pbis/bin/lwsm set-log-target -p lsass -  file /tmp/lsass.log
  - /opt/pbis/bin/lwsm set-log-level -p lsass - debug
  - attach log (attached)

**Output/Error**:
```
Error: Undocumented exception [code 0x00009efc]

An undocumented exception has occurred. Please contact BeyondTrust technical support and use the error code to identify this exception.
20200331172427:ERROR:Undocumented exception [code 0x00009efc]
```

**Steps to Reproduce**:
 1. install command
```
wget https://github.com/BeyondTrust/pbis-open/releases/download/9.1.0/pbis-open-9.1.0.551.linux.x86_64.deb.sh
chmod +x ./pbis-open-9.1.0.551.linux.x86_64.deb.sh
sudo ./pbis-open-9.1.0.551.linux.x86_64.deb.sh
```
 2. Domainjoin command
```sudo /opt/pbis/bin/domainjoin-cli --logfile . --loglevel verbose join --assumeDefaultDomain yes --userDomainPrefix mydomain -- mydomain.local Administrator "somepassword"```
 3. Command that returns issue
`domainjoin-cli`
outpt:
```
Error: Undocumented exception [code 0x00009efc]

An undocumented exception has occurred. Please contact BeyondTrust technical support and use the error code to identify this exception.
20200331172427:ERROR:Undocumented exception [code 0x00009efc]
```

Notes: I've tried the same commands on a Centos7 machine and it worked as expected. I've seen issues #66 and #115 that look similar, but they don't help. Issue #27 seems very related but I don't see any resolution there.
[lsass.log](https://github.com/BeyondTrust/pbis-open/files/4409704/lsass.log)

**Comment by nbommu1** [comment]
I had same problem, when I re-install pbis-open it just joined without running domainjoin-cli and users are able to login with AD credentials.

here is the output I got

Importing registry...

/opt/pbis/share/config/accounts.reg
/opt/pbis/share/config/dcerpcd.reg
/opt/pbis/share/config/eventlogd.reg
/opt/pbis/share/config/lsassd.reg
/opt/pbis/share/config/lwiod.reg
/opt/pbis/share/config/lwreg.reg
/opt/pbis/share/config/netlogond.reg
/opt/pbis/share/config/privileges.reg
/opt/pbis/share/config/rdr.reg
/opt/pbis/share/config/reapsysl.reg
/opt/pbis/share/config/usermonitor.reg

Installing Packages was successful

This computer is joined to mydomain.com

**Comment by rbest-bt** [comment]
pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
