### ISSUE TITLE
pbis works in opensuse with this warning and this fix

### ISSUE THREAD

**Issue by mauro-miatello** [BeyondTrust/pbis-open#288]
**Version**: 9.1.0-551
**OS/Distro**: OpenSuse Tumbleweed
**Issue/Impact**:
join has success with warning
```
Warning: A resumable error occurred while processing the 'hostname' module
ERROR_FILE_NOT_FOUND [code 0x00000002]
```
then other commands give error unless I remove /etc/xml/suse-catalog.xml

**Comment by rbest-bt** [comment]
Tumbleweed is not yet fully supported. If there is higher demand, we'll look into adding it into our regular rotation.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
