### ISSUE TITLE
Issue Authenticating to Domain with Two Way Trust Established

### ISSUE THREAD

**Issue by THahnke** [BeyondTrust/pbis-open#289]
**Version**: 9.1.0.551 and 9.0.2.534

**OS/Distro**: OSX 10.15 and 10.13 (Catalina and High Sierra)

**Issue/Impact**: Users accounts on a domain that we have a two way trust with cannot login. pbis authenticate-user results in Error: LW\_ERROR\_NOT_HANDLED (0x9c51). Users in our domain are able to authenticate and login.
 
/opt/pbis/bin/lwsm list

`lwreg          running (container: 299)
dcerpc         stopped
eventlog       running (container: 329)
lsass          running (container: 409)
lwio           running (container: 406)
netlogon       running (container: 401)
rdr            running (io: 406)
reapsysl       running (container: 438)
usermonitor    stopped`
 
pbis status - domain with two-way trust

	[Domain: Trusted]
        DNS Domain:       TRUSTED.EDU
		Netbios name:     TRUSTED
		Forest name:      
		Trustee DNS name: DOMAIN.FROOT.DOMAIN.EDU
		Client site name: 
		Domain SID:       *
		Domain GUID:      00000000-0000-0000-0000-000000000000
		Trust Flags:      [0x0022]
		                  [0x0002 - Outbound]
		                  [0x0020 - Inbound]
		Trust type:       Up Level
		Trust Attributes: [0x0004]
		                  [0x0004 - Filter SIDs]
		Trust Direction:  Twoway Trust
		Trust Mode:       External Trust (ET)
		Domain flags:     [0x0002]
		                  [0x0002 - Offline]`
I've noticed that the domain flags will sometimes return offline when running pbis status. We've verified that the domain is online and users of the domain are able to authenticate on Windows machines.
[lsass.log](https://github.com/BeyondTrust/pbis-open/files/4589402/lsass.log)

Lsass.log - attached

**Steps to Reproduce**:
 1. install -pkg /Volumes/pbis-open/pbis-open-pbis-open-9.1.0.551.pkg -target /
 2. /opt/pbis/bin/domainjoin-cli join domain.edu user@domain.edu password
 3. Command that returns issue
pbis authenticate-user --user as123 --domain coco2k

**Comment by rbest-bt** [comment]
External trusted domains that report offline are usually related to DNS issues. Have a look at the troubleshooting guide for "Solve Domain-Join Problems". It has tests for name resolution.
