### ISSUE TITLE
Will ldap still work if it was installed and then hostname/IP were changed after

### ISSUE THREAD

**Issue by vpekelis28** [BeyondTrust/pbis-open#29]
will pbis ldap still work if you modify the IP or the hostname after installation. Say it was on a temporary IP with ldap already installed for testing. Are there any specific files that need to be modified or will pbis need to be fully re-installed?

**Comment by rbest-bt** [comment]
I would recommend changing the hostname with the domainjoin commands option "setname" then issue a new domainjoin to update the AD computer object.
`/opt/pbis/bin/domainjoin-cli setname newname`
`/opt/pbis/bin/domainjoin-cli join domain admin`

For IP Just make sure to update your DNS. We have a tool that can help with this:
`/opt/pbis/bin/update-dns`
