### ISSUE TITLE
can't to share folder by DC user

### ISSUE THREAD

**Issue by chart41** [BeyondTrust/pbis-open#291]
**Version**: 9.1.0.551
**OS/Distro**: mint 19.3
**Issue/Impact**:
*Note:
![4444](https://user-images.githubusercontent.com/44474464/82886177-35b13b00-9f57-11ea-80b0-61d3b32a8741.jpg)

**1)** trying to share folder from dc user but checkbox is inactive
In blue part it says something like _"It's necessary to install samba, add firewall rules, also your user account should be in sambashare group."_
samba is installed, UFW firewall wasn't used and now disabled, and user already in sambashare group.
btw I can share folder when logging by ordinary non DC user
**2)** How can I disable lsass debuggin?
"
*

 **1. systemctl status lwsmd.service active (running)**
 **2. /opt/pbis/bin/lwsm list**
```
lwreg          running (container: 924)
dcerpc         stopped
eventlog       running (container: 962)
lsass          running (container: 1039)
lwio           running (container: 1012)
netlogon       running (container: 988)
rdr            running (io: 1012)
reapsysl       running (container: 1077)
usermonitor    stopped
```
 **3. /opt/pbis/domainjoin-cli query**
bash: /opt/pbis/domainjoin-cli: No such file or directory

 **4. pbis status** is ok

 **5. /opt/pbis/bin/enum-users** is ok
 6. attach logs

  - /opt/pbis/bin/lwsm set-log-target -p lsass -  file /tmp/lsass.log
  - /opt/pbis/bin/lwsm set-log-level -p lsass - debug 
  - attach log

**Output/Error**:

**Steps to Reproduce**:
 1. rclick on folder
 2. try to share folder
[lsasss.LOG](https://github.com/BeyondTrust/pbis-open/files/4681289/lsasss.LOG)

**Comment by rbest-bt** [comment]
This could be an issue with that tool interacting with the share. I would not think pbis-open would be in play at this point.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
