### ISSUE TITLE
New message in log from RequireMembershipOf

### ISSUE THREAD

**Issue by NdK73** [BeyondTrust/pbis-open#292]
**Version**: 9.1.0.551
**OS/Distro**: Debian 10.4
**Issue/Impact**: 
I recently started spotting messages like
`Restricted login list - aliases, such as str957.tecnici, are not allowed [40041]`
in daemon.log file, and actually members of the impacted groups can not login anymore.

The given groups are standard domain-local AD groups. Why are they considered aliases?

Tks.

**Comment by rbest-bt** [comment]
Please upgrade to Active Directory Bridge Enterprise. If the issue still exists then please submit a ticket to our service team and we’ll have a look for you.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
