### ISSUE TITLE
compability problem with openssl 1.1.1

### ISSUE THREAD

**Issue by 29217321** [BeyondTrust/pbis-open#293]
In general, CentOS 8 and newer Ubuntu etc. platforms are using OpenSSL 1.1.1 widely already. 
However, the PBIS internal embedded openssl library is still 1.0.x which caused compability issues on OSs which has openssl-1.1.1, some typical issues include e.g. krb5_plugins, HMAC (see https://developer.akamai.com/blog/2017/02/14/upgrade-openssl-110) which is used by libschannel etc., which is embedded in PBIS source.

Do we have any suggestsion/ideas/plan to address this concern? thanks

**Comment by rbest-bt** [comment]
Active Directory Bridge Enterprise will be addressing this.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
