### ISSUE TITLE
pbis took long time to install

### ISSUE THREAD

**Issue by devops2k9** [BeyondTrust/pbis-open#295]
Dear team,

Recently, we faced with issue that pbis took long time when install.
After check the log, I see that it take time to update profile 
`Aug  4 15:14:07 cloud-init: Uploading Package Profile`
`Aug  4 15:14:07 cloud-init: Cannot upload package profile. Is this client registered?`
`Aug  4 15:16:14 cloud-init: Uploading Tracer Profile`
`Aug  4 15:16:14 cloud-init: Cannot upload tracer data, is this client registered?`
`Aug  4 15:16:14 cloud-init: Verifying  : pbis-open-upgrade-9.1.0-551.x86_64                           1/2`
`Aug  4 15:16:14 cloud-init: Verifying  : pbis-open-9.1.0-551.x86_64                                   2/2`
`Aug  4 15:16:14 cloud-init: Installed:`
`Aug  4 15:16:14 cloud-init: pbis-open.x86_64 0:9.1.0-551`
`Aug  4 15:16:14 cloud-init: Dependency Installed:`
`Aug  4 15:16:14 cloud-init: pbis-open-upgrade.x86_64 0:9.1.0-551`
`Aug  4 15:16:14 cloud-init: Complete!`

Could you share me why it need to upload profile and how can I speed up this process ?

Regards

**Comment by dmorash-BT** [comment]
cloud-init is not a pbis feature but appears to be a systemd one.  You could try disabling it if you don't need it.  [cloud-init Boot stages](https://cloudinit.readthedocs.io/en/latest/topics/boot.html)

**Comment by devops2k9** [comment]
> cloud-init is not a pbis feature but appears to be a systemd one. You could try disabling it if you don't need it. [cloud-init Boot stages](https://cloudinit.readthedocs.io/en/latest/topics/boot.html)

it not related to cloud-init. This just process userdata script when launch instances.

**Comment by rbest-bt** [comment]
The delay seems to occur before pbis-open is installing. I would investigate the package profiler. pbis-open install logs should be in /var/log.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
