### ISSUE TITLE
PBIS yum repository appears to be broken

### ISSUE THREAD

**Issue by MarketDown** [BeyondTrust/pbis-open#296]
**Version**: N/A
**OS/Distro**: CentOS
**Issue/Impact**:
Yum repository appears to be up but it seems the packages aren't there.
 
Says pbis-open package not found

yum install pbis-open pbis-open-upgrade

**Comment by steversk** [comment]
I noticed this same issue yesterday. I ended up switching to the installer script since the repo is down.

**Comment by Chiango2** [comment]
I noticed the same error yesterday. Any walk around for this please ?
curl "http://repo.pbis.beyondtrust.com/yum/pbiso.repo" -O "/etc/yum.repos.d/pbiso.repo"
sudo yum install libnsl -y
sudo yum clean all
sudo yum install pbis-open -y
#####################################
Last metadata expiration check: 0:13:36 ago on Tue 18 Aug 2020 05:50:26 PM UTC.
No match for argument: pbis-open

**Comment by rbest-bt** [comment]
Having a look into it.

**Comment by balan2002cbe** [comment]
Yes, pbis-open packages are not there and we are seeing errors from yesterday.

**Comment by jlmagee** [comment]
I've experienced this all day

yum  --enablerepo=pbsio list pbis*
Loaded plugins: product-id, search-disabled-repos, subscription-manager

This system is not registered with an entitlement server. You can use subscription-manager to register.

Error getting repository data for pbsio, repository not found

  AND when trying to browse to the repo in a browser

Forbidden
You don't have permission to access this resource.

**Comment by rbest-bt** [comment]
This has been fixed. There was an issue with the release process which I'll be looking into.
