### ISSUE TITLE
The project is not being built

### ISSUE THREAD

**Issue by uriah56** [BeyondTrust/pbis-open#297]
Version: 9.1.0
OS/Distro: Linux Mint 20 Cinnamon
Compiler GCC-8

When I build the project using GCC-8, I got an error message saying ("неопределённая ссылка на" is "undefined link to")
[link] /opt/pbis/lib/liblwadvapi.so.0.0.0 (host/x86_64)
/usr/bin/ld: stage/opt/pbis/lib/liblwadvapi_nothr.so: неопределённая ссылка на «dlopen»
/usr/bin/ld: stage/opt/pbis/lib/liblwadvapi_nothr.so: неопределённая ссылка на «dlclose»
/usr/bin/ld: stage/opt/pbis/lib/liblwadvapi_nothr.so: неопределённая ссылка на «dlerror»
/usr/bin/ld: stage/opt/pbis/lib/liblwadvapi_nothr.so: неопределённая ссылка на «dlsym»
collect2: error: ld returned 1 exit status
              [link] FAILED: 'gcc-8' '-o' 'stage/opt/pbis/libexec/verify-sd' 'object/reskit/security-descriptor/verify-sd.verify-sd.host.x86_64.o' '-Lstage/opt/pbis/lib' '-m64' '-O0' '-g' '-Wl,-rpath,/opt/pbis/lib' '-Wl,-rpath-link,stage/opt/pbis/lib' '-llwadvapi_nothr' '-llwbase' '-llwbase_nothr'
make: *** [Makefile:13061: stage/opt/pbis/libexec/verify-sd] Ошибка 1 (Error 1)

Steps to Reproduce:
mkdir debug && cd debug
../configure --debug=yes --build-isas=x86_64 --fail-on-warn=no
make -j2

But if I use GCC-9 I have another errors and the project doesn't build
All necessary tools and libraries described in README.md are installed.
This steps done on another systems (Linux Mint 19, xubuntu 20.04, xubuntu 18.04) but the project doesn't build.  Errors everytime are different.

**Comment by pavalenta** [comment]
I get the same error during compiling on Ubuntu 18.04 with gcc 7.5

stage/opt/pbis/lib/liblwadvapi_nothr.so: undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
              [link] FAILED: 'gcc' '-o' 'stage/opt/pbis/libexec/verify-sd' 'object/reskit/security-descriptor/verify-sd.verify-sd.host.x86_64.o' '-Lstage/opt/pbis/lib' '-m64' '-O0' '-g' '-Wl,-rpath,/opt/pbis/lib' '-Wl,-rpath-link,stage/opt/pbis/lib' '-llwadvapi_nothr' '-llwbase' '-llwbase_nothr'
Makefile:13061: recipe for target 'stage/opt/pbis/libexec/verify-sd' failed
make: *** [stage/opt/pbis/libexec/verify-sd] Error 1
make: *** Waiting for unfinished jobs....
           [symlink] /opt/pbis/lib/libeventlog_norpc.so.0 -> libeventlog_norpc.so.0.0.0
           [symlink] /opt/pbis/lib/libeventlog_norpc.so -> libeventlog_norpc.so.0.0.0
         [configure] end curl (host/x86_64)

**Comment by pavalenta** [comment]
Compiling with GCC 9 on Ubuntu 18.04 I get this eventually with make -j all package


cc1: all warnings being treated as errors
           [compile] FAILED: 'gcc' '-m64' '-O0' '-g' '-Wall' '-Werror' '-fno-strict-aliasing' '-I../lwio/server/rdr/.' '-Iobject/lwio/server/rdr/.' '-I../lwio/server/rdr/../include' '-Iobject/lwio/server/rdr/../include' '-I../lwio/server/rdr/../../include' '-Iobject/lwio/server/rdr/../../include' '-DDEBUG=1' '-Istage/opt/pbis/include' '-DHAVE_CONFIG_H' '-D_MK_HOST_X86_64' '-D_MK_HOST' '-fPIC' '-MMD' '-MP' '-MF' '.MakeKitDeps/object_lwio_server_rdr_querydir2.rdr.host.x86_64.dep' '-o' 'object/lwio/server/rdr/querydir2.rdr.host.x86_64.o' '-c' '../lwio/server/rdr/querydir2.c'
Makefile:4089: recipe for target 'object/lwio/server/rdr/querydir2.rdr.host.x86_64.o' failed
make: *** [object/lwio/server/rdr/querydir2.rdr.host.x86_64.o] Error 1
make: *** Waiting for unfinished jobs....
                [la] /opt/pbis/lib/libschannel.la (host/x86_64)
cc1: all warnings being treated as errors
cc1: all warnings being treated as errors
           [compile] FAILED: 'gcc' '-m64' '-O0' '-g' '-Wall' '-Werror' '-fno-strict-aliasing' '-I../lwio/server/rdr/.' '-Iobject/lwio/server/rdr/.' '-I../lwio/server/rdr/../include' '-Iobject/lwio/server/rdr/../include' '-I../lwio/server/rdr/../../include' '-Iobject/lwio/server/rdr/../../include' '-DDEBUG=1' '-Istage/opt/pbis/include' '-DHAVE_CONFIG_H' '-D_MK_HOST_X86_64' '-D_MK_HOST' '-fPIC' '-MMD' '-MP' '-MF' '.MakeKitDeps/object_lwio_server_rdr_querydir.rdr.host.x86_64.dep' '-o' 'object/lwio/server/rdr/querydir.rdr.host.x86_64.o' '-c' '../lwio/server/rdr/querydir.c'
Makefile:4085: recipe for target 'object/lwio/server/rdr/querydir.rdr.host.x86_64.o' failed
make: *** [object/lwio/server/rdr/querydir.rdr.host.x86_64.o] Error 1
           [compile] FAILED: 'gcc' '-m64' '-O0' '-g' '-Wall' '-Werror' '-fno-strict-aliasing' '-I../lwio/server/rdr/.' '-Iobject/lwio/server/rdr/.' '-I../lwio/server/rdr/../include' '-Iobject/lwio/server/rdr/../include' '-I../lwio/server/rdr/../../include' '-Iobject/lwio/server/rdr/../../include' '-DDEBUG=1' '-Istage/opt/pbis/include' '-DHAVE_CONFIG_H' '-D_MK_HOST_X86_64' '-D_MK_HOST' '-fPIC' '-MMD' '-MP' '-MF' '.MakeKitDeps/object_lwio_server_rdr_smb2.rdr.host.x86_64.dep' '-o' 'object/lwio/server/rdr/smb2.rdr.host.x86_64.o' '-c' '../lwio/server/rdr/smb2.c'
Makefile:4133: recipe for target 'object/lwio/server/rdr/smb2.rdr.host.x86_64.o' failed
make: *** [object/lwio/server/rdr/smb2.rdr.host.x86_64.o] Error 1
         [configure] end krb5/src (host/x86_64)

**Comment by rbest-bt** [comment]
Open was built with a very old compiler to support older versions of distributions. Using newer compilers you'll need to remove the -Werror flags to get around the warnings.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
