### ISSUE TITLE
Access denied for group members defined in RequireMembershipOf

### ISSUE THREAD

**Issue by dandeliger** [BeyondTrust/pbis-open#299]
**Version**: 9.1.0.551
**OS/Distro**: CentOS release 6.9 (Final), CentOS Linux release 8.2.2004 (Core)
**Issue/Impact**: I am using RequireMembershipOf to control which AD groups can access certain servers. For the most part this is working but I have a couple of servers where no user can login even when they are in the allowed groups . Users can only login when remove the restriction.

I am not sure what could be causing this. I've deployed pbis-open to other servers with the same settings and they have no issues. My work around for now is to remove restriction but obviously this is a big security hole.

Reinstalling pbis-open does not correct the issue either. I've also tried deleting ad-cache and restarting lsass service and reboot. I am out of ideas of what could be the issue and need help in resolving this.

Commands:
/opt/pbis/bin/uninstall.sh uninstall
/opt/pbis/bin/ad-cache --delete-all
systemctl restart lwsmd.service
/opt/pbis/bin/lwsm restart lsass

Here is the log from /var/log/secure
Sep  8 21:38:57 server-qa01 sshd[3076]: [lsass-pam] [module:pam_lsass]User domain\user is denied access because they are not in the 'require membership of' list
Sep  8 21:38:57 server-qa01 sshd[3076]: [lsass-pam] [module:pam_lsass]pam_sm_acct_mgmt failed [login:domain\user][error code:40158]
Sep  8 21:38:57 server-qa01 sshd[3076]: [lsass-pam] [module:pam_lsass]User domain\user is denied access because they are not in the 'require membership of' list
Sep  8 21:38:57 server-qa01 sshd[3076]: [lsass-pam] [module:pam_lsass]pam_sm_acct_mgmt failed [login:domain\user][error code:40158]
Sep  8 21:38:57 server-qa01 sshd[3077]: fatal: Access denied for user domain\user by PAM account configuration

Here is the config I am using:
Name: AssumeDefaultDomain
Description: Apply domain name prefix to account name at logon
Type: boolean
Current Value: false
Accepted Values: true, false
Current Value is determined by local policy.

Name: UserDomainPrefix
Description: Domain short name prefix to be used when AssumeDefaultDomain setting is enabled
Type: string
Current Value: ""
Current Value is determined by local policy.

Name: RequireMembershipOf
Description: Restrict logon access to computer to specific users or group members, or SIDs
Type: multistring
Current Values:
"DOMAIN\\GROUP1"
"DOMAIN\\GROUP2"
Current Value is determined by local policy.

Name: LoginShellTemplate
Description: Default login shell template
Type: string
Current Value: "/bin/bash"
Current Value is determined by local policy.

Name: HomeDirTemplate
Description: Format string for user's home directory path. This value can contain substitution string markers for HomeDirPrefix (%H), Domain (%D), and User (%U).
Type: string
Current Value: "%H/%D/%U"
Current Value is determined by local policy.

When reporting an issue it's important that we have as much detail as you can provide. The following is a list of commands to check.
 1. systemctl status lwsmd.service
● lwsmd.service - BeyondTrust AD Bridge Service Manager
   Loaded: loaded (/usr/lib/systemd/system/lwsmd.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2020-09-09 13:31:44 UTC; 4min 48s ago
  Process: 1124190 ExecStop=/opt/pbis/bin/lwsm shutdown (code=exited, status=0/SUCCESS)
  Process: 1124236 ExecStart=/opt/pbis/sbin/lwsmd --start-as-daemon (code=exited, status=0/SUCCESS)
 Main PID: 1124238 (lwsmd)
    Tasks: 112 (limit: 49390)
   Memory: 33.5M
   CGroup: /system.slice/lwsmd.service
           ├─1124238 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─1124251 lw-container lwreg
           ├─1124269 lw-container eventlog
           ├─1124285 lw-container netlogon
           ├─1124300 lw-container lwio
           ├─1124317 lw-container lsass
           └─1124339 lw-container reapsysl

Sep 09 13:31:44 server-qa01 systemd[1]: Stopped BeyondTrust AD Bridge Service Manager.
Sep 09 13:31:44 server-qa01 systemd[1]: Starting BeyondTrust AD Bridge Service Manager...
Sep 09 13:31:44 server-qa01 /opt/pbis/sbin/lwsmd[1124238]: Logging started
Sep 09 13:31:44 server-qa01 lwreg[1124251]: Logging started
Sep 09 13:31:44 server-qa01 eventlog[1124269]: Logging started
Sep 09 13:31:44 server-qa01 netlogon[1124285]: Logging started
Sep 09 13:31:44 server-qa01 lwio[1124300]: Logging started
Sep 09 13:31:44 server-qa01 lsass[1124317]: Logging started
Sep 09 13:31:44 server-qa01 reapsysl[1124339]: Logging started
Sep 09 13:31:44 server-qa01 systemd[1]: Started BeyondTrust AD Bridge Service Manager.

 2. /opt/pbis/bin/lwsm list
lwreg          running (container: 1124251)
dcerpc         stopped
eventlog       running (container: 1124269)
lsass          running (container: 1124317)
lwio           running (container: 1124300)
netlogon       running (container: 1124285)
rdr            running (io: 1124300)
reapsysl       running (container: 1124339)
usermonitor    stopped

 3. /opt/pbis/domainjoin-cli query
Name = server-qa01
Domain = DOMAIN.ORG
Distinguished Name = CN=SERVER-QA01,OU=OU2,OU=OU1,DC=domain,DC=org

 4. pbis status

 5. /opt/pbis/bin/enum-users

 6. attach logs
  - /opt/pbis/bin/lwsm set-log-target -p lsass -  file /tmp/lsass.log
  - /opt/pbis/bin/lwsm set-log-level -p lsass - debug
  - attach log

**Output/Error**:

**Steps to Reproduce**:
 1. install command
     ./pbis-open-9.1.0.551.linux.x86_64.rpm.sh
     also tried from repo:
    sudo wget -O /etc/yum.repos.d/pbiso.repo http://repo.pbis.beyondtrust.com/yum/pbiso.repo
    sudo yum install pbis-open

     #Set default shell
     /opt/pbis/bin/config LoginShellTemplate /bin/bash

     #Configure directory structure
     /opt/pbis/bin/config HomeDirTemplate %H/%D/%U

     #Set SSH restriction
     /opt/pbis/bin/config RequireMembershipOf "DOMAIN\\group1"

 2. Domainjoin command
   #Join server to domain
   /opt/pbis/bin/domainjoin-cli join --ou "OU1/OU2/OU3" --notimesync --disable hostname subdomain.domain.org services

 3. Command that returns issue

**Comment by dahabakuk** [comment]
did u try if groups are case sensitive? i experience a similar issue...

**Comment by dahabakuk** [comment]
i fixed my issue: the groups have been domain local -> using domain global all starts working again.
