### ISSUE TITLE
Error running /opt/pbis/bin/config commands

### ISSUE THREAD

**Issue by bgtron** [BeyondTrust/pbis-open#3]
I'm trying to setup pbis-open 8.5.1-206 on a CentOS 7 x64 server and the following happens:

# /opt/pbis/bin/config AssumeDefaultDomain true
Problem executing '/opt/pbis/bin/ad-cache --delete-all >/dev/null 2>/dev/null'
Error: Error returned by external program

Any ideas? Other sites show this was a bug in earlier versions.  Maybe a regression?

**Comment by RBoulton-BT** [comment]
This generally occurs when one of the domains is appearing offline. If you run the "/opt/pbis/bin/ad-cache --delete-all" manually you should see a message to this effect.

With 8.5.1 you should find we log a message in syslog stating which domain appears to be offline.

It would be interesting to see the output of a "pbis status" and see what the domain trust relationship is with the offline domain.

The idea behind this check is to make sure we don't clear the cache while a domain is offline as it would stop offline authentication working.

The solution could be to fix your network connectivity to a certain domain, or it could be we are being too aggressive with our domain validation for certain trust relationships.

**Comment by bgtron** [comment]
If I run this command results come back from the domain:
    id <domain>\\<userid>

Wouldn't that mean the domain is properly online?  Of the three domains I have presented when I run "pbis status" all but one of them work.  The other shouldn't matter because I'm not on that domain. To be sure, how can I determine which domain controller I'm currently connected to?

**Comment by RBoulton-BT** [comment]
It's difficult for me to comment without more details on your domain structure. 

As I mentioned previously this check was added to avoid clearing the cache of accounts if a domain is offline. The codebase is used for Open and for our Enterprise product where domain authentication is possible across a wide range of trust relationships. So in your scenario it may be this domain is not relevant, but other users of the code may be using accounts from the equivalent of your offline domain that would be adversely affected.

We are aware that our current strategy for offline checking may be too aggressive for all configurations so we are looking to identify what we can do to improve this.

**Comment by bgtron** [comment]
Ok.  How can I determine which DC the server is currently connected to?

**Comment by RBoulton-BT** [comment]
If you want to find out which domain is offline you need to run '/opt/pbis/bin/ad-cache --delete-all' and then look in your syslog files for the offline message.

If you run "pbis status" that should give you all the information you need to determine what domain you are connected to. It will also show the trust relationships for your domains.

What you're interested in is the section for the domain that's showing offline.

The [Domain Controller (DC) Information] section shows the current DC PBIS is using.

Here's an example:

# pbis status
LSA Server Status:

Compiled daemon version: 8.5.2.0
Packaged product version: 8.5.0.0
Uptime:        5 days 17 hours 44 minutes 42 seconds

[Authentication provider: lsa-activedirectory-provider]

	Status:        Online
	Mode:          Named Cell
	Domain:        DEMO.COM
	Domain SID:    
	Forest:        demo.local
	Site:          Default-First-Site-Name
	Online check interval:  300 seconds
	Sub mode:      Directory Integrated
	Cell:          CN=$LikewiseIdentityCell,OU=test,DC=demo,DC=local
	[Trusted Domains: 2]


	[Domain: DEMO]

		DNS Domain:       demo.local
		Netbios name:     DEMO
		Forest name:      demo.local
		Trustee DNS name: 
		Client site name: Default-First-Site-Name
		Domain SID:       <SID>
		Domain GUID:      <GUID>
		Trust Flags:      [0x001d]
		                  [0x0001 - In forest]
		                  [0x0004 - Tree root]
		                  [0x0008 - Primary]
		                  [0x0010 - Native]
		Trust type:       Up Level
		Trust Attributes: [0x0000]
		Trust Direction:  Primary Domain
		Trust Mode:       In my forest Trust (MFT)
		Domain flags:     [0x0001]
		                  [0x0001 - Primary]

		[Domain Controller (DC) Information]

			DC Name:              dc01.demo.local
			DC Address:           <IP ADDRESS>
			DC Site:              Default-First-Site-Name
			DC Flags:             [0x000033fd]
			DC Is PDC:            yes
			DC is time server:    yes
			DC has writeable DS:  yes
			DC is Global Catalog: yes
			DC is running KDC:    yes

		[Global Catalog (GC) Information]

			GC Name:              dc01.demo.local
			GC Address:           <IP ADDRESS
			GC Site:              Default-First-Site-Name
			GC Flags:             [0x000033fd]
			GC Is PDC:            yes
			GC is time server:    yes
			GC has writeable DS:  yes
			GC is running KDC:    yes

	[Domain: HOME]

		DNS Domain:       home.demo.local
		Netbios name:     HOME
		Forest name:      demo.local
		Trustee DNS name: DEMO.LOCAL
		Client site name: Default-First-Site-Name
		Domain SID:       <SID>
		Domain GUID:      <GUID>
		Trust Flags:      [0x0023]
		                  [0x0001 - In forest]
		                  [0x0002 - Outbound]
		                  [0x0020 - Inbound]
		Trust type:       Up Level
		Trust Attributes: [0x0020]
		                  [0x0020 - Within forest]
		Trust Direction:  Twoway Trust
		Trust Mode:       In my forest Trust (MFT)
		Domain flags:     [0x0000]

		[Domain Controller (DC) Information]

			DC Name:              dc02.home.demo.local
			DC Address:           <IP ADDRESS>
			DC Site:              Default-First-Site-Name
			DC Flags:             [0x000031fd]
			DC Is PDC:            yes
			DC is time server:    yes
			DC has writeable DS:  yes
			DC is Global Catalog: yes
			DC is running KDC:    yes

		[Global Catalog (GC) Information]

			GC Name:              dc01.demo.local
			GC Address:           <IP ADDRESS>
			GC Site:              Default-First-Site-Name
			GC Flags:             [0x000033fd]
			GC Is PDC:            yes
			GC is time server:    yes
			GC has writeable DS:  yes
			GC is running KDC:    yes

**Comment by bgtron** [comment]
Thanks for the information.  Last week I tested an older version of pbis-open (which I had installed several months ago and didn't have this issue), and it now has the same error as the latest version.  Here's what I'm suspecting:

There is a site in our AD domain that I can't access because it is a different site.  I'm suspecting that pbis-open is trying to connect to this other site and it cannot.  Is pbis-open site-aware?  Could this be the issue?  It appears that the commands are working because the desired changes are occurring, and the integration is working in every way I'm testing it (except for this verification errors).  Maybe this helps?

**Comment by RBoulton-BT** [comment]
PBIS is site aware so it should be hitting the DCs for it's site. There are some corner cases in a DMZ where it can be unable to work out the Site, bit on the whole that should not be a problem.

You're right this error message should not affect the setting you apply. It's just complaining as the side effect of making these setting changes is to clear the cache and the changes to our code to prevent clearing the cache in an offline scenario are just stopping that part. So these messages are annoying rather than breaking anything.

I'll see if we can take another look at the checks we perform when clearing the cache to see if we can make it less of an issue.

**Comment by West** [comment]
This is by no means a fix, but its a workaround.

This issue happens on one of my domains, but not the other.  It started after version 8.0, and has existed since.  

If you simply get ahold of the lsa file from an 8.0 installation and copy over /opt/pbis/bin/lsa with a version 8.0 installation it will work. 

For example (assuming you already have lsa file from version 8.0):
# cp /home/itglocal/lsa8.0 /opt/pbis/bin/lsa

**Comment by rbest-bt** [comment]
This could work but I can not recommend it as you re-introduce a bug where you can clear your cache while offline and would not be able to authenticate with any ad accounts until you can reach the domain again.

**Comment by West** [comment]
Our issue only resides in our DMZ as well.  What is the fix for this? IIRC, we are unable to login with AD creds with the issue present in any version newer than 8.0 in our DMZ.

**Comment by West** [comment]
Anything?

**Comment by RBoulton-BT** [comment]
This would not stop login, this is only an issue where config commands incorrectly report an error clearing the cache. Could you clarify what you are saying your issue is?

To clarify this isse, if you see the error message when running config then running 
pbis ad-cache --delete-all --force-offline-delete true

Will result in a successful clearing of the cache.

This should certainly not result in any login issues.

**Comment by luflores** [comment]
I am see ing the same issue, im my case it is online

pbis status | grep -i status
LSA Server Status:
	Status:        Online

**Comment by luflores** [comment]
Would there be any setting to turn this off?

**Comment by RBoulton-BT** [comment]
You'd need to grep -i offline to find any offline domains, it's not always on the Status line.

As discussed, in general you would not want the cache being cleared when a domain is offline. It sounds like some people have environments where certain domains will always appear offline to certain agents.

If you have domains that will always appear offline, have you considered ignoring them using the DomainManagerExcludeTrustList config setting?

/opt/pbis/bin/config DomainManagerExcludeTrustList offlinedomain.company.com

then restart lwsmd.

**Comment by luflores** [comment]
Thanks I will give that a try

. : | : . : | : .  Luis E. Flores  |  Systems Engineering  |  lef@cisco.com<mailto:lef@cisco.com>  |  919.368.5901  | Meeting Room<http://cs.co/lef>

On Jul 20, 2017, at 4:48 AM, Richard Boulton <notifications@github.com<mailto:notifications@github.com>> wrote:


You'd need to grep -i offline to find any offline domains, it's not always on the Status line.

As discussed, in general you would not want the cache being cleared when a domain is offline. It sounds like some people have environments where certain domains will always appear offline to certain agents.

If you have domains that will always appear offline, have you considered ignoring them using the DomainManagerExcludeTrustList config setting?

/opt/pbis/bin/config DomainManagerExcludeTrustList offlinedomain.company.com<http://offlinedomain.company.com>

then restart lwsmd.

**Comment by Prakashadapala** [comment]
Could some one help me to understand, Why adjoin is impacting the network on linux servers. 
When we tried to join the AD all the virtual IP's on the network are coming downor) reloading

**Comment by rbest-bt** [comment]
please log a new issue
