### ISSUE TITLE
Upgrade to Ubuntu 20.04 on notebook

### ISSUE THREAD

**Issue by cloud81** [BeyondTrust/pbis-open#301]
**Version**: 9.1.0.551
**OS/Distro**: Ubuntu desktop 18.04 - Gnome3 desktop
**Issue/Impact**:
Hi,
I just installed pbis-open version 9.1.0.551 and I would like to know if I can upgrade my notebook from Ubuntu 18.04 to Ubuntu 20.04 without breaking my AD connection for logins.

**Comment by dmorash-BT** [comment]
The upgrade should be fine as long as you check your current PAM configuration.  You can always leave the domain and rejoin again.  See man domainjoin-cli.

**Comment by cloud81** [comment]
> The upgrade should be fine as long as you check your current PAM configuration. You can always leave the domain and rejoin again. See man domainjoin-cli.

Hi, thanks for your reply, I'll try with unjoin, upgrade and rejoin and let you know.

**Comment by rbest-bt** [comment]
Leave > upgrade > join
This should be enough depending on the files modified during the upgrade. Some OS might clear out required files so we recommend uninstall also.

See:
https://www.beyondtrust.com/docs/ad-bridge/getting-started/installation/install-agent/upgrade-os.htm

**Comment by cloud81** [comment]
Still have to try, I'll do for sure in the next weeks, thanks for suggestion!

**Comment by cloud81** [comment]
All done! Thanks ;-)
