### ISSUE TITLE
Multiple AD Site

### ISSUE THREAD

**Issue by hasanakgoz** [BeyondTrust/pbis-open#303]
Hello,
I have more than one Active Directory site. I don't  want the server to logon another sites. Each server must be logged in from its own site. When I check the tcpdump logs, I see that it tries to connect with other active directory sites. I added it to the blacklist as follows. But still trying to go to other sites. How do I take action/option so that it only talks to one Active Directory or one site? 

Thanks
/opt/pbis/bin/config BlacklistDC "1.2.3.4", "1.2.3.5"

OS/Distro:

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

box@ftp01:/home/box# pbis status
LSA Server Status:

Compiled daemon version: 9.1.0.551
Packaged product version: 9.1.551.2

**Comment by rbest-bt** [comment]
BlacklistDC only prevents netlogon from connecting to those DCs, not the site. This could be managed in a few ways within Active Directory depending on the setup for the sites. 

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
