### ISSUE TITLE
issue when Domain Controller rebooted

### ISSUE THREAD

**Issue by DustScripts** [BeyondTrust/pbis-open#307]
Had an issue when a domain controller rebooted that it locked up from anybody logging into the server even local accounts.  

Soon as I rebooted the host within vmware, and the reboot stopped pbis it allowed ssh and login connections.  login wouldn't come back with a password prompt and ssh just wouldn't connect.  So we are looking at what could have caused this on particular server but not others.

**Comment by rbest-bt** [comment]
Please upgrade to Active Directory Bridge Enterprise. If the issue still exists then please submit a ticket to our service team and we’ll have a look for you.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
