### ISSUE TITLE
Linker Error: Undefined Reference to dlopen, dlclose, dlerror, dlsym

### ISSUE THREAD

**Issue by mikeym88** [BeyondTrust/pbis-open#309]
**Version**: 9.1.2 (commit 7119ef7)
**OS/Distro**: Ubuntu desktop 18.04 - unity desktop (in a VirtualBox 6.1.18 VM running on a Windows 10 Enterprise host)
**Issue/Impact**: Unable to make package on Ubuntu.

**Output/Error**:
```
              [link] /opt/pbis/libexec/verify-sd (host/x86_64)
stage/opt/pbis/lib/liblwadvapi_nothr.so: undefined reference to `dlopen'
stage/opt/pbis/lib/liblwadvapi_nothr.so: undefined reference to `dlclose'
stage/opt/pbis/lib/liblwadvapi_nothr.so: undefined reference to `dlerror'
stage/opt/pbis/lib/liblwadvapi_nothr.so: undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
              [link] FAILED: 'gcc' '-o' 'stage/opt/pbis/libexec/verify-sd' 'object/reskit/security-descriptor/verify-sd.verify-sd.host.x86_64.o' '-Lstage/opt/pbis/lib' '-m64' '-O0' '-g' '-Wl,-rpath,/opt/pbis/lib' '-Wl,-rpath-link,stage/opt/pbis/lib' '-llwadvapi_nothr' '-llwbase' '-llwbase_nothr'
Makefile:13061: recipe for target 'stage/opt/pbis/libexec/verify-sd' failed
make: *** [stage/opt/pbis/libexec/verify-sd] Error 1
make: *** Waiting for unfinished jobs....
```

**Steps to Reproduce**:

Install commands:
```
mkdir debug && cd debug
../configure --debug --build-isas=x86_64
make -j2 package
```
**Note**: Running `configure` without the `build-isas` flag results in an error: `could not determine endianness` (as mentioned in #124).

**Potential Fix**:

Add `'-ldl'` to linker options, as shown in this stackoverflow.com answer: https://stackoverflow.com/questions/956640/linux-c-error-undefined-reference-to-dlopen/956698#956698. When I ran the following command manually, it seemed to work:

```
'gcc' '-o' 'stage/opt/pbis/libexec/verify-sd' 'object/reskit/security-descriptor/verify-sd.verify-sd.host.x86_64.o' '-Lstage/opt/pbis/lib' '-m64' '-O0' '-g' '-Wl,-rpath,/opt/pbis/lib' '-Wl,-rpath-link,stage/opt/pbis/lib' '-llwadvapi_nothr' '-llwbase' '-llwbase_nothr' '-ldl'
```

**Comment by rbest-bt** [comment]
pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
