### ISSUE TITLE
Authentication is taking more than 5 min due to token size exceeds 1024 bytes

### ISSUE THREAD

**Issue by teodororios** [BeyondTrust/pbis-open#31]
Hi guys!!!

We're facing issues when we try to authenticate with PBIS 8.2.2-2993 in an Active Domain using users where the token size exceeds 1024 bytes. Users are able to log in the servers but after 5 min which is not acceptable. We have enabled verbose mode and we are getting this cache error in the log:

20170412092522:VERBOSE:lsass:AD_OnlineQueryMemberOfForSid():lsass/server/auth-providers/ad-open-provider/online.c:4369: Cache entry for user's group membership for sid S-1-5-21-329068152-1454471165-1417001333-2254287 is incomplete

If we try with a test user with a loken size lower than 1024, user logs very quickly. I´ve checked a similar issue here (group membership won't resolve completely) and we have tried the solution for it, install the last beta PBIS version (8.5.3) that fixes BUG 84274 - fix group membership lookup for ldap queries in PBIS Open but it doesn´t work either. 

It's not a solution to reduce group membership for users because we're not the Domain administrator and they're based in very complicated Company policies.

Any suggestions?.
Thx in advance.

**Comment by RBoulton-BT** [comment]
It sometimes helps in scenarios with very large group memberships to enable the name service cache daemon (nscd) on the host. Assuming you're running on a platform that supports this.
