### ISSUE TITLE
Unable to change local user password - 'token manipulation error'

### ISSUE THREAD

**Issue by alexray92** [BeyondTrust/pbis-open#310]
Is there a way to change the password for local accounts when you have PBIS set with AssumeDefaultDomain so you can login to domain accounts without @domain.tld or domain.tld\username?  I think that's the problem here; it treats 'root' as 'root@domain.tld' instead of trying to change the local shadow password.

**Version**: 9.1.0.551
**OS/Distro**: Ubuntu Server 20.04
**Issue/Impact**: Unable to change local user password

 1. systemctl status lwsmd.service
* lwsmd.service - BeyondTrust AD Bridge Service Manager
     Loaded: loaded (/lib/systemd/system/lwsmd.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2021-02-09 08:44:38 PST; 1 day 23h ago

 2. /opt/pbis/bin/lwsm list
lwreg          running (container: 558)
dcerpc         stopped
eventlog       running (container: 587)
lsass          running (container: 665)
lwio           running (container: 638)
netlogon       running (container: 613)
rdr            running (io: 638)
reapsysl       running (container: 702)
usermonitor    stopped

 3. /opt/pbis/domainjoin-cli query
(shows correct name, domain, DN)

 4. pbis status
LSA Server Status:

Compiled daemon version: 9.1.0.551
Packaged product version: 9.1.551.2
Uptime:        1 days 23 hours 11 minutes 52 seconds

[Authentication provider: lsa-activedirectory-provider]

        Status:        Online
        Mode:          Un-provisioned
...

 5. /opt/pbis/bin/enum-users
(shows a whole bunch of AD users)

**Output/Error**:
passwd: Authentication token manipulation error
passwd: password unchanged

**Steps to Reproduce**:
 1. passwd (local user account)
 2. Receive "passwd: Authentication token manipulation error" "passwd: password unchanged" immediately

I'm, guessing it's trying to change the password as if it were a domain account, I'm not sure if there's a different way I'm supposed to specify that it's local (like on Windows I might do hostname\localaccount or .\localaccount).

log shows

20210211111241:DEBUG:lsass:AD_FindObjectByNameTypeNoCache():lsass/server/auth-providers/ad-open-provider/online.c:2826: Error code: 40081 (symbol: LW_ERROR_NOT_SUPPORTED)
20210211111241:DEBUG:lsass:LsaAdBatchFindObjects():lsass/server/auth-providers/ad-open-provider/batch.c:1761: Batch Find Objects 1
20210211111241:DEBUG:lsass:LsaSrvFindProviderByName():lsass/server/api/state.c:128: Error code: 40040 (symbol: LW_ERROR_INVALID_AUTH_PROVIDER)
20210211111241:DEBUG:lsass:LsaSrvProviderServicesDomain():lsass/server/api/provider.c:160: Error code: 40040 (symbol: LW_ERROR_INVALID_AUTH_PROVIDER)
20210211111241:VERBOSE:lsass:LsaAdBatchMarshal():lsass/server/auth-providers/ad-open-provider/batch_marshal.c:596: Did not find object by NT4 name 'localuser'
20210211111241:DEBUG:lsass:LsaAdBatchFindSingleObject():lsass/server/auth-providers/ad-open-provider/batch.c:1517: Error code: 40071 (symbol: LW_ERROR_NO_SUCH_OBJECT)
20210211111241:DEBUG:lsass:AD_FindObjectByNameTypeNoCache():lsass/server/auth-providers/ad-open-provider/online.c:2811: Error code: 40071 (symbol: LW_ERROR_NO_SUCH_OBJECT)
20210211111241:DEBUG:lsass:AD_OnlineFindObjectByName():lsass/server/auth-providers/ad-open-provider/online.c:3553: Error code: 40008 (symbol: LW_ERROR_NO_SUCH_USER)
20210211111241:VERBOSE:lsass-ipc:lwmsg_peer_task_handle_assoc_error():lwmsg/src/peer-task.c:625: (session:f9ce1f84b1281d6b-ee9aa60b0b3b51fd) Dropping: LWMSG_STATUS_PEER_CLOSE
20210211111241:VERBOSE:lsass-ipc:lwmsg_peer_task_handle_assoc_error():lwmsg/src/peer-task.c:625: (session:892df020df7017df-7a4d030f0502def0) Dropping: LWMSG_STATUS_PEER_CLOSE

**Comment by alexray92** [comment]
Actually, looks like I _might_ have figured it out.  Setting UserDomainPrefix to "" and leaving/rejoining domain - keeping AssumeDefaultDomain true - seems to let me both change local account passwords and login without the domain in the username when trying LDAP auth.

**Comment by rbest-bt** [comment]
pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
