### ISSUE TITLE
Frequently AD authentication to server fails and we noticed this happens when PBIS switch to anther Domain controller. How to specify the domain controller while joining the server to domain using pbis ?  Also let me know is there any option to specify only few Domain controller in configuration so that the switch happens only between them ?  

### ISSUE THREAD

**Issue by bmrajan12** [BeyondTrust/pbis-open#311]
**Version**: 8.5.4.334
**OS/Distro**: Ubuntu desktop 16.04 - unity desktop
**Issue/Impact**:
*Note: replace content with your own*
When reporting an issue it's important that we have as much detail as you can provide. The following is a list of commands to check.
 1. systemctl status lwsmd.service
 2. /opt/pbis/bin/lwsm list
 3. /opt/pbis/domainjoin-cli query
 4. pbis status
 5. /opt/pbis/bin/enum-users
 6. attach logs
  - /opt/pbis/bin/lwsm set-log-target -p lsass -  file /tmp/lsass.log
  - /opt/pbis/bin/lwsm set-log-level -p lsass - debug
  - attach log

**Output/Error**:

**Steps to Reproduce**:
 1. install command
 2. Domainjoin command
 3. Command that returns issue

**Comment by dmorash-BT** [comment]
You can ignore specific DC's by setting the BlackListDC config setting.  

- First use `/opt/pbis/bin/get-dc-list <domain>` to get the list of DC's for the specified domain.

- Then use `/opt/pbis/bin/config BlackListDC <ip address>`  to specify the DC's to ignore.  If you need to specify more than one, provide the ip's separated by spaces, e.g. `/opt/pbis/bin/config BlackListDC <ip address> <ip address>`

Running `/opt/pbis/bin/config` will provide information on it's usage.
