### ISSUE TITLE
Domain Join problem

### ISSUE THREAD

**Issue by AnkitMalhotra22** [BeyondTrust/pbis-open#312]
The users are lead to join the domain each time after the pc goes to sleep.
OS version we using is Ubuntu 20.04
The issue occurs to 8 out of 10 PC's. If possible guide me to the solution.
Thank you

**Comment by rbest-bt** [comment]
Please upgrade to Active Directory Bridge Enterprise. If the issue still exists then please submit a ticket to our service team and we’ll have a look for you.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
