### ISSUE TITLE
Samba-interop-install needed after updates and reboots

### ISSUE THREAD

**Issue by hanserasmus** [BeyondTrust/pbis-open#314]
**Version**: 9.5.0.55
**OS/Distro**: Ubuntu Server 20.04 LTS
**Issue/Impact**: Samba stops working after updates.

Hi

We have all of our servers correctly joined to a domain. Currently we are seeing an issue whenever samba or samba-related packages are updated, or the libpam-module gets updated, that samba shares on the client side stop working. The fix for this is to manually only rerun `samba-interop-install --install` and reboot the server, then all works again. This is without making any other config changes.

The same packages can be updated on an Ubuntu 16.04 install with Samba 4.3, and nothing will break. This initially seemed related to samba > 4.8.0 requiring winbind service, but even after installing and enabling that, it still breaks.

My workaround has been to put `samba-interop-install --install && systemctl restart smbd.service nmbd.service` into crontab @ reboot, but that feels icky. 

Any ideas what might be causing this issue and what would be the permanent fix?
Regards

**Comment by rbest-bt** [comment]
This is noted in our documentation. See the Upgrade section of the following guide
https://www.beyondtrust.com/docs/ad-bridge/how-to/integration/samba/index.htm

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
