### ISSUE TITLE
Option to update a computer accounts password?

### ISSUE THREAD

**Issue by matt-radtke-sw** [BeyondTrust/pbis-open#315]
Our AD administrators would like to sort for old/off/broken machines by sorted by the last change of a computer's password.  They have requested the equivalent of 

`net ads changetrustpw `

Does pbis-open provide this or equivalent?  Thanks!

**Comment by rbest-bt** [comment]
This option exists in the licensing tool of Active Directory Bridge Enterprise.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
