### ISSUE TITLE
Sudo failing for domain users 

### ISSUE THREAD

**Issue by andrescontilde** [BeyondTrust/pbis-open#318]
**Version**: 9.1.0.551
**OS/Distro**: AIX 7.2
**Issue/Impact**: Domain users can't run sudo 

I think this has more to do with sudo configuration than pbis-open, but anyway, I'm posting here just in case it is a known condition. I have some AIX boxes that are failing when I try to run sudo with my domain users. What is misleading is that with the same exact version, configuration and user I can run sudo from another servers and I can't find any difference. 

Maybe anyone in here can suggest what can I look for in order to investigate what could be going on. 

I'm clueless in this one so I don't know which information could be valuable to share in this issue. 

Any information, tip or clue will be very well appreciated.

**Comment by davidmorash** [comment]
I'd check /etc/security/methods.cfg, I believe you need to add an LSASS stanza with a program = /usr/lib/security/LSASS line.

I believe this is a known issue, but I'm without the ability to lookup what the exact solution is and I don't have access to an AIX machine at present, so this is all from memory.

IIRC

Sep. 2, 2021 8:44:31 p.m. andrescontilde ***@***.***>:

**Comment by davidmorash** [comment]
The workaround for this is /etc/security/login.cfg, usw stanza, AUTH_TYPE must be set to PAM_AUTH.   The domain join code should be already setting that but isn't for some reason.

**Comment by andrescontilde** [comment]
Thanks @davidmorash 

I have checked methods.cfg and login.cfg but both files have the same values as other servers that are working fine. 

I see this has nothing to do with the authentication process that is working as expected but only with the sudo command execution. I have tested other versions of sudo and a couple of combinations of values but it has the same results. 

Maybe some suggestions regarding sudo configuration and something that needs to be set for sudo to work with AD users. 

Thanks again.

**Comment by rbest-bt** [comment]
There is not much to the configuration which you can find information on here:
https://www.beyondtrust.com/docs/ad-bridge/getting-started/linux-admin/sudoers-file.htm

I recommend using visudo to validate the file on close. 

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
