### ISSUE TITLE
Can log in with password, cannot log in with ssh private key

### ISSUE THREAD

**Issue by exeter-matthew-wakeling** [BeyondTrust/pbis-open#319]
**Version**: Probably 7.1.0.1203 (I didn't install it)
**OS/Distro**: Bright Cluster Manager 7.0, Based on Scientific Linux release 6
**Issue/Impact**: I can log in with my username/password from AD using ssh. However, I cannot log in using ssh with a private key that is correctly stored in .ssh/authorized_keys, unless I am simultaneously already logged in using ssh on a separate connection, or have recently been logged in. 

For instance, if I have left the server without logging in for a while, and try to log in using ssh with a private key, then it will fail, reliably and repeatedly. If I then log in without the private key, and use my password instead, then it will succeed. If I then try to log in using the private key, it will also succeed.

The PBIS configuration uses a RequireMembershipOf with a group that I am a member of. When logging in fails, then a message appear in /var/log/secure saying:

```
sshd[3179207]: [lsass-pam] [module:pam_lsass]User mw501 is denied access because they are not in the 'require membership of' list
```

However, I have observed this happening, while at the same time a "getent group groupname" correctly states that I am a member of the correct group. Likewise, my cron jobs all fail to run, and a message in /var/log/secure states:

```
crond[2577107]: [lsass-pam] [module:pam_lsass]User mw501 is denied access because they are not in the 'require membership of' list
```

But when I log in via ssh using my password, then my cron jobs start running again.

 1. systemctl status lwsmd.service - This server doesn't have systemctl.

 2. /opt/pbis/bin/lwsm list
```
lwreg          running (container: 1045927)
dcerpc         stopped
eventlog       running (container: 1045963)
lsass          running (container: 3759534)
lwio           running (container: 1046030)
netlogon       running (container: 1045997)
rdr            running (io: 1046030)
reapsysl       running (container: 1046114)
usermonitor    stopped
```
 3. /opt/pbis/bin/domainjoin-cli query
```
Name = <correct server name>
Domain = <correct AD domain>
Distinguished Name = <correct DN>
```
 4. pbis status - There is no "pbis" in the path.
 5. /opt/pbis/bin/enum-users - This returns a very long list of users.
 6. attach logs
  - /opt/pbis/bin/lwsm set-log-target -p lsass -  file /tmp/lsass.log
This returns:
```
Error: LW_ERROR_NO_SUCH_SERVICE (41204)
No service with the specified name exists
```

**Comment by davidmorash** [comment]
Can you post your /etc/nsswitch.conf file and your pam stack for auth?

**Comment by rbest-bt** [comment]
Please upgrade to Active Directory Bridge Enterprise. If the issue still exists then please submit a ticket to our service team and we’ll have a look for you.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
