### ISSUE TITLE
project is no longer maintained without an explanation

### ISSUE THREAD

**Issue by maxadamo** [BeyondTrust/pbis-open#320]
could you please add a note in the README to explain what is the future of this project, why this project is not maintained, and why there aren't any type of updates, not even security updates, or new releases for newer versions of OS? 

I noticed that the enterprise version is being updated, I decided to contact your sale department but they tried to sell me a different product (a replacement for LastPass).

**Comment by rbest-bt** [comment]
I'm sorry to hear that. If you reach out to sales in the future, give them my name and I'll make sure you get what you're looking for. 

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
