### ISSUE TITLE
samba4 user lever permissions homedir issue

### ISSUE THREAD

**Issue by jelayeb** [BeyondTrust/pbis-open#33]
Hi 

i used to have a samba server 3.6 configured with winbind to auth against windows AD, and was everything fine, untill i migrated to samba 4.2 and joined the domain with pbis-open. 
everything is configured fine and samba is running and the integration components installed according to the manual of pbis, 

the issue i found is samba can not control the share with user lever permissions. like homedirs as they have 700 permissions then the users can not access thier home dirs, and receive access denied.  unless i change permissions to 755 or change the group domain^users  and give it read permissions only, then the users have read access only. 
other shares works fine as they are shared with group permissions only. 

another strange behavior when i give write permissions to the group so the users can write on home dir for testing, if i right click and create a new folder then then 5 newfolders will be created  newfolder newfolder1 newfolder2 newfolder3 newfolder4
PBIS Vesrion: pbis-open-8.5.0-153.x86_6
OS: Centos 6.8
Samba: samba4-4.2.10-7.el6_8.x86_64

i wish someone can advice with this
here are my configs 
`[global]
        msdfs root              = yes
        security = ads
        workgroup = DOMAIN
        realm = DOMAINNAME.COM
        netbios name = server01
        machine password timeout = 0
        log level = 10
        log file = /var/log/samba/smbd.log
        Kerberos method = dedicated keytab
        dedicated keytab file = /etc/krb5.keytab
        template homedir         = /export/home/%U
        max protocol                                = SMB2
        include  = /etc/samba/shares.conf
[homes]
        comment                         = Home Directory of User %U in Doamin %D
        browseable                      = no
        writable                        = yes
        path                            = /export/home/%S
        create mask                     = 640
        directory mask                  = 2750

Pbis-dump

AllowDeleteTo ""
AllowReadTo ""
AllowWriteTo ""
MaxDiskUsage 104857600
MaxEventLifespan 90
MaxNumEvents 100000
DomainSeparator "+"
SpaceReplacement "^"
EnableEventlog false
SaslMaxBufSize 16777215
Providers "ActiveDirectory"
DisplayMotd false
PAMLogLevel "error"
UserNotAllowedError "Access denied"
AssumeDefaultDomain true
CreateHomeDir false
CreateK5Login true
SyncSystemTime true
TrimUserMembership true
LdapSignAndSeal false
LogADNetworkConnectionEvents true
NssEnumerationEnabled true
NssGroupMembersQueryCacheOnly true
NssUserMembershipQueryCacheOnly false
RefreshUserCredentials true
CacheEntryExpiry 14400
DomainManagerCheckDomainOnlineInterval 300
DomainManagerUnknownDomainCacheTimeout 3600
MachinePasswordLifespan 2592000
MemoryCacheSizeCap 0
HomeDirPrefix "/export/home"
HomeDirTemplate "%H/%U"
RemoteHomeDirTemplate ""
HomeDirUmask "022"
LoginShellTemplate "/bin/sh"
SkeletonDirs "/etc/skel"
UserDomainPrefix "DOMAIN"
DomainManagerIgnoreAllTrusts false
DomainManagerIncludeTrustsList
DomainManagerExcludeTrustsList
RequireMembershipOf
Local_AcceptNTLMv1 true
Local_HomeDirTemplate "%H/%U"
Local_HomeDirUmask "022"
Local_LoginShellTemplate "/bin/sh"
Local_SkeletonDirs "/etc/skel"
UserMonitorCheckInterval 1800
LsassAutostart true
EventlogAutostart true
BlacklistDC
`

**Comment by jelayeb** [comment]
i've tested the same config on samba 3.5 and centos 5 and works fine with home dirs.

**Comment by skyph** [comment]
Same here on Debian Jessie with Samba 4. User level permissions don't apply to folders/files. Group level permissions work OK. In my case issue goes beyond homedir permissions.
On Debian Wheezy with Samba 3.5 permissions works fine.

**Comment by rbest-bt** [comment]
Can you try 8.5.6 and let me know if the issue persists?

**Comment by rbest-bt** [comment]
Tested on Debian 9.3 with samba 4.5.12-Debian with home directory 700
> [homes]
	comment = Home Directory of User %U in Domain %D
	path = /home/PBIS/%U
	browseable = No
	create mask = 0640
	directory mask = 0750
	read only = No
	valid users = %U

I'm not experiencing the issues you describe.
> # ls -l 
>total 4
drwx------ 3 PBIS\samba1 PBIS\domain^users 4096 Dec 13 06:31 samba1
># ls -l ./samba1/
>total 4
drwxr-x--- 2 PBIS\samba1 PBIS\domain^users 4096 Dec 13 06:31 New folder
-rw-r----- 1 PBIS\samba1 PBIS\domain^users    0 Dec 13 06:31 New Text Document.txt

I would need more detailed guide on your setup in order to reproduce the issue.

**Comment by rhinosys** [comment]
I have same issue on

redhat 7.3 samba 4.6.2-12.el7_4.x86_64

When i have 700 on folder same user have access denied.

regards,

**Comment by rbest-bt** [comment]
9.1.0 added a fix for winbind 4.6.2+ which might address the issue.

pbis-open will longer receive updates and will be archive. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
