### ISSUE TITLE
Full Domain Queries Smash CacheDB

### ISSUE THREAD

**Issue by ferricoxide** [BeyondTrust/pbis-open#34]
We make use of PBIS-open to allow our non-ephemeral Linux instances to authenticate against Active Directroy. Ours is mostly a large Windows shop with a large backing AD service (several tens of thousands of user and group entries). For the most part, PBIS Open works well for the Linux systems it's used on. However, if an Linux administrator makes the mistake of doing a full enumeration of the AD name-space (e.g., with the equivalent of a `getent passwd` or `getent groups`), PBIS has a stroke. There's only two ways to recover from the situation:

* Wholly uninstall - ensuring to nuke the various `*/pbis/*` directories and files
* Nuke the sqlite cache DB and re-join the host to the domain

Looking for tips on how we might prevent PBIS from crushing its sqlite cache DB other than "don't (accidentally) try to enumerate 80,000 user objects".

**Comment by RBoulton-BT** [comment]
There is a MemoryCacheSizeCap option you can set via the /opt/pbis/bin/config utility which I believe sets the maximum bytes to store in the memory cache.

Maybe try:
/opt/pbis/bin/config MemoryCacheSizeCap 16777216
