### ISSUE TITLE
DNS error

### ISSUE THREAD

**Issue by wernerbarnard** [BeyondTrust/pbis-open#35]
Hi,

So our DNS/DC is on Azure, and i'm trying to join an Ubuntu machine that's on AWS to the domain.

How can I troubleshoot the below error?  Is there a log file somewhere?

`Error: DNS_ERROR_BAD_PACKET [code 0x0000251e]`
`A bad packet was received from a DNS server. Potentially the requested address does not exist.`

**Comment by rbest-bt** [comment]
Can the Ubuntu machine ping the AWS domain?

**Comment by wernerbarnard** [comment]
Hi @rbest-bt 

not 100% what you're asking.

Domain Controller = Windows on Azure
Client (that wants to join) = Ubuntu 16.04 on AWS

The ubuntu machine is on the internet and DNS is working, can ping domains fine.

**Comment by rbest-bt** [comment]
We do not have an azure setup at this time. It's in the backlog to test against.

**Comment by rbest-bt** [comment]
Some things that could pose an issue. Are the systems on the same network? Is there a NAT router in the way? Can you resolve the actual IP of the domain or an external IP?

**Comment by wernerbarnard** [comment]
Hi @rbest-bt 

I resolved this issue by adding "dns-nameserver" as the domain controller in /etc/network/interfaces before attempting "domainjoin-cli".

Not sure what the network consists of in Azure, but the 2 servers were in the same subnet - i.e. Domain Controller = 1.0.0.4, Server to join = 1.0.0.35 (Example addresses).

**Comment by rbest-bt** [comment]
Thanks for posting your solution.
