### ISSUE TITLE
pbis-open on lubuntu 16.04.1 does not compile 

### ISSUE THREAD

**Issue by Neill-R** [BeyondTrust/pbis-open#37]
Sorry if this is in the wrong place but I am new to all of this. any help or advice would be much appreciated 

I want the pbis-open software installed on my machine (HP-G61 laptop) 4gb ram running lubuntu 16.04 desktop. I tried 8-5 and then Master. I followed the instructions
I have run the same on my xeon-4core server and results shown are from there.

https://github.com/BeyondTrust/pbis-open/commit/4b208ea6061aa89d465c0894dafe9724e04d00d2

sudo apt-get install build-essential fakeroot devscripts debhelper autoconf automake libtool libncurses5-dev flex bison libpam0g-dev libxml2-dev libpopt-dev libglade2-dev lib32ncurses5 lib32z1 libc6-dev-i386 gcc-multilib

note ia32-libs being replaced by  lib32ncurses5 lib32z1 

Package ia32-libs is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  lib32ncurses5 lib32z1

sudo apt-get install gawk

I downloaded the zip file and extracted the folder and it contents to by home folder Documents 
cd ~/Documents/pbis-open-master/

mkdir debug && cd debug
sudo ../configure --debug
sudo make -j4  package  ## where XX is 2x CPU cores

**I got warnings** 
          [compile] btkrb5/ktldap.c (host/x86_64)
../btkrb5/keytab.c: In function ‘KtKrb5AddKeyA’:
../btkrb5/keytab.c:414:19: warning: implicit declaration of function ‘KtLdapGetBaseDnA’ [-Wimplicit-function-declaration]
         dwError = KtLdapGetBaseDnA(pszDcName, &pszBaseDn);
                   ^
../btkrb5/keytab.c:419:23: warning: implicit declaration of function ‘KtLdapGetKeyVersionA’ [-Wimplicit-function-declaration]
             dwError = KtLdapGetKeyVersionA(pszDcName,
                       ^
../btkrb5/keytab.c: In function ‘KtKrb5GetSaltingPrincipalA’:
../btkrb5/keytab.c:924:15: warning: implicit declaration of function ‘KtLdapGetSaltingPrincipalA’ [-Wimplicit-function-declaration]
     dwError = KtLdapGetSaltingPrincipalA(pszDcName,
               ^
../btkrb5/keytab.c: At top level:
../btkrb5/keytab.c:1078:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
 KtKrb5GetUserSaltingPrincipalA(https://github.com/BeyondTrust/pbis-open/commit/4b208ea6061aa89d465c0894dafe9724e04d00d2
 ^
           [compile] lwadtool/adtool/main.c (host/x86_64)
  **Then error**
         [compile] lwsm/server/driver.c (host/x86_64)
../lwsm/server/main.c:40:20: fatal error: ctexec.h: No such file or directory
compilation terminated.
           [compile] FAILED: 'gcc' '-m64' '-O0' '-g' '-Wall' '-Werror' '-Wmissing-prototypes' '-I../lwsm/server/.' '-Iobject/lwsm/server/.' '-I../lwsm/server/../include' '-Iobject/lwsm/server/../include' '-DDEBUG=1' '-DLWSM_DISABLE_DEPRECATED' '-DLWSM_BUILD' '-Istage/opt/pbis/include' '-DHAVE_CONFIG_H' '-D_MK_HOST_X86_64' '-D_MK_HOST' '-fPIC' '-MMD' '-MP' '-MF' '.MakeKitDeps/object_lwsm_server_main.lwsmd.host.x86_64.dep' '-o' 'object/lwsm/server/main.lwsmd.host.x86_64.o' '-c' '../lwsm/server/main.c'
Makefile:7445: recipe for target 'object/lwsm/server/main.lwsmd.host.x86_64.o' failed
make: *** [object/lwsm/server/main.lwsmd.host.x86_64.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by rbest-bt** [comment]
Thanks for the input. I'm currently working on updating the README.md to address compile errors on 17.04. I'll try and get a lubuntu box up to try it out.

Have you tried the pre-compiled installer?
[pbis-open-8.5.3.293.linux.x86.deb.sh](https://github.com/BeyondTrust/pbis-open/releases/download/8.5.3/pbis-open-8.5.3.293.linux.x86.deb.sh)
[pbis-open-8.5.3.293.linux.x86_64.deb.sh](https://github.com/BeyondTrust/pbis-open/releases/download/8.5.3/pbis-open-8.5.3.293.linux.x86_64.deb.sh)

**Comment by rbest-bt** [comment]
I'm able to reproduce the issue on lubuntu 16.04:
../lwsm/server/main.c:40:20: fatal error: ctexec.h: No such file or directory

**Comment by rbest-bt** [comment]
Can you try cutting down the jobs to 2:
> make -j2 package

I've noticed this happening when I have the job count high.

**Comment by viralmutant** [comment]
Is this resolved ?
I am hitting this with 16.04 with no job count, just plain
`make package`

**Comment by rbest-bt** [comment]
Can you please log a new issue for this? It is not the same as the original issue.

**Comment by viralmutant** [comment]
The ctexec.h failure is exactly same as this one.
However I have filed new issue with all the details and workarounds
