### ISSUE TITLE
pbis doesn't do nothing

### ISSUE THREAD

**Issue by mmiat** [BeyondTrust/pbis-open#38]
I've Ubuntu 16.04.2 LTS, no DE
I've launched:

> /opt/pbis/bin/domainjoin-cli join MYDOMAIN.LOCAL admin@MYDOMAIN.LOCAL

it gives me SUCCESS, but nothing happens

wbinfo -u give me

> Error looking up domain users

and "/opt/pbis/bin/domainjoin-cli query" gives me empty domain

**Comment by rbest-bt** [comment]
wbinfo -u will not return anything unless you ran samba-interop-install. Also this it not the best method for listing users, use /opt/pbis/bin/enum-users instead.

As for the empty domain, what does your logs says about the domainjoin?

**Comment by mmiat** [comment]
I suppose I've not give the right commands...
I simply run "/opt/pbis/bin/domainjoin-cli join domainName joinAccount" but maybe it's not enough
in pdf guide I can't find any other step

where can I found last official guide? I've found [this](https://community.spiceworks.com/how_to/80336-join-ubuntu-14-04lts-to-a-windows-domain-using-pbis-open) but it's for an old ubuntu version

this evening I'll retry and post log
thanks

**Comment by rbest-bt** [comment]
That is the right command, just make sure your running it as root or sudo.

Current Enterprise documentation:
https://www.beyondtrust.com/resources/education/documentation/?subcategory=ad-bridge

I hope to create a section with all the documentation uploaded to github.

**Comment by mmiat** [comment]
I've re-given all commands, including "samba-interop-install --install", as write [here](https://gist.github.com/apsbiker/5cd9cbd0fbeb74b94d12)

I have an error:

> wbinfo: relocation error: wbinfo: symbol wbcPingDc2, version WBCLIENT_0.10 not defined in file libwbclient.so.0 with link time reference

but it works, now my server is joined to mydomain
thanks

**Comment by rbest-bt** [comment]
Glade to hear it works for you. Here is also a direct link to the [samba integration guide](https://www.beyondtrust.com/wp-content/uploads/documentation-pbis-samba-integration-guide.pdf?1456510450)

**Comment by mmiat** [comment]
I've a new problem, I edit my /etc/sudoers with visudo but I can't add "Domain Admins" group, but I think it's a problem with Ubuntu implementation. I've tried many ways (with spaces, commas, etc). I'll search in Ubuntu forums. Thanks again.

**Comment by rbest-bt** [comment]
There is an example in the [Quick Start guide](https://github.com/BeyondTrust/pbis-open/wiki/docs/PBIS_Open_Quick_Start.pdf). Note that to format needs to match exactly. So if you have AssumeDefaultDomain = True then you would not have the domain portion in the sudoers file.
