### ISSUE TITLE
add sparc solaris 10 to domain

### ISSUE THREAD

**Issue by kamilnew** [BeyondTrust/pbis-open#39]
when i try to add solaris 10 serwer do domain i got LW_ERROR_LDAP_SERVER_DOWN 0x00009d5e
dc closed an ldap connection in the middle of a query
ad server is in same vlan, firewall is off , ldap is working , when i snoop communication i see: 

LDAP:  ----- Lightweight Directory Access Protocol Header -----
LDAP:    *[LDAPMessage]
*** Decode length error, PDU length = 1456 ***
LDAP:       [Message ID]
LDAP:      Operation *[APPL 0: Bind Request]
*** Decode length error, PDU length = 1449 ***
LDAP:          [Version]
LDAP:          [Object Name]
LDAP:         Authentication: SASL *[3]
*** Decode length error, PDU length = 1440 ***
LDAP:             [OctetString]
LDAP:                  GSS-SPNEGO
LDAP:             [OctetString]
*** Decode length error, PDU length = 1424 ***
LDAP:              *** NOT PRINTED - Too long value ***
LDAP:

**Comment by kamilnew** [comment]
BTW same problem is on enterprise version

**Comment by rbest-bt** [comment]
Can you give me the list of commands up to this:
1. install method
2. domainjoin command
3. are you able to resolve domain and dc ip?

**Comment by kamilnew** [comment]
hi
im working on this problem with pbis support - this seems to be solaris specyfic
commands and dns resolving has beed checked and all is proper
