### ISSUE TITLE
Password Reset does not work

### ISSUE THREAD

**Issue by Kabe0** [BeyondTrust/pbis-open#40]
Ubuntu Gnome 17.04

We can login/out fine with the gnome login, but if a user is set to have their password reset, the login will notify them allowing them to put in a new password, but instead of changing the password the tool say's an error is thrown and fails to register the login.

I am unsure if this is related to the gnome login. Any suggestions?

**Comment by rbest-bt** [comment]
Installed gnome-shell on unity based version and it's working for me. Setting up ubuntugnome to try.

Are you having any issues with passwd? Have you made any changes to your pam files?

**Comment by Kabe0** [comment]
I have installed pam_mount but otherwise have not touched any of the other pam configurations.

This is what happens when you put in a password using su
```
su testok
Password:
Your password has expired
Current Password:
New password:
Re-enter password:
su: Authentication token manipulation error
```
If im already logged in as that user, passwd works fine.

**Comment by rbest-bt** [comment]
When you make changes to the pam configuration, you are changing the authentication workflow. Have a look at where pam_mount might be interfering with pam_lsass in regards to password changes. We have not tested pam_mount with PBIS but it should be possible.

I highly recommend to read up on the [PAM configuration file syntax](http://www.linux-pam.org/Linux-PAM-html/sag-configuration-file.html)

**Comment by Kabe0** [comment]
Ok I just tried it with a fresh instance of Ubuntu 17.04 gnome and ran into the exact same error. This is without anything installed beforehand.

This is what my common-auth looks like.
```
#
# /etc/pam.d/common-auth - authentication settings common to all services
#
# This file is included from other service-specific PAM config files,
# and should contain a list of the authentication modules that define
# the central authentication scheme for use on the system
# (e.g., /etc/shadow, LDAP, Kerberos, etc.).  The default is to use the
# traditional Unix authentication mechanisms.
#
# As of pam 1.0.1-6, this file is managed by pam-auth-update by default.
# To take advantage of this, it is recommended that you configure any
# local modules either before or after the default block, and use
# pam-auth-update to manage selection of other modules.  See
# pam-auth-update(8) for details.

# here are the per-package modules (the "Primary" block)
auth	[success=2 default=ignore]	pam_lsass.so 
auth	[success=1 default=ignore]	pam_unix.so nullok_secure try_first_pass
# here's the fallback if no module succeeds
auth	requisite			pam_deny.so
# prime the stack with a positive return value if there isn't one already;
# this avoids us returning an error just because nothing sets a success code
# since the modules above will each just jump around
auth	required			pam_permit.so
# and here are more per-package modules (the "Additional" block)
auth	optional			pam_cap.so 
# end of pam-auth-update config
```

**Comment by rbest-bt** [comment]
That file looks ok. You would also want to look at the other common- files to make sure pam_lsass is above pam_unix.
common-account
common-password
common-auth
common-session
common-session-noninteractive

I've retested this on ubuntugnome and I can not reproduce this.  I need a break down of your steps:
- version of ubuntu - https://wiki.ubuntu.com/UbuntuGNOME/GetUbuntuGNOME ?
- account initializing the login - root/local/AD
- How you are triggering the expired password? time out or must change on next login?
- any special setup for the ad account?
- have you tried on a different domain? is the domain read-only? Can the account password reset on a windows machine?

**Comment by Kabe0** [comment]
- Version is Ubuntu Gnome 17.04 64-bit
- "Force account to change password at next login" is what I am enabling on the user...
- The password reset works fine on Windows computers.
- The account is just a domain admin. I am just running the join <domain> <user> command.

I will have to get you the other details later.

**Comment by Kabe0** [comment]
Ok I tried with a few other configurations and still no luck. The domain is not a read only. I am initializing the account using the root administrator account with full permissions.

**Comment by Kabe0** [comment]
I found only these to files with the pam_lsass not at the top

common-session
common-session-noninteractive

```
# here are the per-package modules (the "Primary" block)
session [default=1]                     pam_permit.so
# here's the fallback if no module succeeds
session requisite                       pam_deny.so
# prime the stack with a positive return value if there isn't one already;
# this avoids us returning an error just because nothing sets a success code
# since the modules above will each just jump around
session required                        pam_permit.so
# The pam_umask module will set the umask according to the system default in
# /etc/login.defs and user settings, solving the problem of different
# umask settings with different shells, display managers, remote sessions etc.
# See "man pam_umask".
session optional                        pam_umask.so
# and here are more per-package modules (the "Additional" block)
session optional        pam_lsass.so
session required        pam_unix.so
session optional        pam_mount.so
session optional        pam_systemd.so
# end of pam-auth-update config
session required     pam_mkhomedir.so skel=/etc/skel umask=0022
```

```
# here are the per-package modules (the "Primary" block)
session [default=1]                     pam_permit.so
# here's the fallback if no module succeeds
session requisite                       pam_deny.so
# prime the stack with a positive return value if there isn't one already;
# this avoids us returning an error just because nothing sets a success code
# since the modules above will each just jump around
session required                        pam_permit.so
# The pam_umask module will set the umask according to the system default in
# /etc/login.defs and user settings, solving the problem of different
# umask settings with different shells, display managers, remote sessions etc.
# See "man pam_umask".
session optional                        pam_umask.so
# and here are more per-package modules (the "Additional" block)
session optional        pam_lsass.so
session required        pam_unix.so
# end of pam-auth-update config
```

**Comment by rbest-bt** [comment]
Next time you try a password reset can you gather the lsass logs. Below will set the logging and send it to /tmp/lsass.log
> /opt/pbis/bin/lwsm set-log-level lsass - debug; /opt/pbis/bin/lwsm set-log-target lsass - file /tmp/lsass.log

Send us the logs to openproject@beyondtrust.com
