### ISSUE TITLE
Can't Login on Scientific Linux 7

### ISSUE THREAD

**Issue by Caasi67** [BeyondTrust/pbis-open#41]
Running Scientific Linux 7 and I am unable to login with PBIS.  I'm able to install, join the domain, I can use the find user scripts just fine, the ID command works fine, getent passwd works fine, but it won't let me login with an AD account.

Here's /var/log/secure for an attempt:
Jun 12 10:52:43 gntcs-alit-hp1 sshd[5619]: Invalid user knoflicek from 144.92.163.197
Jun 12 10:52:43 gntcs-alit-hp1 sshd[5619]: input_userauth_request: invalid user knoflicek [preauth]
Jun 12 10:52:43 gntcs-alit-hp1 sshd[5619]: Postponed keyboard-interactive for invalid user knoflicek from 144.92.163.197 port 50527 ssh2 [preauth]
Jun 12 10:52:44 gntcs-alit-hp1 sshd[5621]: pam_unix(sshd:auth): check pass; user unknown
Jun 12 10:52:44 gntcs-alit-hp1 sshd[5621]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=dyn-144-92-163-197.genetics.wisc.edu
Jun 12 10:52:47 gntcs-alit-hp1 sshd[5619]: error: PAM: User not known to the underlying authentication module for illegal user knoflicek from dyn-144-92-163-197.genetics.wisc.edu
Jun 12 10:52:47 gntcs-alit-hp1 sshd[5619]: Failed keyboard-interactive/pam for invalid user knoflicek from 144.92.163.197 port 50527 ssh2
Jun 12 10:52:47 gntcs-alit-hp1 sshd[5619]: Postponed keyboard-interactive for invalid user knoflicek from 144.92.163.197 port 50527 ssh2 [preauth]
Jun 12 10:52:47 gntcs-alit-hp1 sshd[5619]: Connection closed by 144.92.163.197 [preauth]

I also noticed that I cannot login with local users after I've joined the domain, I get this error:

Jun 12 10:45:42 gntcs-alit-hp1 sshd[5600]: [lsass-pam] [module:pam_lsass]pam_sm_acct_mgmt failed [login:test34][error code:40016]

If I run authconfig --updateall it fixed the problem, but I can no longer run the id and getent commands for AD accounts.

Any advice would be greatly appreciated.

Thanks,
Isaac

**Comment by jelayeb** [comment]
i think this happens because of this message logname= uid=0 euid=0  are you trying to login with a root priviliged user. 
then you might want to chnage this line in /etc/ssh/sshd_config 
PermitRootLogin yes

have you tried switching to that user from root su - username to see if that works.

**Comment by rbest-bt** [comment]
Can you provide the steps you use to setup the machine? do you have any other pam_modules installed?

Scientific linux is no longer a regularly supported platform but it did work fine. If you give me a detailed setup I can try and reproduce the issue.

**Comment by Caasi67** [comment]
Thanks for the response.  We did originally try winbind for AD Authentication and it worked, but then some users weren’t able to login and it seemed like a bug so we thought we’d try PBIS.

My first thought was that something had gotten screwed up in that initial winbind installation, but I tried again on a vanilla web server we had setup and I saw the exact same symptoms.  It would bind to the domain just fine, I could use the scripts to query AD objects, I could use “ID” and dump the entire domain, I could even SU as other users, but I couldn’t login.

Thanks!
Isaac

**Comment by rbest-bt** [comment]
Are you able to authenticate with:
`/opt/pbis/bin/lsa authenticate-user`

What does your system-auth pam file look like? If authconfig --updateall is causing a change then it seems like an issue with your pam stack.

**Comment by rbest-bt** [comment]
Were you able to try authenicate-user?

**Comment by rbest-bt** [comment]
closing due to lack of response

**Comment by frayber** [comment]
> Are you able to authenticate with:
> `/opt/pbis/bin/lsa authenticate-user`
> 
> What does your system-auth pam file look like? If authconfig --updateall is causing a change then it seems like an issue with your pam stack.

I have the same problem with an installation of Centos 7.5. I'm able to authenticate with /opt/pbis/bin/lsa authenticate-user
We have hundreds of machines with pbis and we haven't problems. 
Any ideas?
