### ISSUE TITLE
Cannot change root password

### ISSUE THREAD

**Issue by crazyworlds** [BeyondTrust/pbis-open#42]
I have installed pbis from apt repository on debian stable.
I join domain, and now i can login with AD account, but if I login with root local account, Im unable ta change password.

```
root@syslog-1:~# id
uid=0(root) gid=0(root) gruppi=0(root)
root@syslog-1:~# passwd
passwd: Errore manipolazione token di autenticazione
passwd: password unchanged
root@syslog-1:~# 
```
and this is the error that I recive:

```
giu 15 09:02:47 syslog-1 passwd[27269]: [lsass-pam] [module:pam_lsass]LsaPamCheckCurrentPassword failed [login:root][error code: 40008]

```
this is my version of pbis:

```
ii  pbis-open                         8.5.3.293                      amd64        Authentication services for Active Directory domains
ii  pbis-open-upgrade                 8.5.3.293                      amd64        Helper package for upgrading systems with versions preceding

```
How I can change root password?

**Comment by rbest-bt** [comment]
do you have any other PAM modules installed besides pbis? Can you give me more information about your setup?

1. What version of debian
2. steps up to the password reset
3. method of logging in as root

**Comment by rbest-bt** [comment]
no updates - closing

**Comment by lefaikao** [comment]
I have the same exact issue. I created a local user, and am trying to change the password:
passwd: Authentication token manipulation error
passwd: password unchanged

Ubuntu16 logs show:
Jun  3 17:12:24 slrs02v00000018 passwd[3733]: [lsass-pam] [module:pam_lsass]LsaPamCheckCurrentPassword failed [login:username_redacted_here][error code: 40008]
