### ISSUE TITLE
which package should I download for Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by wesdahab** [BeyondTrust/pbis-open#43]
which package should I download for Ubuntu 16.04 LTS 64bit

**Comment by rbest-bt** [comment]
Any of the [linux.x86_64.deb.sh](https://github.com/BeyondTrust/pbis-open/releases/download/8.5.3/pbis-open-8.5.3.293.linux.x86_64.deb.sh) installers will work for it. We always recommend the latest.
