### ISSUE TITLE
error when I try run domainjoin-gui

### ISSUE THREAD

**Issue by wesdahab** [BeyondTrust/pbis-open#44]
root@PrintServer:  /opt/likewise/bin/domainjoin-gui
/opt/likewise/bin/domainjoin-gui: error while loading shared libraries: libglade-2.0.so.0: cannot open shared object file: No such file or directory
root@PrintServer:

**Comment by rbest-bt** [comment]
try installing libglade?
apt-get install libglade2-0

**Comment by wesdahab** [comment]
after installing "libglade2-0", now I can open GUI, but after try to join I got this message 
A sshd config file was at {nowhere}, and a sshd binary file was found at {nowhere}. Exactly one config file and one binary must exist on the system in a standard location. Uninstall any unused copies of ssh.

**Comment by rbest-bt** [comment]
Seems you do not have a ssh server on your machine (apt-get install openssh-server). If you want pbis then you need to disable it from trying to configure ssh (option: --disable ssh). This can be done from domainjoin-cli.

example command
/opt/pbis/bin/domainjoin-cli join --disable ssh DOMAIN WINADMIN

**Comment by wesdahab** [comment]
thanks for quick help you are awesome
