### ISSUE TITLE
Losing connection with AD

### ISSUE THREAD

**Issue by mbulik** [BeyondTrust/pbis-open#45]
Hi,
I'm running pbis-open 8.5.3.293 on Debian Jessie (installe via the repository) and from time to time it disconnects from the AD. In the logs I find messages like this :
juin 20 10:12:30 fraef-storiq2 lsass[20378]: [lsass] Failed to authenticate user (name = 'XXXXXXX') -> error = 40121, symbol = LW_ERROR_DOMAIN_IS_OFFLINE, client pid = 4029
Of course when this happens samba stops working, file rights change in a strange manner (I use ACLs). How can I understand what happens ?
Thanks you,
Michal
PS. I'm running several other systems with PBIS Open installed and it's the first time I see this kind of problems

**Comment by cboutilier-bt** [comment]
I think that this issue may have been fixed in the newest release. Please check 8.5.5.372 and let us know if you still see the same behaviour.

**Comment by rbest-bt** [comment]
No response. closing

**Comment by mbulik** [comment]
Sorry for the late answer.
The problem was due to the presence of winbind on the system. After cleaning this up the link with the AD is working fine.
Thank you,
Michal
