### ISSUE TITLE
High cpu and memory usage

### ISSUE THREAD

**Issue by al-lac** [BeyondTrust/pbis-open#47]
On some of our servers the lwsmd service is using a lot of cpu and slows down the whole system. When activating the lsass debug log it constantly writes, so much that it filled up the whole disk. 

This is the debug output:

`20170627094152:VERBOSE:lsass:AD_OnlineGetGroupMemberSids():lsass/server/auth-providers/ad-open-provider/online.c:4714: Cache entry for group membership for sid <sid> is incomplete
20170627094152:DEBUG:lsass:AD_EnumMembers():lsass/server/auth-providers/ad-open-provider/provider-main.c:5263: Error code: 259 (symbol: ERROR_NO_MORE_ITEMS)
20170627094152:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:474: Switched gss krb5 credentials path from <null> to FILE:/var/lib/pbis/krb5cc_lsass.DOMAIN.LOCAL
20170627094152:DEBUG:lsass:LsaSrvEnumMembers():lsass/server/api/api2.c:1149: Error code: 259 (symbol: ERROR_NO_MORE_ITEMS)
20170627094152:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:474: Switched gss krb5 credentials path from <null> to FILE:/var/lib/pbis/krb5cc_lsass.DOMAIN.LOCAL`

We tried the newest version 8.5.4, but the error still occured. Is this a configuration error or a bug?

**Comment by RBoulton-BT** [comment]
We have seen some performance issues where there is a large number of entries in the PBIS group membership cache. For now the simplest mechanism to work around this limitation is to enable the name service cache daemon (nscd) for passwd and group on platforms that support it.

**Comment by Alex-L-ander** [comment]
We already tried that, but it did not resolve the problem. The problem only occurs on one server, other servers in the same domain do not have such a problem.

**Comment by rbest-bt** [comment]
What is the operating system and version?
How many users/groups are members of the sid that fails to complete?

**Comment by Alex-L-ander** [comment]
RHEL 6.9

The lookup fails for multiple groups. The groups have between 0 and over 100 members.

**Comment by rbest-bt** [comment]
This has been improved a lot in the recent releases. I would recommend upgrading to BeyondTrust Active Directory Bridge for continued support.  https://www.beyondtrust.com/privilege-management/active-directory-bridge

pbis-open will longer receive updates and will be archive. Closing all outstanding issues.
