### ISSUE TITLE
update-dns replace address instead of add address?

### ISSUE THREAD

**Issue by lmt73** [BeyondTrust/pbis-open#48]
**Version**: 8.5.0-3287
**OS/Distro**: RHEL/CentOS 6
**Issue/Impact**:

I would like the provided update-dns binary to REPLACE the IP of my host in MS AD DNS rather than add second entry if the IP changes.  In our DR situation, if a host fails over from one site to the other, it gets a new IP.  I have /opt/pbis/bin/update-dns running from cron to keep the IP current... but instead of replacing the old IP with the new one, it adds a second dns entry for the new one.  So now, when clients attempt to resolve my hostname to an address, they get two addresses: one valid, one old.

Anybody else dealing with this?

**Comment by rbest-bt** [comment]
We do have this feature request in our backlog for update-dns but it's not currently scheduled.

For now I recommend [enabling Aging and Scavenging for DNS](https://technet.microsoft.com/en-us/library/cc771362(v=WS.10).aspx)
