### ISSUE TITLE
Cant login after I set a group in RequireMembershipOf

### ISSUE THREAD

**Issue by agentk0921** [BeyondTrust/pbis-open#49]
**Version**: 8.5.4.334
**OS/Distro**: Rhel 6/7
**Issue/Impact**: Either no one can login or everyone
pbis status = good
Machine is joined to AD
DNS is configured and working correctly
All services are running

**Output/Error**:
When I configure /opt/pbis/bin/config RequireMembershipOf "domain\\group name" **Theres 2 slashes but for some reason this forum is removing the other
it never lets anyone login from any domain unless I set the default value and then everyone can login.

Environment:
Domain A has a one way external Trust with Domain B. Domain A is where I connected machines into AD.

Question? Are there any work-arounds to this?

**Comment by rbest-bt** [comment]
Is RequireMembershipOf set for a group of Domain A or B? Is the user from Domain A or B? Do you have AssumeDefaultDomain set? Does "enum-groups" return the group in question?

**Comment by agentk0921** [comment]
I have tried groups within both domains. It will see users within Domain A but not Domain B. If I add a user in either of those groups that is on Domain B, it doesn't see the users that belong to Domain B or any of Domain B's child domains in that group.

**Comment by rbest-bt** [comment]
If you need this working with one-way trusts now I would recommend upgrading to enterprise. We can handle this with cells in ADUC. We will try and look into this in the future but currently it's not scheduled.

**Comment by agentk0921** [comment]
When you look at your documentation, it states it fully supports the one way trust that we have so I'm curious why it says it supports that yet doesn't work?

**Comment by RBoulton-BT** [comment]
Most of the documentation refers to the Enterprise feature set using Named Cells. One way trusts are supported in Open, however they can be tricky to setup and diagnose any issues. If you want a commercially supported environment where you are not relying on community help to get these environments configured then Enterprise is the way to go.

I did however try setting up a one way external trust environment locally using PBIS Open. With domain local groups I can control access using the RequireMembershipOf using groups from either domain.

Please can you confirm, without RequireMembershipOf set, doing a logon as these users does running "id" show the groups correctly for the users?

**Comment by agentk0921** [comment]
I understand the differences between free and commercial but they're not going to pay for it unless this works. Believe me if i could convince them, I would... Seeing is believing in this case. 

When I use the default with RequireMembershipOf, I do not see all the groups. I only see the groups from the trusted domain (Domain B) and not the groups they have been placed within the primary domain (Domain A).

**Comment by rbest-bt** [comment]
I'd recommend requesting a [demo of Enterprise](https://www.beyondtrust.com/products/powerbroker-identity-services-ad-bridge/). They can help get a setup that will work for you.
