### ISSUE TITLE
ERROR_FILE_NOT_FOUND [code 0x00000002] on domain-join

### ISSUE THREAD

**Issue by AndyMc64** [BeyondTrust/pbis-open#5]
We are unable to join several RHEL 6 Update 8 x86_64 servers to the local domain using PBIS.

We have installed the pbis-open-8.5.1-206 version on each of the servers and was unable success fully attach to the domain and received the following ERROR message when running domainjoin-cli

ERROR_FILE_NOT_FOUND [code 0x00000002] 

The following is the output from the domainjoin-cli.log
20161109175308:INFO:Domainjoin invoked with the join command (remaining arguments will be printed later):
20161109175308:INFO:    [/opt/pbis/bin/domainjoin-cli]
20161109175308:INFO:    [--loglevel]
20161109175308:INFO:    [verbose]
20161109175308:INFO:    [join]
20161109175308:INFO:Domainjoin invoked with 3 arg(s) to the join command:
20161109175308:INFO:    [vchs.vodafone.net]
20161109175308:INFO:    [domainadd]
20161109175308:INFO:    [<password>]
20161109175308:INFO:Adding hb1-xxx-dbr-01 (fqdn hb1-xxx-dbr-01.vchs.vodafone.net) to /etc/hosts ip 10.10.10.77, removing hb1-xxx-dbr-01, hb1-xxx-dbr-01.vchs.vodafone.net, hb1-xxx-dbr-01, hb1-xxx-dbr-01.vchs.vodafone.net
20161109175308:INFO:Reading krb5 file /tmp/likewisetmprRMn7m/etc/krb5.conf
20161109175308:VERBOSE:Found krb5 stanza '[logging]
'
20161109175308:VERBOSE:Found krb5 name value pair ' default = FILE:/var/log/krb5libs.log
'
20161109175308:VERBOSE:Found krb5 name value pair ' kdc = FILE:/var/log/krb5kdc.log
'
20161109175308:VERBOSE:Found krb5 name value pair ' admin_server = FILE:/var/log/kadmind.log
'
20161109175308:VERBOSE:Found krb5 comment '
'
20161109175308:VERBOSE:Found krb5 stanza '[libdefaults]
'
20161109175308:VERBOSE:Found krb5 name value pair ' default_realm = EXAMPLE.COM
'
20161109175308:VERBOSE:Found krb5 name value pair ' dns_lookup_realm = false
'
20161109175308:VERBOSE:Found krb5 name value pair ' dns_lookup_kdc = false
'
20161109175308:VERBOSE:Found krb5 name value pair ' ticket_lifetime = 24h
'
20161109175308:VERBOSE:Found krb5 name value pair ' renew_lifetime = 7d
'
20161109175308:VERBOSE:Found krb5 name value pair ' forwardable = true
'
20161109175308:VERBOSE:Found krb5 name value pair ' default_keytab_name = /etc/krb5.keytab
'
20161109175308:VERBOSE:Found krb5 comment '
'
20161109175308:VERBOSE:Found krb5 stanza '[realms]
'
20161109175308:VERBOSE:Found krb5 compound statement ' EXAMPLE.COM = {
'
20161109175308:VERBOSE:Found krb5 name value pair '  kdc = kerberos.example.com
'
20161109175308:VERBOSE:Found krb5 name value pair '  admin_server = kerberos.example.com
'
20161109175308:VERBOSE:Found krb5 compound end ' }
'
20161109175308:VERBOSE:Found krb5 comment '
'
20161109175308:VERBOSE:Found krb5 stanza '[domain_realm]
'
20161109175308:VERBOSE:Found krb5 name value pair ' .example.com = EXAMPLE.COM
'
20161109175308:VERBOSE:Found krb5 name value pair ' example.com = EXAMPLE.COM
'
20161109175308:INFO:Reading nsswitch file /etc/nsswitch.conf
20161109175308:INFO:Reading krb5 file /tmp/likewisetmptTpcGz/etc/krb5.conf
20161109175308:VERBOSE:Found krb5 stanza '[logging]
'
20161109175308:VERBOSE:Found krb5 name value pair ' default = FILE:/var/log/krb5libs.log
'
20161109175308:VERBOSE:Found krb5 name value pair ' kdc = FILE:/var/log/krb5kdc.log
'
20161109175308:VERBOSE:Found krb5 name value pair ' admin_server = FILE:/var/log/kadmind.log
'
20161109175308:VERBOSE:Found krb5 comment '
'
20161109175308:VERBOSE:Found krb5 stanza '[libdefaults]
'
20161109175308:VERBOSE:Found krb5 name value pair ' default_realm = EXAMPLE.COM
'
20161109175308:VERBOSE:Found krb5 name value pair ' dns_lookup_realm = false
'
20161109175308:VERBOSE:Found krb5 name value pair ' dns_lookup_kdc = false
'
20161109175308:VERBOSE:Found krb5 name value pair ' ticket_lifetime = 24h
'
20161109175308:VERBOSE:Found krb5 name value pair ' renew_lifetime = 7d
'
20161109175308:VERBOSE:Found krb5 name value pair ' forwardable = true
'
20161109175308:VERBOSE:Found krb5 name value pair ' default_keytab_name = /etc/krb5.keytab
'
20161109175308:VERBOSE:Found krb5 comment '
'
20161109175308:VERBOSE:Found krb5 stanza '[realms]
'
20161109175308:VERBOSE:Found krb5 compound statement ' EXAMPLE.COM = {
'
20161109175308:VERBOSE:Found krb5 name value pair '  kdc = kerberos.example.com
'
20161109175308:VERBOSE:Found krb5 name value pair '  admin_server = kerberos.example.com
'
20161109175308:VERBOSE:Found krb5 compound end ' }
'
20161109175308:VERBOSE:Found krb5 comment '
'
20161109175308:VERBOSE:Found krb5 stanza '[domain_realm]
'
20161109175308:VERBOSE:Found krb5 name value pair ' .example.com = EXAMPLE.COM
'
20161109175308:VERBOSE:Found krb5 name value pair ' example.com = EXAMPLE.COM
'
20161109175308:INFO:Distro Version 6.8
20161109175308:INFO:Reading pam configuration
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/other
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/cvs
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/login
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/reboot
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/sudo-i
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/runuser
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/password-auth-ac
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/system-auth-ac
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/vmtoolsd
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/setup
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/passwd
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/subscription-manager
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/system-config-network-cmd
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/polkit-1
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/run_init
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/chfn
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/eject
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/smartcard-auth
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/vsftpd
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/newrole
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/rhn_register
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/su-l
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/system-config-network
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/screen
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/sudo
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/password-auth
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/ssh-keycat
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/crond
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/fingerprint-auth-ac
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/chsh
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/halt
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/abrt-cli-root
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/smartcard-auth-ac
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/config-util
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/su
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/smtp.postfix
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/fingerprint-auth
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/poweroff
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/runuser-l
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/remote
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/atd
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/smtp
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/system-auth
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.d/sshd
20161109175308:INFO:Reading pam file /tmp/likewisetmpbvoofM/etc/pam.conf
20161109175308:INFO:File /tmp/likewisetmpbvoofM/etc/pam.conf does not exist
20161109175308:INFO:Found config file /etc/ssh/sshd_config
20161109175308:INFO:Found binary /usr/sbin/sshd
20161109175308:INFO:Reading ssh file /etc/ssh/sshd_config
20161109175308:INFO:Found open sshd version 5.3.-1p1
20161109175308:INFO:Testing option ChallengeResponseAuthentication
20161109175308:INFO:Option ChallengeResponseAuthentication supported
20161109175308:INFO:Testing option UsePAM
20161109175308:INFO:Testing option PAMAuthenticationViaKBDInt
20161109175308:INFO:Option PAMAuthenticationViaKBDInt not supported
20161109175308:INFO:Testing option KbdInteractiveAuthentication
20161109175308:INFO:Option KbdInteractiveAuthentication supported
20161109175308:INFO:Testing option GSSAPIAuthentication
20161109175308:INFO:Testing option GSSAPICleanupCredentials
20161109175308:INFO:Found config file /etc/ssh/ssh_config
20161109175308:INFO:Found binary /usr/bin/ssh
20161109175308:INFO:Reading ssh file /etc/ssh/ssh_config
20161109175308:INFO:Testing option GSSAPIAuthentication
20161109175308:INFO:Testing option GSSAPIDelegateCredentials
20161109175308:INFO:Option GSSAPIDelegateCredentials supported
20161109175308:INFO:Running module join
20161109175308:VERBOSE:eventlog:LwEvtOpenEventlog():/builder/src-git/Platform/src/linux/eventlog/client/eventlog.c:174: client::eventlog.c OpenEventlog server=<null>)

20161109175308:ERROR:ERROR_FILE_NOT_FOUND [ERROR_FILE_NOT_FOUND]

Stack Trace:
/builder/src-git/Platform/src/linux/domainjoin/domainjoin-cli/src/main.c:1211
/builder/src-git/Platform/src/linux/domainjoin/domainjoin-cli/src/main.c:583
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djmodule.c:355
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djauthinfo.c:857
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djauthinfo.c:1255

We have run several straces and tcpdumps on connectivity to attempt to find out what the ERROR is related to.

Please can assist with any possible troubleshooting we can do to isolate the issue.

Regards

Andy
andy.mcdougall@vodafone.com

**Comment by RBoulton-BT** [comment]
Based on that log it looks like that ERROR_FILE_NOT_FOUND is actually being passed back from the lsass service. The easiest way to get a log of this occurring will be to temporarily set lass to log to a file while you perform the join:

Turn on debug logging:
/opt/pbis/bin/lwsm set-log-target lsass - file /var/log/lsass.log
/opt/pbis/bin/lwsm set-log-level lsass - debug

Then do your join:
domainjoin-cli join <yourdomain>

Turn off debug by just restarting lsass:
/opt/pbis/bin/lwsm restart lsass

Hopefully the /var/log/lsass.log should show us some more.

**Comment by AndyMc64** [comment]
HI Richard,
I have the command as suggested and below is the output, I cannot see any file specifically that is missing.


20161115092606:ALWAYS: Logging started
20161115092614:ALWAYS:LwSmSetMaxLogLevel():lwsm/server/logger.c:662: Log level changed to DEBUG
20161115092651:VERBOSE:lsass:LsaSrvIpcCheckPermissions():lsass/server/api/ipc_state.c:79: Permission granted for (uid = 0, gid = 0, pid = 17861) to open LsaIpcServer
20161115092651:VERBOSE:lsass-ipc:lwmsg_peer_log_accept():lwmsg/src/peer-log.c:230: (session:4faa86ce65294941-edf7e71244ac6344) Accepted <local euid:0 egid:0 pid:17861>
20161115092651:DEBUG:lsass:AD_JoinDomain():lsass/server/auth-providers/ad-open-provider/provider-main.c:2440: Joining domain VCHS.VODAFONE.NET
20161115092651:VERBOSE:lsass:AD_JoinDomain():lsass/server/auth-providers/ad-open-provider/provider-main.c:2460: Affinitized to DC 'vchs-xxx-xx-01.vchs.vodafone.net' for join request to domain 'VCHS.VODAFONE.NET'
20161115092651:DEBUG:lsass:AD_PreJoinDomain():lsass/server/auth-providers/ad-open-provider/provider-main.c:2288: Clearing old join state
20161115092651:DEBUG:lwreg:RegTransactOpenKeyExW():lwreg/client/clientipc.c:438: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
20161115092651:DEBUG:lwreg:LwNtRegOpenKeyExA():lwreg/client/regntclient.c:933: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
20161115092651:DEBUG:lwreg:RegShellUtilGetValue():lwreg/shellutil/rsutils.c:1427: Error: 40700
20161115092651:DEBUG:LwpsLegacyGetDefaultJoinedDomain():lsass/pstore/lsapstore-backend-legacy-internal.c:711: -> 0 (ERROR_SUCCESS) (EE = 685)
20161115092651:DEBUG:lwreg:RegTransactOpenKeyExW():lwreg/client/clientipc.c:438: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
20161115092651:DEBUG:lwreg:LwNtRegOpenKeyExA():lwreg/client/regntclient.c:933: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
20161115092651:DEBUG:lwreg:RegShellUtilGetValue():lwreg/shellutil/rsutils.c:1427: Error: 40700
20161115092651:DEBUG:LwpsLegacyGetDefaultJoinedDomain():lsass/pstore/lsapstore-backend-legacy-internal.c:711: -> 0 (ERROR_SUCCESS) (EE = 685)
20161115092651:DEBUG:lwreg:RegTransactOpenKeyExW():lwreg/client/clientipc.c:438: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
20161115092651:DEBUG:lwreg:RegShellIsValidKey():lwreg/shellutil/rsutils.c:235: Error: 40700
20161115092651:DEBUG:lwreg:RegShellUtilDeleteTree():lwreg/shellutil/rsutils.c:511: Error: 40700
20161115092651:DEBUG:lwreg:RegTransactOpenKeyExW():lwreg/client/clientipc.c:438: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
20161115092651:DEBUG:lwreg:RegShellUtilGetKeyObjectCounts():lwreg/shellutil/rsutils.c:1175: Error: 40700
20161115092651:DEBUG:lsass:LsaSetSMBCreds():lsass/server/auth-providers/ad-open-provider/join/lsakrb5smb.c:178: Switching default credentials path for new access token
20161115092651:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:474: Switched gss krb5 credentials path from FILE:/tmp/krb5cc_0 to FILE:/tmp/tktzcY0xE
20161115092651:DEBUG:lsass:NtlmServerAcquireCredentialsHandle():lsass/server/ntlm/acquirecreds.c:103: Error code: 40506 (symbol: LW_ERROR_NO_CRED)
20161115092651:DEBUG:lsass:NtlmServerAcquireCredentialsHandle():lsass/server/ntlm/acquirecreds.c:103: Error code: 40506 (symbol: LW_ERROR_NO_CRED)
20161115092651:DEBUG:lsass:NtlmTransactAcquireCredentialsHandle():lsass/client/ntlm/clientipc.c:299: Error code: 40506 (symbol: LW_ERROR_NO_CRED)
20161115092651:DEBUG:lsass:NtlmClientAcquireCredentialsHandle():lsass/client/ntlm/acquirecreds.c:76: Error code: 40506 (symbol: LW_ERROR_NO_CRED)
20161115092651:DEBUG:lsass:NtlmServerAcquireCredentialsHandle():lsass/server/ntlm/acquirecreds.c:103: Error code: 40506 (symbol: LW_ERROR_NO_CRED)
20161115092651:DEBUG:lsass:NtlmTransactAcquireCredentialsHandle():lsass/client/ntlm/clientipc.c:299: Error code: 40506 (symbol: LW_ERROR_NO_CRED)
20161115092651:DEBUG:lsass:NtlmClientAcquireCredentialsHandle():lsass/client/ntlm/acquirecreds.c:76: Error code: 40506 (symbol: LW_ERROR_NO_CRED)
20161115092651:DEBUG:lsass:ntlm_gss_init_sec_context():lsass/interop/gssntlm/gssntlm.c:891: Error code: 40506 (symbol: LW_ERROR_NO_CRED)
20161115092651:DEBUG:lsass:LsaMachDnsNameSearch():lsass/server/auth-providers/ad-open-provider/join/join.c:2673: Ldap error code: 16
20161115092652:DEBUG:lsass:SamrLookupNames():lsass/client/rpc/samr/samr_lookupnames.c:103: Error at /builder/src-git/Platform/src/linux/lsass/client/rpc/samr/samr_lookupnames.c:103 [code: C0000073]
20161115092652:DEBUG:lsass:SamrCreateUser2():lsass/client/rpc/samr/samr_createuser2.c:89: Error at /builder/src-git/Platform/src/linux/lsass/client/rpc/samr/samr_createuser2.c:89 [code: C0000034]
20161115092652:DEBUG:lsass:LsaCreateMachineAccount():lsass/server/auth-providers/ad-open-provider/join/join.c:1511: Error at /builder/src-git/Platform/src/linux/lsass/server/auth-providers/ad-open-provider/join/join.c:1511 [code: C0000034]
20161115092652:DEBUG:lsass:LsaJoinDomainInternal():lsass/server/auth-providers/ad-open-provider/join/join.c:618: Error at /builder/src-git/Platform/src/linux/lsass/server/auth-providers/ad-open-provider/join/join.c:618 [code: C0000034]
20161115092652:DEBUG:lsass:LsaJoinDomainUac():lsass/server/auth-providers/ad-open-provider/join/join.c:377: Error code: 2 (symbol: ERROR_FILE_NOT_FOUND)
20161115092652:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:474: Switched gss krb5 credentials path from <null> to FILE:/tmp/krb5cc_0
20161115092652:DEBUG:lsass:AD_JoinDomain():lsass/server/auth-providers/ad-open-provider/provider-main.c:2516: Error code: 2 (symbol: ERROR_FILE_NOT_FOUND)
20161115092652:DEBUG:lsass:AD_ProviderIoControl():lsass/server/auth-providers/ad-open-provider/provider-main.c:4751: Error code: 2 (symbol: ERROR_FILE_NOT_FOUND)
20161115092652:DEBUG:lsass:LsaSrvProviderIoControl():lsass/server/api/provider.c:99: Error code: 2 (symbol: ERROR_FILE_NOT_FOUND)
20161115092652:ERROR:lsass:LsaSrvProviderIoControl():lsass/server/api/provider.c:128: Failed to run provider specific request (request code = 8, provider = 'lsa-activedirectory-provider') -> error = 2, symbol = ERROR_FILE_NOT_FOUND, client pid = 17861
20161115092652:VERBOSE:lsass-ipc:lwmsg_peer_task_handle_assoc_error():lwmsg/src/peer-task.c:625: (session:4faa86ce65294941-edf7e71244ac6344) Dropping: LWMSG_STATUS_PEER_CLOSE
20161115092700:INFO:svcm:StopWorkItem():lwbase/src/svcm.c:493: Executing stop for service 'lsass'
20161115092700:INFO:svcm:StopWorkItem():lwbase/src/svcm.c:496: Starting 50 second shutdown timer for service 'lsass'
20161115092700:INFO:lsass-ipc:lwmsg_peer_shutdown():lwmsg/src/peer.c:572: Shutting down listener
20161115092700:INFO:lsass-ipc:lwmsg_peer_shutdown():lwmsg/src/peer.c:592: Listener shut down
20161115092700:INFO:lsass-ipc:lwmsg_peer_shutdown():lwmsg/src/peer.c:572: Shutting down listener
20161115092700:INFO:lsass-ipc:lwmsg_peer_shutdown():lwmsg/src/peer.c:592: Listener shut down
20161115092700:INFO:lsass:LsaStopRpcSrv():lsass/server/api/rpc_server.c:305: lsarpc rpc server successfully stopped
20161115092700:INFO:lsass:LsaStopRpcSrv():lsass/server/api/rpc_server.c:305: samr rpc server successfully stopped
20161115092700:INFO:lsass:LsaStopRpcSrv():lsass/server/api/rpc_server.c:305: dssetup rpc server successfully stopped
20161115092700:INFO:lsass:LsaStopRpcSrv():lsass/server/api/rpc_server.c:305: wkssvc rpc server successfully stopped
20161115092700:INFO:lsass:LsaSvcmStop():lsass/server/lsassd/main-svcm.c:191: LSA Service exiting...
20161115092700:INFO:svcm:StopWorkItem():lwbase/src/svcm.c:500: Stop of service 'lsass' completed.
20161115092700:VERBOSE:MainTask():lwsm/server/main.c:721: Shutting down on SIGTERM
20161115092700:INFO:Shutdown():lwsm/server/main.c:651: Starting lwsmd shutdown timer
20161115092700:INFO:lwsm-ipc:lwmsg_peer_shutdown():lwmsg/src/peer.c:572: Shutting down listener
20161115092700:INFO:lwsm-ipc:lwmsg_peer_shutdown():lwmsg/src/peer.c:592: Listener shut down
20161115092700:INFO:Shutdown():lwsm/server/main.c:668: Services were stopped, cancelling shutdown timer

**Comment by RBoulton-BT** [comment]
It appears we're trying to create the computer account in the default Computers container (samr_createuser2.c:89 [code: C0000034]) but get STATUS_OBJECT_NAME_NOT_FOUND. This is translated to the closest error we have ERROR_FILE_NOT_FOUND. 

So that's an explanation of the error, the difficult bit is an explanation of why we get that error.

The samr calls are RPC calls to the DC, so it could be your DC has errors indicating why it replied with STATUS_OBJECT_NAME_NOT_FOUND in the event log.

Are there any accounts in your computers container that could be conflicting with this new computer account name?

Have you tried using the --ou <organizationalUnit> on the domainjoin-cli command line to force the creation of the computer account in a specific OU? Even if you choose the same OU of Computers, we follow a different code path which should pre-create the computer account using LDAP calls and may give more information or bypass the issue.

I'll ask around and see if anyone else has seen this problem.

**Comment by AndyMc64** [comment]
BY setting the --ou option and pointing it to the container we were able to install successfully. Many thanks for your help.
