### ISSUE TITLE
Can't join domain (ERROR:LW_ERROR_LDAP_CONSTRAINT_VIOLATION)

### ISSUE THREAD

**Issue by dgroos** [BeyondTrust/pbis-open#51]
**Version**: 8.5.4.334
**OS/Distro**: Ubuntu desktop 16.04 - unity desktop
**Issue/Impact**:

> I had pbis working well for last few years on Ubuntu 14.04.
I recently installed 16.04 but have been unable to join the domain as described below.
I've been troubleshooting for 2 days now. My best guess is that I didn't leave the domain before reinstalling the OS (see copied text of a forum content describing this at the bottom of this error report). I tried the suggested changing hostname (sudo /opt/likewise/bin/domainjoin-cli setname NewName), I tried restarting afterwards but no success still. Below is requested info.

 1. systemctl status lwsmd.service

> $ systemctl status lwsmd.service
● lwsmd.service - BeyondTrust PBIS Service Manager
   Loaded: loaded (/lib/systemd/system/lwsmd.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2017-08-19 11:28:22 CDT; 14min ago
  Process: 939 ExecStart=/opt/pbis/sbin/lwsmd --start-as-daemon (code=exited, status=0/SUCCESS)
 Main PID: 964 (lwsmd)
   CGroup: /system.slice/lwsmd.service
           ├─ 964 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─ 986 lw-container lwreg
           ├─1014 lw-container eventlog
           ├─1040 lw-container netlogon
           ├─1066 lw-container lwio
           ├─1092 lw-container lsass
           └─1130 lw-container reapsysl

> Aug 19 11:28:22 sci1 systemd[1]: Starting BeyondTrust PBIS Service Manager...
Aug 19 11:28:22 sci1 /opt/pbis/sbin/lwsmd[964]: Logging started
Aug 19 11:28:22 sci1 lwreg[986]: Logging started
Aug 19 11:28:22 sci1 eventlog[1014]: Logging started
Aug 19 11:28:22 sci1 netlogon[1040]: Logging started
Aug 19 11:28:22 sci1 lwio[1066]: Logging started
Aug 19 11:28:22 sci1 lsass[1092]: Logging started
Aug 19 11:28:22 sci1 reapsysl[1130]: Logging started
Aug 19 11:28:22 sci1 systemd[1]: Started BeyondTrust PBIS Service Manager.

 2. /opt/pbis/bin/lwsm list

> $ /opt/pbis/bin/lwsm list
lwreg          running (container: 986)
dcerpc         stopped
eventlog       running (container: 1014)
lsass          running (container: 1092)
lwio           running (container: 1066)
netlogon       running (container: 1040)
rdr            running (io: 1066)
reapsysl       running (container: 1130)
usermonitor    stopped

 3. /opt/pbis/domainjoin-cli query

> $ /opt/pbis/domainjoin-cli query
-bash: /opt/pbis/domainjoin-cli: No such file or directory

 4. pbis status

> $ pbis status
LSA Server Status:

> Compiled daemon version: 8.5.4.334
Packaged product version: 8.5.334.8
Uptime:        0 days 0 hours 19 minutes 37 seconds

> [Authentication provider: lsa-activedirectory-provider]

	Status:        Unknown
	Mode:          Unknown

 5. /opt/pbis/bin/enum-users

> $ /opt/pbis/bin/enum-users
TotalNumUsersFound: 0

 6. attach logs
  - /opt/pbis/bin/lwsm set-log-target -p lsass -  file /tmp/lsass.log
  - /opt/pbis/bin/lwsm set-log-level -p lsass - debug
  - attach log

**Output/Error**:

> cat domainjoin-cli.log 
20170819090320:ERROR:LW_ERROR_LDAP_CONSTRAINT_VIOLATION [LW_ERROR_LDAP_CONSTRAINT_VIOLATION]

> Stack Trace:
/builder/src-git/Platform/src/linux/domainjoin/domainjoin-cli/src/main.c:1211
/builder/src-git/Platform/src/linux/domainjoin/domainjoin-cli/src/main.c:583
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djmodule.c:355
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djauthinfo.c:857
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djauthinfo.c:1265
20170819100138:ERROR:LW_ERROR_LDAP_CONSTRAINT_VIOLATION [LW_ERROR_LDAP_CONSTRAINT_VIOLATION]

**Steps to Reproduce**:
 1. install command

> (I purged previous install sudo /opt/pbis/bin/uninstall.sh purge)
 sudo ~/Downloads/pbis-open-8.5.4.334.linux.x86_64.deb.sh

 2. Domainjoin command

> sudo /opt/likewise/bin/domainjoin-cli join DOMAIN user.with.permission.to.join

 3. Command that returns issue

> The join command give above. Also through domainjoin-gui

Below was a forum comment that seemed to apply but solution didn't work:
> https://ubuntuforums.org/archive/index.php/t-1506627.html
> I see what you mean. Based on the LDAP error codes (http://www.stone-ware.com/support/techdocs/kb/s2150/LDAP%20Error%20Codes.htm). More info here (http://download.oracle.com/javase/1.3/docs/api/javax/naming/directory/InvalidAttributeValueException.html).
> 
> I think I've run into something similar before when trying to rejoin a domain with the same machine name after installing a new OS. I might be able to work around it simply by changing the machine name.
> 
> OK this worked.
> 
> sudo vi /etc/hostname
> 
> <picked a new hostname>
> 
> sudo domainjoin-cli --loglevel info --logfile . join my.company.domain.com username
> 
> <about 90 seconds of waiting, then lots of messages followed by the important one:>
> 
> SUCCESS
> 
> I should have left the domain before formatting the drive and installing Ubuntu. It isn't critical at this point, but I could probably get my old hostname joined by using it on another computer then joining and leaving the domain, then leaving and joining again with this one. Not worth the trouble though.
>

**Comment by rbest-bt** [comment]
Some of your paths use /opt/likewise. Did you install the legacy package?

Have you tried deleting the computer object in AD? You can do it with PBIS using the adtool:
`/opt/pbis/bin/adtool -d domain.com -n admin -x password -a  delete-object --dn CN=$HOSTNAME,OU=theOU,DC=domain,DC=com`

**Comment by dgroos** [comment]
Hi @rbest-bt thanks for your quick reply!
For the original install, I added pbis repository then apt installed the package. However, the domainjoin gui was missing so had to find how to install that and I must have hit upon an old package--what's the current way to add it?

As I'm a teacher in the district I'd have to e-mail the admin of our AD and will do that in necessary. I'm wondering if that will work, since I already changed the /etc/hostname/ on the computer and that didn't work, would deleting the computer object? 

Tomorrow morning I'm going to put a spare HD from last year (w/working pbis system) into the computer in question, join then unjoin the domain, then swap back in the other HD w/ the new OS and try joining again. If that doesn't work I'll re-instll the OS, add pbis open and try again. If that doesn't work I'll contact the AD admin to have the computer object in AD deleted. Just in case, any other ideas? Thanks!

**Comment by dgroos** [comment]
Success :-)
I did as described above--in essence, installed the old HD on the machine I had used the previous year (the same also as using this year), booted on the old system, (so of course the /etc/hostname had exact same name as last year), then through the gui joined/unjoined twice then shut down.

Then I put the HD with the new, 16.04 ubuntu HD (that I'm trying to join to our district AD), booted, then made sure that it had the same name in /etc/hostname (though probably could have used a new name?). Opened the domainjoin-gui, put in the required info and...
Success :-)
Thanks for your support @rbest-bt

**Comment by rbest-bt** [comment]
I'm happy to hear your solution and that it worked. Here are some pointers for the future:

Package for domainjoin gui: pbis-open-domainjoin-gui

Command line domainjoin:
`/opt/pbis/bin/domainjoin-cli join domain.com admin`

Leaving the domain and deleting the computer object:
`/opt/pbis/bin/domainjoin-cli leave --deleteAccount admin pass`

Changing the hostname with pbis:
`/opt/pbis/bin/domainjoin-cli setname newname`
Remember issue a domainjoin again to update the AD computer object

**Comment by dgroos** [comment]
Re-opened this issue:
I did this because the solution to the original solution to this problem is now unavailable and am encountering the same problem again as I'm working on getting the clonezilla-produced clone of the working server mentioned in #79 to join the AD domain.

The accepted solution to the "Error: LW_ERROR_LDAP_CONSTRAINT_VIOLATION [code 0x00009d7b]"  was installing the old HD, leaving, then joining and leaving the domain again, then re-installing the hard drive with the new system. As mentioned, this solution is not possible. Furthermore, none of the solutions suggested solutions such as the following, worked:
> have the AD administrator delete the machine records for the specific hostname in AD

> Changing the hostname with pbis:
/opt/pbis/bin/domainjoin-cli setname newname

> Leaving the domain and deleting the computer object:
/opt/pbis/bin/domainjoin-cli leave --deleteAccount admin pass

Any ideas? I've spent a few hours on this such as: leaving the domain on the original server, then changing the cloned hostename back to original server's name and successfully joining with the original servers hostname! (I did get the message that I needed to restart the server since this was the first time I had joined a domain). I also tried all of the ideas discussed in #79 to no avail.
Thanks for re-considering this problem!

**Comment by rbest-bt** [comment]
The above is a little confusing so I'm going to explain a possible solution to cloning system drives with pbis.
1. Get a system to a golden state you would like
2. Install pbis on the system but DO NOT JOIN THE DOMAIN
3. Create an image of the system

Post cloning the system
1. make sure there is no IP conflicts, or use dhcp
2. change the host name - /opt/pbis/bin/domainjoin-cli setname
3. issue domain join

If you would like to have a more universal image I would just copy the PBIS package to /root/ to be installed post cloning.

**Comment by dgroos** [comment]
This is great advice when starting fresh and am saving this info for the future (copy/pasting to my personal problem-solving database).

However, I'd rather not set up a fresh golden image at this point if there is some way to deal with this such as delete a cache etc. Simple uninstalling and re-installing doesn't seem to accomplish this. Can you tell me where the info is stored?

**Comment by rbest-bt** [comment]
We are aware of a bug that prevents domain leaves if it can not reach the computer object in Active Directory (AD). Work around is to restart lwsmd - or just lsass - then trying the domain leave.

To clean up the systems I would do that following in this order
1. Issue domainleave
2. If 1 fails then restart lsass and repeat leave - /opt/pbis/bin/lwsm restart lsass 
3. Repeat 1 for each machine
4. Delete all the ad objects that match those machines. If you do not have access to an AD workstation you can do this with the adtool. Login on a pbis workstation with an AD admin account - /opt/pbis/bin/adtool -a delete-object --dn CN=$HOSTNAME,OU=location
5. use domainjoin setname on each machine to make sure they are unique
6. join them to the domain

I apologize if these are the steps you've already taken I'm just trying to clear up where you are at.

**Comment by dgroos** [comment]
Thanks for being clear with step-by-step troubleshooting steps. I think I've done everything but step 4. Will give them a go at end of day, Thanks!
Clarification on step 4:
* Those ad objects you mention exist on the AD server? 
* If an AD administrator has deleted those machine records for me, is that the same thing as deleting "ad objects", or are they something different?

**Comment by rbest-bt** [comment]
By "ad objects" I meant the "computer objects" that exist in the domains Active Directory.

The adtool action of delete-object can be used to delete users or machine objects as long as the distinguished name (dn) matches. I recommend a good naming convention where user and computer objects should never match.

**Comment by dgroos** [comment]
OK, not sure if I succeeded with steps 1 and 2 above (not sure how to interpret the output)

:~$ sudo /opt/pbis/bin/domainjoin-cli leave
Leaving AD Domain:   (unknown)
SUCCESS
(I guess this does NOT mean success...)

sudo /opt/pbis/bin/lwsm restart lsass
Stopping service: lsass
Starting service: lsass

And then again:
:~$ sudo /opt/pbis/bin/domainjoin-cli leave
Leaving AD Domain:   (unknown)
SUCCESS

And again, I'm guessing not success, so as a guess I tried:
:~$ sudo /opt/pbis/bin/lwsm restart lwsmd
Error: LW_ERROR_NO_SUCH_SERVICE (41204)
No service with the specified name exists
(googling this error line I get lots of hits from 2010...)

Here's a possible clue? When I issued sudo /opt/pbis/bin/lwsm restart lsass , the 'Leaving AD Domain...' and the Stopping... and Starting... responses was basically instantaneous, not the 1 second pause between the Stop and the Start that I expected like when I did that command with another computer a week ago.

**Comment by dmorash-BT** [comment]
Couple of things that may help:

1. Leaving AD Domain: (unknown)  indicates that pbis thinks it isn't joined, instead of producing an error it just considers that as success.

2. You are trying to restart the pbis service manager daemon lwsmd.  You want to start the lsass service, so sudo /opt/pbis/bin/lwsm restart lsass 

FYI lwsmd is the pbis service manager daemon that is responsible for starting up/shutting down services when it is itself started/shutdown as part of booting, or manually via systemctl etc., e.g. sudo systemctl start lwsmd.service.  The lwsm command just sends requests to lwsmd to do the actual work.

lwsmd doesn't consider itself a service, hence lwsm restart lwsmd produces the no such service error.

**Comment by dgroos** [comment]
TGIF--getting some time to work on this after work today. @dmorash-BT thanks for your info on the meanings of the output and lwsmd vs lsass.

I now went back to try step number 4 given by @rbest-bt above: 
`sudo /opt/pbis/bin/adtool -a delete-object --dn CN=$HOSTNAME,OU=location`

The variables I needed to enter included HOSTNAME AND location. I entered the computer's hostname in all caps. I was stymied by the location, however. I issued the command `pbis --dump` on my server that's successfully joined to the district AD server to get the proper info. 

Even after perusing that --dump info, I was unable to determine the OU location to use. I googled OU of course and tried many of the seemingly promising organizational units from the pbis --dump command but always got the following after issuing the command with (apparently) the incorrect location:
`ERROR: 400051: Failed to locate NT domain the machine is joined to`
Or, it could be the fact that the machine wasn't joined to the AD domain? 

As mentioned [above](https://github.com/BeyondTrust/pbis-open/issues/51#issuecomment-342475559) I got no satisfaction with steps 1 and 2 so perhaps step 4 was mute. Again, I think that the info is deleted from the AD server, and the problem is local to the cloned machine, perhaps some info is cached?

Suggestions?
Thanks!
David

**Comment by dgroos** [comment]
For times sake I think I'm going to setup a fresh server and as you say above, don't do the join until cloned and ready. I'll follow the steps you gave above and get back to you. Thanks for your help.

**Comment by rbest-bt** [comment]
Simplest way to get the location after joined is with the domainjoin-cli query
>rbest@123456789:~$ sudo /opt/pbis/bin/domainjoin-cli query
Name = 123456789
Domain = PBIS.COM
Distinguished Name = CN=123456789,OU=location,DC=pbis,DC=com

This would not work for you in your current state(unjoined). If you are not using the --ou option during domainjoins, and the computer objects were not staged, then they should be showing up in the computers container.
>rbest@123456789:~$ sudo /opt/pbis/bin/domainjoin-cli query
Name = 123456789
Domain = PBIS.COM
Distinguished Name = CN=123456789,CN=Computers,DC=pbis,DC=com

Notice that Computers is CN= and not OU=

So your command would be:
>sudo /opt/pbis/bin/adtool -a delete-object --dn CN=123456789,CN=Computers,DC=pbis,DC=com

This would be assuming that your on a second box logged in as an AD administrator

**Comment by dgroos** [comment]
I set up a fresh install of Ubuntu 16.04 desktop and got it to the 'golden state' (w/out issuing any pbis command and also used clonezilla to make an image for future use.).

On the fresh install, I changed the hostname (it had a generic name) and rebooted. Then I did the domainjoin-cli join command but got the same error as previously reported:
Error: LW_ERROR_LDAP_CONSTRAINT_VIOLATION [code 0x00009d7b]

How can I explain that? It's a fresh install and I've been assured that this particular hostname has been deleted from the AD records. 

I can think of only 1 possibility: Is it possible that there is some building-level cache of this AD machine record even though it has been deleted from the main district-wide AD records?

Just for thoroughness sake I tried the delete-object command you provided on my 1 machine that is joined to the AD server. I used the query command and thanks to your detailed description and the example of using it was able to figure it out. However, it didn't work, guess my AD admin user account doesn't have permission to delete other machine records accounts and got:
ERROR: 500048: Inappropriate authentication
(also tried the lsass restart but that didn't help)

Any other ideas?
Thanks,
David

**Comment by dgroos** [comment]
Did a fresh install of Ubuntu 16.04 which erased the HD before installation. Gave a unique computer name (hostname) during install. After installation, performed the following commands:
sudo apt update && sudo apt dist-upgrade
#reboot
sudo apt autoremove
sudo apt install openssh-server
#then via ssh from other machine:
sudo nano /etc/apt/sources.list #added the following 2 to the sources list
   deb https://repo.pbis.beyondtrust.com/apt pbiso main
   deb https://repo.pbis.beyondtrust.com/apt pbise non-free
wget -O - http://repo.pbis.beyondtrust.com/apt/RPM-GPG-KEY-pbis|sudo apt-key add - 
sudo apt-get update
sudo apt install pbis-open
sudo /opt/pbis/bin/domainjoin-cli join DOMAIN USER@my.domain
#and got again:
Error: LW_ERROR_LDAP_CONSTRAINT_VIOLATION [code 0x00009d7b]

How could this be? This is a fresh install, only pbis and openssh-server are installed beyond the standard desktop install. True, it's using a NIC that has been used before, but I just tried on a fresh NIC and get the same Error. I've got no more ideas here...

**Comment by rbest-bt** [comment]
Every time I've seen a CONSTRAINT_VIOLATION it was due to the admin account not having rights to set all the required fields for the Computer object in AD. The two big ones would be the ServicePrincipalName and the DNSHostname. 

DNSHostname - how we preform the initial ad object match 
ServicePrincipalName - required for kerberos

If you do have an admin account it will pass the valid account and the access checks. Then it will try to create the computer object but AD will return the CONSTRAINT_VIOLATION error when it fails to set an attribute.

I would check if you have rights to write to those attributes. If you do we'll need to check out any other attributes you might not have access to.

**Comment by dgroos** [comment]
I submitted this question to our district AD people, I'd hoped to hear from them today but am hoping for tomorrow.

@rbest-bt I don't understand how I can successfully join one server to our AD domain but couldn't with the fresh install, same user account in both situations.

**Comment by rbest-bt** [comment]
Depends on a few things. Are you using the --ou option during domainjoin to state where you want the object? Is there an existing computer object in ad on the successful joins?
AD rights can be different in different locations of AD.

**Comment by dgroos** [comment]
1. The command I use is invariably: sudo /opt/pbis/bin/domainjoin-cli join MY.DOMAIN MYUSER@domain.x.y.z. Not sure if it matters, the "MY.DOMAIN" to which I'm joining and the "domain.x.y.z" to which my admin user belongs are on different root-level forks of our district directory structure. They always have been though, no change there.

1. I'm not positive of what you mean:

> Is there an existing computer object in ad on the successful joins?

- If you're asking if a computer object is created in AD upon a successful join, then I'd say yes, if you're asking if a computer object might already exist at join from a previous join I don't have a guess.

Thanks!

**Comment by dgroos** [comment]
Been working on this quite a bit more. In the end, I concluded that the problem wasn't with my AD admin user not having enough privledge to set certain variables: that wouldn't explain why on 1 computer/setup it worked and why on another very similar it didn't work.

In the end I was unable to get any cloned system (w/clonezilla) to join, even before pbis had been copied onto it much less setup. Likewise, I was able to easily join systems that were fresh installs. So, the significant difference was whether it was a cloned or installed system.

I was able to join cloned systems in 14.04 and earlier so infer that some change in 16.04 precludes successfully using pbis-open on cloned (via clonezilla) systems. While it would be nice to know what is is about cloned systems that elicits the "LW_ERROR_LDAP_CONSTRAINT_VIOLATION" error, I'm good for this school year. Thanks @rbest-bt for your support. This can be re-closed with the conclusion: doesn't work on cloned systems.

**Comment by dgroos** [comment]
Update:
I had been installing an older pbis, joining/unjoining, purging then installing the current version though this morning I tested to see if that was necessary. This morning with a fresh install, I found that if I installed the current version first, I get the "LW_ERROR_LDAP_CONSTRAINT_VIOLATION" message, but if I purged the current, installed the older version, the join would succeed! Then I purged the older version, re-installed the current version then again the join succeeded!
Older version: pbis-open-8.0.0.2016.linux.x86_64.deb.sh
Current version: pbis-open-8.5.7.385.linux.x86_64.deb.sh
Note the attached screen shot I get this error message:
![screenshot from 2018-01-04 08-43-27](https://user-images.githubusercontent.com/4097759/34568832-9ee03ee0-f12c-11e7-8040-811718484505.png)

**Comment by dgroos** [comment]
And to conclude... The work-around of first installing pbis-open-8.0.0.2016.linux.x86_64.deb.sh, joining then unjoining then uninstalling this version, then installing pbis-open-8.5.7.385.linux.x86_64.deb.sh continued to work for fresh-installs of Ubuntu 16.04 in our particular environment. However, it did not work on any cloned system (even those that didn't have pbis-open installed on them). Still getting the error message shown above, but it works!!!

**Comment by rbest-bt** [comment]
LW_ERROR_LDAP_CONSTRAINT_VIOLATION error or the ubuntu internal error?

**Comment by dgroos** [comment]
The error message that we were getting on the Ubuntu system stopped a couple of weeks ago at least, so that is good. Some update must have taken care of it.

On a side note, there seems to be some negative interaction between lsass and a program I use to manage users/groups. I don't have any idea in which logs to start looking for errors. Basically when I launch this other program it takes almost 10 minutes to launch and htop shows that there are several .../lsass threads involved somehow. If you can give me a hint I'll investigate and create a new post. Thanks

**Comment by rbest-bt** [comment]
16.04 was the early days of systemd which did have some issues causing lwsmd to crash. Depending on the version I could see updates fixing that.

lsass service handles user/group lookup and authentication. Easiest way to gather logs is with tap-log during the times your having issues:
> /opt/pbis/bin/lwsm tap-log lsass - debug

More information about gathering log is located in the troubleshooting guide.

**Comment by dgroos** [comment]
Thanks will check into this as I get a chance!

**Comment by dgroos** [comment]
The error message that we were getting on the Ubuntu system stopped a couple of weeks ago at least, so that is good. Some update must have taken care of it.

On a side note, there seems to be some negative interaction between lsass and a program I use to manage users/groups. I don't have any idea in which logs to start looking for errors. Basically when I launch this other program it takes almost 10 minutes to launch and htop shows that there are several .../lsass threads involved somehow. If you can give me a hint I'll investigate and create a new post. Thanks

**Comment by rbest-bt** [comment]
Does your problem still exist?

**Comment by strasharo** [comment]
I'm hitting it on CentOS 6.4 with PBIS 9.0.2.

**Comment by strasharo** [comment]
Downgrading to 8.5.0.153 fixed the issues for me.

**Comment by dgroos** [comment]
> Does your problem still exist?

I wanted to make a note of my experience with this over the last 1.5 years. I've joined my computer using pbis-open on several computers running 16.04 and 18.04, both standard gnome and mate.

Invariably, If I try to install 8.5.x or above, I get the ...CONSTRAINT_VIOLATION. However, if I purge that, install pbis-open-8.0.0.2016.linux.x86_64.deb.sh I can successfully join! Then, I un-join (leave), purge the 8.0.0... version, reinstall any recent version (including current 9.1), and I can successfully join. 

This is completely reproducible on my system, including just did it this morning again on a new setup (on Ubuntu 18.04.3). Thanks @rbest-bt for all your support!

Leaving this note for anyone who might encounter this issue.

**Comment by krizex** [comment]
#248 also reported the same issue.
My invesgation shows it was introduced by https://github.com/BeyondTrust/pbis-open/commit/66debf03a9aac07e1002156b52933ab04c75b6d7 and around https://github.com/BeyondTrust/pbis-open/blob/master/lsass/server/auth-providers/ad-open-provider/join/join.c#L773

RCA of this issue is PBIS intend to create a disabled machine account but in some domain it was not allowed so it will get the ERROR:LW_ERROR_LDAP_CONSTRAINT_VIOLATION

**Comment by rbest-bt** [comment]
pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
