### ISSUE TITLE
UID Generation

### ISSUE THREAD

**Issue by robcanini** [BeyondTrust/pbis-open#52]
**Version**: 8.5.4.334
**OS/Distro**: Ubuntu desktop 16.04 - unity desktop
**Issue/Impact**: Cannot emulate LsaUidHashCalc algorythm

Hi,
i need to reproduce above hash logic necessary to generate user uid from ldap sid/rid.
How can i achieve that?

I'm currently developing on a Java web application using Spring Ldap Connector. I thought that i could get user uid directly from ldap but it's automatically generated from LikeWise on my system environment and i need each user uid searching by samaccountname.

I'm thinking that i need to reproduce uid generation logic in my Java application currently located in lsass/common/utils/lsasecurityidentifier.c source file.

Thanks.

**Comment by rbest-bt** [comment]
In Enterprise we use the additional AD schema attributes from RFC 2307 to store these in Directory integrated mode. They are easy to retrieve with an ldap lookup as they are gidNumber and uidNumber.

Information is located in the [installation guide](https://github.com/BeyondTrust/pbis-open/wiki/docs/PBIS_Installation_Guide.pdf), PBIS overview - storage mode section (page 20)

**Comment by robcanini** [comment]
What about open version? We currently can't update AD schema adding custom attributes.
Is user uid generation algorythm reproducible or there are any other ways to retrieve that?

**Comment by rbest-bt** [comment]
These are not custom attributes. They come with RFC 2307 which should be on any updated domain running 2003 or higher. The scheme change we do is only indexing some of them and making them available in the global catalog. Both of these options are just checkboxes on existing attributes.

As for the code you have the right file - lsass/common/utils/lsasecurityidentifier.c - just look at:
LsaUidHashCalc.

**Comment by robcanini** [comment]
```
String sid = "{$USER_SID$}";
int headerSize = 6;
int dwHash = 0;
int dwHashTemp = 0;

sid = sid.substring(headerSize);

String[] pdwAuthorities = sid.split("-");
int dwAuthorityCount = pdwAuthorities.length;

if (pdwAuthorities.length > 3)
{
	dwHash ^= Integer.valueOf(pdwAuthorities[dwAuthorityCount - 4]);
	dwHash ^= Integer.valueOf(pdwAuthorities[dwAuthorityCount - 3]);
	dwHash ^= Integer.valueOf(pdwAuthorities[dwAuthorityCount - 2]);
}

dwHashTemp = dwHash;

// squish into 12 bits
dwHash = (dwHashTemp & 0xFFF00000) >> 20;
dwHash += (dwHashTemp & 0x000FFF00) >> 8;
dwHash += (dwHashTemp & 0x000000FF);
dwHash &= 0x0000FFF;

// now, combine with 19 bits of the RID
dwHash <<= 19;
dwHash += (Integer.valueOf(pdwAuthorities[dwAuthorityCount - 1])) & 0x0007FFFF;

// dwHash contains generated UID
```

This is the working Java implementation of user UID generation from user SID for those people who need it too.

**Comment by damageboy** [comment]
Hey, for whomever cares, I've ported @robcanini's java to python:

I'll keep an up to date version here:

https://gist.github.com/damageboy/67cc8e753d50aad3254f4ec2d2ccd3e1

But here it is inline just in case...:

```python
#!/usr/bin/python3
import sys

sid = sys.argv[1]
headerSize = 6
dwHash = 0
dwHashTemp = 0;

sid = sid[headerSize:]

pdwAuthorities = sid.split("-");
dwAuthorityCount = len(pdwAuthorities)

if dwAuthorityCount > 3:
	dwHash ^= int(pdwAuthorities[dwAuthorityCount - 4])
	dwHash ^= int(pdwAuthorities[dwAuthorityCount - 3])
	dwHash ^= int(pdwAuthorities[dwAuthorityCount - 2])

dwHashTemp = dwHash

# squish into 12 bits
dwHash = (dwHashTemp & 0xFFF00000) >> 20
dwHash += (dwHashTemp & 0x000FFF00) >> 8
dwHash += (dwHashTemp & 0x000000FF)
dwHash &= 0x0000FFF

# now, combine with 19 bits of the RID
dwHash <<= 19;
dwHash += (int(pdwAuthorities[dwAuthorityCount - 1])) & 0x0007FFFF;

print(dwHash)
```

**Comment by damageboy** [comment]
Hey, for whomever cares, I've ported @robcanini's java to python:

I'll keep an up to date version here:

https://gist.github.com/damageboy/67cc8e753d50aad3254f4ec2d2ccd3e1

But here it is inline just in case...:

```python
#!/usr/bin/python3
import sys

sid = sys.argv[1]
headerSize = 6
dwHash = 0
dwHashTemp = 0;

sid = sid[headerSize:]

pdwAuthorities = sid.split("-");
dwAuthorityCount = len(pdwAuthorities)

if dwAuthorityCount > 3:
	dwHash ^= int(pdwAuthorities[dwAuthorityCount - 4])
	dwHash ^= int(pdwAuthorities[dwAuthorityCount - 3])
	dwHash ^= int(pdwAuthorities[dwAuthorityCount - 2])

dwHashTemp = dwHash

# squish into 12 bits
dwHash = (dwHashTemp & 0xFFF00000) >> 20
dwHash += (dwHashTemp & 0x000FFF00) >> 8
dwHash += (dwHashTemp & 0x000000FF)
dwHash &= 0x0000FFF

# now, combine with 19 bits of the RID
dwHash <<= 19;
dwHash += (int(pdwAuthorities[dwAuthorityCount - 1])) & 0x0007FFFF;

print(dwHash)
```

**Comment by rbest-bt** [comment]
Thank you. I've just removed the duplicate post
