### ISSUE TITLE
Can't  execute "domainjoin-gui

### ISSUE THREAD

**Issue by Excalibure86** [BeyondTrust/pbis-open#54]
**Version**: 8.5.4.334
**OS/Distro**: Ubuntu desktop 16.04 - unity desktop
**Issue/Impact**:
Hello,
I have downloaded pbis and install it on my ubuntu VM to join it to my domain.
When i try "domainjoin-gui" it's not there : no such command .
When i try it from /opt/pbis/bin/domainjoin-gui i got the error :"./domainjoin-gui: error while loading shared libraries: libglade-2.0.so.0: cannot open shared object file: No such file or directory"
Bellow you can find all the data requested .
Can you help me please.

Thanks!!
#####################################
 test@VM-1000:~$ systemctl status lwsmd.service 
● lwsmd.service - BeyondTrust PBIS Service Manager
   Loaded: loaded (/lib/systemd/system/lwsmd.service; enabled; vendor preset: enabled)
   Active: active (running) since lun. 2017-09-04 13:32:46 CET; 2min 47s ago
  Process: 932 ExecStart=/opt/pbis/sbin/lwsmd --start-as-daemon (code=exited, status=0/SUCCESS)
 Main PID: 954 (lwsmd)
   CGroup: /system.slice/lwsmd.service
           ├─ 954 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─ 962 lw-container lwreg
           ├─1007 lw-container eventlog
           ├─1053 lw-container netlogon
           ├─1093 lw-container lwio
           ├─1120 lw-container lsass
           └─1251 lw-container reapsysl

sept. 04 13:32:46 VM-GAC-1000 systemd[1]: Starting BeyondTrust PBIS Service Manager...
sept. 04 13:32:46 VM-GAC-1000 /opt/pbis/sbin/lwsmd[954]: Logging started
sept. 04 13:32:46 VM-GAC-1000 lwreg[962]: Logging started
sept. 04 13:32:46 VM-GAC-1000 eventlog[1007]: Logging started
sept. 04 13:32:46 VM-GAC-1000 netlogon[1053]: Logging started
sept. 04 13:32:46 VM-GAC-1000 lwio[1093]: Logging started
sept. 04 13:32:46 VM-GAC-1000 lsass[1120]: Logging started
sept. 04 13:32:46 VM-GAC-1000 lsass[1120]: Logging redirected
sept. 04 13:32:46 VM-GAC-1000 reapsysl[1251]: Logging started
sept. 04 13:32:46 VM-GAC-1000 systemd[1]: Started BeyondTrust PBIS Service Manager.
############################################
test@VM-1000:~$ /opt/pbis/bin/lwsm list
lwreg          running (container: 962)
dcerpc         stopped
eventlog       running (container: 1007)
lsass          running (container: 1120)
lwio           running (container: 1093)
netlogon       running (container: 1053)
rdr            running (io: 1093)
reapsysl       running (container: 1251)
usermonitor    stopped
###########################################
test@VM-1000:~$ pbis status
LSA Server Status:

Compiled daemon version: 8.5.4.334
Packaged product version: 8.5.334.8
Uptime:        0 days 0 hours 3 minutes 15 seconds

[Authentication provider: lsa-activedirectory-provider]

	Status:        Unknown
	Mode:          Unknown
##########################################
test@VM-1000:~$ /opt/pbis/bin/enum-users 
TotalNumUsersFound: 0
##########################################
test@VM-1000:~$ /opt/pbis/bin/domainjoin-cli query

Error: LW_ERROR_ACCESS_DENIED [code 0x00009cde]

Incorrect access attempt

**Output/Error**:
sudo ./domainjoin-gui 
./domainjoin-gui: error while loading shared libraries: libglade-2.0.so.0: cannot open shared object file: No such file or directory

[Isass.log.zip](https://github.com/BeyondTrust/pbis-open/files/1274699/Isass.log.zip)

**Comment by RBoulton-BT** [comment]
Have you tried using the domainjoin-cli? Personally I always use the domainjoin-cli as the domainjoin-gui has a number of rather old libglade dependencies.

**Comment by rbest-bt** [comment]
Have a look at the closed issue #44 

Solution is to install libglade
`apt-get install libglade2-0`

**Comment by Excalibure86** [comment]
I have tried domainjoin-cli like RBoulton-BT  said.
It worked 
Thanks for your help
