### ISSUE TITLE
Unable to change Password for expired Domain user 

### ISSUE THREAD

**Issue by sudhirmhrj** [BeyondTrust/pbis-open#57]
**Version**: 8.5.4.334
**OS/Distro**: CentOS Linux release 7.3.1611 (Core)
**Issue/Impact**:
I am unable to change the password for expired users from the Linux Terminal. This issue is only for expired users. 

If I try to change the password for other domain users whose password is not expired then there is no issue and I am able to change the password without any issue.

I am attaching the screenshot with this. 

Thanks.

**Output/Error**:
When Tried to change password

![image](https://user-images.githubusercontent.com/31720057/30146769-ace16012-93b9-11e7-95c9-0cf482a31aa1.png)

Screenshot of Log
![image](https://user-images.githubusercontent.com/31720057/30146829-10edc1fe-93ba-11e7-91fd-57ba3d9c72c7.png)

**Comment by sudhirmhrj** [comment]
Hi there,

Any solution for this.

Thanks.

**Comment by rbest-bt** [comment]
Has there been any change to the pam config? I've rechecked and expired accounts can update their password fine on centos 7.3 with selinux enabled

**Comment by sudhirmhrj** [comment]
I have not changed any setting in the pam files. 
here is the config from the pam files.

/etc/pam.d/system-auth
auth        required      pam_env.so
auth        sufficient    pam_lsass.so    smartcard_prompt    try_first_pass 
auth        sufficient    pam_unix.so nullok try_first_pass
auth        requisite     pam_succeed_if.so uid >= 1000 quiet_success
auth        sufficient      pam_lsass.so      try_first_pass
auth        required      pam_deny.so

account     required      pam_lsass.so      unknown_ok
account     sufficient      pam_lsass.so
account     required      pam_unix.so
account     sufficient    pam_localuser.so
account     sufficient    pam_succeed_if.so uid < 1000 quiet
account     required      pam_permit.so

password    requisite     pam_pwquality.so try_first_pass local_users_only retry=3 authtok_type=
password    sufficient    pam_unix.so sha512 shadow nullok try_first_pass use_authtok
password    sufficient      pam_lsass.so      try_first_pass      use_authtok
password    required      pam_deny.so

session     optional      pam_keyinit.so revoke
session     required      pam_limits.so
-session     optional      pam_systemd.so
session     [success=1 default=ignore] pam_succeed_if.so service in crond quiet use_uid
session     required      pam_unix.so

/etc/pam.d/login
#%PAM-1.0
auth [user_unknown=ignore success=ok ignore=ignore default=bad] pam_securetty.so
auth       substack     system-auth
auth       include      postlogin
account    required     pam_nologin.so
account    include      system-auth
password   include      system-auth
# pam_selinux.so close should be the first session rule
session    required     pam_selinux.so close
session    required     pam_loginuid.so
session    optional     pam_console.so
# pam_selinux.so open should only be followed by sessions to be executed in the user context
session    required     pam_selinux.so open
session    required     pam_namespace.so
session    optional     pam_keyinit.so force revoke
session    include      system-auth
session    include      postlogin
session    sufficient      pam_lsass.so
-session   optional     pam_ck_connector.so

/etc/pam.d/passwd
#%PAM-1.0
auth       include      system-auth
account    include      system-auth
password   substack     system-auth
-password   optional    pam_gnome_keyring.so use_authtok
password   substack     postlogin


/etc/pam.d/sshd
#%PAM-1.0
auth       required     pam_sepermit.so
auth       substack     password-auth
auth       include      postlogin
account    required     pam_nologin.so
account    include      password-auth
password   include      password-auth
# pam_selinux.so close should be the first session rule
session    required     pam_selinux.so close
session    required     pam_loginuid.so
# pam_selinux.so open should only be followed by sessions to be executed in the user context
session    required     pam_selinux.so open env_params
session    optional     pam_keyinit.so force revoke
session    include      password-auth
session    include      postlogin
session    sufficient      pam_lsass.so

**Comment by sudhirmhrj** [comment]
No Solution so far.

Thanks

**Comment by rbest-bt** [comment]
Pam files look ok. Does it work with a user that is set to change password at next login?

**Comment by sudhirmhrj** [comment]
No it doesn't work.

Only works for the user whose password is not expiring and is active.

Doesn't work with the user with chance password on next logon and users with expired passwords.

Thanks

**Comment by sudhirmhrj** [comment]
No need for PBIS any more

We have switched to samba. 

Which is working great.

Thanks
