### ISSUE TITLE
pbiso works on classroom server but breaks on LTSP clients

### ISSUE THREAD

**Issue by dgroos** [BeyondTrust/pbis-open#60]
**Version**: 8.5.4.334
**OS/Distro**: Ubuntu desktop 16.04 - unity desktop - amd64
**Issue/Impact**:
*The context:*
I have successfully gotten pbis-o to work on my installation. This is great! So what's the problem?
I use, and have used for 9 years now, an implementation of Linux referred to as LTSP. Basically, one runs a command to make a boot image of the computer one is on (call it the server). With PXE-booting, one uses this image to boot the clients connected to the server's LAN. The clients don't have HD, they are just older PC's. I have used pbis/lw-o successfully since 2010 with LTSP on Ubuntu 10.04, 12.04, 14.04.

*Description of the problem:*
The clients (I've got 30 in my class and there are another about 100 in our school) boot perfectly. If I have not joined to the AD (via pbiso) I can sit at a client and log in as a local user, works perfectly. However, when I go back to the classroom server for these clients, run "sudo /opt/pbis/bin/domainjoin-cli join DOMAIN.COM adminuser" and successfully join the AD, then go back to the client, I can neither log in as a local user now and also neither as an AD user. If I un join, then I go back to being able to log in as a local user at the client. And to repeat, when joined to the AD, login at the server works with both local and AD users. In conclusion, joining breaks authentication on clients but works on server.

This is a tough nut to crack. The people in the LTSP community don't know pbiso, those in pbiso community don't know ltsp. Do you have any recommendations on places to start to dig for possible useful information, either at the client or at the server? What would I look for in the logs (I'm not any linux expert!). BTW, I'm using LightDM on the server, and LTSP-DM on the clients. I've been working on this for 2 weeks now.

Thanks,
David

**Comment by dgroos** [comment]
I continue to struggle with the AD joining software working great on the Ubuntu LTSP-pnp server (for both local and AD users) but breaking authentication on its fat clients (for both local and AD users). This is completely repeatable by joining the AD and unjoining it.

I know there's a lot of stuff here so I've spent a few hours doing my best to organize relevant logs, from the server and the client, using some annotations and putting most relevant logs first on the paste-bin pages. Please help me sort this out.
Thanks,
David
(PS I continue to seek help on this from the LTSP community)

*************************
*************************
LOGS FROM SERVER

(Log shows records from server states, in order: Unjoined, Joined, Unjoined)
This is auth.log at the server. It includes logs showing successful and unsuccessful login attempts according to whether joined or not. I've annotated sections by what's happening (as far as I can interpret) as well as the amount of time since the last log entry Min:Sec [I've subbed in MY-SERVER, ADMIN-USER, LOCAL-USER, MY.DOMAIN.COM, ADMIN]:
http://paste.ubuntu.com/25557715/

(Log shows records from server states, in order: Unjoined, Joined, Unjoined)
This is the syslog at the server during the same time period. It's included for reference:
http://paste.ubuntu.com/25557785/

*************************
*************************

LOGS FROM LTSP CLIENT

(Logs when server is Unjoined)
This is the authlog, ldmlog and syslog (in that order) obtained by epoptes (root user on client). LOCAL-USER logs in successfully. Note that the auth.log and ldm log don't go past line number 49.
http://paste.ubuntu.com/25558410/

(Logs when server is Joined)
This is the auth.log, ldm and syslog from the ltspclient. Includes (unsuccessful) login attempts by both LOCAL-USER and AD-USER. Note that the auth.log and ldm logs don't go past line number 35.
http://paste.ubuntu.com/25558816/

**Comment by rbest-bt** [comment]
While you wait for me to learn LTSP what was the last working setup? pbis/lw-o and ubuntu versions

**Comment by dgroos** [comment]
;-)

A person in the ltsp community suggested a test which seems to be giving some useful info. Furthermore, your question above got me asking a further question to the ltsp community (comparing the LDM of 14.04 and 16.04). Thanks.

The LTSP setup was working on Ubuntu 14.04.x with pbis-open-8.3.0.3287.linux.x86.deb.sh (using i386 system). So, thinking about it, another difference between successful setups on Ubuntu 10.04, 12.04 and 14.04 VS the unsuccessful 16.04 is that the successful ones were 32 arch and am currently using 64.

Will continue to dig.
David

**Comment by dgroos** [comment]
So... the ltsp person had some thoughts. First, he said that the point of failure looks to be the LDM (ltsp-display-manager). However, he said it has changed little over the years. I wonder if there's something new in pbis-open? Am keeping that thought in mind but doesn't give me much traction yet.

Furthermore he saw these lines in the client auth.log when the server was in an UNJOINED state and wondered about lsass-pam. As mentioned, when UNJOINED, login works for local users as opposed to during JOINED state login doesn't work. (The ltsp expert thinks that maybe some pam module that is supposed to be and successfully works on the server is being put onto the client image. Therefore, the client image is trying to do some login action locally instead of referring login actions to the server. To make this long story shorter, if I could identify this possible pam module I could find a way to have it excluded from the client image--that's the idea at the moment!)
```
Sep 15 18:18:47 MY-LTSP-CLIENT su[1821]: [lsass-pam] [module:pam_lsass]User LOCAL-USER is denied access because they are not in the 'require membership of' list
Sep 15 18:18:47 MY-LTSP-CLIENT su[1821]: [lsass-pam] [module:pam_lsass]User LOCAL-USER is denied access because they are not in the 'require membership of' list
Sep 15 18:18:47 MY-LTSP-CLIENT su[1821]: Successful su for LOCAL-USER by root
Sep 15 18:18:47 MY-LTSP-CLIENT su[1821]: + ??? root:LOCAL-USER
Sep 15 18:18:47 MY-LTSP-CLIENT su[1821]: pam_unix(su:session): session opened for user LOCAL-USER by (uid=0)
Sep 15 18:18:47 MY-LTSP-CLIENT systemd-logind[744]: New session c1 of user LOCAL-USER.
Sep 15 18:18:47 MY-LTSP-CLIENT systemd: [lsass-pam] [module:pam_lsass]User LOCAL-USER is denied access because they are not in the 'require membership of' list
Sep 15 18:18:47 MY-LTSP-CLIENT systemd: [lsass-pam] [module:pam_lsass]User LOCAL-USER is denied access because they are not in the 'require membership of' list
```

Any guesses or anything not looking quite right?

Thanks for your willingness to consider this problem when half of the overall framework is basically unavailable (I'm not asking you to study ltsp!).
David

**Comment by dgroos** [comment]
Further...
The LTSP person followed up with:

> If there's a relevant active service running, you could try disabling
> it, but this sounds like it's edits to your PAM/NSS configuration that
> may be incompatible with the local configuration.
> 
> My hunch is you'll need to revert at image creation time (or boot time)
> changes to /etc/pam.d/* and /etc/nsswitch.conf to support AD.

Thoughts? Config files? What I should be exploring/focusing on? true I'm no expert, just a motivated teacher wanting to provide the best for his students, and colleagues.
Thanks,
David

**Comment by dmorash-BT** [comment]
It looks like users are being denied because they aren't specified in the RequireMembershipOf setting.  RequireMembershipOf is used to restrict who can logon.  Could you post the output of:
/opt/pbis/bin/config --detail RequireMembershipOf

If it has been inadvertently set, you can clear it by executing (via sudo or as root):
/opt/pbis/bin/config RequireMembershipOf ""

**Comment by dgroos** [comment]
Hi @dmorash-BT That is an interesting idea. Here is the result of the test:

When run on the server (where login works) I get this results:
$ /opt/pbis/bin/config --detail RequireMembershipOf
Name: RequireMembershipOf
Description: Restrict logon access to computer to specific users or group members, or SIDs
Type: multistring
Current Values:
Current Value is determined by local policy.

Tomorrow after the students leave I'll run this on the client and see what I get, can't wait to check! (I'll have to do a couple things before I can return the client to normal testing state). Thanks for your help and @rbest-bt  help!

**Comment by dgroos** [comment]
Couldn't wait.
Just ran the command on the client: /opt/pbis/bin/config --detail RequireMembershipOf
The client also said the exact same things...
?

**Comment by dgroos** [comment]
So, actually I don't want authentication handled by pbis-open at the client. LTSP is designed to refer login at the client to the server. As mentioned above by the quote from the ltsp person, is there some way to:

> ...revert at image creation time (or boot time) changes to /etc/pam.d/* and /etc/nsswitch.conf

Authentication is working fine at the server.

**Comment by rbest-bt** [comment]
Simplest way is to issue a domainleave
`/opt/pbis/bin/domainjoin-cli leave`

PBIS needs to be in the pam configuration to handle authentication. Sounds like they are conflicting pam configuration.

**Comment by dgroos** [comment]
Sounds right. Going to do fresh install of Ubuntu/ltsp. Then I'll install pbis-open and using [etckeeper](https://help.ubuntu.com/lts/serverguide/etckeeper.html) I'll be able to see where the changes are being made to the system, then examine which of these changes is getting carried forward to the fat client image.

**Comment by dgroos** [comment]
More specific question:
When I issue: 
`/opt/pbis/bin/domainjoin-cli join domain.com adminuser`

some files must get altered causing the change in state (from unjoined --> joined)
Which files get altered during join/leave?

I ask this since it is the joined state where local clients can't authenticate and they return to being able to log in once the `... leave` command has been issued.

**Comment by davidmorash** [comment]
If you run 
/opt/pbis/bin/domainjoin-cli join --advanced --preview domain.com

you'll see which join "modules" that will be run.  Leave supports similar functionality, e.g. 

/opt/pbis/bin/domainjoin-cli leave --advanced --preview.

For some modules you can get more information via /opt/pbis/bin/domainjoin-cli join --advanced --details module domain.com The Linux Administration Guide, §Domain Join Tool Commands has more information on these commands.

Based on what you say above, the problem is most likely that we make changes to the pam stack so that AD users get authenticated via PBIS.

**Comment by dgroos** [comment]
On Fri, Sep 22, 2017 at 12:23 PM, David Morash <notifications@github.com>
wrote:

> If you run
> /opt/pbis/bin/domainjoin-cli join --advanced --preview domain.com
>
> you'll see which join "modules" that will be run. Leave supports similar
> functionality, e.g.
>
> /opt/pbis/bin/domainjoin-cli leave --advanced --preview.
>
> For some modules you can get more information via
> /opt/pbis/bin/domainjoin-cli join --advanced --details module domain.com
> The Linux Administration Guide, §Domain Join Tool Commands has more
> information on these commands.
>
 Excellent info, I'll be exploring!

> Based on what you say above, the problem is most likely that we make
> changes to the pam stack so that AD users get authenticated via PBIS.
>
Does anything jump to mind that might have changed between v. 8.3 and
current version of pbis-open? I ask because 8.3 just worked with ltsp. BUT,
of course, the change could also be between 14.04-->16.04. But, the ltsp
people say they haven't made much changes in how they do authentication
much in several version changes so that's why I'm leaning towards possible
changes in pbis-open.

THANKS!
David

>
>

**Comment by dgroos** [comment]
>         [F] stop           - stop daemons
>         [F] hostname       - set computer hostname
>         [F] keytab         - initialize kerberos keytab
>     [X] [N] join           - join computer to AD
>         [F] nsswitch       - enable/disable PowerBroker Identity Services nsswitch module
>     [X] [N] cache          - manage caches for this host
>         [F] start          - start daemons
>     [X] [N] krb5           - configure krb5.conf
>         [F] bash           - fix bash prompt for backslashes in usernames
>     [X] [N] pam            - configure pam.d/pam.conf
>     [X] [S] ssh            - configure ssh and sshd
>         [F] DDNS           - Configure Dynamic DNS Entry for this host

So...

1.  I only need to focus on the 5 modules with an [X] in front of them...
1.  Using  ... details module ... It looks like the most important aspects for this problem are:
    1. for join module I'll need to look into: Sychronize time to DC.
    1. for pam module I'll need to check into: pam.d/pam.conf and look into system utility pam-auth-update
    1. for ssh module I'll need to check into /etc/ssh/sshd_config and GSSAPIAuthentication

Does that analysis seem reasonable?
Thanks again,
David

**Comment by dgroos** [comment]
Getting close!

Looks like I can make things work if I can get /opt/pbis/share/config/lsassd.reg to load the edit that I made:
```
"OtherPasswordPrompt" = {
    default = "Password: "
    doc = "Password prompt for non-local, non-ActiveDirectory users"
```
Or is there some other way I should have made it say `"Password: "`?

**Comment by dgroos** [comment]
I didn't mean to close it yet! (wishful thinking?)

**Comment by dgroos** [comment]
As per the instructions on the [main pbis-open github page](https://github.com/BeyondTrust/pbis-open) I ran: 
`sudo /opt/pbis/bin/lwregshell`
which returned:
`sudo: /opt/pbis/bin/lwregshell: command not found`
And looking in the bin/ directory there was no lwregshell but instead regshell...

As per the instructions [on this page](https://www.tux.in.ua/articles/3117) to reload the registries (translated from Russian I believe):
`sudo /opt/pbis/bin/regshell import /opt/pbis/share/config/lsassd.reg`

And it looks like it might have worked. I'll be testing!

**Comment by dgroos** [comment]
Unexplainable. 
I can make the client to successfully log into AD when I:
`sudo nano /opt/pbis/share/config/lsassd.reg`
and change the entry:

> "ActiveDirectoryPasswordPrompt" = {
>     default = ""

to _anything_ like:

> "ActiveDirectoryPasswordPrompt" = {
>     default = "Passwerd: "

Neither the entries for "LocalPasswordPrompt" or "OtherPasswordPrompt" affected the success or failure of logins. Local users can't login to the clients but that is (minimally) acceptable right now.

Each time I ran the following to reload the edited registry:
` sudo /opt/pbis/bin/regshell import /opt/pbis/share/config/lsassd.reg`
 
But at the moment, I'm happy that students can get at the computers!
Thanks for all of your suggestions,
David

**Comment by dgroos** [comment]
So, from the perspective of the client computer:
pbis modifies the prompt for a password sent by the LTSP Display Manager (LDM):
Normally LDM sends the password prompt like this: "`david@localhost's password:`"
But with the pbis modification it is simply: "`Password:`"
So, pbis modifies the password prompt and LDM can't cope with that.

So what we want to achieve is this: when you `ssh user@server` from client pc, you want to see "Password: " with exactly one space at the end, instead of "Password:" with no space as it is now

For some reason, by editing the line  in `/opt/pbis/share/config/lsassd.reg`:
>     "ActiveDirectoryPasswordPrompt" = {
>     default = ""
so that the default value says `anything`, this need of LDM becomes satisfied for AD users.

I don't understand why putting in some random value for the default value seems to allow pbis to function properly for the ltsp client pc. But am glad it does!

**Comment by dgroos** [comment]
So, from the perspective of the client computer:
pbis modifies the prompt for a password sent by the LTSP Display Manager (LDM):
Normally LDM sends the password prompt like this: "`david@localhost's password:`"
But with the pbis modification it is simply: "`Password:`"
So, pbis modifies the password prompt and LDM can't cope with that.

So what we want to achieve is this: when you `ssh user@server` from client pc, you want to see "Password: " with exactly one space at the end, instead of "Password:" with no space as it is now

For some reason, by editing the line  in `/opt/pbis/share/config/lsassd.reg`:
>     "ActiveDirectoryPasswordPrompt" = {
>     default = ""
so that the default value says `anything`, this need of LDM becomes satisfied for AD users.

I don't understand why putting in some random value for the default value seems to allow pbis to function properly for the ltsp client pc. But am glad it does!

**Comment by davidmorash** [comment]
Well that does seem to be an odd solution, i.e. I wouldn't have expected LDM to care, but awesome that you have a solution.     

Additionally, it might be easier to use a) edit-reg or b) regshell directly to edit that value instead of editing the .reg file and reimporting it.

**Comment by dmorash-BT** [comment]
Updated the README to fix incorrect reference to lwregshell. Added note about edit-reg.
