### ISSUE TITLE
Samba Server Performance Low

### ISSUE THREAD

**Issue by jelayeb** [BeyondTrust/pbis-open#61]
**Version**: 8.5.4.334
**OS/Distro**: Centos 6.7 / Samba4 File Server  samba4-4.2.10-7.
**Issue/Impact**:
*Note: replace content with your own*

 1. systemctl status lwsmd.service
 service lwsmd status
lwsmd (pid 41387 41318 41234 41164 41095 41023 40956) is running...

 2. /opt/pbis/bin/lwsm list
/opt/pbis/bin/lwsm list
lwreg          running (container: 41023)
dcerpc         stopped
eventlog       running (container: 41318)
lsass          running (container: 41234)
lwio           running (container: 41164)
netlogon       running (container: 41095)
rdr            running (io: 41164)
reapsysl       running (container: 41387)
usermonitor    stopped

 3. /opt/pbis/domainjoin-cli query
 domainjoin-cli query
Name = HOSTNAME
Domain = DOMAINNAME.COM
Distinguished Name = CN=HOSTNAME,OU=Servers,OU=Local,DC=domainname,DC=com

 4. pbis status
 5. /opt/pbis/bin/enum-users
TotalNumUsersFound: 2426

my problem here is with slow samba server performance since I start using pbis-open with the file server. 
I can see many running processing belongs to lwsmd  lw-containers lsass, lw-containers lwreg, lw-container lwio, lw-container netlogon ,lw-container eventlog and lw-container reapsysl 

I have 3 sessions only opened with samba and about 32GB of RAM Used, 0 memory left. 
normally it is normal for a file server with huge memory used, but never seen it with only 3 sessions, I mean before I use pbis-open

I wish if you can advice me here about this issue

**Comment by rbest-bt** [comment]
We are having a look into some other samba issues. I'll make a note to check on this also.

**Comment by rbest-bt** [comment]
This has been improved a lot in the recent releases. I would recommend upgrading to BeyondTrust Active Directory Bridge for continued support.  https://www.beyondtrust.com/privilege-management/active-directory-bridge

pbis-open will longer receive updates and will be archived. Closing all outstanding issues.
