### ISSUE TITLE
Can't Login - LW_ERROR_KRB5_NOPERM_ETYPE

### ISSUE THREAD

**Issue by effh** [BeyondTrust/pbis-open#63]
Version: 8.5.4.334
Distro: Fedora 26
Details:
I am unable to login as a domain user, pbis authenticate user returns Kerberos Encryption Type Not Permitted.
(I am redacting username and domain details.)

 1. systemctl status lwsmd.service
● lwsmd.service - BeyondTrust PBIS Service Manager
   Loaded: loaded (/usr/lib/systemd/system/lwsmd.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-09-25 16:28:37 BST; 32min left
  Process: 946 ExecStart=/opt/pbis/sbin/lwsmd --start-as-daemon (code=exited, status=0/SUCCESS)
 Main PID: 1025 (lwsmd)
    Tasks: 315 (limit: 4915)
   CGroup: /system.slice/lwsmd.service
           ├─1025 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─1068 lw-container lwreg
           ├─1144 lw-container eventlog
           ├─1190 lw-container netlogon
           ├─1238 lw-container lwio
           ├─1287 lw-container lsass
           └─1373 lw-container reapsysl

Sep 25 16:28:36 sour-00170 reapsysl[1373]: Logging started
Sep 25 16:28:37 sour-00170 systemd[1]: Started BeyondTrust PBIS Service Manager.
Sep 25 16:29:36 sour-00170 lsass[1287]: [lsass] Domain '#####.####.net' is now online
Sep 25 15:29:35 sour-00170 lsass[1287]: [lsass] Failed to sync system time [error code: 40075]
Sep 25 15:31:09 sour-00170 lsass[1287]: [LwKrb5InitializeUserLoginCredentials /builder/src-git/Platform/src/linux/lwadvapi/threaded/lwkrb5.c:1492] KRB5 Error code: -1765328148 (Message: Encryption type not permitted)
Sep 25 15:31:09 sour-00170 lsass[1287]: [lsass] Failed to authenticate user (name = '#####') -> error = 41969, symbol = LW_ERROR_KRB5_NOPERM_ETYPE, client pid = 2654
Sep 25 15:52:08 sour-00170 lsass[1287]: [LwKrb5InitializeUserLoginCredentials /builder/src-git/Platform/src/linux/lwadvapi/threaded/lwkrb5.c:1492] KRB5 Error code: -1765328148 (Message: Encryption type not permitted)
Sep 25 15:52:08 sour-00170 lsass[1287]: [lsass] Failed to authenticate user (name = '#####') -> error = 41969, symbol = LW_ERROR_KRB5_NOPERM_ETYPE, client pid = 3080
Sep 25 15:52:21 sour-00170 lsass[1287]: [LwKrb5InitializeUserLoginCredentials /builder/src-git/Platform/src/linux/lwadvapi/threaded/lwkrb5.c:1492] KRB5 Error code: -1765328148 (Message: Encryption type not permitted)
Sep 25 15:52:21 sour-00170 lsass[1287]: [lsass] Failed to authenticate user (name = '#####') -> error = 41969, symbol = LW_ERROR_KRB5_NOPERM_ETYPE, client pid = 3086

 2. /opt/pbis/bin/lwsm list
lwreg          running (container: 1068)
dcerpc         stopped
eventlog       running (container: 1144)
lsass          running (container: 1287)
lwio           running (container: 1238)
netlogon       running (container: 1190)
rdr            running (io: 1238)
reapsysl       running (container: 1373)
usermonitor    stopped

 3. /opt/pbis/domainjoin-cli query
run with sudo, this returns Name, Domain and distinguished name, which all look correct.

 4. pbis status
returns more information on the structure of the company network that I probably need to know, all looks sensible in that it definitely came from the company DC.

 5. /opt/pbis/bin/enum-users
Domain users are returned.

 6. attach logs
  - /opt/pbis/bin/lwsm set-log-target -p lsass -  file /tmp/lsass.log
  - /opt/pbis/bin/lwsm set-log-level -p lsass - debug
  - attach log
[lsass.redacted.log](https://github.com/BeyondTrust/pbis-open/files/1329947/lsass.redacted.log)

**Output/Error**:
pbis authenticate-user --user ***** --domain *****.****.net
Password:
Error: LW_ERROR_KRB5_NOPERM_ETYPE (0xa3f1)

**Prior formation and experience**
I have 8.5.3.293 on fedora 25 connected to the company domain, so this is something new with 8.5.4 and fc26.

Thanks in advance for your time.

**edited to add**
Additionally, I have now run through the login-section of the troubleshooting guide.
nothing in there helped, but I can confirm that I am able to su into the user account.

**Comment by RBoulton-BT** [comment]
I've not come across this one before but the message appears to be stating it doesn't like one of the encryption types kerberos is offering. We have some entries in the krb5.conf file that we haven't removed in case it affects legacy systems. You could try editing the following lines in /etc/krb5.conf to remove the DES entries

[libdefaults]
  default_tgs_enctypes = AES256-CTS AES128-CTS RC4-HMAC
  default_tkt_enctypes = AES256-CTS AES128-CTS RC4-HMAC
  preferred_enctypes = AES256-CTS AES128-CTS RC4-HMAC

**Comment by effh** [comment]
I've now tried that change, both with and without allow_weak_crypto = true set, without any change.
For the avoidance of doubt, I've also tried deliberate wrong entry of password, which gives a password mis-match error instead, so it isn't a case of using the wrong password.

**Comment by RBoulton-BT** [comment]
Have you tried without the RC4-HMAC?

**Comment by effh** [comment]
Thanks for the prompt response.
Between my last comment and now, I have tried a different change; I prevented the loading of /etc/krb5.conf.d/ and the contained crypto-policies file.  This has resulted in successful /pbis authenticate-user/ and successful login using domain credentials.
Again Thank-you for your help.

Summary: On Fedora 26, the default /etc/krb5.conf.d/crypto-policies is too restrictive. The Quick fix is to remove the link.
A Longer-term fix would be to work out what is wrong with the default and edit/apply.

**Comment by hasanakgoz** [comment]
> I've not come across this one before but the message appears to be stating it doesn't like one of the encryption types kerberos is offering. We have some entries in the krb5.conf file that we haven't removed in case it affects legacy systems. You could try editing the following lines in /etc/krb5.conf to remove the DES entries
> 
> [libdefaults]
> default_tgs_enctypes = AES256-CTS AES128-CTS RC4-HMAC
> default_tkt_enctypes = AES256-CTS AES128-CTS RC4-HMAC
> preferred_enctypes = AES256-CTS AES128-CTS RC4-HMAC

it works for me. Thanks
