### ISSUE TITLE
PBIS doesn't obey AD Account Password GPO Policy 

### ISSUE THREAD

**Issue by sonfrau** [BeyondTrust/pbis-open#64]
**Version**: 8.5.4.334
**OS/Distro**: Ubuntu desktop 16.04 - unity desktop
**Issue/Impact**: Low
* Note: How to enforce the Active Directory Account Password GPO policy from PBIS (/ opt / pbis / bin / password).

We have defined an AD Account Password GPO Policy to make sure the strength of used passwords by our users.

We have noticed that if we change the user password using PBIS, we can jump this GPO policy.

Is there any way to enforce that PBIS uses this GPO Policy?

Thanks and kind regards

**Output/Error**:

**Steps to Reproduce**:
 1. install command
 2. Domainjoin command
 3. Command that returns issue

**Comment by dmorash-BT** [comment]
Hi,
We haven't seen password policies not being respected; for AD users the password change is sent to the DC to be processed so password policies should be respected.

Could you provide a bit more information so we can track down what might be happening:
- are the password policies enforced when changing user passwords on the DC?
- are you modifying the Default Domain policy  or is this is a separate policy?
- are you joined to an OU?
- can you provide a copy of your pam stack ?

**Comment by sonfrau** [comment]
Sorry, you're right I misread the password account policy.

PBIS is working flawlessly.

Accept my apologies

Kind regards.
