### ISSUE TITLE
ask local user password

### ISSUE THREAD

**Issue by mmiat** [BeyondTrust/pbis-open#65]
**Version**: 8.5.4.334
**OS/Distro**: Ubuntu desktop 16.04 - gnome desktop

I've a local user mauro, and a domain user mmiat, and i login as m.miat (that is in visudo)
when i install some packages from shell, it ask me m.miat password and install
when i install some packages from gui, it ask me mauro password

why? how fix? thanks

**Comment by rbest-bt** [comment]
If you give the user rights via a group you can then add the group to the policy kit:
`root@ubu1604:~# cat /etc/polkit-1/localauthority.conf.d/51-ubuntu-admin.conf 
[Configuration]
AdminIdentities=unix-group:sudo;unix-group:admin;unix-group:DOMAIN\\domain^users`

This will allow that group of users to authenticate software center installs.

Reference
https://askubuntu.com/questions/385520/software-center-prompts-password-of-another-user

**Comment by mmiat** [comment]
I've added

> AdminIdentities=unix-group:sudo;unix-group:admin;unix-group:ANTEA\\m.miat

but still ask mauro password

**Comment by rbest-bt** [comment]
Is m.miat the user? If so you need to use unix-user
`AdminIdentities=unix-group:sudo;unix-group:admin;unix-user:ANTEA\\m.miat`

http://manpages.ubuntu.com/manpages/precise/man8/pklocalauthority.8.html

**Comment by mmiat** [comment]
awesome, it works! thank you vey much!
