### ISSUE TITLE
Fails to work when the machine has more than one NIC { eth0, eth1}

### ISSUE THREAD

**Issue by ngudger2021** [BeyondTrust/pbis-open#67]
**Version**: 8.5.4.334
**OS/Distro**: Ubuntu desktop 16.04.3  - unity desktop
** Fails to work when the machine has more than one NIC { eth0, eth1} **:

When reporting an issue it's important that we have as much detail as you can provide. The following is a list of commands to check.

 1.  lwsmd.service - BeyondTrust PBIS Service Manager
   Loaded: loaded (/lib/systemd/system/lwsmd.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2017-10-05 10:10:43 BST; 2h 7min ago
  Process: 1237 ExecStart=/opt/pbis/sbin/lwsmd --start-as-daemon (code=exited, status=0/SUCCESS)
 Main PID: 1300 (lwsmd)
    Tasks: 106
   Memory: 30.7M
      CPU: 19.411s
   CGroup: /system.slice/lwsmd.service
           ├─1300 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─1315 lw-container lwreg
           ├─1466 lw-container eventlog
           ├─1486 lw-container netlogon
           ├─1505 lw-container lwio
           ├─1524 lw-container lsass
           └─1631 lw-container reapsysl

 2. /opt/pbis/bin/lwsm list : 
lwreg          running (container: 1315)
dcerpc         stopped
eventlog       running (container: 1466)
lsass          running (container: 1524)
lwio           running (container: 1505)
netlogon       running (container: 1486)
rdr            running (io: 1505)
reapsysl       running (container: 1631)
usermonitor    stopped

 3. /opt/pbis/domainjoin-cli query :
Name = linuxupdates
Domain = ********.**.**
Distinguished Name = CN=linuxupdates,CN=Computers,DC=*********,DC=**,DC=**

 4. pbis status
LSA Server Status:
Compiled daemon version: 8.5.4.334
Packaged product version: 8.5.334.8
Uptime:        0 days 2 hours 11 minutes 34 seconds
[Authentication provider: lsa-activedirectory-provider]
        Status:        Unknown
        Mode:          Unknown

 5. /opt/pbis/bin/enum-users
TotalNumberOfUsersFound 0

 6. attach logs
  - /opt/pbis/bin/lwsm set-log-target -p lsass -  file /tmp/lsass.log
  - /opt/pbis/bin/lwsm set-log-level -p lsass - debug
  - attach log

Hi i have install with this guide  https://www.kiloroot.com/add-ubuntu-14-04-lts-server-to-a-windows-active-directory-domain-fullest-integration/  and it works on all linux boxes that have 1 network connection, but i have 2 machines that have 2 network interfaces and it will install but not let me log in.

does anybody have any idea??

is there a way to tell PBIS to use a specific NIC example { eth0 }.

Thanks in advance

**Comment by rbest-bt** [comment]
Is this no longer an issue? Can you let us know what the issue was?
