### ISSUE TITLE
Two users have same UID

### ISSUE THREAD

**Issue by theonyxsun** [BeyondTrust/pbis-open#68]
**Version**: 8.5.5.372
**OS/Distro**: Ubuntu desktop 16.04 - unity desktop
**Issue/Impact**: Two users have same UID

Hello, I am using PBISO to connect several Linux systems to an Active Directory domain. I discovered that when one of our users logs in to a system, their files sometimes show up as belonging to the wrong username.

By running "id" on both usernames, I discovered that both users have the same UID. I ran this test on multiple machines, some using 8.5.5.372 and others using 8.5.4.334. All machines report that both users have the same ID of 1505433401. A reboot makes no difference.

Additionally, if I run an "id 1505433401," it's pretty well a crap shoot which username I'm going to get reported back to me.

Using chown to change ownership of files to one username or the other makes no difference. The ownership of the files seems to be completely random between the two users. One time I'll run "ls -l" and see user A's username, and then the next time I'll get user B's username.

**Steps to Reproduce**:
 1. Install PBISO
 2. Run "id userA"
 3. Run "id userB"
 4. Observe that their UIDs are the same
 5. Run "chown userA file1"
 6. Run "ls -l file1"
 7. Observe that file ownership does not appear to be userA, but rather userB

Additional information: The users should have nothing to do with eachother in AD. They are both simply user accounts for different users in our organization.

There are also LDAP-authenticated Unix machines (Macs and Linux) in our environment that use other solutions besides PBISO to keep UIDs the same across systems, and these users have completely different UIDs on those systems.

**Comment by theonyxsun** [comment]
This is causing serious problems, as it is flooding my syslog with the following error every second:

Conflict discovered for UID 1505433401. User ADS\userA had this UID at time 2017/10/18 09:25:14, but now (2017/10/18 09:25:14) user ADS\userB has the UID. Please check that these users are not currently conflicting in Active Directory. This could also happen (safely) if the UIDs were swapped between these users.

**Comment by RBoulton-BT** [comment]
The algorithm used to generate UIDs is based on the user's SID. There can be an issue if more than 2^19 (524,288) users/groups/computers have been created in your domain. Where objects have a RID greater than 524,288 there is a possibility of UID could conflict with one below that figure.

**Comment by theonyxsun** [comment]
Thank you.

Yeah, we're way over that number of objects in our AD environment. Do you have any suggestions for working around that limitation? One of the users doesn't need to have access to this Linux system at all. I would suspect this wouldn't be the only case of this happening on our domain.

**Comment by theonyxsun** [comment]
SOrry for the duplicate post, but I wasn't sure if I should reply here or
on github:


Thank you.

Yeah, we're way over that number of objects in our AD environment. Do you
have any suggestions for working around that limitation? One of the users
doesn't need to have access to this Linux system at all. I would suspect
this wouldn't be the only case of this happening on our domain.

**Comment by rbest-bt** [comment]
There is no option to limit the available users within open. With that many objects you may want to upgrade to enterprise. You'll be able to configure cells to provision users/groups to use pbis. Within the cells you can control assigning UIDs and GIDs. Users that are not provision to the appropriate cell will not show up on the linux machine. 

More information can be found within the administration guide.
