### ISSUE TITLE
PBIS Crashing after restart / cant login after restart Ubuntu 16.04

### ISSUE THREAD

**Issue by seritest** [BeyondTrust/pbis-open#7]
Hi.
We're having two issues on many PCs. One is we often have to restart lwsmd service after each PC restart before being able to login with a domain account. The second is the service is often crashing.
Could you let me know which logs we should be looking at or what I can provide to get some help with this please?
Thanks

**Comment by RBoulton-BT** [comment]
Issue https://github.com/BeyondTrust/pbis-open/issues/6 discusses similar scenario. It appears we will get better results by changing the lwsmd.service file (/lib/systemd/system/lwsmd.service) to reference After=network-online.target and also the TrustEnumerationWait settings have been introduce to help improve this.

For the crash, if you grab a crash report and send it we should be able to identify where the problem is occurring.

**Comment by seritest** [comment]
I made the change to the lwsmd.service file but still had the issue. I've attached the crash report. Does this give any clue?

[_opt_pbis_sbin_lwsmd.0.crash.zip](https://github.com/BeyondTrust/pbis-open/files/599788/_opt_pbis_sbin_lwsmd.0.crash.zip)

**Comment by RBoulton-BT** [comment]
Hi,

You mention you had 2 issues, was this the second issue you are referring to or both?

This crash report is the same as another bug we have been tracking internally. However, we have been seeing this only on first logon after PBIS installation. Do you have any more details regarding the situation you are seeing the crash?

**Comment by seritest** [comment]
I was referring to the issue of having to restart the lwsmd service after a system restart. The crash I uploaded I thought may have been related..I'm pretty sure we see this occur more frequently than just the first logon after installation, but I'll start to keep a record to be sure.

**Comment by seritest** [comment]
Another clue.. When in the situation where after a restart I cant login. If I ssh to the PC and login with a local account. Immediately login with the domain account now works.

**Comment by rbest-bt** [comment]
8.5.5.372 was released Tuesday. This has a fix for the login issue. Give it a try and see if the issue still exists

**Comment by theonyxsun** [comment]
Hi I'm having this same issue and I use the APT repo to update several machines on our network. Do you know when the repo will be updated with this release?

Thanks,

Matt

**Comment by rbest-bt** [comment]
I update the repos last. I haven't decided whether is will be late today or Monday. But for sure beginning of next week.

**Comment by rbest-bt** [comment]
Repos have been updated
