### ISSUE TITLE
teamviewer 12

### ISSUE THREAD

**Issue by mmiat** [BeyondTrust/pbis-open#70]
**Version**: 8.5.4.334
**OS/Distro**: Ubuntu desktop 16.04 - gnome desktop

i've ubuntu 16, joined to a domain
if i login with a local user, i can connect with teamviewer
if i login with a domain user, i can't, see black screen
there is something that i've to configure to teamviewer to give it access to the domain user session?
thanks

**Comment by rbest-bt** [comment]
Do you have systems logs or teamviewer logs reporting errors?

**Comment by mmiat** [comment]
TeamViewer12_Logfile.log
[oggi.txt](https://github.com/BeyondTrust/pbis-open/files/1401122/oggi.txt)
hope this can help

**Comment by mmiat** [comment]
i think it could be related to gdm, i remember that in the past i've similar problem and i solved using lightdm

**Comment by rbest-bt** [comment]
Can you get me the logs from when to try to connect. Run the following then connect:
> /opt/pbis/bin/lwsm set-log-level lsass - debug; /opt/pbis/bin/lwsm set-log-target lsass - file /tmp/lsass.log

Is the connection a first time login? Or was a local login done before teamviewer?

**Comment by rbest-bt** [comment]
no response closing

**Comment by mmiat** [comment]
I've launched 
` /opt/pbis/bin/lwsm set-log-level lsass - debug;
then
`/opt/pbis/bin/lwsm` set-log-target lsass - file /tmp/lsass.log
but the file lsass.log is empty
this is TeamViewer12_Logfile.log

> 2018/01/11 15:09:39.636  1627 4127619904 S   Estimated RTT to Router: 20 ms, Reliability: 2, Carrier: 1
2018/01/11 15:09:40.653  1627 4119227200 S   Estimated RTT to 266061114: 0 ms, Reliability: 2, Carrier: 2
2018/01/11 15:09:40.653  3735 4057975616 DX0   Estimated RTT to 266061114: 0 ms (rel=2)
2018/01/11 15:09:46.213  3735 3976194880 DX0   DisplayQuality m=0, bpp=32, q=95, echo=10, conRating=3, cpu=23200, capacity=75954, RTT=709, reliability=1
2018/01/11 15:09:46.241  3735 4047485760 DX0   Desktopencoding: Tiles, buffer depth=32bpp, transmitted color depth=8bpc, features=127
2018/01/11 15:09:46.262  3735 4047485760 DX0   Tile caching activated
2018/01/11 15:09:46.265  3735 4047485760 DX0   CScreenStreamSender::SendDisplayParams() 1920x1080x32 on 5 to 3
2018/01/11 15:09:46.357  1627 4110834496 S   Estimated Bandwidth Capacity to Router: 12954 kbit/s, Reliability: 2, Carrier: 1
2018/01/11 15:09:46.995  1627 4102441792 S   Estimated Bandwidth Capacity to 266061114: 110616 kbit/s, Reliability: 2, Carrier: 2
2018/01/11 15:09:46.995  3735 4016036672 DX0   Estimated bandwidth capacity to 266061114: 110616 kbit/s (rel=2)

I've tried connecting both before and after user logon
