### ISSUE TITLE
Trust enumeration can take multiple minutes

### ISSUE THREAD

**Issue by Alex-L-ander** [BeyondTrust/pbis-open#71]
**Version**: 8.5.4.334
**OS/Distro**: RHEL 7.4
**Issue/Impact**: It can take multiple minutes after a reboot until a user can sign in again because of trust enumeration. Can this timeout of 30 seconds per trust be lowered?

**Output/Error**:
Oct 20 12:44:35 testserver lsass: [lsass] Ignoring failure enumerating trusts for forest forest.local. Error was NERR_DCNotFound (2453)
Oct 20 12:45:05 testserver lsass: [lsass] Ignoring failure enumerating trusts for forest forest2.local. Error was NERR_DCNotFound (2453)
Oct 20 12:45:35 testserver lsass: [lsass] Ignoring failure enumerating trusts for forest forest3.local. Error was NERR_DCNotFound (2453)
Oct 20 12:46:05 testserver lsass: [lsass] Ignoring failure enumerating trusts for forest forest4.local. Error was NERR_DCNotFound (2453)
Oct 20 12:46:20 testserver lsass: [lsass] Ignoring failure enumerating trusts for forest forest5.local. Error was NERR_DCNotFound (2453)
Oct 20 12:46:50 testserver lsass: [lsass] Ignoring failure enumerating trusts for forest domain.forest5.local. Error was NERR_DCNotFound (2453)
Oct 20 12:47:20 testserver lsass: [lsass] Ignoring failure enumerating trusts for forest domain.forest5.local. Error was NERR_DCNotFound (2453)

**Steps to Reproduce**:
1. Reboot

**Comment by rbest-bt** [comment]
Try upgrading to 8.5.5.372
fixed as part of issue #6
