### ISSUE TITLE
domainjoin-gui

### ISSUE THREAD

**Issue by sacarde** [BeyondTrust/pbis-open#73]
**Version**: 8.5.5.372
**OS/Distro**: Kubuntu desktop 16.04 64

where is domainjoin-gui ?

thank you

**Comment by rbest-bt** [comment]
seems that did not get built. We are looking into why this was and adding checks for it.

**Comment by rbest-bt** [comment]
We have identified the issue and will get it fixed for the next release. For now you can try out one of the new features in this release.
> 91702 - Domainjoin-cli prompts for missing parameters

Just issue 'domainjoin-cli join' and it will ask for everything you need.

**Comment by rbest-bt** [comment]
8.5.6 uploaded with it fixed

**Comment by BuckRogers25** [comment]
Still broken I'm afraid.  Tried on Ubuntu 17.10 & Debian stretch, same in both.  Checked another thread for dependencies, no dependencies missing, and nothing useful in syslog.

`root@svhal-observium1:/# domainjoin-gui -verbose
domainjoin-gui: command not found
root@svhal-observium1:/# apt search pbis
Sorting... Done
Full Text Search... Done
pbis-open/unknown,now 8.5.6.375 amd64 [installed,automatic]
  Authentication services for Active Directory domains

pbis-open-dev/unknown 8.5.6.375 amd64
  PowerBroker Identity Services Open SDK

pbis-open-gui/unknown,now 8.5.6.375 amd64 [installed]
  Desktop utility for joining Active Directory domains

pbis-open-legacy/unknown 8.5.6.375 amd64
  Provides symbolic links from the older command names and paths in Likewise Open to the new names and paths in PowerBroker Identity Services Open.

pbis-open-upgrade/unknown,now 8.5.6.375 amd64 [installed]
  Helper package for upgrading systems with versions preceding
`
Inititally installed from the .sh, then removed and installed from repo just in case, error and version info above.

Let us know if I can be of any help and what log info you might need.

**Comment by sacarde** [comment]
8.5.6 works for me in kubuntu-16.04

/opt/pbis/bin/<command> ...

**Comment by rbest-bt** [comment]
@BuckRogers25 try the full path
> /opt/pbis/bin/domainjoin-gui

**Comment by Adyel** [comment]
I installed pbis-open from the [PPA](https://repo.pbis.beyondtrust.com/apt.html). There is no domainjoin-gui. Is this issue fixed ? Only I am facing this issue ?

# pbis status
```
Compiled daemon version: 8.5.7.385
Packaged product version: 8.5.385.1
```

**Comment by rbest-bt** [comment]
From the repository you will need to install [pbis-open-gui](https://repo.pbis.beyondtrust.com/apt/pool/main/p/pbis-open-gui/).

We recommend using domainjoin-cli instead of domainjoin-gui as you will have less  issues with  libglade dependencies.

**Comment by MaDjiDoU0911** [comment]
Hello !
I installed pbis-open-8.7.1.494.linux.x86_64.deb.sh (latest version) on ubuntu 18.04 LTS and there is no domainjoin-gui. Is this problem solved?

**Comment by rbest-bt** [comment]
domainjoin-gui was [deprecated in 8.7.0.](https://github.com/BeyondTrust/pbis-open/releases/tag/8.7.0)

**Comment by MaDjiDoU0911** [comment]
OK then, you advise me which version of pbis ?!!

**Comment by rbest-bt** [comment]
8.6.0 was the last version. It's not needed as the domainjoin-cli provides all the options you will need.
