### ISSUE TITLE
NFS4 Centos7   Permission denied

### ISSUE THREAD

**Issue by jelayeb** [BeyondTrust/pbis-open#75]
**Version**: 8.5.4.334
**OS/Distro**: Centos 7.4

hi a problem here with Linux File server NFS, where users get always access denied when they are trying to access a share that they are member of the owner groups. 
home dir shares have no problem and other test share where the user is the owner of the share. 
i tried to create a local linux user and group and add them to the ACLs and mount the share localy on the server, this works fine which makes me think about pbis-open, 
the same setup works fine from Centos6 NFS Server nfs3, 
i tried to disable nfs 4 and use only 3 on centos7 but the same. 

clients are centos4, centos7.1, centos7.4 centos5.11 centos 6.8 all affected. 

Server Side
Centos 7.4 just updated from 7.1 to make sure it is not a missing update issue
/etc/exports
/export/data/IT                                  192.168.96.0/24(async,insecure,no_root_squash,no_all_squash)
/export/data/TEST                             192.168.96.0/24(async)
 
/etc/nfs.conf
[nfsd]
 vers3=y
 vers4=y
 vers4.0=y
 vers4.1=n
 vers4.2=n
 
/NIS auto.data
IT                                          -rw,sec=sys,no_root_squash,no_all_squash,intr,wsize=32768,rsize=32768   stp6100:/export/data/&
TEST                                    -intr,largefiles                stp6100:/export/data/&
 
 getent passwd mohaboud
mohaboud:PBIS:2129141939:2129134081:Aboud, Moh:/export/home/mohaboud:/bin/sh

[root@stp6100 ~]# /opt/pbis/bin/list-groups-for-user mohaboud |grep tp.resfs.linux.data.it
Group[48 of 235] name = tp.resfs.linux.data.it (gid = 2129154733)

[root@stp6100]#getfacl /export/data/IT
getfacl: Removing leading '/' from absolute path names
`# file: export/data/IT`
`# owner: root`
`# group: root`
`# flags: -s-`
user::rwx
group::rwx
group:ha.resfs.fileaccess:rwx
group:tp.resfs.linux.data.it:rwx
group:tp.resfs.linux.data.it_r:r-x
mask::rwx
other::---
default:user::rwx
default:group::rwx
default:group:ha.resfs.fileaccess:rwx
default:group:tp.resfs.linux.data.it:rwx
default:group:tp.resfs.linux.data.it_r:r-x
default:mask::rwx
default:other::---

[root@stp6100]# getfacl /export/data/TEST 
getfacl: Removing leading '/' from absolute path names
`# file: export/data/TEST`
`# owner: mohaboud`
`# group: root`
`# flags: -s-`
user::rwx
group::rwx
group:testuser:rwx
group:ha.resfs.fileaccess:rwx
group:tp.resfs.linux.data.it:rwx
group:tp.resfs.linux.data.it_r:r-x
mask::rwx
other::---
default:user::rwx
default:group::rwx
default:group:testuser:rwx
default:group:ha.resfs.fileaccess:rwx
default:group:tp.resfs.linux.data.it:rwx
default:group:tp.resfs.linux.data.it_r:r-x
default:mask::rwx
default:other::---

Client Test
Centos7.1
 getent passwd mohaboud
mohaboud:PBIS:2129141939:2129134081:Aboud, Moh:/export/home/mohaboud:/bin/sh

[root@stp5180 data]# su - mohaboud
Last login: Tue Oct 24 12:41:48 EET 2017 on pts/0
-bash-4.2$ pwd
/home/mohaboud
-bash-4.2$ mount |grep mohaboud
stp6100:/export/home/mohaboud on /home/mohaboud type nfs4 (rw,relatime,vers=4.0,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=192.168.96.42,local_lock=none,addr=192.168.96.7)
-bash-4.2$
-bash-4.2$ cd /data/TEST
-bash-4.2$ mount |grep TEST
stp6100:/export/data/TEST on /data/TEST type nfs4 (rw,relatime,vers=4.0,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=192.168.96.42,local_lock=none,addr=192.168.96.7)
 
-bash-4.2$ cd /data/IT
-bash: cd: /data/IT: Permission denied
-bash-4.2$ mount |grep IT
stp6100:/export/data/IT on /data/IT type nfs4 (rw,relatime,vers=4.0,rsize=32768,wsize=32768,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=192.168.96.42,local_lock=none,addr=192.168.96.7)
-bash-4.2$

**Comment by rbest-bt** [comment]
With pbis I would recommend mounting nfs shares with kerberos. You'll need 8.5.5 which has the new config option. Update your export file to use sec=krb5.

Before joining the domain on both the server and client configure your SPN to include the nfs service type
> /opt/pbis/bin/config ServicePrincipalName "host" "nfs"

Now you should be able to do a host to host connection with kerberos with the option sec=krb5. File systems permissions have worked for me with that setup.

**Comment by jelayeb** [comment]
thanks for your answer
unfortunatly this didnt work with me 
i added the spn on both server and client, then 
on server /etc/exports
/export/data/IT                                  *(rw,no_root_squash,sec=krb5)
auto_data for autofs 
IT                                      -fstype=nfs4,rw,no_root_squash,sec=krb5 stp6100:/export/data/&

on client
as root 
[root@stp5180 data]# cd IT
-bash: cd: IT: No such file or directory
as normal user
[root@stp5180 data]# su - jaelayeb.ra
Last login: Wed Oct 25 10:05:06 EET 2017 on pts/0
-bash-4.2$ cd /data/IT
-bash: cd: /data/IT: No such file or directory
-bash-4.2$

then i changed on the server the autofs config to remove the fstype=nfs4
IT                                      -rw,no_root_squash,sec=krb5 stp6100:/export/data/&

on client as root 
[root@stp5180 data]# cd IT
-bash: cd: IT: Permission denied
[root@stp5180 data]# 
as normal user 
[root@stp5180 data]# su - jaelayeb.ra
Last login: Wed Oct 25 10:11:43 EET 2017 on pts/0
-bash-4.2$ cd /data/IT
-bash: cd: /data/IT: Key has expired
-bash-4.2$ 

and i can see that IT is mounted as ver3,  here
stp6100:/export/data/IT on /data/IT type nfs (rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=krb5,mountaddr=192.168.96.7,mountvers=3,mountport=20048,mountproto=udp,local_lock=none,addr=192.168.96.7)

is it possible to share your exports and mounting options you used 

Thanks

**Comment by ferricoxide** [comment]
From your initial information:

~~~
[root@stp6100 ~]# /opt/pbis/bin/list-groups-for-user mohaboud |grep tp.resfs.linux.data.it
Group[48 of 235] name = tp.resfs.linux.data.it (gid = 2129154733)
~~~

You're likely to hit two issues here - one NFS and one AD:

- Depending on your domain controller, once a user exceeds about [120 group-associations](https://support.microsoft.com/en-us/help/327825/problems-with-kerberos-authentication-when-a-user-belongs-to-many-grou), the passing of group memberships can become unreliable.
- NFS has a historical limitation on the number of groups (16) a user can be in before _it_ becomes problematic. There are [workarounds](https://access.redhat.com/solutions/17372), but you can still suffer reliability issues.

Per the Red Hat article I linked to, some of the "too many groups for NFS" problem can be mitigated by switching to Kerberos. However, doing so likely pushes you into the linked-to Active Directory issue.

**Comment by jelayeb** [comment]
but this is a very old nfs problem and i never faced this problem since 2011. 
plus i have another nfs server with centos6 and pbis-open and works fine with even more than 
[538 of 538] groups.

**Comment by ferricoxide** [comment]
Dunno. First ran into _both_ issues early on in our integration of RHEL/CentOS 5 & 6 with our AD domains. As we've been undertaking RHEL/CentOS 7, we've mostly switched to native (sssd) where we bother with AD at all (most of our EL7 "hosts" are ephemeral and/or AD integration is done at the hosted-applications rather than OS level). Then again, the domain controllers used with those EL 5&6 systems had been running in 2003 compatibility mode long after our organization had abandoned 2003. More frequently, we ran into issues with AD groups than NFS group-association limits (NFS group-limits were more problematic for other platforms we were using PBIS with, particularly Solaris). So, may have been more a function of AD than the client-side authentication/NFS implementations.

**Comment by ferricoxide** [comment]
Also, with respect to the 16 group limit, the age of the comes from the age of the problem - which is due to NFS's default usage of `auth_sys` (see [RFCs for `auth_sys`](https://tools.ietf.org/html/rfc5531)) .

With the 2.6.21 or higher Linux kernel, you could add the `-g` option to your Linux-based NFS server (some implementations made this the default behavior) as a workaround. If you're unable to modify the NFS server's options, you could sometimes work around it by using something other than `auth_sys` to manage your permissions.

**Comment by jelayeb** [comment]
i'm able to authenticate users 
on Server 
[root@stp6100 domain]# /opt/pbis/bin/kinit jaelayeb.ra
Password for jaelayeb.ra@DOMAIN: 
[root@stp6100 domain]# 

on client centos4
[root@stp2040:~]# kinit jaelayeb.ra
Password for jaelayeb.ra@DOMAIN: 
[root@stp2040:~]# 

on client centos7
-bash-4.2$ /opt/pbis/bin/kinit jaelayeb.ra
Password for jaelayeb.ra@DOMAIN: 
-bash-4.2$

**Comment by jelayeb** [comment]
unfortunately i couldn't manage to make this work till now. 
if anyone have done an nfs server on centos7 and pbis-open worked, i would appreciate that he share with us his configurations from server and client side. 

Thanks

**Comment by jelayeb** [comment]
unfortunately i couldn't manage to make this work till now. 
if anyone have done an nfs server on centos7 and pbis-open worked, i would appreciate that he share with us his configurations from server and client side. 

Thanks

**Comment by jelayeb** [comment]
just wanted to share my experience on this ticket. 
those steps i used to make it work with me 
It is a mixed issue between nfs4 and Kerberos and Centos7
To make it work first we need to have an SPN configured for server and client with nfs then we enable krb5 on nfs exports and autofs. 

# Server Setup
1.	Update pbis-open to 8.5.6 
`yum update pbis-open pbis-open-upgrade`
2.	Leave the domain and delete the account 
`domainjoin-cli leave --deleteAccount jaelayeb.ra`
3.	Add NFS SPN to the machine. This step need to be done before we join the domain to make sure the right SPNs are added to the machine account and the keytab file. 
otherwise you will have to add them manually to the machine account attributes and to the keytab file. 
`/opt/pbis/bin/config ServicePrincipalName "host" "nfs" "cifs"`
4.	Join the domain
`domainjoin-cli join domain.local jaelayeb.ra`
Check keytab file content for SPNs, here some example entries 
```
 /opt/pbis/bin/ktutil
ktutil:  read_kt /etc/krb5.keytab
ktutil:  list
125    2          host/sha9060@DOMAIN.LOCAL
126   2 host/SHA9060.DOMAIN.LOCAL@DOMAIN.LOCAL
309    2          cifs/sha9060@DOMAIN.LOCAL
165    2 cifs/sha9060.DOMAIN.LOCAL@DOMAIN.LOCAL
172    2           nfs/sha9060@DOMAIN.LOCAL
198    2 nfs/sha9060.DOMAIN.LOCAL@DOMAIN.LOCAL
ktutil: quit
```

5.	Install NFS Server
`yum install nfs-utils nfs4-acl-tools`
6.	Start NFS Server
 `systemctl start nfs-server`
7.	Export Shares
```
 vim /etc/exports
/export/data/test                      *(rw,sec=sys:krb5:krb5i:krb5p,sync,nohide)
/export/data/department           *(rw,sec=sys:krb5:krb5i:krb5p,sync,nohide)
```
8.	Reexport filesystem
`exportfs -ra`

# Client Setup
**(Centos 6)**

1.	Update pbis-open to 8.5.6 
`yum update pbis-open pbis-open-upgrade`
2.	Leave the domain and delete the account 
`domainjoin-cli leave --deleteAccount jaelayeb.ra`
3.	Before Domain Join: 
`/opt/pbis/bin/config ServicePrincipalName "host" "cifs" "nfs"`
4.	Join the domain
`domainjoin-cli join domain.local jaelayeb.ra`

5.	Install nfs4 acl
`yum install nfs4-acl-tools`
6.	Enable NFS4
```
vim /etc/sysconfig/nfs
SECURE_NFS="yes"
```

7.	Services Restart
`service rpcidmapd restart`
8.	Configure Autofs
` vim /etc/auto.test`
`*   -fstype=nfs4,rw,sec=krb5,intr,hard,exec,insecure,no_subtree_check,wsize=4096,rsize=4096 sha9060.domain.local:/export/data/&`
       9. restart autofs
          ` service autofs restart`

now each user should have his krb5 ticket to be able to access the shares, so if you su ? to a user may not work if the user didn?t enter his password via kinit, 
loggedin user will have their own ticket automatically created. 

**Client Setup (Centos 7)**
1.	Update pbis-open to 8.5.6 
Yum update pbis-open pbis-open-upgrade
2.	Leave the domain and delete the account 
`domainjoin-cli leave ?deleteAccount jaelayeb.ra`
3.	Before Domain Join: 
`/opt/pbis/bin/config ServicePrincipalName "host" "cifs" "nfs"`
4.	Join the domain
 `domainjoin-cli join domain.local jaelayeb.ra`

5.	Install nfs4 acl
` yum install nfs4-acl-tools nfs-utils`
6.	Configure Autofs
`vim /etc/auto.test`
`*      -fstype=nfs4,rw,sec=krb5,intr,hard,exec,insecure,no_subtree_check,wsize=4096,rsize=4096	sha9060.domain.local:/export/data/&`

I will assume that Centos6 steps should work with Centos5 as well. 

> **Note:** always use FQDN with on autofs config or mount commands as this is related to Centos7 networking and nfs.

**Comment by rbest-bt** [comment]
Thanks for sharing this information. I need to add documentation to the integration guide for nfs. Would you mind if I just use this (with minor edits)?

**Comment by jelayeb** [comment]
feel free to use it.

**Comment by tux1337** [comment]
@jelayeb 
Do you know why it is necessary to set 
`/opt/pbis/bin/config ServicePrincipalName "host" "nfs"`
on the client side? 

I thought this is only necessary when the machine is an nfs server.

**Comment by jelayeb** [comment]
@tux1337 
as i remember it did work only that way, while i was testing different setups, i didt not investigate why, as it didnt harm  to reconfigure clients with printciple name nfs\HOSTNAME
after everything works fine, i stopped nfs4 and use it as nfs3 as we need to be able to switch from root to any other user without password. which doesnt work with nfs4 for security reasons.

**Comment by tux1337** [comment]
We found out, that this is not necessary. The "host" entry is sufficient. 
You can find the following information on the rpc.gssd man page which describes the behaviour: 

 rpc.gssd searches in the following order for a principal to use.  The first matching credential is used.  For the search, <hostname> and <REALM> are replaced with the local system's hostname and Kerberos realm.

          <HOSTNAME>$@<REALM>
          root/<hostname>@<REALM>
          nfs/<hostname>@<REALM>
          host/<hostname>@<REALM>
          root/<anyname>@<REALM>
          nfs/<anyname>@<REALM>
          host/<anyname>@<REALM>

       The <anyname> entries match on the service name and realm, but ignore the hostname.  These can be used if a principal matching the local host's name is not found.
