### ISSUE TITLE
cannot send different FQDN to AD

### ISSUE THREAD

**Issue by maxadamo** [BeyondTrust/pbis-open#76]
**Version**: ANY
**OS/Distro**: Linux / ANY
**Issue/Impact**:
Cannot use the Kerberos ticket if the server domain name is different from the Active Directory Domain. 
With SSSD (namely `sssd_ad`), through the tool `adcli`, it is possible to overwrite the FQDN using the option `--host-fqdn=<blahblah.domain.com>`, but with PBIS it seems to be impossible (or it's kept secret, as I found nothing in the documentation). 

 1. you register `server.domain.net` on the Active Directory domain `domain.com`
 2. PBIS, instead of sending to AD the proper FQDN, attempts to change the hostname on your server
 3. you roll back the hostname (because you don't want PBIS to change your hostname)
 2. you cannot login with your kerberos ticket. 
 3. you can login only using the password. 

**please note, that with SSSD_AD this procedure was made technically possible:** hence if they do it, I assume you could do it as well. 

**Output/Error**:
`Server not found in Kerberos database`

**Comment by rbest-bt** [comment]
Try leaving the hostname they way you want it and using the domainjoin option "--disable hostname"

> [root@cent7r ~]# /opt/pbis/bin/domainjoin-cli join --disable hostname bt3.com admin
Joining to AD Domain:   bt3.com
With Computer DNS Name: cent7r.bt1.com
admin@BT3.COM's password: 
SUCCESS
[root@cent7r ~]# /opt/pbis/bin/domainjoin-cli query
Name = cent7r
Domain = BT3.COM
Distinguished Name = CN=CENT7R,CN=Computers,DC=bt3,DC=com
[root@cent7r ~]# cat /etc/hosts
127.0.0.1 cent7r.bt1.com cent7r localhost localhost.localdomain localhost4 localhost4.localdomain4
::1 localhost localhost.localdomain localhost6 localhost6.localdomain6
[root@cent7r ~]# /opt/pbis/bin/klist -e -k /etc/krb5.keytab | head -n 4
Keytab name: WRFILE:/etc/krb5.keytab
KVNO Principal
3 CENT7R$@BT1.COM (aes256-cts-hmac-sha1-96) 
[root@cent7r ~]# ssh BT3\\admin@localhost
Password:
-sh-4.2$ /opt/pbis/bin/adtool -a lookup-object --dn CN=CENT7R,CN=Computers,DC=bt3,DC=com --attr servicePrincipalName
HOST/cent7r
HOST/cent7r.bt1.com

**Comment by maxadamo** [comment]
OMG! I've spent a year to try to guess a solution. 
Perhaps you should create a more comprehensive online help. There is not man page, and if I run `domainjoin-cli --help` I see nothing relevant.... or perhaps I should have read your pdf. 
**Anyway:** THANKS-THANKS-THANKS !!

**Comment by rbest-bt** [comment]
It is listed under "join options" but I do agree that it does not have any information as to what it does or what are the modules. I'm going to log a task to look at expanding the help/usage options.
