### ISSUE TITLE
samba integration issue

### ISSUE THREAD

**Issue by jelayeb** [BeyondTrust/pbis-open#77]
**Version**: pbis-open-8.5.5-372.x86_64
**OS/Distro**: Centos7.4 Minimal
**Issue/Impact**:
*Note: replace content with your own*
When reporting an issue it's important that we have as much detail as you can provide. The following is a list of commands to check.
 1. systemctl status lwsmd.service
 2. /opt/pbis/bin/lwsm list
 3. /opt/pbis/domainjoin-cli query
 4. pbis status
 5. /opt/pbis/bin/enum-users
 6. attach logs
  - /opt/pbis/bin/lwsm set-log-target -p lsass -  file /tmp/lsass.log
  - /opt/pbis/bin/lwsm set-log-level -p lsass - debug
  - attach log

**Output/Error**:
the problem is when running samba share, it always asks for username and password, 
i run the debug log for lsass and i could see that it can not find the user. but the user is there on the domain, and can access the system locally and via ssh
pbis finds user with no problem and list all his groups. 
i did a new installation from scratch for testing, and have the same versions. 
when i install the samba integration tools with debug i see this 
[root@sha9060 ~]# /opt/pbis/bin/samba-interop-install --install --loglevel debug
[CheckSambaVersion() /builder/src-git/Platform/src/linux/samba-interop/tools/samba-interop-install.c:500] Found smbd version 4.6.2
[InstallWbclient() /builder/src-git/Platform/src/linux/samba-interop/tools/samba-interop-install.c:628] Linked /usr/lib64/libwbclient.so.0 to /opt/pbis/lib64/libwbclient.so.0
[RegTransactGetValueW() /builder/src-git/Platform/src/linux/lwreg/client/clientipc.c:809] Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
[LwNtRegGetValueA() /builder/src-git/Platform/src/linux/lwreg/client/regntclient.c:793] Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
[TdbRead() /builder/src-git/Platform/src/linux/samba-interop/pstore-plugin/samba-pstore-plugin.c:137] Error code 2
[SetPassword() /builder/src-git/Platform/src/linux/samba-interop/pstore-plugin/samba-pstore-plugin.c:459] Wrote machine password for domain DOMAIN in secrets.tdb
Install successful

it looks like it can not find the machine itself on the domain.

**Comment by jelayeb** [comment]
ntlm works fine as if i try to access the share with IP it works, but not with the machine name

**Comment by RBoulton-BT** [comment]
Have you tried with 8.5.6? There was a fix for Samba integration in that release.

**Comment by jelayeb** [comment]
i just did now after your mentioned it, and it WORKS thanks 
but the problem i was trying many different version of pbis since 3 days and all of them the same. 
but i have other servers which are running fine with 8.5.4 

anyway thanks for the update

**Comment by jelayeb** [comment]
it looks like the 8.5.6 has another issue as now pbis can not find the groups that belong to my user therefore samba will not allow me to access any share that doesnt belong to me, even if i'm member of the group
[root@stp6100 data]# /opt/pbis/bin/list-groups-for-user jaelayeb
Failed to find groups for user 'jaelayeb'.  Error code 40044 (LW_ERROR_NO_SUCH_DOMAIN).
Unknown Active Directory domain

i tried to rejoin the domain but that didnt help

**Comment by jelayeb** [comment]
log sample 
20171102101629:DEBUG:lsass:AD_OnlineQueryMemberOfForSid():lsass/server/auth-providers/ad-open-provider/online.c:4140: Error code: 40044 (symbol: LW_ERROR_NO_SUCH_DOMAIN)
20171102101629:ERROR:lsass:AD_OnlineQueryMemberOfForSid():lsass/server/auth-providers/ad-open-provider/online.c:4234: Failed to find memberships for user 'JAELAYEB' (error = 40044)
20171102101629:DEBUG:lsass:AD_OnlineQueryMemberOf():lsass/server/auth-providers/ad-open-provider/online.c:4333: Error code: 40044 (symbol: LW_ERROR_NO_SUCH_DOMAIN)
20171102101629:DEBUG:lsass:LsaSrvMakeMemberOfFirstPass():lsass/server/api/api2.c:304: Error code: 40044 (symbol: LW_ERROR_NO_SUCH_DOMAIN)
20171102101629:DEBUG:lsass:LsaSrvQueryMemberOfMerged():lsass/server/api/api2.c:1232: Error code: 40044 (symbol: LW_ERROR_NO_SUCH_DOMAIN)
20171102101629:DEBUG:lsass:LsaSrvQueryMemberOf():lsass/server/api/api2.c:1424: Error code: 40044 (symbol: LW_ERROR_NO_SUCH_DOMAIN)
20171102101629:VERBOSE:lsass-ipc:lwmsg_peer_task_handle_assoc_error():lwmsg/src/peer-task.c:625: (session:15558a2a4c8aada1-35cf1b17e0036f38) Dropping: LWMSG_STATUS_PEER_CLOSE

**Comment by jelayeb** [comment]
sorry after testing i found that samba is working fine, but pbis-open still can not display groups belong to user 
[root@stp6100 data]# /opt/pbis/bin/find-user-by-name jaelayeb
User info (Level-0):
====================
Name:              jaelayeb
SID:               S-1-5-21-3765672669-3466858823-547988055-8547
Uid:               2129142115
Gid:               2129134081
Gecos:             Elayeb, Jasem
Shell:             /bin/bash
Home dir:          /export/home/jaelayeb
Logon restriction: NO
[root@stp6100 data]# /opt/pbis/bin/list-groups-for-user jaelayeb
Failed to find groups for user 'jaelayeb'.  Error code 40044 (LW_ERROR_NO_SUCH_DOMAIN).
Unknown Active Directory domain
[root@stp6100 data]# 
[root@stp6100 data]# /opt/pbis/bin/find-group-by-id 2129134081
Group info (Level 0):
====================
Name: domain_users
Gid:  2129134081
SID:  S-1-5-21-3765672669-3466858823-547988055-513
[root@stp6100 data]#

**Comment by RBoulton-BT** [comment]
Were there any errors in the log above the sample you pasted earlier?

**Comment by jelayeb** [comment]
i just stopped lwsmd service and removed the log file and start again 
cleared ad-cahc --delete-all 
and try to list groups of my user 

20171103113126:DEBUG:lsass:NtlmServerAcquireCredentialsHandle():lsass/server/ntlm/acquirecreds.c:103: Error code: 40506 (symbol: LW_ERROR_NO_CRED)
20171103113126:DEBUG:lsass:NtlmTransactAcquireCredentialsHandle():lsass/client/ntlm/clientipc.c:299: Error code: 40506 (symbol: LW_ERROR_NO_CRED)
20171103113126:DEBUG:lsass:NtlmClientAcquireCredentialsHandle():lsass/client/ntlm/acquirecreds.c:76: Error code: 40506 (symbol: LW_ERROR_NO_CRED)
20171103113126:DEBUG:lsass:NtlmServerAcquireCredentialsHandle():lsass/server/ntlm/acquirecreds.c:103: Error code: 40506 (symbol: LW_ERROR_NO_CRED)
20171103113126:DEBUG:lsass:NtlmTransactAcquireCredentialsHandle():lsass/client/ntlm/clientipc.c:299: Error code: 40506 (symbol: LW_ERROR_NO_CRED)
20171103113126:DEBUG:lsass:NtlmClientAcquireCredentialsHandle():lsass/client/ntlm/acquirecreds.c:76: Error code: 40506 (symbol: LW_ERROR_NO_CRED)
20171103113126:DEBUG:lsass:ntlm_gss_init_sec_context():lsass/interop/gssntlm/gssntlm.c:891: Error code: 40506 (symbol: LW_ERROR_NO_CRED)
20171103113126:INFO:lsass:AD_OnlineInitializeOperatingMode():lsass/server/auth-providers/ad-open-provider/online.c:307: Disabling cell support due to cell-support configuration setting
20171103113126:DEBUG:lwreg:RegTransactOpenKeyExW():lwreg/client/clientipc.c:438: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
20171103113126:DEBUG:lwreg:LwNtRegOpenKeyExA():lwreg/client/regntclient.c:933: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
20171103113126:DEBUG:lwreg:RegShellUtilDeleteValue():lwreg/shellutil/rsutils.c:1287: Error: 40700
20171103113129:VERBOSE:lsass:LsaUmpThreadRoutine():lsass/server/auth-providers/ad-open-provider/lsaum_p.c:572: Started user manager thread
20171103113129:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:480: Switched gss krb5 credentials path from <null> to FILE:/var/lib/pbis/krb5cc_lsass.DOMAINNAME.COM
20171103113129:INFO:lsass:ADSyncMachinePasswordThreadRoutine():lsass/server/auth-providers/ad-open-provider/machinepwd.c:263: Machine Password Sync Thread starting
20171103113129:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:480: Switched gss krb5 credentials path from <null> to FILE:/var/lib/pbis/krb5cc_lsass.DOMAINNAME.COM
20171103113129:VERBOSE:lsass:ADRefreshMachineTGT():lsass/server/auth-providers/ad-open-provider/machinepwd.c:556: Refreshing machine TGT
20171103113129:VERBOSE:lsass:ADSyncMachinePasswordThreadRoutine():lsass/server/auth-providers/ad-open-provider/machinepwd.c:385: Machine TGT was refreshed successfully for CORP.DEA-GROUP.COM
20171103113134:VERBOSE:lsass:LsaSrvIpcCheckPermissions():lsass/server/api/ipc_state.c:79: Permission granted for (uid = 0, gid = 0, pid = 6037) to open LsaIpcServer
20171103113134:VERBOSE:lsass-ipc:lwmsg_peer_log_accept():lwmsg/src/peer-log.c:230: (session:fe4bbded702751a7-1ff2ce7a6a1765de) Accepted <local euid:0 egid:0 pid:6037>
20171103113134:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:480: Switched gss krb5 credentials path from <null> to FILE:/var/lib/pbis/krb5cc_lsass.CORP.DEA-GROUP.COM
20171103113135:INFO:lsass:MemCacheBackupRoutine():lsass/server/auth-providers/ad-open-provider/memcache.c:286: Delayed backup scheduled
20171103113135:VERBOSE:lsass-ipc:lwmsg_peer_task_handle_assoc_error():lwmsg/src/peer-task.c:625: (session:fe4bbded702751a7-1ff2ce7a6a1765de) Dropping: LWMSG_STATUS_PEER_CLOSE
20171103113138:VERBOSE:lsass:LsaSrvIpcCheckPermissions():lsass/server/api/ipc_state.c:79: Permission granted for (uid = 0, gid = 0, pid = 6039) to open LsaIpcServer
20171103113138:VERBOSE:lsass-ipc:lwmsg_peer_log_accept():lwmsg/src/peer-log.c:230: (session:70ed3b9869f5ea05-bf7c5f6b42b267a5) Accepted <local euid:0 egid:0 pid:6039>
20171103113138:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:480: Switched gss krb5 credentials path from <null> to FILE:/var/lib/pbis/krb5cc_lsass.DOMAINNAME.COM
20171103113138:DEBUG:lsass:MemCacheFindUserByName():lsass/server/auth-providers/ad-open-provider/memcache.c:996: Error code: 40017 (symbol: LW_ERROR_NOT_HANDLED)
20171103113138:DEBUG:lsass:MemCacheFindUserByName():lsass/server/auth-providers/ad-open-provider/memcache.c:996: Error code: 40017 (symbol: LW_ERROR_NOT_HANDLED)
20171103113138:DEBUG:lsass:ADCacheFindUserByName():lsass/server/auth-providers/ad-open-provider/adcache.c:124: Error code: 40017 (symbol: LW_ERROR_NOT_HANDLED)
20171103113138:DEBUG:lsass:LsaAdBatchResolvePseudoObjectsUnprovMode():lsass/server/auth-providers/ad-open-provider/batch.c:2278: Error code: 40081 (symbol: LW_ERROR_NOT_SUPPORTED)
20171103113138:DEBUG:lsass:LsaAdBatchResolvePseudoObjects():lsass/server/auth-providers/ad-open-provider/batch.c:2460: Error code: 40081 (symbol: LW_ERROR_NOT_SUPPORTED)
20171103113138:DEBUG:lsass:LsaAdBatchFindObjectsPseudoBeforeReal():lsass/server/auth-providers/ad-open-provider/batch.c:1309: Error code: 40081 (symbol: LW_ERROR_NOT_SUPPORTED)
20171103113138:DEBUG:lsass:LsaAdBatchFindObjectsInternal():lsass/server/auth-providers/ad-open-provider/batch.c:1539: Error code: 40081 (symbol: LW_ERROR_NOT_SUPPORTED)
20171103113138:DEBUG:lsass:LsaAdBatchFindObjects():lsass/server/auth-providers/ad-open-provider/batch.c:1646: Error code: 40081 (symbol: LW_ERROR_NOT_SUPPORTED)
20171103113138:DEBUG:lsass:LsaAdBatchFindSingleObject():lsass/server/auth-providers/ad-open-provider/batch.c:1377: Error code: 40081 (symbol: LW_ERROR_NOT_SUPPORTED)
20171103113138:DEBUG:lsass:AD_FindObjectByNameTypeNoCache():lsass/server/auth-providers/ad-open-provider/online.c:2826: Error code: 40081 (symbol: LW_ERROR_NOT_SUPPORTED)
20171103113138:DEBUG:lsass:LsaSrvFindProviderByName():lsass/server/api/state.c:128: Error code: 40040 (symbol: LW_ERROR_INVALID_AUTH_PROVIDER)
20171103113138:DEBUG:lsass:LsaSrvProviderServicesDomain():lsass/server/api/provider.c:151: Error code: 40040 (symbol: LW_ERROR_INVALID_AUTH_PROVIDER)
20171103113138:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:480: Switched gss krb5 credentials path from <null> to FILE:/var/lib/pbis/krb5cc_lsass.CORP.DEA-GROUP.COM
20171103113138:VERBOSE:lsass:AD_OnlineQueryMemberOfForSid():lsass/server/auth-providers/ad-open-provider/online.c:4095: Cache entry for user's group membership for sid S-1-5-21-3765672669-3466858823-547988055-8547 is incomplete
20171103113138:DEBUG:lsass:LsaDmpMustFindDomain():lsass/server/auth-providers/ad-open-provider/lsadm.c:1437: Do not know about domain 'adroot.net'
20171103113138:DEBUG:lsass:LsaDmpLdapOpen():lsass/server/auth-providers/ad-open-provider/lsadm.c:3288: Error code: 40044 (symbol: LW_ERROR_NO_SUCH_DOMAIN)
20171103113138:DEBUG:lsass:ADLdap_GetObjectGroupMembership():lsass/server/auth-providers/ad-open-provider/adldap.c:1336: Error code: 40044 (symbol: LW_ERROR_NO_SUCH_DOMAIN)
20171103113138:ERROR:lsass:ADLdap_GetObjectGroupMembership():lsass/server/auth-providers/ad-open-provider/adldap.c:1483: Failed to group memberships of SID=S-1-5-21-3765672669-3466858823-547988055-8547. [error code:40044]
20171103113138:DEBUG:lsass:AD_OnlineQueryMemberOfForSid():lsass/server/auth-providers/ad-open-provider/online.c:4140: Error code: 40044 (symbol: LW_ERROR_NO_SUCH_DOMAIN)
20171103113138:ERROR:lsass:AD_OnlineQueryMemberOfForSid():lsass/server/auth-providers/ad-open-provider/online.c:4234: Failed to find memberships for user 'DOMAIN\JAELAYEB' (error = 40044)
20171103113138:DEBUG:lsass:AD_OnlineQueryMemberOf():lsass/server/auth-providers/ad-open-provider/online.c:4333: Error code: 40044 (symbol: LW_ERROR_NO_SUCH_DOMAIN)
20171103113138:DEBUG:lsass:LsaSrvMakeMemberOfFirstPass():lsass/server/api/api2.c:304: Error code: 40044 (symbol: LW_ERROR_NO_SUCH_DOMAIN)
20171103113138:DEBUG:lsass:LsaSrvQueryMemberOfMerged():lsass/server/api/api2.c:1232: Error code: 40044 (symbol: LW_ERROR_NO_SUCH_DOMAIN)
20171103113138:DEBUG:lsass:LsaSrvQueryMemberOf():lsass/server/api/api2.c:1424: Error code: 40044 (symbol: LW_ERROR_NO_SUCH_DOMAIN)
20171103113138:VERBOSE:lsass-ipc:lwmsg_peer_task_handle_assoc_error():lwmsg/src/peer-task.c:625: (session:70ed3b9869f5ea05-bf7c5f6b42b267a5) Dropping: LWMSG_STATUS_PEER_CLOSE

**Comment by jelayeb** [comment]
and the command return 
[root@stp6100 ~]# /opt/pbis/bin/ad-cache --delete-all
The cache has been emptied successfully.
[root@stp6100 ~]# /opt/pbis/bin/list-groups-for-user jaelayeb
Failed to find groups for user 'jaelayeb'.  Error code 40044 (LW_ERROR_NO_SUCH_DOMAIN).
Unknown Active Directory domain
[root@stp6100 ~]# less /tmp/lsass.log

**Comment by RBoulton-BT** [comment]
The log looks inconsistent with domain names, did you edit this to obscure your internal names or is that what was actually logged? If you want to avoid posting your network information on GitHub please feel free to send us information using the openproject@beyondtrust.com email address.

**Comment by RBoulton-BT** [comment]
I'm guessing the line that says "Do not know about domain" is the domain it's complaining about.

**Comment by jelayeb** [comment]
i replace only my domainname with DOMAINNAME and DOMAIN 
i just sent the logs via email

**Comment by RBoulton-BT** [comment]
Could you also send the following via email:

/opt/pbis/config –dump
/opt/pbis/bin/get-status
/opt/pbis/bin/find-user-by-name –level 2 jaelayeb

**Comment by jelayeb** [comment]
i used your hint about ignor domains. 
i removed all ignore domains and i could list groups of my user 
i tried to add only one domain that it is not trusted by our domain to the ignore list and i got the same issue. 
it looks like if pbis-open couldnt look into all domains then it will break the procedure

**Comment by RBoulton-BT** [comment]
That does sound odd, I haven't come across issues like this before so I'll ask my colleagues. In the original list of excluded trusts, the forrest root domain seems to be included, I wonder if this may be causing the issue.

One thing to be aware of is that changes to the DomainManagerExcludeTrustsList does require a restart os lsass (/opt/pbis/bin/lwsm restart lsass) for it to pick up the changes.

**Comment by jelayeb** [comment]
yes i noticed that and i restart the service each time i make changes. 
i tried to add only one domain which i'm quite sure that i'm not member of any group on that domain, and is not even trusted by our domain, 
but it breaks

**Comment by RBoulton-BT** [comment]
We have a lot of customers using the excluded trusts options without group issues so there must be something subtle going on here. I'll try and experiment with the option a little more if I get the chance.

**Comment by jelayeb** [comment]
as for my case where samba integration was not working, it is solved by the new update, and i can leave without the domain exclusion for now, as i used it only as a test.

**Comment by jelayeb** [comment]
as for my case where samba integration was not working, it is solved by the new update, and i can leave without the domain exclusion for now, as i used it only as a test.

**Comment by rbest-bt** [comment]
I'm going to close this issue as fixed. For clarity could you log your other issue in a new ticket?
