### ISSUE TITLE
Doesn't fall over to other DCs

### ISSUE THREAD

**Issue by antjpcdrogas** [BeyondTrust/pbis-open#78]
**Version**: 8.5.1-206
**OS/Distro**: Red Hat 7.2
**Issue/Impact**: Doesn't fall over to other DCs
*Note: replace content with your own*
When a DC becomes offline pbis  doesn't use the others it keeps using the first one it registered to.

**Comment by rbest-bt** [comment]
Can you try again with 8.5.6?
Are the other DCs on the same site?
What are the Errors your seeing?

**Comment by antjpcdrogas** [comment]
Hi,

You can close this issue.
We have support and are talking with the support regarding this issue.

Thanks
