### ISSUE TITLE
login with key

### ISSUE THREAD

**Issue by mmiat** [BeyondTrust/pbis-open#80]
**Version**: 8.5.4.334
**OS/Distro**: Ubuntu desktop 16.04 - no desktop

is it possible to save my key in AD and use sshd to use it instead of /root/.ssh/authorized_keys ?

**Comment by rbest-bt** [comment]
In Open there is not. In Enterprise we have a Group Policy Object that allows you to push down any file you like via a computer policy or user policy(user limited to files in their home dir).

You could try k5login with open:
http://web.mit.edu/kerberos/krb5-1.13/doc/user/user_config/k5login.html
