### ISSUE TITLE
the problem with same uid about two users

### ISSUE THREAD

**Issue by HyukDrive** [BeyondTrust/pbis-open#81]
i am testing ad join to active directory with PBISO.
I am using PBISO 8.0.1.2029  ver and Ubuntu 16.04 ver.

when  i checked some users informaion, i recognized these users have same uid.

could you let me know why this issue happened?

thank you.

**Comment by rbest-bt** [comment]
About how many users/group/computers are in your domain? More then 524,288? It could be an issue with exhausting your rid pool.

Look up Rid Pool Error in the [troubleshooting guide](https://github.com/BeyondTrust/pbis-open/wiki/docs/Troubleshooting_Guide.pdf)

**Comment by HyukDrive** [comment]
@rbest-bt 
Hello, Our Linux systems are being operated by multiple Windows Domains.
which domain's amount of user/group/computer do you wanna know?
just one domain(linux system be joined), or all domain?

**Comment by rbest-bt** [comment]
The domain your joined too. If your running into duplicates then you'll need to upgrade to Enterprise. Enterprise allows you to manage the users and groups that are available to the linux system. It will also allow you to set the users/groups IDs indiviually or use the same ones generated from pbis-open.

**Comment by HyukDrive** [comment]
@rbest-bt  dear rbest-bt

thank you for your reply.
so.. could i get some information about enterprise version?
i neet to know price, pakage version, admin guide, etc....

thank you.

**Comment by rbest-bt** [comment]
Duplicates can occur when you start to reach the rip pool limit.

Everything you need should be available on the wiki:
- [Enterprise Documentation](https://github.com/BeyondTrust/pbis-open/wiki/Documentation)
- [Enterprise link](https://www.beyondtrust.com/products/powerbroker-identity-services-ad-bridge/) 

[Quotes](https://www.beyondtrust.com/quote-request/#Active-Directory-(AD)-Bridging), [trial](https://www.beyondtrust.com/free-trial-request/#Active-Directory-(AD)-Bridging) and [Demo ](https://www.beyondtrust.com/demo-request/#Active-Directory-(AD)-Bridging) are all available on the main [Beyond Trust website](https://www.beyondtrust.com/)
