### ISSUE TITLE
domainjoin-gui issue cannot open display

### ISSUE THREAD

**Issue by gnshkl1** [BeyondTrust/pbis-open#82]
**Version**: 8.5.6.375
**OS/Distro**: Xubuntu desktop 16.04 - xfce desktop

 1. systemctl status lwsmd.service

 lwsmd.service - BeyondTrust PBIS Service Manager
   Loaded: loaded (/lib/systemd/system/lwsmd.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2017-11-24 14:48:23 IST; 12min ago
  Process: 3717 ExecStart=/opt/pbis/sbin/lwsmd --start-as-daemon (code=exited, status=0/SUCCESS)
 Main PID: 3721 (lwsmd)
   CGroup: /system.slice/lwsmd.service
           ├─3721 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─3745 lw-container lwreg
           ├─3782 lw-container eventlog
           ├─3808 lw-container netlogon
           ├─3833 lw-container lwio
           ├─3860 lw-container lsass
           └─3892 lw-container reapsysl

Nov 24 14:48:23 gkltsp lsass[3860]: [lsass] Failed to run provider specific request (request code = 12, provider = 'lsa-activedirectory-provider') -> error = 2692, symbol = NERR_SetupNotJoined, client pid = 3986
Nov 24 14:48:54 gkltsp lsass[3860]: [lsass] Failed to run provider specific request (request code = 12, provider = 'lsa-activedirectory-provider') -> error = 2692, symbol = NERR_SetupNotJoined, client pid = 4021
Nov 24 14:51:39 gkltsp lsass[3860]: [lsass] Failed to run provider specific request (request code = 12, provider = 'lsa-activedirectory-provider') -> error = 2692, symbol = NERR_SetupNotJoined, client pid = 4281
Nov 24 14:51:39 gkltsp lsass[3860]: [lsass] Failed to run provider specific request (request code = 12, provider = 'lsa-activedirectory-provider') -> error = 2692, symbol = NERR_SetupNotJoined, client pid = 4369
Nov 24 14:51:39 gkltsp lsass[3860]: [lsass] Failed to run provider specific request (request code = 12, provider = 'lsa-activedirectory-provider') -> error = 2692, symbol = NERR_SetupNotJoined, client pid = 4457
Nov 24 14:52:03 gkltsp lsass[3860]: [lsass] Failed to run provider specific request (request code = 12, provider = 'lsa-activedirectory-provider') -> error = 2692, symbol = NERR_SetupNotJoined, client pid = 4464
Nov 24 14:53:57 gkltsp lsass[3860]: [lsass] Failed to run provider specific request (request code = 12, provider = 'lsa-activedirectory-provider') -> error = 2692, symbol = NERR_SetupNotJoined, client pid = 4582
Nov 24 14:54:55 gkltsp lsass[3860]: [lsass] Failed to run provider specific request (request code = 12, provider = 'lsa-activedirectory-provider') -> error = 2692, symbol = NERR_SetupNotJoined, client pid = 4582
Nov 24 14:55:03 testxrdp lsass[3860]: [lsass] Failed to run provider specific request (request code = 8, provider = 'lsa-activedirectory-provider') -> error = 9502, symbol = DNS_ERROR_BAD_PACKET, client pid = 45
Nov 24 14:55:13 testxrdp lsass[3860]: [lsass] Failed to run provider specific request (request code = 12, provider = 'lsa-activedirectory-provider') -> error = 2692, symbol = NERR_SetupNotJoined, client pid = 45

 2. /opt/pbis/bin/lwsm list
root@testxrdp:/home/accops#  /opt/pbis/bin/lwsm list
lwreg          running (container: 3745)
dcerpc         stopped
eventlog       running (container: 3782)
lsass          running (container: 3860)
lwio           running (container: 3833)
netlogon       running (container: 3808)
rdr            running (io: 3833)
reapsysl       running (container: 3892)
usermonitor    stopped

 3. /opt/pbis/domainjoin-cli query
root@testxrdp:/home/accops# /opt/pbis/bin/domainjoin-cli query
Name = testxrdp
Domain =

 4. pbis status

root@testxrdp:/home/accops# pbis status
LSA Server Status:

Compiled daemon version: 8.5.6.375
Packaged product version: 8.5.375.37
Uptime:        0 days 0 hours 15 minutes 13 seconds

[Authentication provider: lsa-activedirectory-provider]

	Status:        Unknown
	Mode:          Unknown

**Output/Error**:
root@testxrdp:/opt/pbis/bin# ./domainjoin-gui 
./domainjoin-gui: /opt/pbis/lib/libxml2.so.2: no version information available (required by /usr/lib/x86_64-linux-gnu/libglade-2.0.so.0)
No protocol specified

(domainjoin-gui:4682): Gtk-WARNING **: cannot open display: :0.0

**Comment by rbest-bt** [comment]
Are you accessing the machine remotely(ssh)? This usually is an issue with GTK not knowing where to send the display.

Simplest solution is to use the domainjoin-cli. In 8.5.5 we added a prompting feature that makes it easier the the gui:
>/opt/pbis/bin/domainjoin-cli join

**Comment by gnshkl1** [comment]
@rbest-bt No  iam not accessing machine through ssh

**Comment by rbest-bt** [comment]
Have you logged into the machine as a non-root user then su'd to root?

Have you tried domainjoin-cli?

**Comment by rbest-bt** [comment]
I got a copy of xubuntu 16.04 x86_64 up and reproduced a similar error:
> (domainjoin-gui:7746): Gtk-WARNING **: cannot open display:

The steps to reproduce this were:
1. login to local desktop with a non-root user
2. open terminal > ssh root@localhost
3.  /opt/pbis/bin/domainjoin-gui

The fix is to use the -X option with ssh (Needs X11Forwarding enabled in the sshd_confg)
> ssh -X root@localhost

I've also tried from the desktop as a local user:
- sudo localuser
- 'su -'  into root
- From desktop as root

These other scenarios do not have an issue.

**Comment by gnshkl1** [comment]
I am not using SSH. Using Xterm from local user but issue arises sometimes
when domainjoin-gui failed and we again try to launch domainjoin-gui again.

**Comment by rbest-bt** [comment]
Have you tried domainjoin-cli?

**Comment by gnshkl1** [comment]
No. After reboot issue not occurred. But issue is reproducible when
domainjoin-gui failed. Also after domain joined successfully and machine
rebooted and check domainjoin-cli query shows click skew. Sometimes time
sync with AD SERVER mismatched with 5min. difference

On 24-Nov-2017 10:35 PM, "rbest-bt" <notifications@github.com> wrote:

Have you tried domainjoin-cli?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BeyondTrust/pbis-open/issues/82#issuecomment-346870221>,
or mute the thread

**Comment by rbest-bt** [comment]
Great to hear you got it joined. If your in xterm I would recommend domainjoin-cli as it would not give you any issues.

As for your time skew issue, we recommend using a NTP server to keep the systems in sync. Have a look at the troubleshooting guide, section: Verify that the Client Can Connect to the Domain on Port 123

If you have further issue with the time skew please open a new issue.
