### ISSUE TITLE
LW_ERROR_LDAP_LOCAL_ERROR instead of clock skew with AD server

### ISSUE THREAD

**Issue by gnshkl1** [BeyondTrust/pbis-open#83]
**Version**pbis-open-8.5.6.375
**OS/Distro**: Xubuntu desktop 16.04 - xfce desktop
Wrong error shown LW_ERROR_LDAP_LOCAL_ERROR instead of clock skew with AD server.

steps:-
1:-sudo ./domainjoin-gui
2:-enter details of AD server
3:-Get error LW_ERROR_LDAP_LOCAL_ERROR
4:-check AD server clock was not sync with Linux VM
5:-Correct clock on Linux VM and try step  1 and machine will successfully joined domain.
6:-Reboot Linux VM
7:-sudo domainjoin-cli query (shows sometimes error "clock skew"). while we have set default pbis config setting to sync time with AD server)
8:-Reboot Linux VM and repeat step 7 now clock is sync with AD server.

Note:-
1:-Issue was comming with earlier releases of Pbis also still not resolved.
2:-Difference of clock sync is about 6minutes .

**Comment by rbest-bt** [comment]
Thanks for identifying this issue. 

Seems to only be an issue when running the domainjoin-gui with sudo. Root or domainjoin-cli with --notimesync show LW_ERROR_CLOCK_SKEW.

We have plans on removing domainjoin-gui until we have time to bring it up to date.

**Comment by rbest-bt** [comment]
8.7.0 dropped support for the domainjoin-gui
