### ISSUE TITLE
lwsmd/lwio Service Crashes in Cross-domain Trust scenario

### ISSUE THREAD

**Issue by gobenaus** [BeyondTrust/pbis-open#87]
**Version**: pbis-open-8.5.4-334.x86_64
**OS/Distro**: RHEL 6.9
**Issue/Impact**:
**We have a setup that involves two AD domains: a user domain, U, and a resource domain R. There is a one-way trust between the U domain and the R domain, with the R domain being the trusting domain. Our Linux machines are added to the R domain. We create resource groups in the R domain which contain users from the U domain. The resource groups are added to the RequireMembershipOf attribute. We do have a few user accounts in the 'R' domain as a backdoor in case the trust relationship to 'U' is broken. The 'U' domain is hosted in a co-lo data center. The 'R' domain is hosted in an AWS environment and the two communicate via a VPN connection. The domain logins are only used for administrative tasks on the server. They are not used by the applications running on them.

We wanted to eliminate the need for administrators from the U domain to log in using the domainName\Username format and just use user name. Thus, we set the 'UserdomainPrefix' setting to 'U' in PBIS.

We noticed that after a few days, we ended up being unable to log into our boxes, regardless of whether we were using a domain or local account. We had to reboot them. When we checked the messages log, we found the following. 

Once we undid the change and switched the Userdomainprefix back from 'R' from 'U', the errors went away and things started behaving normally.

So our hunch is that setting the UserdomainPrefix to 'U' may have resulted the guest trying to resolve all logon attempts against domain first. We thought that PBIS is only involved when a user logs into the system. But it seemed to be doing something once that value changed that ended up crashing the service, even if users weren't trying to log in. All we had to do is let a server sit there for a while and after a few days, we would be unable to log in. SSH never even got to the password prompt.

Unfortunately, abrt wasn't configured to actually do a core dump for libraries that aren't managed by Redhat. PBIS being a third party, it refused to do the dump. So we'd have to reconfigure abrt to perform core dump even if a libary doesn't have Redhat signature.

Any idea why a userdomainprefix change could result in service crashes?

**Output/Error**:

*Dec  4 13:14:15 vertica3 /opt/pbis/sbin/lwsmd: Restarting dead service: lwio (attempt 2/2)
Dec  4 13:14:15 vertica3 abrtd: Package 'pbis-open' isn't signed with proper key
Dec  4 14:36:59 vertica3 abrt[9025]: Saved core dump of pid 109062 (/opt/pbis/sbin/lwsmd) to /var/spool/abrt/ccpp-2017-12-04-14:36:55-109062 (559874048 bytes)
Dec  4 14:36:59 vertica3 /opt/pbis/sbin/lwsmd: Restarting dead service: lwio (attempt 2/2)
Dec  4 14:36:59 vertica3 abrtd: Package 'pbis-open' isn't signed with proper key
Dec  4 15:56:14 vertica3 abrt[36605]: Saved core dump of pid 9043 (/opt/pbis/sbin/lwsmd) to /var/spool/abrt/ccpp-2017-12-04-15:56:10-9043 (549326848 bytes)
Dec  4 15:56:14 vertica3 /opt/pbis/sbin/lwsmd: Restarting dead service: lwio (attempt 2/2)
Dec  4 15:56:14 vertica3 abrtd: Package 'pbis-open' isn't signed with proper key
Dec  5 04:28:10 vertica3 /opt/pbis/sbin/lwsmd: lwsmd timer expired, executing timer expired action.
Dec  5 04:28:10 vertica3 /opt/pbis/sbin/lwsmd: Service failed to start: lsass
Dec  5 04:28:10 vertica3 /opt/pbis/sbin/lwsmd: Could not shut down service; ignoring error: LW_ERROR_SERVICE_UNRESPONSIVE (41203)#012
Dec  5 04:28:51 vertica3 /opt/pbis/sbin/lwsmd: Logging started
Dec  5 04:32:46 vertica3 /opt/pbis/sbin/lwsmd: Logging started

**Comment by rbest-bt** [comment]
We are unaware and need time to investigate. For now I'm going to mark this as a bug

**Comment by rbest-bt** [comment]
Please upgrade to Active Directory Bridge Enterprise. If the issue still exists then please submit a ticket to our service team and we’ll have a look for you.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
