### ISSUE TITLE
problem to compile - fatal error: lwio/io-types.h not found 

### ISSUE THREAD

**Issue by gabrielfedel** [BeyondTrust/pbis-open#89]
**Version**: 8.5.7
**OS/Distro**: Debian 9
**Issue/Impact**:
When I try to compile last version I get this error:
fatal error: lwio/io-types.h not found 

**Output/Error**:
fatal error: lwio/io-types.h not found 

**Steps to Reproduce**:
mkdir debug && cd debug
../configure --debug
make

**Comment by dmorash-BT** [comment]
We will fix this but if you need to build this yourself, you can do a make -k followed by a second make.   The first make will stage the lwio headers allowing the second make to succeed.

**Comment by dmorash-BT** [comment]
This is now fixed.  Please give it a try.
