### ISSUE TITLE
update to sha256 for the .deb repositories

### ISSUE THREAD

**Issue by kayiwa** [BeyondTrust/pbis-open#9]
Heya,

Is it possible to upgrade your .deb repos to use sha256 to comply Debian and Canonical's https://wiki.debian.org/Teams/Apt/Sha1Removal due January 1? 

Thanks for considering. Unsure if this is the correct place to send this so close with my apologies if it isn't. 

Cheers

**Comment by rbest-bt** [comment]
Thanks for the link.

We already planned on upgrading but will have to try and get that done sooner.

**Comment by AtesComp** [comment]
..and now SHA1 is provably broke ([Thanks, Google!  All SHAttered now!](https://security.googleblog.com/2017/02/announcing-first-sha1-collision.html))

While it's probably quite an overstatement about the security risks, the PBIS-Open repository is the only one I use that is out of compliance.

Sooner, please.

**Comment by rbest-bt** [comment]
Fixed the repo with the 8.5.3 release. There is a new key which will need to be added. 

Page has been updated with the new key:
https://repo.pbis.beyondtrust.com/apt.html
