### ISSUE TITLE
Cannot ssh after joining new domain

### ISSUE THREAD

**Issue by broyuken** [BeyondTrust/pbis-open#90]
**Version**: 8.3.3287.68880
**OS/Distro**: Ubuntu Server 16.04.3 LTS
**Issue/Impact**: I previously had this working perfectly on my old domain. I left that domain, and joined a new one and now I cannot ssh into the box using domain creds.

 1. systemctl status lwsmd.service
```
brian@broyserver:~$ systemctl status lwsmd.service
● lwsmd.service - BeyondTrust PBIS Service Manager
   Loaded: loaded (/lib/systemd/system/lwsmd.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2017-12-15 09:37:21 EST; 20min ago
  Process: 1087 ExecStart=/opt/pbis/sbin/lwsmd --start-as-daemon (code=exited, status=0/SUCCESS)
 Main PID: 1107 (lwsmd)
   CGroup: /system.slice/lwsmd.service
           ├─1107 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─1120 lw-container lwreg
           ├─1142 lw-container eventlog
           ├─1158 lw-container netlogon
           ├─1226 lw-container lwio
           ├─1353 lw-container reapsysl
           └─2010 lw-container lsass

Dec 15 09:37:21 broyserver reapsysl[1353]: Logging started
Dec 15 09:37:21 broyserver systemd[1]: Started BeyondTrust PBIS Service Manager.
Dec 15 09:39:26 broyserver /opt/pbis/sbin/lwsmd[1107]: Service failed to start: lsass
Dec 15 09:39:39 broyserver lsass[1811]: Logging started
Dec 15 09:39:47 broyserver /opt/pbis/sbin/lwsmd[1107]: Service failed to start: lsass
Dec 15 09:39:50 broyserver lsass[1884]: Logging started
Dec 15 09:39:52 broyserver /opt/pbis/sbin/lwsmd[1107]: Service failed to start: lsass
Dec 15 09:39:54 broyserver lsass[1947]: Logging started
Dec 15 09:40:02 broyserver /opt/pbis/sbin/lwsmd[1107]: Service failed to start: lsass
Dec 15 09:40:05 broyserver lsass[2010]: Logging started
```

 2. /opt/pbis/bin/lwsm list
`brian@broyserver:~$ /opt/pbis/bin/lwsm list
lwreg          running (container: 1120)
dcerpc         stopped
eventlog       running (container: 1142)
lsass          running (container: 2010)
lwio           running (container: 1226)
netlogon       running (container: 1158)
rdr            running (io: 1226)
reapsysl       running (container: 1353)
usermonitor    stopped
`
 id broyuken\\broy
works fine

pbis authenticate-user --user broy
Success

logging in via ssh fails with the following from /var/log/auth.log
Dec 15 10:11:41 broyserver sshd[2198]: PAM unable to dlopen(pam_smbpass.so): /lib/security/pam_smbpass.so: cannot open shared object file: No such file or directory
Dec 15 10:11:41 broyserver sshd[2198]: PAM adding faulty module: pam_smbpass.so
Dec 15 10:11:46 broyserver sshd[2198]: error: PAM: Authentication failure for broy from x.x.x.x

**Comment by broyuken** [comment]
I'm assuming there is something cache'd from the old domain in there somewhere, but not sure how to clear it out. I ran sudo /opt/pbis/bin/ad-cache --delete-all but it didn't fix anything.

**Comment by rbest-bt** [comment]
When you issue a domainjoin PBIS configures the PAM files to add our modules(also perform a backup). If you have any custom modifications to PAM there maybe a conflict. I recommend removing pam_smbpass.so entries and see if that clears it up.

If you want to link your samba server with AD you can use the samba-interop-install (see the [Integration guide](https://github.com/BeyondTrust/pbis-open/wiki/docs/PBIS_Integration_Guide.pdf) for more info) to use pbis with Samba.

**Comment by broyuken** [comment]
I don't have a pam_smbpass.so

/lib/security/pam_smbpass.so: cannot open shared object file: No such file or directory

Anything else I can try?

**Comment by rbest-bt** [comment]
If this is still an issue I would recommend a purge, download the latest version and install. Then try again.
