### ISSUE TITLE
Problem to compile/link - cannot find -lpam

### ISSUE THREAD

**Issue by gabrielfedel** [BeyondTrust/pbis-open#91]
**Version**: 8.5.7
**OS/Distro**: Debian 9
**Issue/Impact**:
When I try to compile last version I get this error:
/usr/bin/ld: cannot find -lpam

**Output/Error**:
/usr/bin/ld: cannot find -lpam
collect2: error: ld returned 1 exit status
              [link] FAILED: 'gcc' '-shared' '-o' 'stage/lib32/security/pam_lsass.so' 'object/lsas
s/interop/auth/pam/pam-acct.pam_lsass.host.x86_32.o' 'object/lsass/interop/auth/pam/pam-auth.pam_lsass.host.x86_32.o' 'object/lsass/interop/auth/pam/pam-context.pam_lsass.host.x86_32.o' 'object/ls
ass/interop/auth/pam/pam-conv.pam_lsass.host.x86_32.o' 'object/lsass/interop/auth/pam/pam-error.pa
m_lsass.host.x86_32.o' 'object/lsass/interop/auth/pam/pam-globals.pam_lsass.host.x86_32.o' 'object
/lsass/interop/auth/pam/pam-passwd.pam_lsass.host.x86_32.o' 'object/lsass/interop/auth/pam/pam-session.pam_lsass.host.x86_32.o' 'object/lsass/interop/auth/pam/pam-notify.pam_lsass.host.x86_32.o' '
-Lstage/opt/pbis/lib32' '-m32' '-O0' '-g' '-Wall' '-Werror' '-fno-strict-aliasing' '-Wl,-rpath,/op
t/pbis/lib32' '-Wl,-rpath-link,stage/opt/pbis/lib32' '-fPIC' '-llsaauth' '-lpam'
Makefile:9861: recipe for target 'stage/lib32/security/pam_lsass.so' failed
make: *** [stage/lib32/security/pam_lsass.so] Error 1

**Steps to Reproduce**:
mkdir debug && cd debug
../configure --debug
make

**Comment by rbest-bt** [comment]
Is this being build on a 32bit system? Have you installed the additional 32bit development tools and libraries for compatibility packages when building on x86_64:

- libc6-dev-i386 gcc-multilib libpam0g-dev:i386
- ia32-libs - replaced by lib32ncurses5 lib32z1
