### ISSUE TITLE
Problem executing '/opt/pbis/bin/ad-cache --delete-all >/dev/null 2>/dev/null' -- Offline DC -- RH7

### ISSUE THREAD

**Issue by CanadianRepublican** [BeyondTrust/pbis-open#92]
**Version**: 8.5.* ( Tried with a few Versions)
**OS/Distro**: Redhat 7.4
**Issue/Impact**: Can't run any commands as one domain is offline.  tried running the following to fix but no luck.
/opt/pbis/bin/config DomainManagerExcludeTrustList lbs.ubc.ca
Error: Capability not found

PBIS connects and authenticates. looks like it works fine. But I cannot set the default shell, or any other settings.  ID <username> works great.

/opt/pbis/bin/config AssumeDefaultDomain true
Problem executing '/opt/pbis/bin/ad-cache --delete-all >/dev/null 2>/dev/null'
Error: Error returned by external program

/opt/pbis/bin/config LoginShellTemplate /bin/bash
Problem executing '/opt/pbis/bin/ad-cache --delete-all >/dev/null 2>/dev/null'
Error: Error returned by external program

In Messages log file i get:

Jan  6 13:12:55 pbis chronyd[730]: Selected source 142.103.1.1
Jan  6 13:13:18 pbis systemd: Created slice User Slice of root.
Jan  6 13:13:18 pbis systemd: Starting User Slice of root.
Jan  6 13:13:18 pbis systemd: Started Session 1 of user root.
Jan  6 13:13:18 pbis systemd-logind: New session 1 of user root.
Jan  6 13:13:18 pbis systemd: Starting Session 1 of user root.
Jan  6 13:13:25 pbis lsass: [lsass] Cache could not be emptied because domain lbs.ubc.ca is offline [9502]
Jan  6 13:13:25 pbis lsass: [lsass] Failed to run provider specific request (request code = 1, provider = 'lsa-activedirectory-provider') -> error = 40121, symbol = LW_ERROR_DOMAIN_IS_OFFLINE, client pid = 1344
Jan  6 13:17:36 pbis lsass: [lsass] Cache could not be emptied because domain lbs.ubc.ca is offline [9502]
Jan  6 13:17:36 pbis lsass: [lsass] Failed to run provider specific request (request code = 1, provider = 'lsa-activedirectory-provider') -> error = 40121, symbol = LW_ERROR_DOMAIN_IS_OFFLINE, client pid = 1377

**Comment by CanadianRepublican** [comment]
Set default shell and other config options by : 
1. domainjoin-cli leave
2. /opt/pbis/bin/config LoginShellTemplate /bin/bash
3. /opt/pbis/bin/config AssumeDefaultDomain true
4. domainjoin-cli join <domain> <admin user>

**Comment by avillalsan** [comment]
Thank you very much, I was about to kill myself.
