### ISSUE TITLE
home directory and uid/gid values

### ISSUE THREAD

**Issue by cristianomariacumer** [BeyondTrust/pbis-open#93]
Hello,

I there a way to get uid/gid and homedirs as configured in AD with the unix tools?  Could find anything in the documentation.

**Comment by rbest-bt** [comment]
Adtool can be users to lookup attributes of a user. You will need to logon with an AD account first or use -n (user) and -x (password) to provide one.

>/opt/pbis/bin/adtool -a search-user --name=pbisuser
CN=pbis user,OU=dev,DC=pbis,DC=com
/opt/pbis/bin/adtool -a -a lookup-object --dn='CN=pbis user,OU=dev,DC=pbis,DC=com' | grep uid
uid: pbisuser
uidNumber: 2066220575
