### ISSUE TITLE
Apache startup fails running as AD user

### ISSUE THREAD

**Issue by curmudgeon61** [BeyondTrust/pbis-open#95]
**Version**: 8.5.7385
**OS/Distro**: Ubuntu server 16.04 LTS
**Apache2 fails at Server startup**:
Apache successfully runs as the AD user/group when manually started after logging in with any local or AD user.  However, apache will not start automatically on reboot giving an error message that I'm using an invalid user.  Once Apache is started it behaves as expected - logged in or not.  

Seems like maybe I need to change the startup order in which Apache starts..??

root# systemctl status lwsmd.service
● lwsmd.service - BeyondTrust PBIS Service Manager
   Loaded: loaded (/lib/systemd/system/lwsmd.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2018-01-18 11:28:39 EST; 5min ago
  Process: 1078 ExecStart=/opt/pbis/sbin/lwsmd --start-as-daemon (code=exited, status=0/SUCCESS)
 Main PID: 1143 (lwsmd)
    Tasks: 177
   Memory: 33.1M
      CPU: 651ms
   CGroup: /system.slice/lwsmd.service
           ├─1143 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─1166 lw-container lwreg
           ├─1197 lw-container eventlog
           ├─1227 lw-container netlogon
           ├─1252 lw-container lwio
           ├─1280 lw-container lsass
           └─1318 lw-container reapsysl

Jan 18 11:28:38 serverhostname systemd[1]: Starting BeyondTrust PBIS Service Manager...
Jan 18 11:28:39 serverhostname /opt/pbis/sbin/lwsmd[1143]: Logging started
Jan 18 11:28:39 serverhostname lwreg[1166]: Logging started
Jan 18 11:28:39 serverhostname eventlog[1197]: Logging started
Jan 18 11:28:39 serverhostname netlogon[1227]: Logging started
Jan 18 11:28:39 serverhostname lwio[1252]: Logging started
Jan 18 11:28:39 serverhostname lsass[1280]: Logging started
Jan 18 11:28:39 serverhostname reapsysl[1318]: Logging started
Jan 18 11:28:39 serverhostname systemd[1]: Started BeyondTrust PBIS Service Manager.

root# systemctl status apache2.service
● apache2.service - LSB: Apache2 web server
   Loaded: loaded (/etc/init.d/apache2; bad; vendor preset: enabled)
  Drop-In: /lib/systemd/system/apache2.service.d
           └─apache2-systemd.conf
   Active: failed (Result: exit-code) since Thu 2018-01-18 11:28:41 EST; 5min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1381 ExecStart=/etc/init.d/apache2 start (code=exited, status=1/FAILURE)

Jan 18 11:28:41 serverhostname systemd[1]: Starting LSB: Apache2 web server...
Jan 18 11:28:41 serverhostname apache2[1381]:  * Starting Apache httpd web server apache2
Jan 18 11:28:41 serverhostname apache2[1381]:  *
Jan 18 11:28:41 serverhostname apache2[1381]:  * **The apache2 configtest failed.**
Jan 18 11:28:41 serverhostname apache2[1381]: **Output of config test was:**
Jan 18 11:28:41 serverhostname apache2[1381]: **chown: invalid user: 'myadusername'**
Jan 18 11:28:41 serverhostname systemd[1]: apache2.service: Control process exited, code=exited status=1
Jan 18 11:28:41 serverhostname systemd[1]: Failed to start LSB: Apache2 web server.
Jan 18 11:28:41 serverhostname systemd[1]: apache2.service: Unit entered failed state.
Jan 18 11:28:41 serverhostname systemd[1]: apache2.service: Failed with result 'exit-code'.

root# apache2ctl -t
Syntax OK

**Comment by rbest-bt** [comment]
Simplest solution would be to add lwsmd.service in the "After" list for the apache service. This should hold off starting Apache till lwsmd is ready.

Similiar issue with nginx
https://serverfault.com/questions/617823/how-to-set-systemd-service-dependencies
