### ISSUE TITLE
Compiling pbis-open in FreeBSD 11.1 ?

### ISSUE THREAD

**Issue by tomtomz** [BeyondTrust/pbis-open#96]
# uname  -a
+ uname -a
FreeBSD plvmldocker 11.1-RELEASE FreeBSD 11.1-RELEASE

# ../configure --debug
+ ../configure --debug
           [makekit] initializing
          [platform] build operating system: freebsd
          [platform] build distribution: freebsd
          [platform] build distribution version: 11.1
          [platform] build processor architecture: x86_64
          [platform] build instruction set architectures: x86_64
          [platform] build multiarchitecture binary style: separate
          [platform] host operating system: freebsd
          [platform] host distribution: freebsd
          [platform] host distribution version: 11.1
          [platform] host processor architecture: x86_64
          [platform] host instruction set architectures: x86_64
          [platform] host multiarchitecture binary style: separate
          [platform] cross compiling: no
              [core] program gawk: /usr/local/bin/gawk
              [path] Defaulting to /opt/pbis/lib for platform freebsd-freebsd-x86_64-x86_64
              [path] prefix: /opt/pbis
              [path] exec prefix: /opt/pbis
              [path] library dir (x86_64): /opt/pbis/lib
              [path] include dir: /opt/pbis/include
              [path] binary dir: /opt/pbis/bin
              [path] system binary dir: /opt/pbis/sbin
              [path] system config dir: /etc/pbis
              [path] local state dir: /var
              [path] data root dir: /opt/pbis/share
              [path] data dir: /opt/pbis/share
              [path] documenation dir: /opt/pbis/docs
              [path] HTML documentation dir: /opt/pbis/docs/html
              [path] manpage dir: /usr/share/man
          [compiler] default C compiler: gcc
          [compiler] default C++ compiler: g++
          [compiler] default C preprocessor flags:
          [compiler] default C compiler flags:
          [compiler] default C++ compiler flags:
          [compiler] default linker flags:
          [compiler] C compiler (build/x86_64): gcc
          [compiler] C++ compiler (build/x86_64): g++
          [compiler] C preprocessor flags (build/x86_64):
          [compiler] C compiler flags (build/x86_64): -m64
          [compiler] C++ compiler flags (build/x86_64): -m64
          [compiler] linker flags (build/x86_64):
          [compiler] C compiler (host/x86_64): gcc
          [compiler] C++ compiler (host/x86_64): g++
          [compiler] C preprocessor flags (host/x86_64):
          [compiler] C compiler flags (host/x86_64): -m64
          [compiler] C++ compiler flags (host/x86_64): -m64
          [compiler] linker flags (host/x86_64):
          [compiler] C compiler style (build/x86_64): unknown
          [compiler] C++ compiler style (build/x86_64): unknown
          [compiler] C compiler linker style (build/x86_64): native
          [compiler] C++ compiler linker style (build/x86_64): native
          [compiler] C compiler style (host/x86_64): unknown
          [compiler] C++ compiler style (host/x86_64): unknown
          [compiler] C compiler linker style (host/x86_64): native
          [compiler] C++ compiler linker style (host/x86_64): native
         [autotools] build system string: x86_64-unknown-freebsd11.1.0
         [autotools] host system string (x86_64): x86_64-unknown-freebsd11.1.0
         [autotools] pass-through variables:
          [moonunit] program moonunit: no
        [pkg-config] program pkg-config: /usr/local/bin/pkg-config
              [pbis] cache dir: /var/lib/pbis
              [pbis] config dir: /opt/pbis/share/config
              [pbis] init script dir: /etc/rc.d
              [pbis] developer tool dir: tools
       [package-deb] program dpkg-buildpackage: no
       [package-deb] debian package building: disabled
       [package-rpm] program rpmbuild: /usr/local/bin/rpmbuild
       [package-rpm] RPM package building: enabled
   [package-freebsd] program pkg_create: no
   [package-freebsd] FreeBSD package building: disabled
       [package-pkg] program pkgmk: no
       [package-pkg] program pkgtrans: no
       [package-pkg] Solaris package building: disabled
       [package-lpp] AIX package building: disabled
     [package-depot] program swpackage: no
     [package-depot] HP-UX package building: disabled
       [package-mac] program PackageMaker: no
       [package-mac] Mac package building: disabled
          [platform] configuring pbis  platform 8.5.8.0
          [platform] using bundled libraries: linenoise libiconv libuuid openssl krb5 cyrus-sasl openldap sqlite curl popt libxml2 libedit libtdb
              [krb5] running autogen.sh for src
../mk/command/configure.sh: ./autogen.sh: not found
              [krb5] FAILED: './autogen.sh'

It can't find the 'autogen.sh' file to build Kerberos. The 'src' subdir of 'pbis-open/krb5'
appears to be different.

# find .. -name autogen.sh
+ find .. -name autogen.sh
../pbis-open/openldap/autogen.sh
../pbis-open/curl/autogen.sh
../pbis-open/krb5/src/autogen.sh
../pbis-open/libiconv/autogen.sh
../pbis-open/libiconv/libcharset/autogen.sh
../pbis-open/lwtask/autogen.sh
../pbis-open/cyrus-sasl/autogen.sh
../pbis-open/opensoap/autogen.sh
../pbis-open/lwtest/autogen.sh

It has been a long time since I've debugged a Makefile...

**Comment by dmorash-BT** [comment]
Took a quick look at this but don't have it completely building yet, it looks like the openssl build needs some tweaking. Here is what I found so far:

1.  The autogen.sh issue is because those files reference /bin/bash.  To fix this you'll need to install bash and link /usr/local/bash to /bin/bash.
2. By default configure will use gcc.  If you want to use clang, you'll need to specify that as a configure parameter, e.g. configure CC=clang --debug
3. Standard make doesn't understand our generated Makefile, so you'll need to install and use gmake.
