### ISSUE TITLE
Trusted domain login issue

### ISSUE THREAD

**Issue by Hunlogo** [BeyondTrust/pbis-open#97]
**Version**: 8.2.2.1
**OS/Distro**: Xenserver 7.0.2
**Issue/Impact**: user from trusted domain cannot login
*Note: We have domain A and domain B. Xenserver is in Domain A and we have users in that domain. They can login to Xenserver using Xencenter without any issue. We need to give access to few users in Domain B to able to login to this server in Domain A. 
On Xencenter I could add the user to the users list and could give permission, but could not login. 
on CLi I see the following error: 

Jan 23 08:28:01 server xapi: [debug|server|2752 INET :::80|session.login_with_password D:b39fa8c3fda2|xapi] External authentication AD is enabled
Jan 23 08:28:01 server xapi: [debug|server|2752 INET :::80|session.login_with_password D:b39fa8c3fda2|xapi] Failed to locally authenticate user DOMAINB\user from HTTP request from Internet with User-Agent: XenCenter/7.2.0: Local superuser must be root
Jan 23 08:28:01 server xapi: [debug|server|2752 INET :::80|session.login_with_password D:b39fa8c3fda2|extauth] using external auth plugin AD
Jan 23 08:28:01 server xapi: [debug|server|2752 INET :::80|session.login_with_password D:b39fa8c3fda2|extauth_plugin_ADpbis] execute (omitted for security)
Jan 23 08:28:01 server xapi: [debug|server|2752 INET :::80|session.login_with_password D:b39fa8c3fda2|extauth_plugin_ADpbis] Created process pid (FEFork (58,32644)) for cmd (omitted for security)
Jan 23 08:28:01 server xapi: [error|server|2752 INET :::80|session.login_with_password D:b39fa8c3fda2|extauth_plugin_ADpbis] execute '(omitted for security)': exit_code=[1] output=[Error: LW_ERROR_KRB5KDC_ERR_POLICY (0xa30e);]
Jan 23 08:28:01 server xapi: [debug|server|2752 INET :::80|session.login_with_password D:b39fa8c3fda2|extauth_plugin_ADpbis] Pbis raised an error for cmd (omitted for security): (LW_ERROR_KRB5KDC_ERR_POLICY) Error: LW_ERROR_KRB5KDC_ERR_POLICY (0xa30e)
Jan 23 08:28:01 server xapi: [debug|server|2752 INET :::80|session.login_with_password D:b39fa8c3fda2|xapi] A function failed to catch this exception for user DOMAINB\user from HTTP request from Internet with User-Agent: XenCenter/7.2.0 during external authentication: (LW_ERROR_KRB5KDC_ERR_POLICY) Error: LW_ERROR_KRB5KDC_ERR_POLICY (0xa30e)
Jan 23 08:28:02 server xapi: [debug|server|2753 ||mscgen] xapi=>xapi [label="event.from"];
Jan 23 08:28:02 server xapi: [debug|server|2754 UNIX /var/lib/xcp/xapi||dummytaskhelper] task dispatch:event.from D:f0ad958f0e69 created by task D:b4cc2ef00c03
Jan 23 08:28:06 server xapi: [error|server|2752 INET :::80|dispatch:session.login_with_password D:ee5722b7636e|backtrace] session.login_with_password D:b39fa8c3fda2 failed with exception Server_error(SESSION_AUTHENTICATION_FAILED, [ DOMAINB\user; (LW_ERROR_KRB5KDC_ERR_POLICY) Error: LW_ERROR_KRB5KDC_ERR_POLICY (0xa30e) ])
Jan 23 08:28:06 server xapi: [error|server|2752 INET :::80|dispatch:session.login_with_password D:ee5722b7636e|backtrace] Raised Server_error(SESSION_AUTHENTICATION_FAILED, [ DOMAINB\user; (LW_ERROR_KRB5KDC_ERR_POLICY) Error: LW_ERROR_KRB5KDC_ERR_POLICY (0xa30e) ])
Jan 23 08:28:06 server xapi: [error|server|2752 INET :::80|dispatch:session.login_with_password D:ee5722b7636e|backtrace] 1/8 xapi @ server Raised at file xapi_session.ml, line 399
Jan 23 08:28:06 server xapi: [error|server|2752 INET :::80|dispatch:session.login_with_password D:ee5722b7636e|backtrace] 2/8 xapi @ server Called from file xapi_session.ml, line 38
Jan 23 08:28:06 server xapi: [error|server|2752 INET :::80|dispatch:session.login_with_password D:ee5722b7636e|backtrace] 3/8 xapi @ server Called from file xapi_session.ml, line 38
Jan 23 08:28:06 server xapi: [error|server|2752 INET :::80|dispatch:session.login_with_password D:ee5722b7636e|backtrace] 4/8 xapi @ server Called from file server_helpers.ml, line 75
Jan 23 08:28:06 server xapi: [error|server|2752 INET :::80|dispatch:session.login_with_password D:ee5722b7636e|backtrace] 5/8 xapi @ server Called from file server_helpers.ml, line 90
Jan 23 08:28:06 server xapi: [error|server|2752 INET :::80|dispatch:session.login_with_password D:ee5722b7636e|backtrace] 6/8 xapi @ server Called from file lib/pervasiveext.ml, line 22
Jan 23 08:28:06 server xapi: [error|server|2752 INET :::80|dispatch:session.login_with_password D:ee5722b7636e|backtrace] 7/8 xapi @ server Called from file lib/pervasiveext.ml, line 26
Jan 23 08:28:06 server xapi: [error|server|2752 INET :::80|dispatch:session.login_with_password D:ee5722b7636e|backtrace] 8/8 xapi @ server Called from file lib/backtrace.ml, line 176
Jan 23 08:28:06 server xapi: [error|server|2752 INET :::80|dispatch:session.login_with_password D:ee5722b7636e|backtrace]

 1. systemctl status lwsmd.service
systemctl status lwsmd.service
● lwsmd.service - BeyondTrust PBIS Service Manager
   Loaded: loaded (/etc/pbis/redhat/lwsmd.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/lwsmd.service.d
           └─slice.conf
   Active: active (running) since Tue 2018-01-23 00:07:03 PST; 8h ago
  Process: 959 ExecStart=/opt/pbis/sbin/lwsmd --start-as-daemon (code=exited, status=0/SUCCESS)
 Main PID: 1455 (lwsmd)
   CGroup: /control.slice/lwsmd.service
           ├─ 1455 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─ 1478 lw-container lwreg
           ├─ 1512 lw-container netlogon
           ├─ 1538 lw-container lwio
           └─19804 lw-container lsass

 2. /opt/pbis/bin/lwsm list

/opt/pbis/bin/lwsm list
lwreg       running (container: 1478)
dcerpc      stopped
eventlog    stopped
lsass       running (container: 19804)
lwio        running (container: 1538)
netlogon    running (container: 1512)
rdr         running (io: 1538)

 3. /opt/pbis/domainjoin-cli query

/opt/pbis/bin/domainjoin-cli query
Name = Server
Domain = DOMAINA
Distinguished Name = CN=Server,CN=Computers,DC=DOMAINA

 4. pbis status

pbis status
LSA Server Status:

Compiled daemon version: 8.2.2.1
Packaged product version: 8.2.1.0
Uptime:        0 days 7 hours 27 minutes 51 seconds

[Authentication provider: lsa-activedirectory-provider]

        Status:        Online
        Mode:          Un-provisioned
        Domain:        DOMAINA
        Domain SID:    S-1-5-21-3446955097-3477261712-2643277873
        Forest:        DOMAINA
        Site:          World
        Online check interval:  300 seconds
        [Trusted Domains: 2]

        [Domain: DOMAINA]

                DNS Domain:       DOMAINA
                Netbios name:     DOMAINA
                Forest name:      DOMAINA
                Trustee DNS name:
                Client site name: World
                Domain SID:       S-1-5-21-3446955097-3477261712-2643277873
                Domain GUID:      cc1bcbbf-6a56-754d-ab46-0005c344370d
                Trust Flags:      [0x001d]
                                  [0x0001 - In forest]
                                  [0x0004 - Tree root]
                                  [0x0008 - Primary]
                                  [0x0010 - Native]
                Trust type:       Up Level
                Trust Attributes: [0x0000]
                Trust Direction:  Primary Domain
                Trust Mode:       In my forest Trust (MFT)
                Domain flags:     [0x0001]
                                  [0x0001 - Primary]

                [Domain Controller (DC) Information]

                        DC Name:              COMPANY02DC.DOMAINA
                        DC Address:           10.0.0.17
                        DC Site:              World
                        DC Flags:             [0x000031fd]
                        DC Is PDC:            yes
                        DC is time server:    yes
                        DC has writeable DS:  yes
                        DC is Global Catalog: yes
                        DC is running KDC:    yes

                [Global Catalog (GC) Information]

                        GC Name:              COMPANY02DC.DOMAINA
                        GC Address:           10.0.0.17
                        GC Site:              World
                        GC Flags:             [0x000031fd]
                        GC Is PDC:            yes
                        GC is time server:    yes
                        GC has writeable DS:  yes
                        GC is running KDC:    yes

        [Domain: DOMAINB]

                DNS Domain:       DOMAINB
                Netbios name:     DOMAINB
                Forest name:
                Trustee DNS name: DOMAINA
                Client site name: Somewhere over rainbow
                Domain SID:       S-1-5-21-3788810083-4052863948-3026399015
                Domain GUID:      00000000-0000-0000-0000-000000000000
                Trust Flags:      [0x0022]
                                  [0x0002 - Outbound]
                                  [0x0020 - Inbound]
                Trust type:       Up Level
                Trust Attributes: [0x0014]
                                  [0x0004 - Filter SIDs]
                                  [0x0010 - Cross organization]
                Trust Direction:  Twoway Trust
                Trust Mode:       External Trust (ET)
                Domain flags:     [0x0000]

                [Domain Controller (DC) Information]

                        DC Name:              SFDOMAINBDC01.DOMAINB
                        DC Address:           10.0.0.25
                        DC Site:              Somewhere over rainbow
                        DC Flags:             [0x000031fd]
                        DC Is PDC:            yes
                        DC is time server:    yes
                        DC has writeable DS:  yes
                        DC is Global Catalog: yes
                        DC is running KDC:    yes

 5. /opt/pbis/bin/enum-users
Shows only users in DOMAINA

**Comment by rbest-bt** [comment]
enum-users will only list users from the domain you are joined to. 
>Failed to locally authenticate user DOMAINB\user from HTTP request

Is the user logging into an apache server? What keytab file are you using and how was it generate?

**Comment by Hunlogo** [comment]
user is trying to log into xencenter. I use the default keytab from xen. Just joined the server to the domain from xencenter with local root user.

**Comment by Hunlogo** [comment]
do you have any idea ?

**Comment by rbest-bt** [comment]
Xenserver is not actively supported. It could be something we add in the future but it's not on any current plans.

**Comment by Hunlogo** [comment]
I could do it and could add user from trusted domain. My only missing problem was that on the AD computer you need to allow to authenticate the domain users. With that both domain users could and can login to the server :D Hope that helps

**Comment by rbest-bt** [comment]
Thank you for the update. Hopefully that will assist future Xenserver admins until we can officially support it.
