### ISSUE TITLE
Error: ERROR_DOMAIN_BLACKLISTED [code 0x0000251c]

### ISSUE THREAD

**Issue by miguelcornelli** [BeyondTrust/pbis-open#98]
Hello, with a problem I can not join a machine without domain after the command sudo domainjoin-cli join --disable ssh decora.com administratorof this error below:
Joining to AD Domain:   decora.com
With Computer DNS Name: nuc-018.decora.com

administrator@DECORA.COM's password: 

Error: ERROR_DOMAIN_BLACKLISTED [code 0x0000251c]

Could not reach the DC, it has been blacklisted.

**Comment by rbest-bt** [comment]
Test to see if the domain is  reachable with:
>/opt/pbis/bin/get-dc-list decora.com

We have a known issue with the error logic. If we can not reach the domain at all it assumes that it's been blacklisted.

**Comment by nlseitz** [comment]
the question remains, how to unblock the domain? is there a workaround?

**Comment by rbest-bt** [comment]
The issue above is a networking issue. Because it can not be reached it assumes it's blacklisted. If that is not the cause then an investigation into the network and dns need to occur.

**Comment by nlseitz** [comment]
but i don't have the same issue with Ubuntu 18 server or Centos 7 - both of which it works perfectly... also I can ping via hostname and IP4 on ubuntu 18 workstation. So its reaching DNS and resolving hostnames. 
![pbis-1](https://user-images.githubusercontent.com/23104751/45559978-e7efb000-b811-11e8-9644-02fb3b59b345.PNG)

**Comment by ciampix** [comment]
Found a solution... sharing here in the hope it will help someone. Same problem resolved in this way:
Changed an /etc/nsswitch.conf line from:
hosts:          files mdns4_minimal [NOTFOUND=return] dns myhostname
to:
hosts:          files dns mdns4_minimal [NOTFOUND=return] myhostname
with Ubuntu 18.04 ...

**Comment by henhuy** [comment]
I had the same error - maybe this helps?
Solution for me was to remove avahi-daemon temporarily:
```
sudo apt-get remove avahi-daemon
sudo domainjoin-cli join ...
sudo apt-get install avahi-daemon
```
