### ISSUE TITLE
Cannot Enumerate Proper Groups Consistently

### ISSUE THREAD

**Issue by Ramorous** [BeyondTrust/pbis-open#99]
**Version**: 8.5.7-385
**OS/Distro**: CentOS 7.4
**Issue/Impact**: Cannot Enumerate Proper Groups Consistently

Here are the steps.
1. id <user> (should display 100s of groups, it displays 14)
2. ad-cache --delete-user --name <user>
3. list-groups-for-user <user> (displays 30)
4. ad-cache --delete-all
5. enum-groups --level 1
6. list-groups-for-user <user> (still 30)

lsass verbose outputs this when doing search
20180125141022:VERBOSE:lsass: Using cache entry for sid S-1-5-21-xxxxxx-55137, updated 9 seconds ago
20180125141022:VERBOSE:lsass: Using cache entry for sid S-1-5-21-xxxxxx-55137, updated 9 seconds ago
20180125141022:VERBOSE:lsass: Using cache entry for sid S-1-5-21-xxxxxx-55137, updated 9 seconds ago
20180125141022:VERBOSE:lsass: Using cache entry for sid S-1-5-21-3448487843-1543089549-1233480760-513, updated 116 seconds ago
20180125141022:VERBOSE:lsass: Cache entry for group membership for sid S-1-5-21-3448487843-1543089549-1233480760-513 is incomplete
20180125141022:VERBOSE:lsass: Using cache entry for sid S-1-5-21-xxxxxx-55137, updated 9 seconds ago
20180125141022:VERBOSE:lsass: Using cache entry for sid S-1-5-21-xxxxxx-55137, updated 9 seconds ago
20180125141022:VERBOSE:lsass: Cache entry for user's group membership for sid S-1-5-21-3448487843-1543089549-1233480760-55137 is incomplete
20180125141022:VERBOSE: Caught LDAP_NO_SUCH_OBJECT Error on ldap search
20180125141022:ERROR:lsass: Failed to group memberships of SID=S-1-5-21-xxxxxx-55137. [error code:40318]
20180125141022:ERROR:lsass: Failed to find memberships for user 'ADNAME\Group1' (error = 40318)
20180125141022:ERROR:lsass: Failed to find memberships for user 'ADNAME\User1' (error = 40318)
20180125141022:VERBOSE:lsass-ipc: (session:1ed06a16c5bd54fc-f6602494b74ddfff) Dropping: LWMSG_STATUS_PEER_CLOSE

**Comment by rbest-bt** [comment]
We are aware of group enumeration issues and are looking into it.

**Comment by jelayeb** [comment]
is there any updates regarding this ticket??? could you have a workaround for it.

**Comment by rbest-bt** [comment]
There is a workaround in Enterprise with limiting the amount of groups you provision.

**Comment by rbest-bt** [comment]
Open does not have a method for managing accounts in Active Directory. Instead it runs in unprovisioned mode with all accounts available.

Enterprise uses "cells" to map ad accounts to UID/GID. This allows admins the ability to limit the users and groups on the end machines. More information can be found in the [Installation Guide](https://github.com/BeyondTrust/pbis-open/wiki/docs/PBIS_Installation_Guide.pdf) and [Windows Administration Guide.](https://github.com/BeyondTrust/pbis-open/wiki/docs/PBIS_Windows_Administration_Guide.pdf)

**Comment by rbest-bt** [comment]
Give 9.0.1 a try and see if that addresses the issue
